SimpleITK: itk::simple::scope_exit< F > Struct Template Reference
itk::simple::scope_exit< F > Struct Template Reference
#include <sitkTemplateFunctions.h>
Detailed Description
template<typename F>
struct itk::simple::scope_exit< F >
Definition at line 250 of file sitkTemplateFunctions.h.
Public Member Functions
scope_exit & operator= (const scope_exit &)=delete
scope_exit & operator= (scope_exit &&rhs)=delete
scope_exit (const scope_exit &)=delete
scope_exit (F f) noexcept
scope_exit (scope_exit &&rhs) noexcept
~scope_exit ()
Public Attributes
F f_
bool run_
Constructor & Destructor Documentation
scope_exit() [1/3]
template<typename F> itk::simple::scope_exit< F >::scope_exit (F f) inline explicit noexcept
Definition at line 254 of file sitkTemplateFunctions.h.
Referenced by operator=(), operator=(), scope_exit(), and scope_exit().
scope_exit() [2/3]
template<typename F> itk::simple::scope_exit< F >::scope_exit (scope_exit< F > && rhs) inline noexcept
Definition at line 258 of file sitkTemplateFunctions.h.
References scope_exit().
~scope_exit()
template<typename F> itk::simple::scope_exit< F >::~scope_exit () inline
Definition at line 262 of file sitkTemplateFunctions.h.
References f_, and run_.
scope_exit() [3/3]
template<typename F> itk::simple::scope_exit< F >::scope_exit (const scope_exit< F > &) delete
References scope_exit().
Member Function Documentation
operator=() [1/2]
template<typename F> scope_exit & itk::simple::scope_exit< F >::operator= (const scope_exit< F > &) delete
References scope_exit().
operator=() [2/2]
template<typename F> scope_exit & itk::simple::scope_exit< F >::operator= (scope_exit< F > && rhs) delete
References scope_exit().
Member Data Documentation
f_
template<typename F> F itk::simple::scope_exit< F >::f_
Definition at line 252 of file sitkTemplateFunctions.h.
Referenced by ~scope_exit().
run_
template<typename F> bool itk::simple::scope_exit< F >::run_
Definition at line 253 of file sitkTemplateFunctions.h.
Referenced by ~scope_exit().
The documentation for this struct was generated from the following file:
sitkTemplateFunctions.h