SimpleITK: itk::simple::BinaryOpeningByReconstructionImageFilter Class Reference
itk::simple::BinaryOpeningByReconstructionImageFilter Class Reference
binary morphological closing of an image.
#include <sitkBinaryOpeningByReconstructionImageFilter.h>
Detailed Description
binary morphological closing of an image.
This filter removes small (i.e., smaller than the structuring element) objects in the image. It is defined as: Opening(f) = ReconstructionByDilatation(Erosion(f)).
The structuring element is assumed to be composed of binary values (zero or one). Only elements of the structuring element having values > 0 are candidates for affecting the center pixel.
Author
Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA de Jouy-en-Josas, France.
This implementation was taken from the Insight Journal paper: https://doi.org/10.54294/q6auw4
See also
MorphologyImageFilter , OpeningByReconstructionImageFilter , BinaryClosingByReconstructionImageFilter
itk::simple::BinaryOpeningByReconstruction for the procedural interface
itk::BinaryOpeningByReconstructionImageFilter for the Doxygen on the original ITK class.
Definition at line 54 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Public Types
using PixelIDTypeList = IntegerPixelIDTypeList
using Self = BinaryOpeningByReconstructionImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
BinaryOpeningByReconstructionImageFilter ()
Image Execute (const Image &image1)
void FullyConnectedOff ()
void FullyConnectedOn ()
double GetBackgroundValue () const
double GetForegroundValue () const
bool GetFullyConnected () const
std::vector< unsigned int > GetKernelRadius () const
KernelEnum GetKernelType () const
std::string GetName () const
void SetBackgroundValue (double BackgroundValue)
void SetForegroundValue (double ForegroundValue)
void SetFullyConnected (bool FullyConnected)
void SetKernelRadius (std::vector< unsigned int > KernelRadius)
void SetKernelRadius (unsigned int value)
void SetKernelType (KernelEnum KernelType)
std::string ToString () const
virtual ~BinaryOpeningByReconstructionImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_BackgroundValue { 0.0 }
double m_ForegroundValue { 1.0 }
bool m_FullyConnected { false }
std::vector< unsigned int > m_KernelRadius { std::vector<uint32_t>(3, 1) }
KernelEnum m_KernelType { itk::simple::sitkBall }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::BinaryOpeningByReconstructionImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 161 of file sitkBinaryOpeningByReconstructionImageFilter.h.
PixelIDTypeList
using itk::simple::BinaryOpeningByReconstructionImageFilter::PixelIDTypeList = IntegerPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 66 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Self
using itk::simple::BinaryOpeningByReconstructionImageFilter::Self = BinaryOpeningByReconstructionImageFilter
Definition at line 56 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Constructor & Destructor Documentation
~BinaryOpeningByReconstructionImageFilter()
virtual itk::simple::BinaryOpeningByReconstructionImageFilter::~BinaryOpeningByReconstructionImageFilter () virtual
Destructor
BinaryOpeningByReconstructionImageFilter()
itk::simple::BinaryOpeningByReconstructionImageFilter::BinaryOpeningByReconstructionImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::BinaryOpeningByReconstructionImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::BinaryOpeningByReconstructionImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::BinaryOpeningByReconstructionImageFilter::FullyConnectedOff () inline
Definition at line 139 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::BinaryOpeningByReconstructionImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 137 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References SetFullyConnected().
GetBackgroundValue()
double itk::simple::BinaryOpeningByReconstructionImageFilter::GetBackgroundValue () const inline
Set the value in eroded part of the image. Defaults to zero
Definition at line 124 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_BackgroundValue.
GetForegroundValue()
double itk::simple::BinaryOpeningByReconstructionImageFilter::GetForegroundValue () const inline
Get the value in the image considered as "foreground". Defaults to maximum value of PixelType.
Definition at line 111 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_ForegroundValue.
GetFullyConnected()
bool itk::simple::BinaryOpeningByReconstructionImageFilter::GetFullyConnected () const inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 145 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_FullyConnected.
GetKernelRadius()
std::vector< unsigned int > itk::simple::BinaryOpeningByReconstructionImageFilter::GetKernelRadius () const inline
Get the radius of the kernel structuring element.
Definition at line 85 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_KernelRadius.
GetKernelType()
KernelEnum itk::simple::BinaryOpeningByReconstructionImageFilter::GetKernelType () const inline
Get the kernel or structuring element used for the morphology.
Definition at line 98 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_KernelType.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::BinaryOpeningByReconstructionImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::BinaryOpeningByReconstructionImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 149 of file sitkBinaryOpeningByReconstructionImageFilter.h.
SetBackgroundValue()
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetBackgroundValue (double BackgroundValue) inline
Set the value in eroded part of the image. Defaults to zero
Definition at line 118 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_BackgroundValue.
SetForegroundValue()
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetForegroundValue (double ForegroundValue) inline
Set the value in the image to consider as "foreground". Defaults to maximum value of PixelType.
Definition at line 105 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_ForegroundValue.
SetFullyConnected()
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetFullyConnected (bool FullyConnected) inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 132 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetKernelRadius() [1/2]
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetKernelRadius (std::vector< unsigned int > KernelRadius) inline
Set the radius of the kernel structuring element.
Definition at line 75 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_KernelRadius.
SetKernelRadius() [2/2]
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetKernelRadius (unsigned int value) inline
Set the values of the KernelRadius vector all to value
Definition at line 80 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_KernelRadius.
SetKernelType()
void itk::simple::BinaryOpeningByReconstructionImageFilter::SetKernelType (KernelEnum KernelType) inline
Set the kernel or structuring element used for the morphology.
Definition at line 92 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References m_KernelType.
ToString()
std::string itk::simple::BinaryOpeningByReconstructionImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 162 of file sitkBinaryOpeningByReconstructionImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_BackgroundValue
double itk::simple::BinaryOpeningByReconstructionImageFilter::m_BackgroundValue { 0.0 } private
Definition at line 173 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Referenced by GetBackgroundValue(), and SetBackgroundValue().
m_ForegroundValue
double itk::simple::BinaryOpeningByReconstructionImageFilter::m_ForegroundValue { 1.0 } private
Definition at line 171 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Referenced by GetForegroundValue(), and SetForegroundValue().
m_FullyConnected
bool itk::simple::BinaryOpeningByReconstructionImageFilter::m_FullyConnected { false } private
Definition at line 175 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_KernelRadius
std::vector<unsigned int> itk::simple::BinaryOpeningByReconstructionImageFilter::m_KernelRadius { std::vector<uint32_t>(3, 1) } private
Definition at line 167 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Referenced by GetKernelRadius(), SetKernelRadius(), and SetKernelRadius().
m_KernelType
KernelEnum itk::simple::BinaryOpeningByReconstructionImageFilter::m_KernelType { itk::simple::sitkBall } private
Definition at line 169 of file sitkBinaryOpeningByReconstructionImageFilter.h.
Referenced by GetKernelType(), and SetKernelType().
The documentation for this class was generated from the following file:
sitkBinaryOpeningByReconstructionImageFilter.h