SimpleITK: itk::simple::SymmetricForcesDemonsRegistrationFilter Class Reference
itk::simple::SymmetricForcesDemonsRegistrationFilter Class Reference
Deformably register two images using the demons algorithm.
#include <sitkSymmetricForcesDemonsRegistrationFilter.h>
Detailed Description
Deformably register two images using the demons algorithm.
This class was contributed by Corinne Mattmann, ETH Zurich, Switzerland. based on a variation of the DemonsRegistrationFilter . The basic modification is to use equation (5) from Thirion's paper along with the modification for avoiding large deformations when gradients have small values.
SymmetricForcesDemonsRegistrationFilter implements the demons deformable algorithm that register two images by computing the deformation field which will map a moving image onto a fixed image.
A deformation field is represented as a image whose pixel type is some vector type with at least N elements, where N is the dimension of the fixed image. The vector type must support element access via operator []. It is assumed that the vector elements behave like floating point scalars.
This class is templated over the fixed image type, moving image type and the deformation field type.
The input fixed and moving images are set via methods SetFixedImage and SetMovingImage respectively. An initial deformation field maybe set via SetInitialDisplacementField or SetInput. If no initial field is set, a zero field is used as the initial condition.
The algorithm has one parameters: the number of iteration to be performed.
The output deformation field can be obtained via methods GetOutput or GetDisplacementField.
This class make use of the finite difference solver hierarchy. Update for each iteration is computed in DemonsRegistrationFunction .
Warning
This filter assumes that the fixed image type, moving image type and deformation field type all have the same number of dimensions.
See also
SymmetricForcesDemonsRegistrationFunction
DemonsRegistrationFilter
DemonsRegistrationFunction
itk::SymmetricForcesDemonsRegistrationFilter for the Doxygen on the original ITK class.
Definition at line 71 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = SymmetricForcesDemonsRegistrationFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &fixedImage, const Image &movingImage)
Image Execute (const Image &fixedImage, const Image &movingImage, const Image &initialDisplacementField)
uint32_t GetElapsedIterations () const
Number of iterations run.
double GetIntensityDifferenceThreshold () const
double GetMaximumError () const
unsigned int GetMaximumKernelWidth () const
double GetMaximumRMSError () const
double GetMetric () const
std::string GetName () const
uint32_t GetNumberOfIterations () const
double GetRMSChange () const
bool GetSmoothDisplacementField () const
bool GetSmoothUpdateField () const
std::vector< double > GetStandardDeviations () const
std::vector< double > GetUpdateFieldStandardDeviations () const
bool GetUseImageSpacing () const
void SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold)
void SetMaximumError (double MaximumError)
void SetMaximumKernelWidth (unsigned int MaximumKernelWidth)
void SetMaximumRMSError (double MaximumRMSError)
void SetNumberOfIterations (uint32_t NumberOfIterations)
void SetSmoothDisplacementField (bool SmoothDisplacementField)
void SetSmoothUpdateField (bool SmoothUpdateField)
void SetStandardDeviations (double value)
void SetStandardDeviations (std::vector< double > StandardDeviations)
void SetUpdateFieldStandardDeviations (double value)
void SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations)
void SetUseImageSpacing (bool UseImageSpacing)
void SmoothDisplacementFieldOff ()
void SmoothDisplacementFieldOn ()
void SmoothUpdateFieldOff ()
void SmoothUpdateFieldOn ()
void StopRegistration ()
Stop the registration after the current iteration.
SymmetricForcesDemonsRegistrationFilter ()
std::string ToString () const
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~SymmetricForcesDemonsRegistrationFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *fixedImage, const Image *movingImage, const Image *initialDisplacementField)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
std::unique_ptr< itk::ProcessObject, ProcessObjectDeleter > m_Filter {nullptr}
double m_IntensityDifferenceThreshold { 0.001 }
double m_MaximumError { 0.1 }
unsigned int m_MaximumKernelWidth { 30u }
double m_MaximumRMSError { 0.02 }
uint32_t m_NumberOfIterations { 10u }
std::function< uint32_t()> m_pfGetElapsedIterations
std::function< double()> m_pfGetMetric
std::function< void()> m_pfGetStopRegistration
double m_RMSChange { 0.0 }
bool m_SmoothDisplacementField { true }
bool m_SmoothUpdateField { false }
std::vector< double > m_StandardDeviations { std::vector<double>(3, 1.0) }
std::vector< double > m_UpdateFieldStandardDeviations { std::vector<double>(3, 1.0) }
bool m_UseImageSpacing { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::SymmetricForcesDemonsRegistrationFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    fixedImage, const Image *
    movingImage, const Image *
    initialDisplacementField)
Setup for member function dispatching
Definition at line 274 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
PixelIDTypeList
using itk::simple::SymmetricForcesDemonsRegistrationFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 83 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Self
using itk::simple::SymmetricForcesDemonsRegistrationFilter::Self = SymmetricForcesDemonsRegistrationFilter
Definition at line 73 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Constructor & Destructor Documentation
~SymmetricForcesDemonsRegistrationFilter()
virtual itk::simple::SymmetricForcesDemonsRegistrationFilter::~SymmetricForcesDemonsRegistrationFilter () virtual
Destructor
SymmetricForcesDemonsRegistrationFilter()
itk::simple::SymmetricForcesDemonsRegistrationFilter::SymmetricForcesDemonsRegistrationFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/2]
Image itk::simple::SymmetricForcesDemonsRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage)
Execute() [2/2]
Image itk::simple::SymmetricForcesDemonsRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage, const Image & initialDisplacementField)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::SymmetricForcesDemonsRegistrationFilter::ExecuteInternal (const Image * fixedImage, const Image * movingImage, const Image * initialDisplacementField) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetElapsedIterations()
uint32_t itk::simple::SymmetricForcesDemonsRegistrationFilter::GetElapsedIterations () const inline
Number of iterations run.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 233 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_pfGetElapsedIterations.
GetIntensityDifferenceThreshold()
double itk::simple::SymmetricForcesDemonsRegistrationFilter::GetIntensityDifferenceThreshold () const inline
Definition at line 208 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
GetMaximumError()
double itk::simple::SymmetricForcesDemonsRegistrationFilter::GetMaximumError () const inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 197 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumError.
GetMaximumKernelWidth()
unsigned int itk::simple::SymmetricForcesDemonsRegistrationFilter::GetMaximumKernelWidth () const inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 185 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumKernelWidth.
GetMaximumRMSError()
double itk::simple::SymmetricForcesDemonsRegistrationFilter::GetMaximumRMSError () const inline
Definition at line 121 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumRMSError.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::SymmetricForcesDemonsRegistrationFilter::GetMemberFunctionFactory () static private
GetMetric()
double itk::simple::SymmetricForcesDemonsRegistrationFilter::GetMetric () const inline
Get the metric value. The metric value is the mean square difference in intensity between the fixed image and transforming moving image computed over the overlapping region between the two images. This value is calculated for the current iteration
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 250 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_pfGetMetric.
GetName()
std::string itk::simple::SymmetricForcesDemonsRegistrationFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 261 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
GetNumberOfIterations()
uint32_t itk::simple::SymmetricForcesDemonsRegistrationFilter::GetNumberOfIterations () const inline
Definition at line 111 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_NumberOfIterations.
GetRMSChange()
double itk::simple::SymmetricForcesDemonsRegistrationFilter::GetRMSChange () const inline
Set/Get the root mean squared change of the previous iteration. May not be used by all solvers.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 241 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_RMSChange.
GetSmoothDisplacementField()
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::GetSmoothDisplacementField () const inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 139 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_SmoothDisplacementField.
GetSmoothUpdateField()
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::GetSmoothUpdateField () const inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 157 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_SmoothUpdateField.
GetStandardDeviations()
std::vector< double > itk::simple::SymmetricForcesDemonsRegistrationFilter::GetStandardDeviations () const inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 101 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_StandardDeviations.
GetUpdateFieldStandardDeviations()
std::vector< double > itk::simple::SymmetricForcesDemonsRegistrationFilter::GetUpdateFieldStandardDeviations () const inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 173 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
GetUseImageSpacing()
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::GetUseImageSpacing () const inline
Definition at line 224 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_UseImageSpacing.
SetIntensityDifferenceThreshold()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold) inline
Set/Get the threshold below which the absolute difference of intensity yields a match. When the intensities match between a moving and fixed image pixel, the update vector (for that iteration) will be the zero vector. Default is 0.001.
Definition at line 203 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
SetMaximumError()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetMaximumError (double MaximumError) inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 191 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumError.
SetMaximumKernelWidth()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetMaximumKernelWidth (unsigned int MaximumKernelWidth) inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 179 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumKernelWidth.
SetMaximumRMSError()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetMaximumRMSError (double MaximumRMSError) inline
Definition at line 116 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_MaximumRMSError.
SetNumberOfIterations()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetNumberOfIterations (uint32_t NumberOfIterations) inline
Definition at line 106 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_NumberOfIterations.
SetSmoothDisplacementField()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetSmoothDisplacementField (bool SmoothDisplacementField) inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 127 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_SmoothDisplacementField.
Referenced by SmoothDisplacementFieldOff(), and SmoothDisplacementFieldOn().
SetSmoothUpdateField()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetSmoothUpdateField (bool SmoothUpdateField) inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 145 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_SmoothUpdateField.
Referenced by SmoothUpdateFieldOff(), and SmoothUpdateFieldOn().
SetStandardDeviations() [1/2]
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetStandardDeviations (double value) inline
Set the values of the StandardDeviations vector all to value
Definition at line 96 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_StandardDeviations.
SetStandardDeviations() [2/2]
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetStandardDeviations (std::vector< double > StandardDeviations) inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 91 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_StandardDeviations.
SetUpdateFieldStandardDeviations() [1/2]
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetUpdateFieldStandardDeviations (double value) inline
Set the values of the UpdateFieldStandardDeviations vector all to value
Definition at line 168 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUpdateFieldStandardDeviations() [2/2]
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations) inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 163 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUseImageSpacing()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Definition at line 213 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
SmoothDisplacementFieldOff()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SmoothDisplacementFieldOff () inline
Definition at line 134 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothDisplacementFieldOn()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SmoothDisplacementFieldOn () inline
Set the value of SmoothDisplacementField to true or false respectfully.
Definition at line 132 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothUpdateFieldOff()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SmoothUpdateFieldOff () inline
Definition at line 152 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetSmoothUpdateField().
SmoothUpdateFieldOn()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::SmoothUpdateFieldOn () inline
Set the value of SmoothUpdateField to true or false respectfully.
Definition at line 150 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetSmoothUpdateField().
StopRegistration()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::StopRegistration () inline
Stop the registration after the current iteration.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 258 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References m_pfGetStopRegistration.
ToString()
std::string itk::simple::SymmetricForcesDemonsRegistrationFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseImageSpacingOff()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::UseImageSpacingOff () inline
Definition at line 220 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::SymmetricForcesDemonsRegistrationFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 218 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 278 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Filter
std::unique_ptr<itk::ProcessObject, ProcessObjectDeleter> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_Filter {nullptr} private
Definition at line 317 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
m_IntensityDifferenceThreshold
double itk::simple::SymmetricForcesDemonsRegistrationFilter::m_IntensityDifferenceThreshold { 0.001 } private
Definition at line 304 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetIntensityDifferenceThreshold(), and SetIntensityDifferenceThreshold().
m_MaximumError
double itk::simple::SymmetricForcesDemonsRegistrationFilter::m_MaximumError { 0.1 } private
Definition at line 302 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetMaximumError(), and SetMaximumError().
m_MaximumKernelWidth
unsigned int itk::simple::SymmetricForcesDemonsRegistrationFilter::m_MaximumKernelWidth { 30u } private
Definition at line 300 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetMaximumKernelWidth(), and SetMaximumKernelWidth().
m_MaximumRMSError
double itk::simple::SymmetricForcesDemonsRegistrationFilter::m_MaximumRMSError { 0.02 } private
Definition at line 292 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetMaximumRMSError(), and SetMaximumRMSError().
m_NumberOfIterations
uint32_t itk::simple::SymmetricForcesDemonsRegistrationFilter::m_NumberOfIterations { 10u } private
Definition at line 289 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetNumberOfIterations(), and SetNumberOfIterations().
m_pfGetElapsedIterations
std::function<uint32_t()> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_pfGetElapsedIterations private
Definition at line 310 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetElapsedIterations().
m_pfGetMetric
std::function<double()> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_pfGetMetric private
Definition at line 312 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetMetric().
m_pfGetStopRegistration
std::function<void()> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_pfGetStopRegistration private
Definition at line 313 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by StopRegistration().
m_RMSChange
double itk::simple::SymmetricForcesDemonsRegistrationFilter::m_RMSChange { 0.0 } private
Definition at line 311 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetRMSChange().
m_SmoothDisplacementField
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::m_SmoothDisplacementField { true } private
Definition at line 294 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetSmoothDisplacementField(), and SetSmoothDisplacementField().
m_SmoothUpdateField
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::m_SmoothUpdateField { false } private
Definition at line 296 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetSmoothUpdateField(), and SetSmoothUpdateField().
m_StandardDeviations
std::vector<double> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_StandardDeviations { std::vector<double>(3, 1.0) } private
Definition at line 286 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetStandardDeviations(), SetStandardDeviations(), and SetStandardDeviations().
m_UpdateFieldStandardDeviations
std::vector<double> itk::simple::SymmetricForcesDemonsRegistrationFilter::m_UpdateFieldStandardDeviations { std::vector<double>(3, 1.0) } private
Definition at line 298 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetUpdateFieldStandardDeviations(), SetUpdateFieldStandardDeviations(), and SetUpdateFieldStandardDeviations().
m_UseImageSpacing
bool itk::simple::SymmetricForcesDemonsRegistrationFilter::m_UseImageSpacing { true } private
Definition at line 306 of file sitkSymmetricForcesDemonsRegistrationFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
The documentation for this class was generated from the following file:
sitkSymmetricForcesDemonsRegistrationFilter.h