SimpleITK: itk::simple::Euler3DTransform Class Reference
itk::simple::Euler3DTransform Class Reference
A rigid 3D transform with rotation in radians around a fixed center with translation.
#include <sitkEuler3DTransform.h>
Detailed Description
A rigid 3D transform with rotation in radians around a fixed center with translation.
See also
itk::Euler3DTransform
Definition at line 33 of file sitkEuler3DTransform.h.
Public Types
using Self = Euler3DTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
Self & ComputeZYXOff ()
Self & ComputeZYXOn ()
Euler3DTransform ()
Euler3DTransform (const Euler3DTransform &)
Euler3DTransform (const std::vector< double > &fixedCenter, double angleX=0.0, double angleY=0.0, double angleZ=0.0, const std::vector< double > &translation=std::vector< double >(3, 0.0))
Euler3DTransform (const Transform &)
double GetAngleX () const
double GetAngleY () const
double GetAngleZ () const
std::vector< double > GetCenter () const
bool GetComputeZYX () const
std::vector< double > GetMatrix () const
std::string GetName () const override
std::vector< double > GetTranslation () const
Euler3DTransform & operator= (const Euler3DTransform &)
Self & SetCenter (const std::vector< double > &params)
Self & SetComputeZYX (bool _arg)
Self & SetMatrix (const std::vector< double > &matrix, double tolerance=1e-10)
Self & SetRotation (double angleX, double angleY, double angleZ)
Self & SetTranslation (const std::vector< double > &translation)
~Euler3DTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< double()> m_pfGetAngleX
std::function< double()> m_pfGetAngleY
std::function< double()> m_pfGetAngleZ
std::function< std::vector< double >()> m_pfGetCenter
std::function< bool()> m_pfGetComputeZYX
std::function< std::vector< double >()> m_pfGetMatrix
std::function< std::vector< double >()> m_pfGetTranslation
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(bool)> m_pfSetComputeZYX
std::function< void(const std::vector< double > &, double)> m_pfSetMatrix
std::function< void(double, double, double)> m_pfSetRotation
std::function< void(const std::vector< double > &)> m_pfSetTranslation
Member Typedef Documentation
Self
using itk::simple::Euler3DTransform::Self = Euler3DTransform
Definition at line 36 of file sitkEuler3DTransform.h.
Superclass
using itk::simple::Euler3DTransform::Superclass = Transform
Definition at line 37 of file sitkEuler3DTransform.h.
Constructor & Destructor Documentation
~Euler3DTransform()
itk::simple::Euler3DTransform::~Euler3DTransform () override
Euler3DTransform() [1/4]
itk::simple::Euler3DTransform::Euler3DTransform ()
Referenced by Euler3DTransform(), Euler3DTransform(), and operator=().
Euler3DTransform() [2/4]
itk::simple::Euler3DTransform::Euler3DTransform (const std::vector< double > & fixedCenter, double angleX = 0.0, double angleY = 0.0, double angleZ = 0.0, const std::vector< double > & translation = std::vector< double >(3, 0.0)) explicit
Euler3DTransform() [3/4]
itk::simple::Euler3DTransform::Euler3DTransform (const Euler3DTransform &)
References Euler3DTransform().
Euler3DTransform() [4/4]
itk::simple::Euler3DTransform::Euler3DTransform (const Transform &) explicit
References Euler3DTransform(), and itk::simple::Transform::Transform().
Member Function Documentation
ComputeZYXOff()
Self & itk::simple::Euler3DTransform::ComputeZYXOff () inline
Definition at line 93 of file sitkEuler3DTransform.h.
References SetComputeZYX().
ComputeZYXOn()
Self & itk::simple::Euler3DTransform::ComputeZYXOn () inline
Definition at line 91 of file sitkEuler3DTransform.h.
References SetComputeZYX().
GetAngleX()
double itk::simple::Euler3DTransform::GetAngleX () const
GetAngleY()
double itk::simple::Euler3DTransform::GetAngleY () const
GetAngleZ()
double itk::simple::Euler3DTransform::GetAngleZ () const
GetCenter()
std::vector< double > itk::simple::Euler3DTransform::GetCenter () const
GetComputeZYX()
bool itk::simple::Euler3DTransform::GetComputeZYX () const
GetMatrix()
std::vector< double > itk::simple::Euler3DTransform::GetMatrix () const
additional methods
GetName()
std::string itk::simple::Euler3DTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 59 of file sitkEuler3DTransform.h.
GetTranslation()
std::vector< double > itk::simple::Euler3DTransform::GetTranslation () const
InternalInitialization() [1/2]
void itk::simple::Euler3DTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::Euler3DTransform::InternalInitialization (TransformType * transform) private
operator=()
Euler3DTransform & itk::simple::Euler3DTransform::operator= (const Euler3DTransform &)
References Euler3DTransform().
SetCenter()
Self & itk::simple::Euler3DTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetComputeZYX()
Self & itk::simple::Euler3DTransform::SetComputeZYX (bool _arg)
Referenced by ComputeZYXOff(), and ComputeZYXOn().
SetMatrix()
Self & itk::simple::Euler3DTransform::SetMatrix (const std::vector< double > & matrix, double tolerance = 1e-10)
SetPimpleTransform()
void itk::simple::Euler3DTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetRotation()
Self & itk::simple::Euler3DTransform::SetRotation (double angleX, double angleY, double angleZ)
parameter
SetTranslation()
Self & itk::simple::Euler3DTransform::SetTranslation (const std::vector< double > & translation)
Member Data Documentation
m_pfGetAngleX
std::function<double()> itk::simple::Euler3DTransform::m_pfGetAngleX private
Definition at line 118 of file sitkEuler3DTransform.h.
m_pfGetAngleY
std::function<double()> itk::simple::Euler3DTransform::m_pfGetAngleY private
Definition at line 119 of file sitkEuler3DTransform.h.
m_pfGetAngleZ
std::function<double()> itk::simple::Euler3DTransform::m_pfGetAngleZ private
Definition at line 120 of file sitkEuler3DTransform.h.
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::Euler3DTransform::m_pfGetCenter private
Definition at line 116 of file sitkEuler3DTransform.h.
m_pfGetComputeZYX
std::function<bool()> itk::simple::Euler3DTransform::m_pfGetComputeZYX private
Definition at line 124 of file sitkEuler3DTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::Euler3DTransform::m_pfGetMatrix private
Definition at line 125 of file sitkEuler3DTransform.h.
m_pfGetTranslation
std::function<std::vector<double>()> itk::simple::Euler3DTransform::m_pfGetTranslation private
Definition at line 122 of file sitkEuler3DTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::Euler3DTransform::m_pfSetCenter private
Definition at line 115 of file sitkEuler3DTransform.h.
m_pfSetComputeZYX
std::function<void(bool)> itk::simple::Euler3DTransform::m_pfSetComputeZYX private
Definition at line 123 of file sitkEuler3DTransform.h.
m_pfSetMatrix
std::function<void(const std::vector<double> &, double)> itk::simple::Euler3DTransform::m_pfSetMatrix private
Definition at line 126 of file sitkEuler3DTransform.h.
m_pfSetRotation
std::function<void(double, double, double)> itk::simple::Euler3DTransform::m_pfSetRotation private
Definition at line 117 of file sitkEuler3DTransform.h.
m_pfSetTranslation
std::function<void(const std::vector<double> &)> itk::simple::Euler3DTransform::m_pfSetTranslation private
Definition at line 121 of file sitkEuler3DTransform.h.
The documentation for this class was generated from the following file:
sitkEuler3DTransform.h