SimpleITK: itk::simple::FlipImageFilter Class Reference
itk::simple::FlipImageFilter Class Reference
Flips an image across user specified axes.
#include <sitkFlipImageFilter.h>
Detailed Description
Flips an image across user specified axes.
FlipImageFilter flips an image across user specified axes. The flip axes are set via method SetFlipAxes(array) where the input is a FixedArray<bool,ImageDimension>. The image is flipped across axes for which array[i] is true.
In terms of grid coordinates the image is flipped within the LargestPossibleRegion of the input image. As such, the LargestPossibleRegion of the output image is the same as the input.
In terms of geometric coordinates, the output origin is such that the image is flipped with respect to the coordinate axes.
See also
itk::simple::Flip for the procedural interface
itk::FlipImageFilter for the Doxygen on the original ITK class.
Definition at line 50 of file sitkFlipImageFilter.h.
Public Types
using PixelIDTypeList = NonLabelPixelIDTypeList
using Self = FlipImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1)
void FlipAboutOriginOff ()
void FlipAboutOriginOn ()
FlipImageFilter ()
bool GetFlipAboutOrigin () const
std::vector< bool > GetFlipAxes () const
std::string GetName () const
void SetFlipAboutOrigin (bool FlipAboutOrigin)
void SetFlipAxes (std::vector< bool > FlipAxes)
std::string ToString () const
virtual ~FlipImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_FlipAboutOrigin { false }
std::vector< bool > m_FlipAxes { std::vector<bool>(3, false) }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::FlipImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 114 of file sitkFlipImageFilter.h.
PixelIDTypeList
using itk::simple::FlipImageFilter::PixelIDTypeList = NonLabelPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 62 of file sitkFlipImageFilter.h.
Self
using itk::simple::FlipImageFilter::Self = FlipImageFilter
Definition at line 52 of file sitkFlipImageFilter.h.
Constructor & Destructor Documentation
~FlipImageFilter()
virtual itk::simple::FlipImageFilter::~FlipImageFilter () virtual
Destructor
FlipImageFilter()
itk::simple::FlipImageFilter::FlipImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::FlipImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::FlipImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FlipAboutOriginOff()
void itk::simple::FlipImageFilter::FlipAboutOriginOff () inline
Definition at line 92 of file sitkFlipImageFilter.h.
References SetFlipAboutOrigin().
FlipAboutOriginOn()
void itk::simple::FlipImageFilter::FlipAboutOriginOn () inline
Set the value of FlipAboutOrigin to true or false respectfully.
Definition at line 90 of file sitkFlipImageFilter.h.
References SetFlipAboutOrigin().
GetFlipAboutOrigin()
bool itk::simple::FlipImageFilter::GetFlipAboutOrigin () const inline
Controls how the output origin is computed. If FlipAboutOrigin is "On", the flip will occur about the origin of the axis, otherwise, the flip will occur about the center of the axis. Default is "On".
Definition at line 98 of file sitkFlipImageFilter.h.
References m_FlipAboutOrigin.
GetFlipAxes()
std::vector< bool > itk::simple::FlipImageFilter::GetFlipAxes () const inline
Set/Get the axis to be flipped. The image is flipped along axes for which array[i] is true. Default is false.
Definition at line 77 of file sitkFlipImageFilter.h.
References m_FlipAxes.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::FlipImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::FlipImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 102 of file sitkFlipImageFilter.h.
SetFlipAboutOrigin()
void itk::simple::FlipImageFilter::SetFlipAboutOrigin (bool FlipAboutOrigin) inline
Controls how the output origin is computed. If FlipAboutOrigin is "On", the flip will occur about the origin of the axis, otherwise, the flip will occur about the center of the axis. Default is "On".
Definition at line 85 of file sitkFlipImageFilter.h.
References m_FlipAboutOrigin.
Referenced by FlipAboutOriginOff(), and FlipAboutOriginOn().
SetFlipAxes()
void itk::simple::FlipImageFilter::SetFlipAxes (std::vector< bool > FlipAxes) inline
Set/Get the axis to be flipped. The image is flipped along axes for which array[i] is true. Default is false.
Definition at line 71 of file sitkFlipImageFilter.h.
References m_FlipAxes.
ToString()
std::string itk::simple::FlipImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 115 of file sitkFlipImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FlipAboutOrigin
bool itk::simple::FlipImageFilter::m_FlipAboutOrigin { false } private
Definition at line 122 of file sitkFlipImageFilter.h.
Referenced by GetFlipAboutOrigin(), and SetFlipAboutOrigin().
m_FlipAxes
std::vector<bool> itk::simple::FlipImageFilter::m_FlipAxes { std::vector<bool>(3, false) } private
Definition at line 120 of file sitkFlipImageFilter.h.
Referenced by GetFlipAxes(), and SetFlipAxes().
The documentation for this class was generated from the following file:
sitkFlipImageFilter.h