SimpleITK: itk::simple::MorphologicalWatershedImageFilter Class Reference
itk::simple::MorphologicalWatershedImageFilter Class Reference
Watershed segmentation implementation with morphological operators.
#include <sitkMorphologicalWatershedImageFilter.h>
Detailed Description
Watershed segmentation implementation with morphological operators.
Watershed pixel are labeled 0. TOutputImage should be an integer type. Labels of output image are in no particular order. You can reorder the labels such that object labels are consecutive and sorted based on object size by passing the output of this filter to a RelabelComponentImageFilter .
The morphological watershed transform algorithm is described in Chapter 9.2 of Pierre Soille's book "Morphological Image Analysis: Principles and Applications", Second Edition, Springer, 2003.
This code was contributed in the Insight Journal paper: "The watershed transform in ITK - discussion and new developments" by Beare R., Lehmann G. https://doi.org/10.54294/lf8u75
Author
Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA de Jouy-en-Josas, France.
See also
WatershedImageFilter , MorphologicalWatershedFromMarkersImageFilter
itk::simple::MorphologicalWatershed for the procedural interface
itk::MorphologicalWatershedImageFilter for the Doxygen on the original ITK class.
Definition at line 57 of file sitkMorphologicalWatershedImageFilter.h.
Public Types
using PixelIDTypeList = ScalarPixelIDTypeList
using Self = MorphologicalWatershedImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1)
void FullyConnectedOff ()
void FullyConnectedOn ()
bool GetFullyConnected () const
double GetLevel () const
bool GetMarkWatershedLine () const
std::string GetName () const
void MarkWatershedLineOff ()
void MarkWatershedLineOn ()
MorphologicalWatershedImageFilter ()
void SetFullyConnected (bool FullyConnected)
void SetLevel (double Level)
void SetMarkWatershedLine (bool MarkWatershedLine)
std::string ToString () const
virtual ~MorphologicalWatershedImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_FullyConnected { false }
double m_Level { 0.0 }
bool m_MarkWatershedLine { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::MorphologicalWatershedImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 140 of file sitkMorphologicalWatershedImageFilter.h.
PixelIDTypeList
using itk::simple::MorphologicalWatershedImageFilter::PixelIDTypeList = ScalarPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 69 of file sitkMorphologicalWatershedImageFilter.h.
Self
using itk::simple::MorphologicalWatershedImageFilter::Self = MorphologicalWatershedImageFilter
Definition at line 59 of file sitkMorphologicalWatershedImageFilter.h.
Constructor & Destructor Documentation
~MorphologicalWatershedImageFilter()
virtual itk::simple::MorphologicalWatershedImageFilter::~MorphologicalWatershedImageFilter () virtual
Destructor
MorphologicalWatershedImageFilter()
itk::simple::MorphologicalWatershedImageFilter::MorphologicalWatershedImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::MorphologicalWatershedImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::MorphologicalWatershedImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::MorphologicalWatershedImageFilter::FullyConnectedOff () inline
Definition at line 118 of file sitkMorphologicalWatershedImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::MorphologicalWatershedImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 116 of file sitkMorphologicalWatershedImageFilter.h.
References SetFullyConnected().
GetFullyConnected()
bool itk::simple::MorphologicalWatershedImageFilter::GetFullyConnected () const inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 124 of file sitkMorphologicalWatershedImageFilter.h.
References m_FullyConnected.
GetLevel()
double itk::simple::MorphologicalWatershedImageFilter::GetLevel () const inline
Definition at line 82 of file sitkMorphologicalWatershedImageFilter.h.
References m_Level.
GetMarkWatershedLine()
bool itk::simple::MorphologicalWatershedImageFilter::GetMarkWatershedLine () const inline
Set/Get whether the watershed pixel must be marked or not. Default is true. Set it to false do not only avoid writing watershed pixels, it also decrease algorithm complexity.
Definition at line 103 of file sitkMorphologicalWatershedImageFilter.h.
References m_MarkWatershedLine.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::MorphologicalWatershedImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::MorphologicalWatershedImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 128 of file sitkMorphologicalWatershedImageFilter.h.
MarkWatershedLineOff()
void itk::simple::MorphologicalWatershedImageFilter::MarkWatershedLineOff () inline
Definition at line 97 of file sitkMorphologicalWatershedImageFilter.h.
References SetMarkWatershedLine().
MarkWatershedLineOn()
void itk::simple::MorphologicalWatershedImageFilter::MarkWatershedLineOn () inline
Set the value of MarkWatershedLine to true or false respectfully.
Definition at line 95 of file sitkMorphologicalWatershedImageFilter.h.
References SetMarkWatershedLine().
SetFullyConnected()
void itk::simple::MorphologicalWatershedImageFilter::SetFullyConnected (bool FullyConnected) inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 111 of file sitkMorphologicalWatershedImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetLevel()
void itk::simple::MorphologicalWatershedImageFilter::SetLevel (double Level) inline
Definition at line 77 of file sitkMorphologicalWatershedImageFilter.h.
References m_Level.
SetMarkWatershedLine()
void itk::simple::MorphologicalWatershedImageFilter::SetMarkWatershedLine (bool MarkWatershedLine) inline
Set/Get whether the watershed pixel must be marked or not. Default is true. Set it to false do not only avoid writing watershed pixels, it also decrease algorithm complexity.
Definition at line 90 of file sitkMorphologicalWatershedImageFilter.h.
References m_MarkWatershedLine.
Referenced by MarkWatershedLineOff(), and MarkWatershedLineOn().
ToString()
std::string itk::simple::MorphologicalWatershedImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 141 of file sitkMorphologicalWatershedImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FullyConnected
bool itk::simple::MorphologicalWatershedImageFilter::m_FullyConnected { false } private
Definition at line 150 of file sitkMorphologicalWatershedImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_Level
double itk::simple::MorphologicalWatershedImageFilter::m_Level { 0.0 } private
Definition at line 146 of file sitkMorphologicalWatershedImageFilter.h.
Referenced by GetLevel(), and SetLevel().
m_MarkWatershedLine
bool itk::simple::MorphologicalWatershedImageFilter::m_MarkWatershedLine { true } private
Definition at line 148 of file sitkMorphologicalWatershedImageFilter.h.
Referenced by GetMarkWatershedLine(), and SetMarkWatershedLine().
The documentation for this class was generated from the following file:
sitkMorphologicalWatershedImageFilter.h