SimpleITK: itk::simple::DiffeomorphicDemonsRegistrationFilter Class Reference
itk::simple::DiffeomorphicDemonsRegistrationFilter Class Reference
Deformably register two images using a diffeomorphic demons algorithm.
#include <sitkDiffeomorphicDemonsRegistrationFilter.h>
Detailed Description
Deformably register two images using a diffeomorphic demons algorithm.
This class was contributed by Tom Vercauteren, INRIA & Mauna Kea Technologies, based on a variation of the DemonsRegistrationFilter . The basic modification is to use diffeomorphism exponentials.
See T. Vercauteren, X. Pennec, A. Perchant and N. Ayache, "Non-parametric Diffeomorphic Image Registration with the Demons Algorithm", Proc. of MICCAI 2007.
DiffeomorphicDemonsRegistrationFilter implements the demons deformable algorithm that register two images by computing the deformation field which will map a moving image onto a fixed image.
A deformation field is represented as a image whose pixel type is some vector type with at least N elements, where N is the dimension of the fixed image. The vector type must support element access via operator []. It is assumed that the vector elements behave like floating point scalars.
This class is templated over the fixed image type, moving image type and the deformation field type.
The input fixed and moving images are set via methods SetFixedImage and SetMovingImage respectively. An initial deformation field maybe set via SetInitialDisplacementField or SetInput. If no initial field is set, a zero field is used as the initial condition.
The output deformation field can be obtained via methods GetOutput or GetDisplacementField.
This class make use of the finite difference solver hierarchy. Update for each iteration is computed in DemonsRegistrationFunction .
Author
Tom Vercauteren, INRIA & Mauna Kea Technologies
Warning
This filter assumes that the fixed image type, moving image type and deformation field type all have the same number of dimensions.
This implementation was taken from the Insight Journal paper: https://doi.org/10.54294/ux2obj
See also
DemonsRegistrationFilter
DemonsRegistrationFunction
itk::DiffeomorphicDemonsRegistrationFilter for the Doxygen on the original ITK class.
Definition at line 68 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = DiffeomorphicDemonsRegistrationFilter
enum UseGradientTypeType {
Symmetric ,
Fixed ,
WarpedMoving ,
MappedMoving
}
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
DiffeomorphicDemonsRegistrationFilter ()
Image Execute (const Image &fixedImage, const Image &movingImage)
Image Execute (const Image &fixedImage, const Image &movingImage, const Image &initialDisplacementField)
uint32_t GetElapsedIterations () const
Number of iterations run.
double GetIntensityDifferenceThreshold () const
double GetMaximumError () const
unsigned int GetMaximumKernelWidth () const
double GetMaximumRMSError () const
double GetMaximumUpdateStepLength () const
double GetMetric () const
std::string GetName () const
uint32_t GetNumberOfIterations () const
double GetRMSChange () const
bool GetSmoothDisplacementField () const
bool GetSmoothUpdateField () const
std::vector< double > GetStandardDeviations () const
std::vector< double > GetUpdateFieldStandardDeviations () const
bool GetUseFirstOrderExp () const
UseGradientTypeType GetUseGradientType () const
bool GetUseImageSpacing () const
void SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold)
void SetMaximumError (double MaximumError)
void SetMaximumKernelWidth (unsigned int MaximumKernelWidth)
void SetMaximumRMSError (double MaximumRMSError)
void SetMaximumUpdateStepLength (double MaximumUpdateStepLength)
void SetNumberOfIterations (uint32_t NumberOfIterations)
void SetSmoothDisplacementField (bool SmoothDisplacementField)
void SetSmoothUpdateField (bool SmoothUpdateField)
void SetStandardDeviations (double value)
void SetStandardDeviations (std::vector< double > StandardDeviations)
void SetUpdateFieldStandardDeviations (double value)
void SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations)
void SetUseFirstOrderExp (bool UseFirstOrderExp)
void SetUseGradientType (UseGradientTypeType UseGradientType)
void SetUseImageSpacing (bool UseImageSpacing)
void SmoothDisplacementFieldOff ()
void SmoothDisplacementFieldOn ()
void SmoothUpdateFieldOff ()
void SmoothUpdateFieldOn ()
void StopRegistration ()
std::string ToString () const
void UseFirstOrderExpOff ()
void UseFirstOrderExpOn ()
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~DiffeomorphicDemonsRegistrationFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image * fixedImage, const Image * movingImage, const Image * initialDisplacementField)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *fixedImage, const Image *movingImage, const Image *initialDisplacementField)
Private Attributes
itk::ProcessObject * m_Filter {nullptr}
double m_IntensityDifferenceThreshold {0.001}
double m_MaximumError {0.1}
unsigned int m_MaximumKernelWidth {30u}
double m_MaximumRMSError {0.02}
double m_MaximumUpdateStepLength {0.5}
std::unique_ptr< detail::MemberFunctionFactory< MemberFunctionType > > m_MemberFactory
uint32_t m_NumberOfIterations {10u}
std::function< uint32_t()> m_pfGetElapsedIterations
std::function< double()> m_pfGetMetric
std::function< void()> m_pfGetStopRegistration
double m_RMSChange {0.0}
bool m_SmoothDisplacementField {true}
bool m_SmoothUpdateField {false}
std::vector< double > m_StandardDeviations {std::vector<double>(3, 1.0)}
std::vector< double > m_UpdateFieldStandardDeviations {std::vector<double>(3, 1.0)}
bool m_UseFirstOrderExp {false}
UseGradientTypeType m_UseGradientType {itk::simple::DiffeomorphicDemonsRegistrationFilter::Symmetric}
bool m_UseImageSpacing {true}
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::DiffeomorphicDemonsRegistrationFilter::MemberFunctionType = Image (Self::*)(const Image * fixedImage, const Image * movingImage, const Image * initialDisplacementField) private
Setup for member function dispatching
Definition at line 278 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
PixelIDTypeList
using itk::simple::DiffeomorphicDemonsRegistrationFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 80 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Self
using itk::simple::DiffeomorphicDemonsRegistrationFilter::Self = DiffeomorphicDemonsRegistrationFilter
Definition at line 70 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Member Enumeration Documentation
UseGradientTypeType
enum itk::simple::DiffeomorphicDemonsRegistrationFilter::UseGradientTypeType
Enumerator
Symmetric
Fixed
WarpedMoving
MappedMoving
Definition at line 112 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Constructor & Destructor Documentation
~DiffeomorphicDemonsRegistrationFilter()
virtual itk::simple::DiffeomorphicDemonsRegistrationFilter::~DiffeomorphicDemonsRegistrationFilter () virtual
Destructor
DiffeomorphicDemonsRegistrationFilter()
itk::simple::DiffeomorphicDemonsRegistrationFilter::DiffeomorphicDemonsRegistrationFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/2]
Image itk::simple::DiffeomorphicDemonsRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage)
Execute() [2/2]
Image itk::simple::DiffeomorphicDemonsRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage, const Image & initialDisplacementField)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::DiffeomorphicDemonsRegistrationFilter::ExecuteInternal (const Image * fixedImage, const Image * movingImage, const Image * initialDisplacementField) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetElapsedIterations()
uint32_t itk::simple::DiffeomorphicDemonsRegistrationFilter::GetElapsedIterations () const inline
Number of iterations run.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 233 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_pfGetElapsedIterations.
GetIntensityDifferenceThreshold()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetIntensityDifferenceThreshold () const inline
Definition at line 213 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
GetMaximumError()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetMaximumError () const inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 204 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumError.
GetMaximumKernelWidth()
unsigned int itk::simple::DiffeomorphicDemonsRegistrationFilter::GetMaximumKernelWidth () const inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 194 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumKernelWidth.
GetMaximumRMSError()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetMaximumRMSError () const inline
Definition at line 110 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumRMSError.
GetMaximumUpdateStepLength()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetMaximumUpdateStepLength () const inline
Definition at line 143 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumUpdateStepLength.
GetMetric()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetMetric () const inline
Get the metric value. The metric value is the mean square difference in intensity between the fixed image and transforming moving image computed over the overlapping region between the two images. This value is calculated for the current iteration
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 250 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_pfGetMetric.
GetName()
std::string itk::simple::DiffeomorphicDemonsRegistrationFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 263 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
GetNumberOfIterations()
uint32_t itk::simple::DiffeomorphicDemonsRegistrationFilter::GetNumberOfIterations () const inline
Definition at line 102 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_NumberOfIterations.
GetRMSChange()
double itk::simple::DiffeomorphicDemonsRegistrationFilter::GetRMSChange () const inline
Set/Get the root mean squared change of the previous iteration. May not be used by all solvers.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 241 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_RMSChange.
GetSmoothDisplacementField()
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::GetSmoothDisplacementField () const inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 157 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_SmoothDisplacementField.
GetSmoothUpdateField()
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::GetSmoothUpdateField () const inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 171 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_SmoothUpdateField.
GetStandardDeviations()
std::vector< double > itk::simple::DiffeomorphicDemonsRegistrationFilter::GetStandardDeviations () const inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 94 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_StandardDeviations.
GetUpdateFieldStandardDeviations()
std::vector< double > itk::simple::DiffeomorphicDemonsRegistrationFilter::GetUpdateFieldStandardDeviations () const inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 184 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
GetUseFirstOrderExp()
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::GetUseFirstOrderExp () const inline
Use a first-order approximation of the exponential. This amounts to using an update rule of the type s <- s o (Id + u) instead of s <- s o exp(u)
Definition at line 134 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseFirstOrderExp.
GetUseGradientType()
UseGradientTypeType itk::simple::DiffeomorphicDemonsRegistrationFilter::GetUseGradientType () const inline
Definition at line 120 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseGradientType.
GetUseImageSpacing()
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::GetUseImageSpacing () const inline
Definition at line 225 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseImageSpacing.
SetIntensityDifferenceThreshold()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold) inline
Set/Get the threshold below which the absolute difference of intensity yields a match. When the intensities match between a moving and fixed image pixel, the update vector (for that iteration) will be the zero vector. Default is 0.001.
Definition at line 209 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
SetMaximumError()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetMaximumError (double MaximumError) inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 199 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumError.
SetMaximumKernelWidth()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetMaximumKernelWidth (unsigned int MaximumKernelWidth) inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 189 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumKernelWidth.
SetMaximumRMSError()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetMaximumRMSError (double MaximumRMSError) inline
Definition at line 106 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumRMSError.
SetMaximumUpdateStepLength()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetMaximumUpdateStepLength (double MaximumUpdateStepLength) inline
Set/Get the maximum length in terms of pixels of the vectors in the update buffer.
Definition at line 139 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_MaximumUpdateStepLength.
SetNumberOfIterations()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetNumberOfIterations (uint32_t NumberOfIterations) inline
Definition at line 98 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_NumberOfIterations.
SetSmoothDisplacementField()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetSmoothDisplacementField (bool SmoothDisplacementField) inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 148 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_SmoothDisplacementField.
Referenced by SmoothDisplacementFieldOff(), and SmoothDisplacementFieldOn().
SetSmoothUpdateField()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetSmoothUpdateField (bool SmoothUpdateField) inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 162 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_SmoothUpdateField.
Referenced by SmoothUpdateFieldOff(), and SmoothUpdateFieldOn().
SetStandardDeviations() [1/2]
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetStandardDeviations (double value) inline
Set the values of the StandardDeviations vector all to value
Definition at line 89 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_StandardDeviations.
SetStandardDeviations() [2/2]
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetStandardDeviations (std::vector< double > StandardDeviations) inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 86 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_StandardDeviations.
SetUpdateFieldStandardDeviations() [1/2]
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetUpdateFieldStandardDeviations (double value) inline
Set the values of the UpdateFieldStandardDeviations vector all to value
Definition at line 179 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUpdateFieldStandardDeviations() [2/2]
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations) inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 176 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUseFirstOrderExp()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetUseFirstOrderExp (bool UseFirstOrderExp) inline
Use a first-order approximation of the exponential. This amounts to using an update rule of the type s <- s o (Id + u) instead of s <- s o exp(u)
Definition at line 125 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseFirstOrderExp.
Referenced by UseFirstOrderExpOff(), and UseFirstOrderExpOn().
SetUseGradientType()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetUseGradientType (UseGradientTypeType UseGradientType) inline
Definition at line 116 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseGradientType.
SetUseImageSpacing()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Definition at line 217 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
SmoothDisplacementFieldOff()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SmoothDisplacementFieldOff () inline
Definition at line 152 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothDisplacementFieldOn()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SmoothDisplacementFieldOn () inline
Set the value of SmoothDisplacementField to true or false respectfully.
Definition at line 151 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothUpdateFieldOff()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SmoothUpdateFieldOff () inline
Definition at line 166 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetSmoothUpdateField().
SmoothUpdateFieldOn()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::SmoothUpdateFieldOn () inline
Set the value of SmoothUpdateField to true or false respectfully.
Definition at line 165 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetSmoothUpdateField().
StopRegistration()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::StopRegistration () inline
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 259 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References m_pfGetStopRegistration.
ToString()
std::string itk::simple::DiffeomorphicDemonsRegistrationFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseFirstOrderExpOff()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::UseFirstOrderExpOff () inline
Definition at line 129 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetUseFirstOrderExp().
UseFirstOrderExpOn()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::UseFirstOrderExpOn () inline
Set the value of UseFirstOrderExp to true or false respectfully.
Definition at line 128 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetUseFirstOrderExp().
UseImageSpacingOff()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::UseImageSpacingOff () inline
Definition at line 221 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::DiffeomorphicDemonsRegistrationFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 220 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 279 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Filter
itk::ProcessObject* itk::simple::DiffeomorphicDemonsRegistrationFilter::m_Filter {nullptr} private
Definition at line 325 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
m_IntensityDifferenceThreshold
double itk::simple::DiffeomorphicDemonsRegistrationFilter::m_IntensityDifferenceThreshold {0.001} private
Definition at line 311 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetIntensityDifferenceThreshold(), and SetIntensityDifferenceThreshold().
m_MaximumError
double itk::simple::DiffeomorphicDemonsRegistrationFilter::m_MaximumError {0.1} private
Definition at line 309 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetMaximumError(), and SetMaximumError().
m_MaximumKernelWidth
unsigned int itk::simple::DiffeomorphicDemonsRegistrationFilter::m_MaximumKernelWidth {30u} private
Definition at line 307 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetMaximumKernelWidth(), and SetMaximumKernelWidth().
m_MaximumRMSError
double itk::simple::DiffeomorphicDemonsRegistrationFilter::m_MaximumRMSError {0.02} private
Definition at line 293 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetMaximumRMSError(), and SetMaximumRMSError().
m_MaximumUpdateStepLength
double itk::simple::DiffeomorphicDemonsRegistrationFilter::m_MaximumUpdateStepLength {0.5} private
Definition at line 299 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetMaximumUpdateStepLength(), and SetMaximumUpdateStepLength().
m_MemberFactory
std::unique_ptr<detail::MemberFunctionFactory<MemberFunctionType> > itk::simple::DiffeomorphicDemonsRegistrationFilter::m_MemberFactory private
Definition at line 284 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
m_NumberOfIterations
uint32_t itk::simple::DiffeomorphicDemonsRegistrationFilter::m_NumberOfIterations {10u} private
Definition at line 290 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetNumberOfIterations(), and SetNumberOfIterations().
m_pfGetElapsedIterations
std::function<uint32_t()> itk::simple::DiffeomorphicDemonsRegistrationFilter::m_pfGetElapsedIterations private
Definition at line 316 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetElapsedIterations().
m_pfGetMetric
std::function<double()> itk::simple::DiffeomorphicDemonsRegistrationFilter::m_pfGetMetric private
Definition at line 320 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetMetric().
m_pfGetStopRegistration
std::function<void()> itk::simple::DiffeomorphicDemonsRegistrationFilter::m_pfGetStopRegistration private
Definition at line 322 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by StopRegistration().
m_RMSChange
double itk::simple::DiffeomorphicDemonsRegistrationFilter::m_RMSChange {0.0} private
Definition at line 318 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetRMSChange().
m_SmoothDisplacementField
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::m_SmoothDisplacementField {true} private
Definition at line 301 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetSmoothDisplacementField(), and SetSmoothDisplacementField().
m_SmoothUpdateField
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::m_SmoothUpdateField {false} private
Definition at line 303 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetSmoothUpdateField(), and SetSmoothUpdateField().
m_StandardDeviations
std::vector<double> itk::simple::DiffeomorphicDemonsRegistrationFilter::m_StandardDeviations {std::vector<double>(3, 1.0)} private
Definition at line 287 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetStandardDeviations(), SetStandardDeviations(), and SetStandardDeviations().
m_UpdateFieldStandardDeviations
std::vector<double> itk::simple::DiffeomorphicDemonsRegistrationFilter::m_UpdateFieldStandardDeviations {std::vector<double>(3, 1.0)} private
Definition at line 305 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetUpdateFieldStandardDeviations(), SetUpdateFieldStandardDeviations(), and SetUpdateFieldStandardDeviations().
m_UseFirstOrderExp
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::m_UseFirstOrderExp {false} private
Definition at line 297 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetUseFirstOrderExp(), and SetUseFirstOrderExp().
m_UseGradientType
UseGradientTypeType itk::simple::DiffeomorphicDemonsRegistrationFilter::m_UseGradientType {itk::simple::DiffeomorphicDemonsRegistrationFilter::Symmetric} private
Definition at line 295 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetUseGradientType(), and SetUseGradientType().
m_UseImageSpacing
bool itk::simple::DiffeomorphicDemonsRegistrationFilter::m_UseImageSpacing {true} private
Definition at line 313 of file sitkDiffeomorphicDemonsRegistrationFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
The documentation for this class was generated from the following file:
sitkDiffeomorphicDemonsRegistrationFilter.h