SimpleITK: itk::simple::FFTConvolutionImageFilter Class Reference
itk::simple::FFTConvolutionImageFilter Class Reference
Convolve a given image with an arbitrary image kernel using multiplication in the Fourier domain.
#include <sitkFFTConvolutionImageFilter.h>
Detailed Description
Convolve a given image with an arbitrary image kernel using multiplication in the Fourier domain.
This filter produces output equivalent to the output of the ConvolutionImageFilter . However, it takes advantage of the convolution theorem to accelerate the convolution computation when the kernel is large.
Warning
This filter ignores the spacing, origin, and orientation of the kernel image and treats them as identical to those in the input image.
This code was adapted from the Insight Journal contribution:
"FFT Based Convolution" by Gaetan Lehmann https://doi.org/10.54294/0iky0u
See also
ConvolutionImageFilter
InverseDeconvolutionImageFilter
IterativeDeconvolutionImageFilter
itk::simple::FFTConvolution for the procedural interface
itk::FFTConvolutionImageFilter for the Doxygen on the original ITK class.
Definition at line 60 of file sitkFFTConvolutionImageFilter.h.
Public Types
enum BoundaryConditionType {
ZERO_PAD ,
ZERO_FLUX_NEUMANN_PAD ,
PERIODIC_PAD
}
enum OutputRegionModeType {
SAME ,
VALID
}
using PixelIDTypeList = BasicPixelIDTypeList
using Self = FFTConvolutionImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image, const Image &kernelImage)
FFTConvolutionImageFilter ()
BoundaryConditionType GetBoundaryCondition () const
std::string GetName () const
bool GetNormalize () const
OutputRegionModeType GetOutputRegionMode () const
void NormalizeOff ()
void NormalizeOn ()
void SetBoundaryCondition (BoundaryConditionType BoundaryCondition)
void SetNormalize (bool Normalize)
void SetOutputRegionMode (OutputRegionModeType OutputRegionMode)
std::string ToString () const
virtual ~FFTConvolutionImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *image, const Image *kernelImage)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
BoundaryConditionType m_BoundaryCondition { itk::simple::FFTConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD }
bool m_Normalize { false }
OutputRegionModeType m_OutputRegionMode { itk::simple::FFTConvolutionImageFilter::SAME }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::FFTConvolutionImageFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    image, const Image *
    kernelImage)
Setup for member function dispatching
Definition at line 132 of file sitkFFTConvolutionImageFilter.h.
PixelIDTypeList
using itk::simple::FFTConvolutionImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 72 of file sitkFFTConvolutionImageFilter.h.
Self
using itk::simple::FFTConvolutionImageFilter::Self = FFTConvolutionImageFilter
Definition at line 62 of file sitkFFTConvolutionImageFilter.h.
Member Enumeration Documentation
BoundaryConditionType
enum itk::simple::FFTConvolutionImageFilter::BoundaryConditionType
Enumerator
ZERO_PAD
ZERO_FLUX_NEUMANN_PAD
PERIODIC_PAD
Definition at line 94 of file sitkFFTConvolutionImageFilter.h.
OutputRegionModeType
enum itk::simple::FFTConvolutionImageFilter::OutputRegionModeType
Enumerator
SAME
VALID
Definition at line 106 of file sitkFFTConvolutionImageFilter.h.
Constructor & Destructor Documentation
~FFTConvolutionImageFilter()
virtual itk::simple::FFTConvolutionImageFilter::~FFTConvolutionImageFilter () virtual
Destructor
FFTConvolutionImageFilter()
itk::simple::FFTConvolutionImageFilter::FFTConvolutionImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::FFTConvolutionImageFilter::Execute (const Image & image, const Image & kernelImage)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::FFTConvolutionImageFilter::ExecuteInternal (const Image * image, const Image * kernelImage) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetBoundaryCondition()
BoundaryConditionType itk::simple::FFTConvolutionImageFilter::GetBoundaryCondition () const inline
Definition at line 104 of file sitkFFTConvolutionImageFilter.h.
References m_BoundaryCondition.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::FFTConvolutionImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::FFTConvolutionImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 120 of file sitkFFTConvolutionImageFilter.h.
GetNormalize()
bool itk::simple::FFTConvolutionImageFilter::GetNormalize () const inline
Definition at line 92 of file sitkFFTConvolutionImageFilter.h.
References m_Normalize.
GetOutputRegionMode()
OutputRegionModeType itk::simple::FFTConvolutionImageFilter::GetOutputRegionMode () const inline
Definition at line 116 of file sitkFFTConvolutionImageFilter.h.
References m_OutputRegionMode.
NormalizeOff()
void itk::simple::FFTConvolutionImageFilter::NormalizeOff () inline
Definition at line 88 of file sitkFFTConvolutionImageFilter.h.
References SetNormalize().
NormalizeOn()
void itk::simple::FFTConvolutionImageFilter::NormalizeOn () inline
Set the value of Normalize to true or false respectfully.
Definition at line 86 of file sitkFFTConvolutionImageFilter.h.
References SetNormalize().
SetBoundaryCondition()
void itk::simple::FFTConvolutionImageFilter::SetBoundaryCondition (BoundaryConditionType BoundaryCondition) inline
Definition at line 99 of file sitkFFTConvolutionImageFilter.h.
References m_BoundaryCondition.
SetNormalize()
void itk::simple::FFTConvolutionImageFilter::SetNormalize (bool Normalize) inline
Normalize the output image by the sum of the kernel components
Definition at line 81 of file sitkFFTConvolutionImageFilter.h.
References m_Normalize, and itk::simple::Normalize().
Referenced by NormalizeOff(), and NormalizeOn().
SetOutputRegionMode()
void itk::simple::FFTConvolutionImageFilter::SetOutputRegionMode (OutputRegionModeType OutputRegionMode) inline
Definition at line 111 of file sitkFFTConvolutionImageFilter.h.
References m_OutputRegionMode.
ToString()
std::string itk::simple::FFTConvolutionImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 135 of file sitkFFTConvolutionImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_BoundaryCondition
BoundaryConditionType itk::simple::FFTConvolutionImageFilter::m_BoundaryCondition { itk::simple::FFTConvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD } private
Definition at line 144 of file sitkFFTConvolutionImageFilter.h.
Referenced by GetBoundaryCondition(), and SetBoundaryCondition().
m_Normalize
bool itk::simple::FFTConvolutionImageFilter::m_Normalize { false } private
Definition at line 142 of file sitkFFTConvolutionImageFilter.h.
Referenced by GetNormalize(), and SetNormalize().
m_OutputRegionMode
OutputRegionModeType itk::simple::FFTConvolutionImageFilter::m_OutputRegionMode { itk::simple::FFTConvolutionImageFilter::SAME } private
Definition at line 146 of file sitkFFTConvolutionImageFilter.h.
Referenced by GetOutputRegionMode(), and SetOutputRegionMode().
The documentation for this class was generated from the following file:
sitkFFTConvolutionImageFilter.h