SimpleITK: itk::simple::AreaClosingImageFilter Class Reference
itk::simple::AreaClosingImageFilter Class Reference
Morphological closing by attributes.
#include <sitkAreaClosingImageFilter.h>
Detailed Description
Morphological closing by attributes.
An attribute closing removes blobs according to criteria such as area. When applied to grayscale images they have the effect of filling valleys (regions darker than their surroundings) based on area while leaving the rest of the image unchanged.
This code was contributed in the Insight Journal paper
"Grayscale morphological attribute operations" by Beare R. https://doi.org/10.54294/ifvjls
Author
Richard Beare. Department of Medicine, Monash University, Melbourne, Australia.
See also
itk::simple::AreaClosing for the procedural interface
itk::AreaClosingImageFilter for the Doxygen on the original ITK class.
Definition at line 53 of file sitkAreaClosingImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = AreaClosingImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
AreaClosingImageFilter ()
Image Execute (const Image &image1)
void FullyConnectedOff ()
void FullyConnectedOn ()
bool GetFullyConnected () const
double GetLambda () const
std::string GetName () const
bool GetUseImageSpacing () const
void SetFullyConnected (bool FullyConnected)
void SetLambda (double Lambda)
The size of the area opening.
void SetUseImageSpacing (bool UseImageSpacing)
std::string ToString () const
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~AreaClosingImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Private Attributes
bool m_FullyConnected { false }
double m_Lambda { 0.0 }
std::unique_ptr< detail::MemberFunctionFactory< MemberFunctionType > > m_MemberFactory
bool m_UseImageSpacing { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::AreaClosingImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 128 of file sitkAreaClosingImageFilter.h.
PixelIDTypeList
using itk::simple::AreaClosingImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 65 of file sitkAreaClosingImageFilter.h.
Self
using itk::simple::AreaClosingImageFilter::Self = AreaClosingImageFilter
Definition at line 55 of file sitkAreaClosingImageFilter.h.
Constructor & Destructor Documentation
~AreaClosingImageFilter()
virtual itk::simple::AreaClosingImageFilter::~AreaClosingImageFilter () virtual
Destructor
AreaClosingImageFilter()
itk::simple::AreaClosingImageFilter::AreaClosingImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::AreaClosingImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::AreaClosingImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::AreaClosingImageFilter::FullyConnectedOff () inline
Definition at line 108 of file sitkAreaClosingImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::AreaClosingImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 106 of file sitkAreaClosingImageFilter.h.
References SetFullyConnected().
GetFullyConnected()
bool itk::simple::AreaClosingImageFilter::GetFullyConnected () const inline
Definition at line 112 of file sitkAreaClosingImageFilter.h.
References m_FullyConnected.
GetLambda()
double itk::simple::AreaClosingImageFilter::GetLambda () const inline
Definition at line 78 of file sitkAreaClosingImageFilter.h.
References m_Lambda.
GetName()
std::string itk::simple::AreaClosingImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 116 of file sitkAreaClosingImageFilter.h.
GetUseImageSpacing()
bool itk::simple::AreaClosingImageFilter::GetUseImageSpacing () const inline
Set/Get whether the image spacing is used or not - defaults to true.
Definition at line 96 of file sitkAreaClosingImageFilter.h.
References m_UseImageSpacing.
SetFullyConnected()
void itk::simple::AreaClosingImageFilter::SetFullyConnected (bool FullyConnected) inline
Definition at line 101 of file sitkAreaClosingImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetLambda()
void itk::simple::AreaClosingImageFilter::SetLambda (double Lambda) inline
The size of the area opening.
Definition at line 73 of file sitkAreaClosingImageFilter.h.
References m_Lambda.
SetUseImageSpacing()
void itk::simple::AreaClosingImageFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Set/Get whether the image spacing is used or not - defaults to true.
Definition at line 84 of file sitkAreaClosingImageFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
ToString()
std::string itk::simple::AreaClosingImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseImageSpacingOff()
void itk::simple::AreaClosingImageFilter::UseImageSpacingOff () inline
Definition at line 91 of file sitkAreaClosingImageFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::AreaClosingImageFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 89 of file sitkAreaClosingImageFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 129 of file sitkAreaClosingImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FullyConnected
bool itk::simple::AreaClosingImageFilter::m_FullyConnected { false } private
Definition at line 138 of file sitkAreaClosingImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_Lambda
double itk::simple::AreaClosingImageFilter::m_Lambda { 0.0 } private
Definition at line 134 of file sitkAreaClosingImageFilter.h.
Referenced by GetLambda(), and SetLambda().
m_MemberFactory
std::unique_ptr<detail::MemberFunctionFactory<MemberFunctionType> > itk::simple::AreaClosingImageFilter::m_MemberFactory private
Definition at line 131 of file sitkAreaClosingImageFilter.h.
m_UseImageSpacing
bool itk::simple::AreaClosingImageFilter::m_UseImageSpacing { true } private
Definition at line 136 of file sitkAreaClosingImageFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
The documentation for this class was generated from the following file:
sitkAreaClosingImageFilter.h