SimpleITK: itk::simple::ScaleVersor3DTransform Class Reference
itk::simple::ScaleVersor3DTransform Class Reference
A parameterized 3D transform composed of the addition of a versor rotation matrix and a scale matrix around a fixed center with translation.
#include <sitkScaleVersor3DTransform.h>
Detailed Description
A parameterized 3D transform composed of the addition of a versor rotation matrix and a scale matrix around a fixed center with translation.
See also
itk::ScaleVersor3DTransform
Definition at line 35 of file sitkScaleVersor3DTransform.h.
Public Types
using Self = ScaleVersor3DTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
std::vector< double > GetCenter () const
std::vector< double > GetMatrix () const
std::string GetName () const override
std::vector< double > GetScale () const
std::vector< double > GetTranslation () const
std::vector< double > GetVersor () const
ScaleVersor3DTransform & operator= (const ScaleVersor3DTransform &)
ScaleVersor3DTransform ()
ScaleVersor3DTransform (const ScaleVersor3DTransform &)
ScaleVersor3DTransform (const std::vector< double > &scale, const std::vector< double > &axis, double angle, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
ScaleVersor3DTransform (const std::vector< double > &scale, const std::vector< double > &versor, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
ScaleVersor3DTransform (const Transform &)
void SetCenter (const std::vector< double > &params)
void SetRotation (const std::vector< double > &axis, double angle)
void SetRotation (const std::vector< double > &versor)
void SetScale (const std::vector< double > &scale)
void SetTranslation (const std::vector< double > &translation)
void Translate (const std::vector< double > &offset)
~ScaleVersor3DTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< std::vector< double >()> m_pfGetCenter
std::function< std::vector< double >()> m_pfGetMatrix
std::function< std::vector< double >()> m_pfGetScale
std::function< std::vector< double >()> m_pfGetTranslation
std::function< std::vector< double >()> m_pfGetVersor
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(const std::vector< double > &)> m_pfSetRotation1
std::function< void(const std::vector< double > &, double)> m_pfSetRotation2
std::function< void(const std::vector< double > &)> m_pfSetScale
std::function< void(const std::vector< double > &)> m_pfSetTranslation
std::function< void(const std::vector< double > &)> m_pfTranslate
Member Typedef Documentation
Self
using itk::simple::ScaleVersor3DTransform::Self = ScaleVersor3DTransform
Definition at line 38 of file sitkScaleVersor3DTransform.h.
Superclass
using itk::simple::ScaleVersor3DTransform::Superclass = Transform
Definition at line 39 of file sitkScaleVersor3DTransform.h.
Constructor & Destructor Documentation
~ScaleVersor3DTransform()
itk::simple::ScaleVersor3DTransform::~ScaleVersor3DTransform () override
ScaleVersor3DTransform() [1/5]
itk::simple::ScaleVersor3DTransform::ScaleVersor3DTransform ()
Referenced by operator=(), ScaleVersor3DTransform(), and ScaleVersor3DTransform().
ScaleVersor3DTransform() [2/5]
itk::simple::ScaleVersor3DTransform::ScaleVersor3DTransform (const ScaleVersor3DTransform &)
References ScaleVersor3DTransform().
ScaleVersor3DTransform() [3/5]
itk::simple::ScaleVersor3DTransform::ScaleVersor3DTransform (const Transform &) explicit
References itk::simple::Transform::Transform().
ScaleVersor3DTransform() [4/5]
itk::simple::ScaleVersor3DTransform::ScaleVersor3DTransform (const std::vector< double > & scale, const std::vector< double > & versor, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
ScaleVersor3DTransform() [5/5]
itk::simple::ScaleVersor3DTransform::ScaleVersor3DTransform (const std::vector< double > & scale, const std::vector< double > & axis, double angle, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
References ScaleVersor3DTransform().
Member Function Documentation
GetCenter()
std::vector< double > itk::simple::ScaleVersor3DTransform::GetCenter () const
GetMatrix()
std::vector< double > itk::simple::ScaleVersor3DTransform::GetMatrix () const
GetName()
std::string itk::simple::ScaleVersor3DTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 66 of file sitkScaleVersor3DTransform.h.
GetScale()
std::vector< double > itk::simple::ScaleVersor3DTransform::GetScale () const
GetTranslation()
std::vector< double > itk::simple::ScaleVersor3DTransform::GetTranslation () const
GetVersor()
std::vector< double > itk::simple::ScaleVersor3DTransform::GetVersor () const
InternalInitialization() [1/2]
void itk::simple::ScaleVersor3DTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::ScaleVersor3DTransform::InternalInitialization (TransformType * transform) private
operator=()
ScaleVersor3DTransform & itk::simple::ScaleVersor3DTransform::operator= (const ScaleVersor3DTransform &)
References ScaleVersor3DTransform().
SetCenter()
void itk::simple::ScaleVersor3DTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetPimpleTransform()
void itk::simple::ScaleVersor3DTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetRotation() [1/2]
void itk::simple::ScaleVersor3DTransform::SetRotation (const std::vector< double > & axis, double angle)
SetRotation() [2/2]
void itk::simple::ScaleVersor3DTransform::SetRotation (const std::vector< double > & versor)
parameter
SetScale()
void itk::simple::ScaleVersor3DTransform::SetScale (const std::vector< double > & scale)
SetTranslation()
void itk::simple::ScaleVersor3DTransform::SetTranslation (const std::vector< double > & translation)
Translate()
void itk::simple::ScaleVersor3DTransform::Translate (const std::vector< double > & offset)
additional methods
Member Data Documentation
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::ScaleVersor3DTransform::m_pfGetCenter private
Definition at line 116 of file sitkScaleVersor3DTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::ScaleVersor3DTransform::m_pfGetMatrix private
Definition at line 125 of file sitkScaleVersor3DTransform.h.
m_pfGetScale
std::function<std::vector<double>()> itk::simple::ScaleVersor3DTransform::m_pfGetScale private
Definition at line 123 of file sitkScaleVersor3DTransform.h.
m_pfGetTranslation
std::function<std::vector<double>()> itk::simple::ScaleVersor3DTransform::m_pfGetTranslation private
Definition at line 121 of file sitkScaleVersor3DTransform.h.
m_pfGetVersor
std::function<std::vector<double>()> itk::simple::ScaleVersor3DTransform::m_pfGetVersor private
Definition at line 119 of file sitkScaleVersor3DTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::ScaleVersor3DTransform::m_pfSetCenter private
Definition at line 115 of file sitkScaleVersor3DTransform.h.
m_pfSetRotation1
std::function<void(const std::vector<double> &)> itk::simple::ScaleVersor3DTransform::m_pfSetRotation1 private
Definition at line 117 of file sitkScaleVersor3DTransform.h.
m_pfSetRotation2
std::function<void(const std::vector<double> &, double)> itk::simple::ScaleVersor3DTransform::m_pfSetRotation2 private
Definition at line 118 of file sitkScaleVersor3DTransform.h.
m_pfSetScale
std::function<void(const std::vector<double> &)> itk::simple::ScaleVersor3DTransform::m_pfSetScale private
Definition at line 122 of file sitkScaleVersor3DTransform.h.
m_pfSetTranslation
std::function<void(const std::vector<double> &)> itk::simple::ScaleVersor3DTransform::m_pfSetTranslation private
Definition at line 120 of file sitkScaleVersor3DTransform.h.
m_pfTranslate
std::function<void(const std::vector<double> &)> itk::simple::ScaleVersor3DTransform::m_pfTranslate private
Definition at line 124 of file sitkScaleVersor3DTransform.h.
The documentation for this class was generated from the following file:
sitkScaleVersor3DTransform.h