SimpleITK: itk::simple::Similarity3DTransform Class Reference
itk::simple::Similarity3DTransform Class Reference
A similarity 3D transform with rotation as a versor, and isotropic scaling around a fixed center with translation.
#include <sitkSimilarity3DTransform.h>
Detailed Description
A similarity 3D transform with rotation as a versor, and isotropic scaling around a fixed center with translation.
See also
itk::Similarity3DTransform
Definition at line 33 of file sitkSimilarity3DTransform.h.
Public Types
using Self = Similarity3DTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
std::vector< double > GetCenter () const
std::vector< double > GetMatrix () const
std::string GetName () const override
double GetScale () const
std::vector< double > GetTranslation () const
std::vector< double > GetVersor () const
Similarity3DTransform & operator= (const Similarity3DTransform &)
void SetCenter (const std::vector< double > &params)
void SetMatrix (const std::vector< double > &matrix, double tolerance=1e-10)
void SetRotation (const std::vector< double > &axis, double angle)
void SetRotation (const std::vector< double > &versor)
void SetScale (double scale)
void SetTranslation (const std::vector< double > &translation)
Similarity3DTransform ()
Similarity3DTransform (const Similarity3DTransform &)
Similarity3DTransform (const Transform &)
Similarity3DTransform (double scaleFactor, const std::vector< double > &axis, double angle, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
Similarity3DTransform (double scaleFactor, const std::vector< double > &versor, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
void Translate (const std::vector< double > &offset)
~Similarity3DTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< std::vector< double >()> m_pfGetCenter
std::function< std::vector< double >()> m_pfGetMatrix
std::function< double()> m_pfGetScale
std::function< std::vector< double >()> m_pfGetTranslation
std::function< std::vector< double >()> m_pfGetVersor
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(const std::vector< double > &, double)> m_pfSetMatrix
std::function< void(const std::vector< double > &)> m_pfSetRotation1
std::function< void(const std::vector< double >, double &)> m_pfSetRotation2
std::function< void(double)> m_pfSetScale
std::function< void(const std::vector< double > &)> m_pfSetTranslation
std::function< void(const std::vector< double > &)> m_pfTranslate
Member Typedef Documentation
Self
using itk::simple::Similarity3DTransform::Self = Similarity3DTransform
Definition at line 36 of file sitkSimilarity3DTransform.h.
Superclass
using itk::simple::Similarity3DTransform::Superclass = Transform
Definition at line 37 of file sitkSimilarity3DTransform.h.
Constructor & Destructor Documentation
~Similarity3DTransform()
itk::simple::Similarity3DTransform::~Similarity3DTransform () override
Similarity3DTransform() [1/5]
itk::simple::Similarity3DTransform::Similarity3DTransform ()
Referenced by operator=(), Similarity3DTransform(), and Similarity3DTransform().
Similarity3DTransform() [2/5]
itk::simple::Similarity3DTransform::Similarity3DTransform (const Similarity3DTransform &)
References Similarity3DTransform().
Similarity3DTransform() [3/5]
itk::simple::Similarity3DTransform::Similarity3DTransform (const Transform &) explicit
References itk::simple::Transform::Transform().
Similarity3DTransform() [4/5]
itk::simple::Similarity3DTransform::Similarity3DTransform (double scaleFactor, const std::vector< double > & versor, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
Similarity3DTransform() [5/5]
itk::simple::Similarity3DTransform::Similarity3DTransform (double scaleFactor, const std::vector< double > & axis, double angle, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
References Similarity3DTransform().
Member Function Documentation
GetCenter()
std::vector< double > itk::simple::Similarity3DTransform::GetCenter () const
GetMatrix()
std::vector< double > itk::simple::Similarity3DTransform::GetMatrix () const
GetName()
std::string itk::simple::Similarity3DTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 64 of file sitkSimilarity3DTransform.h.
GetScale()
double itk::simple::Similarity3DTransform::GetScale () const
GetTranslation()
std::vector< double > itk::simple::Similarity3DTransform::GetTranslation () const
GetVersor()
std::vector< double > itk::simple::Similarity3DTransform::GetVersor () const
InternalInitialization() [1/2]
void itk::simple::Similarity3DTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::Similarity3DTransform::InternalInitialization (TransformType * transform) private
operator=()
Similarity3DTransform & itk::simple::Similarity3DTransform::operator= (const Similarity3DTransform &)
References Similarity3DTransform().
SetCenter()
void itk::simple::Similarity3DTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetMatrix()
void itk::simple::Similarity3DTransform::SetMatrix (const std::vector< double > & matrix, double tolerance = 1e-10)
SetPimpleTransform()
void itk::simple::Similarity3DTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetRotation() [1/2]
void itk::simple::Similarity3DTransform::SetRotation (const std::vector< double > & axis, double angle)
SetRotation() [2/2]
void itk::simple::Similarity3DTransform::SetRotation (const std::vector< double > & versor)
parameter
SetScale()
void itk::simple::Similarity3DTransform::SetScale (double scale)
SetTranslation()
void itk::simple::Similarity3DTransform::SetTranslation (const std::vector< double > & translation)
Translate()
void itk::simple::Similarity3DTransform::Translate (const std::vector< double > & offset)
additional methods
Member Data Documentation
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::Similarity3DTransform::m_pfGetCenter private
Definition at line 116 of file sitkSimilarity3DTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::Similarity3DTransform::m_pfGetMatrix private
Definition at line 125 of file sitkSimilarity3DTransform.h.
m_pfGetScale
std::function<double()> itk::simple::Similarity3DTransform::m_pfGetScale private
Definition at line 121 of file sitkSimilarity3DTransform.h.
m_pfGetTranslation
std::function<std::vector<double>()> itk::simple::Similarity3DTransform::m_pfGetTranslation private
Definition at line 123 of file sitkSimilarity3DTransform.h.
m_pfGetVersor
std::function<std::vector<double>()> itk::simple::Similarity3DTransform::m_pfGetVersor private
Definition at line 119 of file sitkSimilarity3DTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::Similarity3DTransform::m_pfSetCenter private
Definition at line 115 of file sitkSimilarity3DTransform.h.
m_pfSetMatrix
std::function<void(const std::vector<double> &, double)> itk::simple::Similarity3DTransform::m_pfSetMatrix private
Definition at line 126 of file sitkSimilarity3DTransform.h.
m_pfSetRotation1
std::function<void(const std::vector<double> &)> itk::simple::Similarity3DTransform::m_pfSetRotation1 private
Definition at line 117 of file sitkSimilarity3DTransform.h.
m_pfSetRotation2
std::function<void(const std::vector<double>, double &)> itk::simple::Similarity3DTransform::m_pfSetRotation2 private
Definition at line 118 of file sitkSimilarity3DTransform.h.
m_pfSetScale
std::function<void(double)> itk::simple::Similarity3DTransform::m_pfSetScale private
Definition at line 120 of file sitkSimilarity3DTransform.h.
m_pfSetTranslation
std::function<void(const std::vector<double> &)> itk::simple::Similarity3DTransform::m_pfSetTranslation private
Definition at line 122 of file sitkSimilarity3DTransform.h.
m_pfTranslate
std::function<void(const std::vector<double> &)> itk::simple::Similarity3DTransform::m_pfTranslate private
Definition at line 124 of file sitkSimilarity3DTransform.h.
The documentation for this class was generated from the following file:
sitkSimilarity3DTransform.h