SimpleITK: itk::simple::PasteImageFilter Class Reference
itk::simple::PasteImageFilter Class Reference
Paste an image (or a constant value) into another image.
#include <sitkPasteImageFilter.h>
Detailed Description
Paste an image (or a constant value) into another image.
PasteImageFilter allows a region in a destination image to be filled with a source image or a constant pixel value. The SetDestinationIndex() method prescribes where in the destination input to start pasting data from the source input. The SetSourceRegion method prescribes the section of the second image to paste into the first. When a constant pixel value is set, the SourceRegion describes the size of the region filled. If the output requested region does not include the SourceRegion after it has been repositioned to DestinationIndex, then the output will just be a copy of the input.
This filter supports running "InPlace" to efficiently reuses the destination image buffer for the output, removing the need to copy the destination pixels to the output.
When the source image is a lower dimension than the destination image then the DestinationSkipAxes parameter specifies which axes in the destination image are set to 1 when copying the region or filling with a constant.
Examples
LandmarkRegistration/LandmarkRegistration.cs, and LandmarkRegistration/LandmarkRegistration.cxx.
Definition at line 55 of file sitkPasteImageFilter.h.
Public Types
using PixelIDTypeList = NonLabelPixelIDTypeList
using Self = PasteImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &destinationImage, const Image &sourceImage)
Image Execute (const Image &destinationImage, double constant)
Image Execute (Image &&destinationImage, const Image &sourceImage)
Image Execute (Image &&destinationImage, double constant)
std::vector< int > GetDestinationIndex () const
std::vector< bool > GetDestinationSkipAxes () const
std::string GetName () const
std::vector< int > GetSourceIndex () const
std::vector< unsigned int > GetSourceSize () const
PasteImageFilter ()
void SetDestinationIndex (std::vector< int > DestinationIndex)
void SetDestinationSkipAxes (std::vector< bool > DestinationSkipAxes)
void SetSourceIndex (std::vector< int > SourceIndex)
void SetSourceSize (std::vector< unsigned int > SourceSize)
std::string ToString () const
virtual ~PasteImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunction2Type = Image (Self::*)(const Image * image, double constant)
using MemberFunctionType = Image (Self::*)(const Image * destinationImage, const Image * sourceImage)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *destinationImage, const Image *sourceImage)
template<class TImageType>
Image ExecuteInternal (const Image *image, double constant)
template<class TImageType>
Image ExecuteInternal (const TImageType *destinationImage, const Image *sourceImage, std::integral_constant< unsigned int, 1 > meta)
template<class TImageType, unsigned int OutputDimension>
Image ExecuteInternal (const TImageType *destinationImage, const Image *sourceImage, std::integral_constant< unsigned int, OutputDimension > meta)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
static const detail::MemberFunctionFactory< MemberFunction2Type > & GetMemberFunctionFactory2 ()
Private Attributes
std::vector< int > m_DestinationIndex { std::vector<int>(SITK_MAX_DIMENSION, 0) }
std::vector< bool > m_DestinationSkipAxes {}
bool m_InPlace { false }
std::vector< int > m_SourceIndex { std::vector<int>(SITK_MAX_DIMENSION, 0) }
std::vector< unsigned int > m_SourceSize { std::vector<unsigned int>(SITK_MAX_DIMENSION, 1) }
Friends
struct detail::MemberFunctionAddressor< MemberFunction2Type >
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunction2Type
using itk::simple::PasteImageFilter::MemberFunction2Type = Image (Self::*)(const Image * image, double constant) private
Definition at line 201 of file sitkPasteImageFilter.h.
MemberFunctionType
using itk::simple::PasteImageFilter::MemberFunctionType = Image (Self::*)(const Image * destinationImage, const Image * sourceImage) private
Setup for member function dispatching
Definition at line 179 of file sitkPasteImageFilter.h.
PixelIDTypeList
using itk::simple::PasteImageFilter::PixelIDTypeList = NonLabelPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 68 of file sitkPasteImageFilter.h.
Self
using itk::simple::PasteImageFilter::Self = PasteImageFilter
Definition at line 58 of file sitkPasteImageFilter.h.
Constructor & Destructor Documentation
~PasteImageFilter()
virtual itk::simple::PasteImageFilter::~PasteImageFilter () virtual
Destructor
PasteImageFilter()
itk::simple::PasteImageFilter::PasteImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/4]
Image itk::simple::PasteImageFilter::Execute (const Image & destinationImage, const Image & sourceImage)
Execute() [2/4]
Image itk::simple::PasteImageFilter::Execute (const Image & destinationImage, double constant)
Execute() [3/4]
Image itk::simple::PasteImageFilter::Execute (Image && destinationImage, const Image & sourceImage)
Execute the filter on the input image
Examples
LandmarkRegistration/LandmarkRegistration.cs, LandmarkRegistration/LandmarkRegistration.cxx, and SliceBySliceDecorator/SliceBySliceDecorator.cxx.
Execute() [4/4]
Image itk::simple::PasteImageFilter::Execute (Image && destinationImage, double constant)
ExecuteInternal() [1/4]
template<class TImageType> Image itk::simple::PasteImageFilter::ExecuteInternal (const Image * destinationImage, const Image * sourceImage) private
Referenced by detail::MemberFunctionAddressor< MemberFunction2Type >.
ExecuteInternal() [2/4]
template<class TImageType> Image itk::simple::PasteImageFilter::ExecuteInternal (const Image * image, double constant) private
ExecuteInternal() [3/4]
template<class TImageType> Image itk::simple::PasteImageFilter::ExecuteInternal (const TImageType * destinationImage, const Image * sourceImage, std::integral_constant< unsigned int, 1 > meta) private
ExecuteInternal() [4/4]
template<class TImageType, unsigned int OutputDimension> Image itk::simple::PasteImageFilter::ExecuteInternal (const TImageType * destinationImage, const Image * sourceImage, std::integral_constant< unsigned int, OutputDimension > meta) private
GetDestinationIndex()
std::vector< int > itk::simple::PasteImageFilter::GetDestinationIndex () const inline
Set/Get the destination index (where in the first input the second input will be pasted.
Definition at line 116 of file sitkPasteImageFilter.h.
References m_DestinationIndex.
GetDestinationSkipAxes()
std::vector< bool > itk::simple::PasteImageFilter::GetDestinationSkipAxes () const inline
Set/Get the array describing which axes in the destination image to skip
The axes with true values are set to 1, to fill the difference between the dimension of the input and source image. The number of true values in DestinationSkipAxes plus the DestinationImageDimension must equal the InputImageDimension.
By default this array contains SourceImageDimension false values followed by true values for the remainder.
Definition at line 145 of file sitkPasteImageFilter.h.
References m_DestinationSkipAxes.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::PasteImageFilter::GetMemberFunctionFactory () static private
GetMemberFunctionFactory2()
static const detail::MemberFunctionFactory< MemberFunction2Type > & itk::simple::PasteImageFilter::GetMemberFunctionFactory2 () static private
GetName()
std::string itk::simple::PasteImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 153 of file sitkPasteImageFilter.h.
GetSourceIndex()
std::vector< int > itk::simple::PasteImageFilter::GetSourceIndex () const inline
Definition at line 98 of file sitkPasteImageFilter.h.
References m_SourceIndex.
GetSourceSize()
std::vector< unsigned int > itk::simple::PasteImageFilter::GetSourceSize () const inline
Definition at line 82 of file sitkPasteImageFilter.h.
References m_SourceSize.
SetDestinationIndex()
void itk::simple::PasteImageFilter::SetDestinationIndex (std::vector< int > DestinationIndex) inline
Set/Get the destination index (where in the first input the second input will be pasted.
Examples
LandmarkRegistration/LandmarkRegistration.cs, LandmarkRegistration/LandmarkRegistration.cxx, and SliceBySliceDecorator/SliceBySliceDecorator.cxx.
Definition at line 107 of file sitkPasteImageFilter.h.
References m_DestinationIndex.
SetDestinationSkipAxes()
void itk::simple::PasteImageFilter::SetDestinationSkipAxes (std::vector< bool > DestinationSkipAxes) inline
Set/Get the array describing which axes in the destination image to skip
The axes with true values are set to 1, to fill the difference between the dimension of the input and source image. The number of true value in DestinationSkipAxes plus the DestinationImageDimension must equal the InputImageDimension.
By default this array contains SourceImageDimension false values followed by true values for the remainder.
Definition at line 131 of file sitkPasteImageFilter.h.
References m_DestinationSkipAxes.
SetSourceIndex()
void itk::simple::PasteImageFilter::SetSourceIndex (std::vector< int > SourceIndex) inline
Examples
LandmarkRegistration/LandmarkRegistration.cs, and LandmarkRegistration/LandmarkRegistration.cxx.
Definition at line 90 of file sitkPasteImageFilter.h.
References m_SourceIndex.
SetSourceSize()
void itk::simple::PasteImageFilter::SetSourceSize (std::vector< unsigned int > SourceSize) inline
Examples
LandmarkRegistration/LandmarkRegistration.cs, LandmarkRegistration/LandmarkRegistration.cxx, and SliceBySliceDecorator/SliceBySliceDecorator.cxx.
Definition at line 74 of file sitkPasteImageFilter.h.
References m_SourceSize.
ToString()
std::string itk::simple::PasteImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunction2Type >
friend struct detail::MemberFunctionAddressor< MemberFunction2Type > friend
Definition at line 196 of file sitkPasteImageFilter.h.
References ExecuteInternal().
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 196 of file sitkPasteImageFilter.h.
Member Data Documentation
m_DestinationIndex
std::vector<int> itk::simple::PasteImageFilter::m_DestinationIndex { std::vector<int>(SITK_MAX_DIMENSION, 0) } private
Definition at line 216 of file sitkPasteImageFilter.h.
Referenced by GetDestinationIndex(), and SetDestinationIndex().
m_DestinationSkipAxes
std::vector<bool> itk::simple::PasteImageFilter::m_DestinationSkipAxes {} private
Definition at line 218 of file sitkPasteImageFilter.h.
Referenced by GetDestinationSkipAxes(), and SetDestinationSkipAxes().
m_InPlace
bool itk::simple::PasteImageFilter::m_InPlace { false } private
Definition at line 220 of file sitkPasteImageFilter.h.
m_SourceIndex
std::vector<int> itk::simple::PasteImageFilter::m_SourceIndex { std::vector<int>(SITK_MAX_DIMENSION, 0) } private
Definition at line 214 of file sitkPasteImageFilter.h.
Referenced by GetSourceIndex(), and SetSourceIndex().
m_SourceSize
std::vector<unsigned int> itk::simple::PasteImageFilter::m_SourceSize { std::vector<unsigned int>(SITK_MAX_DIMENSION, 1) } private
Definition at line 212 of file sitkPasteImageFilter.h.
Referenced by GetSourceSize(), and SetSourceSize().
The documentation for this class was generated from the following file:
sitkPasteImageFilter.h