SimpleITK: itk::simple::LabelOverlapMeasuresImageFilter Class Reference
itk::simple::LabelOverlapMeasuresImageFilter Class Reference
Computes overlap measures between the set same set of labels of pixels of two images. Background is assumed to be 0.
#include <sitkLabelOverlapMeasuresImageFilter.h>
Detailed Description
Computes overlap measures between the set same set of labels of pixels of two images. Background is assumed to be 0.
This code was contributed in the Insight Journal paper: "Introducing Dice, Jaccard, and Other Label Overlap Measures To ITK" by Nicholas J. Tustison, James C. Gee https://doi.org/10.54294/1vixgg
Author
Nicholas J. Tustison
See also
LabelOverlapMeasuresImageFilter
itk::LabelOverlapMeasuresImageFilter for the Doxygen on the original ITK class.
Definition at line 51 of file sitkLabelOverlapMeasuresImageFilter.h.
Public Types
using PixelIDTypeList = IntegerPixelIDTypeList
using Self = LabelOverlapMeasuresImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void Execute (const Image &sourceImage, const Image &targetImage)
double GetDiceCoefficient () const
double GetDiceCoefficient (int64_t label) const
double GetFalseDiscoveryRate () const
double GetFalseDiscoveryRate (int64_t label) const
double GetFalseNegativeError () const
double GetFalseNegativeError (int64_t label) const
double GetFalsePositiveError () const
double GetFalsePositiveError (int64_t label) const
double GetJaccardCoefficient () const
double GetJaccardCoefficient (int64_t label) const
double GetMeanOverlap () const
double GetMeanOverlap (int64_t label) const
std::string GetName () const
double GetUnionOverlap () const
double GetUnionOverlap (int64_t label) const
double GetVolumeSimilarity () const
double GetVolumeSimilarity (int64_t label) const
LabelOverlapMeasuresImageFilter ()
std::string ToString () const
virtual ~LabelOverlapMeasuresImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
void ExecuteInternal (const Image *sourceImage, const Image *targetImage)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_DiceCoefficient { 0.0 }
double m_FalseDiscoveryRate { 0.0 }
double m_FalseNegativeError { 0.0 }
double m_FalsePositiveError { 0.0 }
std::unique_ptr< itk::ProcessObject, ProcessObjectDeleter > m_Filter {nullptr}
double m_JaccardCoefficient { 0.0 }
double m_MeanOverlap { 0.0 }
std::function< double(int64_t)> m_pfGetDiceCoefficient
std::function< double(int64_t)> m_pfGetFalseDiscoveryRate
std::function< double(int64_t)> m_pfGetFalseNegativeError
std::function< double(int64_t)> m_pfGetFalsePositiveError
std::function< double(int64_t)> m_pfGetJaccardCoefficient
std::function< double(int64_t)> m_pfGetMeanOverlap
std::function< double(int64_t)> m_pfGetUnionOverlap
std::function< double(int64_t)> m_pfGetVolumeSimilarity
double m_UnionOverlap { 0.0 }
double m_VolumeSimilarity { 0.0 }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::LabelOverlapMeasuresImageFilter::MemberFunctionType private
Initial value:
 void (Self::*)(const Image *
    sourceImage, const Image *
    targetImage)
Setup for member function dispatching
Definition at line 217 of file sitkLabelOverlapMeasuresImageFilter.h.
PixelIDTypeList
using itk::simple::LabelOverlapMeasuresImageFilter::PixelIDTypeList = IntegerPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 63 of file sitkLabelOverlapMeasuresImageFilter.h.
Self
using itk::simple::LabelOverlapMeasuresImageFilter::Self = LabelOverlapMeasuresImageFilter
Definition at line 53 of file sitkLabelOverlapMeasuresImageFilter.h.
Constructor & Destructor Documentation
~LabelOverlapMeasuresImageFilter()
virtual itk::simple::LabelOverlapMeasuresImageFilter::~LabelOverlapMeasuresImageFilter () virtual
Destructor
LabelOverlapMeasuresImageFilter()
itk::simple::LabelOverlapMeasuresImageFilter::LabelOverlapMeasuresImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
void itk::simple::LabelOverlapMeasuresImageFilter::Execute (const Image & sourceImage, const Image & targetImage)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> void itk::simple::LabelOverlapMeasuresImageFilter::ExecuteInternal (const Image * sourceImage, const Image * targetImage) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetDiceCoefficient() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetDiceCoefficient () const inline
Get the mean overlap (Dice coefficient) for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 176 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_DiceCoefficient.
GetDiceCoefficient() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetDiceCoefficient (int64_t label) const inline
Get the mean overlap (Dice coefficient) for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 185 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetDiceCoefficient.
GetFalseDiscoveryRate() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalseDiscoveryRate () const inline
Get the false discovery rate for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 193 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_FalseDiscoveryRate.
GetFalseDiscoveryRate() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalseDiscoveryRate (int64_t label) const inline
Get the false discovery rate for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 202 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetFalseDiscoveryRate.
GetFalseNegativeError() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalseNegativeError () const inline
Get the false negative error for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 74 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_FalseNegativeError.
GetFalseNegativeError() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalseNegativeError (int64_t label) const inline
Get the false negative error for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 83 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetFalseNegativeError.
GetFalsePositiveError() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalsePositiveError () const inline
Get the false positive error for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 91 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_FalsePositiveError.
GetFalsePositiveError() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetFalsePositiveError (int64_t label) const inline
Get the false positive error for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 100 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetFalsePositiveError.
GetJaccardCoefficient() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetJaccardCoefficient () const inline
Get the union overlap (Jaccard coefficient) for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 159 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_JaccardCoefficient.
GetJaccardCoefficient() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetJaccardCoefficient (int64_t label) const inline
Get the union overlap (Jaccard coefficient) for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 168 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetJaccardCoefficient.
GetMeanOverlap() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetMeanOverlap () const inline
Get the mean overlap (Dice coefficient) for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 108 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_MeanOverlap.
GetMeanOverlap() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetMeanOverlap (int64_t label) const inline
Get the mean overlap (Dice coefficient) for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 117 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetMeanOverlap.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::LabelOverlapMeasuresImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::LabelOverlapMeasuresImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 205 of file sitkLabelOverlapMeasuresImageFilter.h.
GetUnionOverlap() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetUnionOverlap () const inline
Get the union overlap (Jaccard coefficient) for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 125 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_UnionOverlap.
GetUnionOverlap() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetUnionOverlap (int64_t label) const inline
Get the union overlap (Jaccard coefficient) for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 134 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetUnionOverlap.
GetVolumeSimilarity() [1/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetVolumeSimilarity () const inline
Get the volume similarity for the specified individual label.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 142 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_VolumeSimilarity.
GetVolumeSimilarity() [2/2]
double itk::simple::LabelOverlapMeasuresImageFilter::GetVolumeSimilarity (int64_t label) const inline
Get the volume similarity for the specified individual label.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 151 of file sitkLabelOverlapMeasuresImageFilter.h.
References m_pfGetVolumeSimilarity.
ToString()
std::string itk::simple::LabelOverlapMeasuresImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 220 of file sitkLabelOverlapMeasuresImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_DiceCoefficient
double itk::simple::LabelOverlapMeasuresImageFilter::m_DiceCoefficient { 0.0 } private
Definition at line 241 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetDiceCoefficient().
m_FalseDiscoveryRate
double itk::simple::LabelOverlapMeasuresImageFilter::m_FalseDiscoveryRate { 0.0 } private
Definition at line 243 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalseDiscoveryRate().
m_FalseNegativeError
double itk::simple::LabelOverlapMeasuresImageFilter::m_FalseNegativeError { 0.0 } private
Definition at line 229 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalseNegativeError().
m_FalsePositiveError
double itk::simple::LabelOverlapMeasuresImageFilter::m_FalsePositiveError { 0.0 } private
Definition at line 231 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalsePositiveError().
m_Filter
std::unique_ptr<itk::ProcessObject, ProcessObjectDeleter> itk::simple::LabelOverlapMeasuresImageFilter::m_Filter {nullptr} private
Definition at line 248 of file sitkLabelOverlapMeasuresImageFilter.h.
m_JaccardCoefficient
double itk::simple::LabelOverlapMeasuresImageFilter::m_JaccardCoefficient { 0.0 } private
Definition at line 239 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetJaccardCoefficient().
m_MeanOverlap
double itk::simple::LabelOverlapMeasuresImageFilter::m_MeanOverlap { 0.0 } private
Definition at line 233 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetMeanOverlap().
m_pfGetDiceCoefficient
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetDiceCoefficient private
Definition at line 242 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetDiceCoefficient().
m_pfGetFalseDiscoveryRate
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetFalseDiscoveryRate private
Definition at line 244 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalseDiscoveryRate().
m_pfGetFalseNegativeError
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetFalseNegativeError private
Definition at line 230 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalseNegativeError().
m_pfGetFalsePositiveError
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetFalsePositiveError private
Definition at line 232 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetFalsePositiveError().
m_pfGetJaccardCoefficient
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetJaccardCoefficient private
Definition at line 240 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetJaccardCoefficient().
m_pfGetMeanOverlap
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetMeanOverlap private
Definition at line 234 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetMeanOverlap().
m_pfGetUnionOverlap
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetUnionOverlap private
Definition at line 236 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetUnionOverlap().
m_pfGetVolumeSimilarity
std::function<double(int64_t)> itk::simple::LabelOverlapMeasuresImageFilter::m_pfGetVolumeSimilarity private
Definition at line 238 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetVolumeSimilarity().
m_UnionOverlap
double itk::simple::LabelOverlapMeasuresImageFilter::m_UnionOverlap { 0.0 } private
Definition at line 235 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetUnionOverlap().
m_VolumeSimilarity
double itk::simple::LabelOverlapMeasuresImageFilter::m_VolumeSimilarity { 0.0 } private
Definition at line 237 of file sitkLabelOverlapMeasuresImageFilter.h.
Referenced by GetVolumeSimilarity().
The documentation for this class was generated from the following file:
sitkLabelOverlapMeasuresImageFilter.h