SimpleITK: itk::simple::TransformixImageFilter Class Reference
itk::simple::TransformixImageFilter Class Reference
#include <sitkTransformixImageFilter.h>
Detailed Description
Examples
Elastix/tfx.cxx.
Definition at line 33 of file sitkTransformixImageFilter.h.
Classes
class TransformixImageFilterImpl
Public Types
typedef std::string ParameterKeyType
typedef ParameterMapType::const_iterator ParameterMapConstIterator
typedef ParameterMapType::iterator ParameterMapIterator
typedef std::map< ParameterKeyType, ParameterValueVectorType > ParameterMapType
typedef std::vector< ParameterMapType > ParameterMapVectorType
typedef std::string ParameterValueType
typedef ParameterValueVectorType::iterator ParameterValueVectorIterator
typedef std::vector< ParameterValueType > ParameterValueVectorType
typedef TransformixImageFilter Self
Public Member Functions
Self & AddTransformParameter (const std::string key, const std::string value)
Self & AddTransformParameter (const unsigned int index, const std::string key, const std::string value)
Self & AddTransformParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Self & ComputeDeformationFieldOff ()
Self & ComputeDeformationFieldOn ()
Self & ComputeDeterminantOfSpatialJacobianOff ()
Self & ComputeDeterminantOfSpatialJacobianOn ()
Self & ComputeSpatialJacobianOff ()
Self & ComputeSpatialJacobianOn ()
Image Execute ()
bool GetComputeDeformationField ()
bool GetComputeDeterminantOfSpatialJacobian ()
bool GetComputeSpatialJacobian ()
Image GetDeformationField ()
std::string GetFixedPointSetFileName ()
std::string GetLogFileName ()
bool GetLogToConsole ()
bool GetLogToFile ()
Image & GetMovingImage ()
std::string GetName () const
unsigned int GetNumberOfTransformParameterMaps ()
std::string GetOutputDirectory ()
Image GetResultImage ()
std::vector< std::string > GetTransformParameter (const std::string key)
std::vector< std::string > GetTransformParameter (const unsigned int index, const std::string key)
std::vector< std::map< std::string, std::vector< std::string > > > GetTransformParameterMap ()
std::vector< std::map< std::string, std::vector< std::string > > > GetTransformParameterMaps ()
Self & LogToConsoleOff ()
Self & LogToConsoleOn ()
Self & LogToFileOff ()
Self & LogToFileOn ()
Self & PrintParameterMap ()
Self & PrintParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Self & PrintParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
std::map< std::string, std::vector< std::string > > ReadParameterFile (const std::string parameterFileName)
Self & RemoveFixedPointSetFileName ()
Self & RemoveLogFileName ()
Self & RemoveMovingImage ()
Self & RemoveOutputDirectory ()
Self & RemoveTransformParameter (const std::string key)
Self & RemoveTransformParameter (const unsigned int index, const std::string key)
Self & SetComputeDeformationField (bool)
Self & SetComputeDeterminantOfSpatialJacobian (const bool)
Self & SetComputeSpatialJacobian (const bool)
Self & SetFixedPointSetFileName (const std::string movingPointSetFileName)
Self & SetLogFileName (const std::string logFileName)
Self & SetLogToConsole (const bool logToConsole)
Self & SetLogToFile (const bool logToFile)
Self & SetMovingImage (const Image &movingImage)
Self & SetOutputDirectory (const std::string outputDirectory)
Self & SetTransformParameter (const std::string key, const std::string value)
Self & SetTransformParameter (const std::string key, const std::vector< std::string > value)
Self & SetTransformParameter (const unsigned int index, const std::string key, const std::string value)
Self & SetTransformParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
Self & SetTransformParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Self & SetTransformParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
Self & SetTransformParameterMaps (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
TransformixImageFilter ()
Self & WriteParameterFile (const std::map< std::string, std::vector< std::string > > parameterMap, const std::string parameterFileName)
~TransformixImageFilter ()
Private Attributes
const std::unique_ptr< TransformixImageFilterImpl > m_Pimple
Member Typedef Documentation
ParameterKeyType
typedef std::string itk::simple::TransformixImageFilter::ParameterKeyType
Definition at line 41 of file sitkTransformixImageFilter.h.
ParameterMapConstIterator
typedef ParameterMapType::const_iterator itk::simple::TransformixImageFilter::ParameterMapConstIterator
Definition at line 48 of file sitkTransformixImageFilter.h.
ParameterMapIterator
typedef ParameterMapType::iterator itk::simple::TransformixImageFilter::ParameterMapIterator
Definition at line 47 of file sitkTransformixImageFilter.h.
ParameterMapType
typedef std::map<ParameterKeyType, ParameterValueVectorType> itk::simple::TransformixImageFilter::ParameterMapType
Definition at line 45 of file sitkTransformixImageFilter.h.
ParameterMapVectorType
typedef std::vector<ParameterMapType> itk::simple::TransformixImageFilter::ParameterMapVectorType
Definition at line 46 of file sitkTransformixImageFilter.h.
ParameterValueType
typedef std::string itk::simple::TransformixImageFilter::ParameterValueType
Definition at line 42 of file sitkTransformixImageFilter.h.
ParameterValueVectorIterator
typedef ParameterValueVectorType::iterator itk::simple::TransformixImageFilter::ParameterValueVectorIterator
Definition at line 44 of file sitkTransformixImageFilter.h.
ParameterValueVectorType
typedef std::vector<ParameterValueType> itk::simple::TransformixImageFilter::ParameterValueVectorType
Definition at line 43 of file sitkTransformixImageFilter.h.
Self
typedef TransformixImageFilter itk::simple::TransformixImageFilter::Self
Definition at line 39 of file sitkTransformixImageFilter.h.
Constructor & Destructor Documentation
TransformixImageFilter()
itk::simple::TransformixImageFilter::TransformixImageFilter ()
~TransformixImageFilter()
itk::simple::TransformixImageFilter::~TransformixImageFilter ()
Member Function Documentation
AddTransformParameter() [1/2]
Self & itk::simple::TransformixImageFilter::AddTransformParameter (const std::string key, const std::string value)
AddTransformParameter() [2/2]
Self & itk::simple::TransformixImageFilter::AddTransformParameter (const unsigned int index, const std::string key, const std::string value)
AddTransformParameterMap()
Self & itk::simple::TransformixImageFilter::AddTransformParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
ComputeDeformationFieldOff()
Self & itk::simple::TransformixImageFilter::ComputeDeformationFieldOff ()
ComputeDeformationFieldOn()
Self & itk::simple::TransformixImageFilter::ComputeDeformationFieldOn ()
ComputeDeterminantOfSpatialJacobianOff()
Self & itk::simple::TransformixImageFilter::ComputeDeterminantOfSpatialJacobianOff ()
ComputeDeterminantOfSpatialJacobianOn()
Self & itk::simple::TransformixImageFilter::ComputeDeterminantOfSpatialJacobianOn ()
ComputeSpatialJacobianOff()
Self & itk::simple::TransformixImageFilter::ComputeSpatialJacobianOff ()
ComputeSpatialJacobianOn()
Self & itk::simple::TransformixImageFilter::ComputeSpatialJacobianOn ()
Execute()
Image itk::simple::TransformixImageFilter::Execute ()
Examples
Elastix/tfx.cxx.
GetComputeDeformationField()
bool itk::simple::TransformixImageFilter::GetComputeDeformationField ()
GetComputeDeterminantOfSpatialJacobian()
bool itk::simple::TransformixImageFilter::GetComputeDeterminantOfSpatialJacobian ()
GetComputeSpatialJacobian()
bool itk::simple::TransformixImageFilter::GetComputeSpatialJacobian ()
GetDeformationField()
Image itk::simple::TransformixImageFilter::GetDeformationField ()
GetFixedPointSetFileName()
std::string itk::simple::TransformixImageFilter::GetFixedPointSetFileName ()
GetLogFileName()
std::string itk::simple::TransformixImageFilter::GetLogFileName ()
GetLogToConsole()
bool itk::simple::TransformixImageFilter::GetLogToConsole ()
GetLogToFile()
bool itk::simple::TransformixImageFilter::GetLogToFile ()
GetMovingImage()
Image & itk::simple::TransformixImageFilter::GetMovingImage ()
GetName()
std::string itk::simple::TransformixImageFilter::GetName () const
GetNumberOfTransformParameterMaps()
unsigned int itk::simple::TransformixImageFilter::GetNumberOfTransformParameterMaps ()
GetOutputDirectory()
std::string itk::simple::TransformixImageFilter::GetOutputDirectory ()
GetResultImage()
Image itk::simple::TransformixImageFilter::GetResultImage ()
Examples
Elastix/tfx.cxx.
GetTransformParameter() [1/2]
std::vector< std::string > itk::simple::TransformixImageFilter::GetTransformParameter (const std::string key)
GetTransformParameter() [2/2]
std::vector< std::string > itk::simple::TransformixImageFilter::GetTransformParameter (const unsigned int index, const std::string key)
GetTransformParameterMap()
std::vector< std::map< std::string, std::vector< std::string > > > itk::simple::TransformixImageFilter::GetTransformParameterMap ()
Referenced by GetTransformParameterMaps().
GetTransformParameterMaps()
std::vector< std::map< std::string, std::vector< std::string > > > itk::simple::TransformixImageFilter::GetTransformParameterMaps () inline
Definition at line 140 of file sitkTransformixImageFilter.h.
References GetTransformParameterMap().
LogToConsoleOff()
Self & itk::simple::TransformixImageFilter::LogToConsoleOff ()
LogToConsoleOn()
Self & itk::simple::TransformixImageFilter::LogToConsoleOn ()
Examples
Elastix/tfx.cxx.
LogToFileOff()
Self & itk::simple::TransformixImageFilter::LogToFileOff ()
LogToFileOn()
Self & itk::simple::TransformixImageFilter::LogToFileOn ()
PrintParameterMap() [1/3]
Self & itk::simple::TransformixImageFilter::PrintParameterMap ()
PrintParameterMap() [2/3]
Self & itk::simple::TransformixImageFilter::PrintParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
PrintParameterMap() [3/3]
Self & itk::simple::TransformixImageFilter::PrintParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
ReadParameterFile()
std::map< std::string, std::vector< std::string > > itk::simple::TransformixImageFilter::ReadParameterFile (const std::string parameterFileName)
RemoveFixedPointSetFileName()
Self & itk::simple::TransformixImageFilter::RemoveFixedPointSetFileName ()
RemoveLogFileName()
Self & itk::simple::TransformixImageFilter::RemoveLogFileName ()
RemoveMovingImage()
Self & itk::simple::TransformixImageFilter::RemoveMovingImage ()
RemoveOutputDirectory()
Self & itk::simple::TransformixImageFilter::RemoveOutputDirectory ()
RemoveTransformParameter() [1/2]
Self & itk::simple::TransformixImageFilter::RemoveTransformParameter (const std::string key)
RemoveTransformParameter() [2/2]
Self & itk::simple::TransformixImageFilter::RemoveTransformParameter (const unsigned int index, const std::string key)
SetComputeDeformationField()
Self & itk::simple::TransformixImageFilter::SetComputeDeformationField (bool)
SetComputeDeterminantOfSpatialJacobian()
Self & itk::simple::TransformixImageFilter::SetComputeDeterminantOfSpatialJacobian (const bool)
SetComputeSpatialJacobian()
Self & itk::simple::TransformixImageFilter::SetComputeSpatialJacobian (const bool)
SetFixedPointSetFileName()
Self & itk::simple::TransformixImageFilter::SetFixedPointSetFileName (const std::string movingPointSetFileName)
SetLogFileName()
Self & itk::simple::TransformixImageFilter::SetLogFileName (const std::string logFileName)
SetLogToConsole()
Self & itk::simple::TransformixImageFilter::SetLogToConsole (const bool logToConsole)
SetLogToFile()
Self & itk::simple::TransformixImageFilter::SetLogToFile (const bool logToFile)
SetMovingImage()
Self & itk::simple::TransformixImageFilter::SetMovingImage (const Image & movingImage)
Examples
Elastix/tfx.cxx.
SetOutputDirectory()
Self & itk::simple::TransformixImageFilter::SetOutputDirectory (const std::string outputDirectory)
SetTransformParameter() [1/4]
Self & itk::simple::TransformixImageFilter::SetTransformParameter (const std::string key, const std::string value)
SetTransformParameter() [2/4]
Self & itk::simple::TransformixImageFilter::SetTransformParameter (const std::string key, const std::vector< std::string > value)
SetTransformParameter() [3/4]
Self & itk::simple::TransformixImageFilter::SetTransformParameter (const unsigned int index, const std::string key, const std::string value)
SetTransformParameter() [4/4]
Self & itk::simple::TransformixImageFilter::SetTransformParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
SetTransformParameterMap() [1/2]
Self & itk::simple::TransformixImageFilter::SetTransformParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
SetTransformParameterMap() [2/2]
Self & itk::simple::TransformixImageFilter::SetTransformParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
Examples
Elastix/tfx.cxx.
Referenced by SetTransformParameterMaps().
SetTransformParameterMaps()
Self & itk::simple::TransformixImageFilter::SetTransformParameterMaps (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector) inline
Definition at line 129 of file sitkTransformixImageFilter.h.
References SetTransformParameterMap().
WriteParameterFile()
Self & itk::simple::TransformixImageFilter::WriteParameterFile (const std::map< std::string, std::vector< std::string > > parameterMap, const std::string parameterFileName)
Member Data Documentation
m_Pimple
const std::unique_ptr<TransformixImageFilterImpl> itk::simple::TransformixImageFilter::m_Pimple private
Definition at line 191 of file sitkTransformixImageFilter.h.
The documentation for this class was generated from the following file:
sitkTransformixImageFilter.h