SimpleITK: itk::simple::ImageRegistrationMethod Class Reference
itk::simple::ImageRegistrationMethod Class Reference
An interface method to the modular ITKv4 registration framework.
#include <sitkImageRegistrationMethod.h>
Detailed Description
An interface method to the modular ITKv4 registration framework.
This interface method class encapsulates typical registration usage by incorporating all the necessary elements for performing a simple image registration between two images. This method also allows for multistage registration whereby each stage is characterized by possibly different transforms and different image metrics. For example, many users will want to perform a linear registration followed by deformable registration where both stages are performed in multiple levels. Each level can be characterized by:
the resolution of the virtual domain image (see below)
smoothing of the fixed and moving images
Multiple stages are handled by linking multiple instantiations of this class where the output transform is added to the optional composite transform input.
See also
itk::ImageRegistrationMethodv4
itk::ImageToImageMetricv4
itk::ObjectToObjectOptimizerBaseTemplate
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
Definition at line 87 of file sitkImageRegistrationMethod.h.
Classes
struct EvaluateMemberFunctionAddressor
Public Types
enum EstimateLearningRateType {
Never ,
Once ,
EachIteration
}
enum MetricSamplingStrategyType {
NONE ,
REGULAR ,
RANDOM
}
Sampling strategies for obtaining points.
using Self = ImageRegistrationMethod
using Superclass = ProcessObject
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Transform Execute (const Image &fixed, const Image &moving)
Optimize the configured registration problem.
unsigned int GetCurrentLevel () const
uint64_t GetMetricNumberOfValidPoints () const
const std::vector< double > & GetMetricSamplingPercentagePerLevel () const
Get the percentage of pixels used for metric evaluation.
double GetMetricValue () const
std::string GetName () const override
double GetOptimizerConvergenceValue () const
unsigned int GetOptimizerIteration () const
double GetOptimizerLearningRate () const
std::vector< double > GetOptimizerPosition () const
std::vector< double > GetOptimizerScales () const
Get the OptimizerScales.
std::string GetOptimizerStopConditionDescription () const
ImageRegistrationMethod ()
double MetricEvaluate (const Image &fixed, const Image &moving)
Get the value of the metric given the state of the method.
void SetInitialTransformAsBSpline (BSplineTransform &transform, bool inPlace=true, const std::vector< unsigned int > &scaleFactors=std::vector< unsigned int >())
Set an initial BSpline transform to optimize.
void SetMetricAsANTSNeighborhoodCorrelation (unsigned int radius)
Use normalized cross correlation using a small neighborhood for each voxel between two images, with speed optimizations for dense registration.
void SetMetricAsCorrelation ()
Use negative normalized cross correlation image metric.
void SetMetricAsDemons (double intensityDifferenceThreshold=0.001)
Use demons image metric.
void SetMetricAsJointHistogramMutualInformation (unsigned int numberOfHistogramBins=20, double varianceForJointPDFSmoothing=1.5)
Use mutual information between two images.
void SetMetricAsMattesMutualInformation (unsigned int numberOfHistogramBins=50)
Use the mutual information between two images to be registered using the method of Mattes et al.
void SetMetricAsMeanSquares ()
Use negative means squares image metric.
void SetMetricFixedMask (const Image &binaryMask)
Set an image mask in order to restrict the sampled points for the metric.
void SetMetricMovingMask (const Image &binaryMask)
Set an image mask in order to restrict the sampled points for the metric in the moving image space.
void SetMetricSamplingStrategy (MetricSamplingStrategyType strategy)
Set sampling strategy for sample generation.
void SetOptimizerAsAmoeba (double simplexDelta, unsigned int numberOfIterations, double parametersConvergenceTolerance=1e-8, double functionConvergenceTolerance=1e-4, bool withRestarts=false)
Set optimizer to Nelder-Mead downhill simplex algorithm.
void SetOptimizerAsConjugateGradientLineSearch (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue=1e-6, unsigned int convergenceWindowSize=10, double lineSearchLowerLimit=0, double lineSearchUpperLimit=5.0, double lineSearchEpsilon=0.01, unsigned int lineSearchMaximumIterations=20, EstimateLearningRateType estimateLearningRate=Once, double maximumStepSizeInPhysicalUnits=0.0)
Conjugate gradient descent optimizer with a golden section line search for nonlinear optimization.
void SetOptimizerAsExhaustive (const std::vector< unsigned int > &numberOfSteps, double stepLength=1.0)
Set the optimizer to sample the metric at regular steps.
void SetOptimizerAsGradientDescent (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue=1e-6, unsigned int convergenceWindowSize=10, EstimateLearningRateType estimateLearningRate=Once, double maximumStepSizeInPhysicalUnits=0.0)
Gradient descent optimizer.
void SetOptimizerAsGradientDescentLineSearch (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue=1e-6, unsigned int convergenceWindowSize=10, double lineSearchLowerLimit=0, double lineSearchUpperLimit=5.0, double lineSearchEpsilon=0.01, unsigned int lineSearchMaximumIterations=20, EstimateLearningRateType estimateLearningRate=Once, double maximumStepSizeInPhysicalUnits=0.0)
Gradient descent optimizer with a golden section line search.
void SetOptimizerAsLBFGS2 (double solutionAccuracy=1e-5, unsigned int numberOfIterations=0, unsigned int hessianApproximateAccuracy=6, unsigned int deltaConvergenceDistance=0, double deltaConvergenceTolerance=1e-5, unsigned int lineSearchMaximumEvaluations=40, double lineSearchMinimumStep=1e-20, double lineSearchMaximumStep=1e20, double lineSearchAccuracy=1e-4)
Limited memory Broyden Fletcher Goldfarb Shannon minimization without bounds.
void SetOptimizerAsLBFGSB (double gradientConvergenceTolerance=1e-5, unsigned int numberOfIterations=500, unsigned int maximumNumberOfCorrections=5, unsigned int maximumNumberOfFunctionEvaluations=2000, double costFunctionConvergenceFactor=1e+7, double lowerBound=std::numeric_limits< double >::min(), double upperBound=std::numeric_limits< double >::max(), bool trace=false)
Limited memory Broyden Fletcher Goldfarb Shannon minimization with simple bounds.
void SetOptimizerAsOnePlusOneEvolutionary (unsigned int numberOfIterations=100, double epsilon=1.5e-4, double initialRadius=1.01, double growthFactor=-1.0, double shrinkFactor=-1.0, unsigned int seed=sitkWallClock)
1+1 evolutionary optimizer strategy.
void SetOptimizerAsPowell (unsigned int numberOfIterations=100, unsigned int maximumLineIterations=100, double stepLength=1, double stepTolerance=1e-6, double valueTolerance=1e-6)
Powell optimization using Brent line search.
void SetOptimizerAsRegularStepGradientDescent (double learningRate, double minStep, unsigned int numberOfIterations, double relaxationFactor=0.5, double gradientMagnitudeTolerance=1e-4, EstimateLearningRateType estimateLearningRate=Never, double maximumStepSizeInPhysicalUnits=0.0)
Regular Step Gradient descent optimizer.
void SetOptimizerScales (const std::vector< double > &scales)
Manually set per parameter weighting for the transform parameters.
void SetOptimizerScalesFromIndexShift (unsigned int centralRegionRadius=5, double smallParameterVariation=0.01)
Estimate scales from maximum voxel shift in index space cause by parameter change.
void SetOptimizerScalesFromJacobian (unsigned int centralRegionRadius=5)
Estimate scales from Jacobian norms.
void SetOptimizerScalesFromPhysicalShift (unsigned int centralRegionRadius=5, double smallParameterVariation=0.01)
Estimating scales of transform parameters a step sizes, from the maximum voxel shift in physical space caused by a parameter change.
void SetShrinkFactorsPerLevel (const std::vector< unsigned int > &shrinkFactors)
Set the isotropic shrink factors for each level.
void SetSmoothingSigmasPerLevel (const std::vector< double > &smoothingSigmas)
Set the sigmas of Gaussian used for smoothing.
bool StopRegistration ()
std::string ToString () const override
Print the information about the object to a string.
~ImageRegistrationMethod () override
InterpolatorEnum GetInterpolator ()
Set and get the interpolator to use.
void SetInterpolator (InterpolatorEnum Interpolator)
Set and get the interpolator to use.
void SetInitialTransform (const Transform &transform)
Set the initial transform and parameters to optimize.
void SetInitialTransform (Transform &transform, bool inPlace=true)
Set the initial transform and parameters to optimize.
Transform GetInitialTransform ()
Set the initial transform and parameters to optimize.
bool GetInitialTransformInPlace () const
Set the initial transform and parameters to optimize.
void SetMovingInitialTransform (const Transform &transform)
Set a fixed transform component towards moving domain.
Transform GetMovingInitialTransform () const
Set a fixed transform component towards moving domain.
void SetFixedInitialTransform (const Transform &transform)
Set transform mapping to the fixed domain.
Transform GetFixedInitialTransform () const
Set transform mapping to the fixed domain.
void SetVirtualDomain (const std::vector< uint32_t > &virtualSize, const std::vector< double > &virtualOrigin, const std::vector< double > &virtualSpacing, const std::vector< double > &virtualDirection)
Set the virtual domain used for sampling.
void SetVirtualDomainFromImage (const Image &virtualImage)
Set the virtual domain used for sampling.
void SetOptimizerWeights (const std::vector< double > &weights)
A per parameter weighting array for the optimizer.
std::vector< double > GetOptimizerWeights () const
A per parameter weighting array for the optimizer.
void SetMetricSamplingPercentage (double percentage, unsigned int seed=sitkWallClock)
Set percentage of pixels sampled for metric evaluation.
void SetMetricSamplingPercentagePerLevel (const std::vector< double > &percentage, unsigned int seed=sitkWallClock)
Set percentage of pixels sampled for metric evaluation.
void SetMetricUseFixedImageGradientFilter (bool)
Enable image gradient computation by a filter.
void MetricUseFixedImageGradientFilterOn ()
Enable image gradient computation by a filter.
void MetricUseFixedImageGradientFilterOff ()
Enable image gradient computation by a filter.
void SetMetricUseMovingImageGradientFilter (bool)
Enable image gradient computation by a filter.
void MetricUseMovingImageGradientFilterOn ()
Enable image gradient computation by a filter.
void MetricUseMovingImageGradientFilterOff ()
Enable image gradient computation by a filter.
void SetSmoothingSigmasAreSpecifiedInPhysicalUnits (bool arg)
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
void SmoothingSigmasAreSpecifiedInPhysicalUnitsOn ()
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
void SmoothingSigmasAreSpecifiedInPhysicalUnitsOff ()
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Protected Member Functions
unsigned long AddITKObserver (const itk::EventObject &, itk::Command *) override
template<class TImageType>
itk::ImageToImageMetricv4< TImageType, TImageType, TImageType, double, itk::DefaultImageToImageMetricTraitsv4< TImageType, TImageType, TImageType, double > > * CreateMetric ()
itk::ObjectToObjectOptimizerBaseTemplate< double > * CreateOptimizer (unsigned int numberOfTransformParameters)
template<typename TMetric>
itk::RegistrationParameterScalesEstimator< TMetric > * CreateScalesEstimator ()
template<unsigned int VDimension>
itk::SpatialObject< VDimension > * CreateSpatialObjectMask (const Image &mask)
template<typename TTransformAdaptorPointer, typename TRegistrationMethod>
std::vector< TTransformAdaptorPointer > CreateTransformParametersAdaptor (TRegistrationMethod *method)
template<class TImage>
double EvaluateInternal (const Image &fixed, const Image &moving)
template<class TImage>
Transform ExecuteInternal (const Image &fixed, const Image &moving)
void OnActiveProcessDelete () noexcept override
void PreUpdate (itk::ProcessObject *p) override
void RemoveITKObserver (EventCommand &e) override
template<class TImageType>
void SetupMetric (itk::ImageToImageMetricv4< TImageType, TImageType, TImageType, double, itk::DefaultImageToImageMetricTraitsv4< TImageType, TImageType, TImageType, double > > *, const TImageType *, const TImageType *)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual itk::ProcessObject * GetActiveProcess ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Private Types
typedef double(ImageRegistrationMethod::* EvaluateMemberFunctionType) (const Image &fixed, const Image &moving)
typedef Transform(ImageRegistrationMethod::* MemberFunctionType) (const Image &fixed, const Image &moving)
enum MetricType {
ANTSNeighborhoodCorrelation ,
Correlation ,
Demons ,
JointHistogramMutualInformation ,
MeanSquares ,
MattesMutualInformation
}
enum OptimizerScalesType {
Manual ,
Jacobian ,
IndexShift ,
PhysicalShift
}
enum OptimizerType {
ConjugateGradientLineSearch ,
RegularStepGradientDescent ,
GradientDescent ,
GradientDescentLineSearch ,
LBFGSB ,
Exhaustive ,
Amoeba ,
Powell ,
OnePlusOneEvolutionary ,
LBFGS2
}
Private Attributes
itk::ObjectToObjectOptimizerBaseTemplate< double > * m_ActiveOptimizer
Transform m_FixedInitialTransform
Transform m_InitialTransform
bool m_InitialTransformInPlace
InterpolatorEnum m_Interpolator
unsigned int m_Iteration
Image m_MetricFixedMaskImage
double m_MetricIntensityDifferenceThreshold
Image m_MetricMovingMaskImage
unsigned int m_MetricNumberOfHistogramBins
unsigned int m_MetricRadius
std::vector< double > m_MetricSamplingPercentage
unsigned int m_MetricSamplingSeed
MetricSamplingStrategyType m_MetricSamplingStrategy
MetricType m_MetricType
bool m_MetricUseFixedImageGradientFilter
bool m_MetricUseMovingImageGradientFilter
double m_MetricValue
double m_MetricVarianceForJointPDFSmoothing
Transform m_MovingInitialTransform
uint64_t m_NumberOfValidPoints
double m_OptimizerConvergenceMinimumValue
unsigned int m_OptimizerConvergenceWindowSize
double m_OptimizerCostFunctionConvergenceFactor
unsigned int m_OptimizerDeltaConvergenceDistance
double m_OptimizerDeltaConvergenceTolerance
double m_OptimizerEpsilon
EstimateLearningRateType m_OptimizerEstimateLearningRate
double m_OptimizerFunctionConvergenceTolerance
double m_OptimizerGradientConvergenceTolerance
double m_OptimizerGradientMagnitudeTolerance
double m_OptimizerGrowthFactor
unsigned int m_OptimizerHessianApproximationAccuracy
double m_OptimizerInitialRadius
double m_OptimizerLearningRate
double m_OptimizerLineSearchAccuracy
double m_OptimizerLineSearchEpsilon
double m_OptimizerLineSearchLowerLimit
unsigned int m_OptimizerLineSearchMaximumEvaluations
unsigned int m_OptimizerLineSearchMaximumIterations
double m_OptimizerLineSearchMaximumStep
double m_OptimizerLineSearchMinimumStep
double m_OptimizerLineSearchUpperLimit
double m_OptimizerLowerBound
unsigned int m_OptimizerMaximumLineIterations
unsigned int m_OptimizerMaximumNumberOfCorrections
unsigned int m_OptimizerMaximumNumberOfFunctionEvaluations
double m_OptimizerMaximumStepSizeInPhysicalUnits
double m_OptimizerMinimumStepLength
unsigned int m_OptimizerNumberOfIterations
std::vector< unsigned int > m_OptimizerNumberOfSteps
double m_OptimizerParametersConvergenceTolerance
double m_OptimizerRelaxationFactor
std::vector< double > m_OptimizerScales
unsigned int m_OptimizerScalesCentralRegionRadius
double m_OptimizerScalesSmallParameterVariation
OptimizerScalesType m_OptimizerScalesType
unsigned int m_OptimizerSeed
double m_OptimizerShrinkFactor
double m_OptimizerSimplexDelta
double m_OptimizerSolutionAccuracy
double m_OptimizerStepLength
double m_OptimizerStepTolerance
bool m_OptimizerTrace
OptimizerType m_OptimizerType
double m_OptimizerUpperBound
double m_OptimizerValueTolerance
std::vector< double > m_OptimizerWeights
bool m_OptimizerWithRestarts
std::function< unsigned int()> m_pfGetCurrentLevel
std::function< uint64_t()> m_pfGetMetricNumberOfValidPoints
std::function< double()> m_pfGetMetricValue
std::function< double()> m_pfGetOptimizerConvergenceValue
std::function< unsigned int()> m_pfGetOptimizerIteration
std::function< double()> m_pfGetOptimizerLearningRate
std::function< std::vector< double >()> m_pfGetOptimizerPosition
std::function< std::vector< double >()> m_pfGetOptimizerScales
std::function< std::string()> m_pfGetOptimizerStopConditionDescription
std::function< void()> m_pfOptimizerStopRegistration
std::function< void(itk::TransformBase *outTransform)> m_pfUpdateWithBestValue
std::vector< unsigned int > m_ShrinkFactorsPerLevel
bool m_SmoothingSigmasAreSpecifiedInPhysicalUnits
std::vector< double > m_SmoothingSigmasPerLevel
std::string m_StopConditionDescription
std::vector< unsigned int > m_TransformBSplineScaleFactors
std::vector< double > m_VirtualDomainDirection
std::vector< double > m_VirtualDomainOrigin
std::vector< uint32_t > m_VirtualDomainSize
std::vector< double > m_VirtualDomainSpacing
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
EvaluateMemberFunctionType
typedef double(ImageRegistrationMethod::* itk::simple::ImageRegistrationMethod::EvaluateMemberFunctionType) (const Image &fixed, const Image &moving) private
Definition at line 833 of file sitkImageRegistrationMethod.h.
MemberFunctionType
typedef Transform(ImageRegistrationMethod::* itk::simple::ImageRegistrationMethod::MemberFunctionType) (const Image &fixed, const Image &moving) private
Definition at line 832 of file sitkImageRegistrationMethod.h.
Self
using itk::simple::ImageRegistrationMethod::Self = ImageRegistrationMethod
Definition at line 90 of file sitkImageRegistrationMethod.h.
Superclass
using itk::simple::ImageRegistrationMethod::Superclass = ProcessObject
Definition at line 91 of file sitkImageRegistrationMethod.h.
Member Enumeration Documentation
EstimateLearningRateType
enum itk::simple::ImageRegistrationMethod::EstimateLearningRateType
Enumerator
Never
Never run estimation, use provided value.
Once
Estimate learning once each level, ignore provided values.
EachIteration
Estimate learning rate at each iteration.
Definition at line 291 of file sitkImageRegistrationMethod.h.
MetricSamplingStrategyType
enum itk::simple::ImageRegistrationMethod::MetricSamplingStrategyType
Sampling strategies for obtaining points.
NONE: use all voxels, sampled points are the voxel centers.
REGULAR: sample every n-th voxel while traversing the image in scan-line order, then within each voxel randomly perturb from center.
RANDOM: sample image voxels with replacement using a uniform distribution, then within each voxel randomly perturb from center.
Enumerator
NONE
REGULAR
RANDOM
Definition at line 568 of file sitkImageRegistrationMethod.h.
MetricType
enum itk::simple::ImageRegistrationMethod::MetricType private
Enumerator
ANTSNeighborhoodCorrelation
Correlation
Demons
JointHistogramMutualInformation
MeanSquares
MattesMutualInformation
Definition at line 923 of file sitkImageRegistrationMethod.h.
OptimizerScalesType
enum itk::simple::ImageRegistrationMethod::OptimizerScalesType private
Enumerator
Manual
Jacobian
IndexShift
PhysicalShift
Definition at line 910 of file sitkImageRegistrationMethod.h.
OptimizerType
enum itk::simple::ImageRegistrationMethod::OptimizerType private
Enumerator
ConjugateGradientLineSearch
RegularStepGradientDescent
GradientDescent
GradientDescentLineSearch
LBFGSB
Exhaustive
Amoeba
Powell
OnePlusOneEvolutionary
LBFGS2
Definition at line 848 of file sitkImageRegistrationMethod.h.
Constructor & Destructor Documentation
~ImageRegistrationMethod()
itk::simple::ImageRegistrationMethod::~ImageRegistrationMethod () override
ImageRegistrationMethod()
itk::simple::ImageRegistrationMethod::ImageRegistrationMethod ()
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
Member Function Documentation
AddITKObserver()
unsigned long itk::simple::ImageRegistrationMethod::AddITKObserver (const itk::EventObject & , itk::Command *) override protected virtual
Reimplemented from itk::simple::ProcessObject.
References AddITKObserver(), and itk::simple::ProcessObject::itk::simple::Command.
Referenced by AddITKObserver().
CreateMetric()
template<class TImageType> itk::ImageToImageMetricv4< TImageType, TImageType, TImageType, double, itk::DefaultImageToImageMetricTraitsv4< TImageType, TImageType, TImageType, double > > * itk::simple::ImageRegistrationMethod::CreateMetric () protected
CreateOptimizer()
itk::ObjectToObjectOptimizerBaseTemplate< double > * itk::simple::ImageRegistrationMethod::CreateOptimizer (unsigned int numberOfTransformParameters) protected
CreateScalesEstimator()
template<typename TMetric> itk::RegistrationParameterScalesEstimator< TMetric > * itk::simple::ImageRegistrationMethod::CreateScalesEstimator () protected
CreateSpatialObjectMask()
template<unsigned int VDimension> itk::SpatialObject< VDimension > * itk::simple::ImageRegistrationMethod::CreateSpatialObjectMask (const Image & mask) protected
CreateTransformParametersAdaptor()
template<typename TTransformAdaptorPointer, typename TRegistrationMethod> std::vector< TTransformAdaptorPointer > itk::simple::ImageRegistrationMethod::CreateTransformParametersAdaptor (TRegistrationMethod * method) protected
EvaluateInternal()
template<class TImage> double itk::simple::ImageRegistrationMethod::EvaluateInternal (const Image & fixed, const Image & moving) protected
Referenced by itk::simple::ImageRegistrationMethod::EvaluateMemberFunctionAddressor< TMemberFunctionPointer >::operator()().
Execute()
Transform itk::simple::ImageRegistrationMethod::Execute (const Image & fixed, const Image & moving)
Optimize the configured registration problem.
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
ExecuteInternal()
template<class TImage> Transform itk::simple::ImageRegistrationMethod::ExecuteInternal (const Image & fixed, const Image & moving) protected
GetCurrentLevel()
unsigned int itk::simple::ImageRegistrationMethod::GetCurrentLevel () const
GetFixedInitialTransform()
Transform itk::simple::ImageRegistrationMethod::GetFixedInitialTransform () const inline
Set transform mapping to the fixed domain.
This transform is used to map from the virtual domain to the fixed image domain.
By default this transform is an identity, and not used.
See also
itk::ImageRegistrationMethodv4::SetFixedInitialTransform
Definition at line 224 of file sitkImageRegistrationMethod.h.
References m_FixedInitialTransform.
GetInitialTransform()
Transform itk::simple::ImageRegistrationMethod::GetInitialTransform () inline
Set the initial transform and parameters to optimize.
This transform is applied before the MovingInitialTransform, to map from the virtual image domain to the moving image domain.
If the inPlace flag is explicitly false, then the ITK registration will internally make a copy, and the transform will not be accessible during registration. Otherwise, the accessible InitialTransform value will be the same object used during registration, and will have a modified value upon completion.
See also
itk::ImageRegistrationMethodv4::SetInitialTransform
Definition at line 152 of file sitkImageRegistrationMethod.h.
References m_InitialTransform.
GetInitialTransformInPlace()
bool itk::simple::ImageRegistrationMethod::GetInitialTransformInPlace () const inline
Set the initial transform and parameters to optimize.
This transform is applied before the MovingInitialTransform, to map from the virtual image domain to the moving image domain.
If the inPlace flag is explicitly false, then the ITK registration will internally make a copy, and the transform will not be accessible during registration. Otherwise, the accessible InitialTransform value will be the same object used during registration, and will have a modified value upon completion.
See also
itk::ImageRegistrationMethodv4::SetInitialTransform
Definition at line 157 of file sitkImageRegistrationMethod.h.
References m_InitialTransformInPlace.
GetInterpolator()
InterpolatorEnum itk::simple::ImageRegistrationMethod::GetInterpolator () inline
Set and get the interpolator to use.
Definition at line 117 of file sitkImageRegistrationMethod.h.
References m_Interpolator.
GetMetricNumberOfValidPoints()
uint64_t itk::simple::ImageRegistrationMethod::GetMetricNumberOfValidPoints () const
Current number of points used of metric evaluation
This is a active measurement connected to the registration processes during registration. This number is number of point in the virtual domain which overlap the fixed image and the moving image. It is valid for sparse or dense sampling. After execution of registration this will contain the last value.
GetMetricSamplingPercentagePerLevel()
const std::vector< double > & itk::simple::ImageRegistrationMethod::GetMetricSamplingPercentagePerLevel () const
Get the percentage of pixels used for metric evaluation.
GetMetricValue()
double itk::simple::ImageRegistrationMethod::GetMetricValue () const
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
GetMovingInitialTransform()
Transform itk::simple::ImageRegistrationMethod::GetMovingInitialTransform () const inline
Set a fixed transform component towards moving domain.
The InitialTransform is added to this transform to form the composite transform which maps from the virtual domain to the moving image's domain. The parameters of this transform are not optimized. This is an advanced option used when the output transformed with be composed into a composite transform.
By default this transform is an identity, and not used.
See also
itk::ImageRegistrationMethodv4::SetMovingInitialTransform
Definition at line 202 of file sitkImageRegistrationMethod.h.
References m_MovingInitialTransform.
GetName()
std::string itk::simple::ImageRegistrationMethod::GetName () const inline override virtual
return user readable name for the filter
Implements itk::simple::ProcessObject.
Definition at line 98 of file sitkImageRegistrationMethod.h.
GetOptimizerConvergenceValue()
double itk::simple::ImageRegistrationMethod::GetOptimizerConvergenceValue () const
GetOptimizerIteration()
unsigned int itk::simple::ImageRegistrationMethod::GetOptimizerIteration () const
Active measurements which can be obtained during call backs.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
GetOptimizerLearningRate()
double itk::simple::ImageRegistrationMethod::GetOptimizerLearningRate () const
GetOptimizerPosition()
std::vector< double > itk::simple::ImageRegistrationMethod::GetOptimizerPosition () const
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, and ImageRegistrationMethod2/ImageRegistrationMethod2.cs.
GetOptimizerScales()
std::vector< double > itk::simple::ImageRegistrationMethod::GetOptimizerScales () const
Get the OptimizerScales.
If the scales are explicitly set then this method returns those values. If an estimator is used then this is an active measurement returning the scales estimated by the estimator and is only available during execution.
GetOptimizerStopConditionDescription()
std::string itk::simple::ImageRegistrationMethod::GetOptimizerStopConditionDescription () const
Measurement updated at the end of execution.
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
GetOptimizerWeights()
std::vector< double > itk::simple::ImageRegistrationMethod::GetOptimizerWeights () const
A per parameter weighting array for the optimizer.
Allows setting of a per-local-parameter weighting array. If unset, the weights are treated as identity. Weights are multiplied by the gradient at the same time scaling is applied. Weights are similar to the scales but not estimated, and may be used, for example, to easily mask out a particular parameter during optimization to hold it constant. Or they may be used to apply another kind of prior knowledge.
MetricEvaluate()
double itk::simple::ImageRegistrationMethod::MetricEvaluate (const Image & fixed, const Image & moving)
Get the value of the metric given the state of the method.
Passing a fixed and moving image, this method constructs and configures a metric object to obtain the value. This will take into consideration the current transforms, metric, interpolator, and image masks. It does not take into consideration the sampling strategy, smoothing sigmas, or the shrink factors.
MetricUseFixedImageGradientFilterOff()
void itk::simple::ImageRegistrationMethod::MetricUseFixedImageGradientFilterOff () inline
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function with be computed as needed.
See also
itk::ImageToImageMetricv4::SetUseFixedImageGradientFilter
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
Definition at line 599 of file sitkImageRegistrationMethod.h.
References SetMetricUseFixedImageGradientFilter().
MetricUseFixedImageGradientFilterOn()
void itk::simple::ImageRegistrationMethod::MetricUseFixedImageGradientFilterOn () inline
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function with be computed as needed.
See also
itk::ImageToImageMetricv4::SetUseFixedImageGradientFilter
Definition at line 594 of file sitkImageRegistrationMethod.h.
References SetMetricUseFixedImageGradientFilter().
MetricUseMovingImageGradientFilterOff()
void itk::simple::ImageRegistrationMethod::MetricUseMovingImageGradientFilterOff () inline
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function will be computed for each sample as needed.
See also
itk::ImageToImageMetricv4::SetUseMovingImageGradientFilter
Definition at line 624 of file sitkImageRegistrationMethod.h.
References SetMetricUseMovingImageGradientFilter().
MetricUseMovingImageGradientFilterOn()
void itk::simple::ImageRegistrationMethod::MetricUseMovingImageGradientFilterOn () inline
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function will be computed for each sample as needed.
See also
itk::ImageToImageMetricv4::SetUseMovingImageGradientFilter
Definition at line 619 of file sitkImageRegistrationMethod.h.
References SetMetricUseMovingImageGradientFilter().
OnActiveProcessDelete()
void itk::simple::ImageRegistrationMethod::OnActiveProcessDelete () override protected virtual noexcept
Reimplemented from itk::simple::ProcessObject.
PreUpdate()
void itk::simple::ImageRegistrationMethod::PreUpdate (itk::ProcessObject * p) override protected virtual
Reimplemented from itk::simple::ProcessObject.
RemoveITKObserver()
void itk::simple::ImageRegistrationMethod::RemoveITKObserver (EventCommand & e) override protected virtual
Reimplemented from itk::simple::ProcessObject.
References RemoveITKObserver().
Referenced by RemoveITKObserver().
SetFixedInitialTransform()
void itk::simple::ImageRegistrationMethod::SetFixedInitialTransform (const Transform & transform) inline
Set transform mapping to the fixed domain.
This transform is used to map from the virtual domain to the fixed image domain.
By default this transform is an identity, and not used.
See also
itk::ImageRegistrationMethodv4::SetFixedInitialTransform
Definition at line 219 of file sitkImageRegistrationMethod.h.
References m_FixedInitialTransform.
SetInitialTransform() [1/2]
void itk::simple::ImageRegistrationMethod::SetInitialTransform (const Transform & transform)
Set the initial transform and parameters to optimize.
This transform is applied before the MovingInitialTransform, to map from the virtual image domain to the moving image domain.
If the inPlace flag is explicitly false, then the ITK registration will internally make a copy, and the transform will not be accessible during registration. Otherwise, the accessible InitialTransform value will be the same object used during registration, and will have a modified value upon completion.
See also
itk::ImageRegistrationMethodv4::SetInitialTransform
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetInitialTransform() [2/2]
void itk::simple::ImageRegistrationMethod::SetInitialTransform (Transform & transform, bool inPlace = true)
Set the initial transform and parameters to optimize.
This transform is applied before the MovingInitialTransform, to map from the virtual image domain to the moving image domain.
If the inPlace flag is explicitly false, then the ITK registration will internally make a copy, and the transform will not be accessible during registration. Otherwise, the accessible InitialTransform value will be the same object used during registration, and will have a modified value upon completion.
See also
itk::ImageRegistrationMethodv4::SetInitialTransform
SetInitialTransformAsBSpline()
void itk::simple::ImageRegistrationMethod::SetInitialTransformAsBSpline (BSplineTransform & transform, bool inPlace = true, const std::vector< unsigned int > & scaleFactors = std::vector< unsigned int >())
Set an initial BSpline transform to optimize.
A specialization of SetInitialTransform for BSplineTransforms which can take an additional scaleFactors parameter. The scaleFactors specifies the a isotropic scaling factor per level for the BSpline transform mesh size with respect to the initial transform. For example to double the BSpline mesh resolution at each of 3 levels the vector [1,2,4] should be provided.
If a per level scale factor is 0 or omitted than no transform adapter will be created for that level.
See also
itk::BSplineTransformParametersAdaptor
Examples
ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx.
SetInterpolator()
void itk::simple::ImageRegistrationMethod::SetInterpolator (InterpolatorEnum Interpolator) inline
Set and get the interpolator to use.
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, ImageRegistrationMethod1/ImageRegistrationMethod1.cxx, ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
Definition at line 122 of file sitkImageRegistrationMethod.h.
References m_Interpolator.
SetMetricAsANTSNeighborhoodCorrelation()
void itk::simple::ImageRegistrationMethod::SetMetricAsANTSNeighborhoodCorrelation (unsigned int radius)
Use normalized cross correlation using a small neighborhood for each voxel between two images, with speed optimizations for dense registration.
See also
itk::ANTSNeighborhoodCorrelationImageToImageMetricv4
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetMetricAsCorrelation()
void itk::simple::ImageRegistrationMethod::SetMetricAsCorrelation ()
Use negative normalized cross correlation image metric.
See also
itk::CorrelationImageToImageMetricv4
Examples
ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx.
SetMetricAsDemons()
void itk::simple::ImageRegistrationMethod::SetMetricAsDemons (double intensityDifferenceThreshold = 0.001)
Use demons image metric.
See also
itk::DemonsImageToImageMetricv4
SetMetricAsJointHistogramMutualInformation()
void itk::simple::ImageRegistrationMethod::SetMetricAsJointHistogramMutualInformation (unsigned int numberOfHistogramBins = 20, double varianceForJointPDFSmoothing = 1.5)
Use mutual information between two images.
See also
itk::JointHistogramMutualInformationImageToImageMetricv4
Examples
ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetMetricAsMattesMutualInformation()
void itk::simple::ImageRegistrationMethod::SetMetricAsMattesMutualInformation (unsigned int numberOfHistogramBins = 50)
Use the mutual information between two images to be registered using the method of Mattes et al.
See also
itk::MattesMutualInformationImageToImageMetricv4
SetMetricAsMeanSquares()
void itk::simple::ImageRegistrationMethod::SetMetricAsMeanSquares ()
Use negative means squares image metric.
See also
itk::MeanSquaresImageToImageMetricv4
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, and ImageRegistrationMethod1/ImageRegistrationMethod1.cxx.
SetMetricFixedMask()
void itk::simple::ImageRegistrationMethod::SetMetricFixedMask (const Image & binaryMask)
Set an image mask in order to restrict the sampled points for the metric.
The image is expected to be in the same physical space as the FixedImage, and if the pixel type is not UInt8 than the image will base cast.
See also
itk::ImageToImageMetricv4::SetFixedImageMask
SetMetricMovingMask()
void itk::simple::ImageRegistrationMethod::SetMetricMovingMask (const Image & binaryMask)
Set an image mask in order to restrict the sampled points for the metric in the moving image space.
The image is expected to be in the same physical space as the MovingImage, and if the pixel type is not UInt8 than the image will base cast.
See also
itk::ImageToImageMetricv4::SetMovingImageMask
SetMetricSamplingPercentage()
void itk::simple::ImageRegistrationMethod::SetMetricSamplingPercentage (double percentage, unsigned int seed = sitkWallClock)
Set percentage of pixels sampled for metric evaluation.
The percentage is of the number of pixels in the virtual domain per level after the shrink factor has been applied.
The seed parameter is used to seed the pseudo-random number generator used in generating the sampling set of points. If the seed parameter is 0, then the wall clock is used, otherwise the fixed seed is used for reproducible behavior.
When providing multiple values the number of entries must match the number of shrink factors and smoothing sigmas. If a single value is given, then the same percentage is used for all levels.
See also
itk::ImageRegistrationMethodv4::SetMetricSamplingPercentage
References itk::simple::sitkWallClock.
SetMetricSamplingPercentagePerLevel()
void itk::simple::ImageRegistrationMethod::SetMetricSamplingPercentagePerLevel (const std::vector< double > & percentage, unsigned int seed = sitkWallClock)
Set percentage of pixels sampled for metric evaluation.
The percentage is of the number of pixels in the virtual domain per level after the shrink factor has been applied.
The seed parameter is used to seed the pseudo-random number generator used in generating the sampling set of points. If the seed parameter is 0, then the wall clock is used, otherwise the fixed seed is used for reproducible behavior.
When providing multiple values the number of entries must match the number of shrink factors and smoothing sigmas. If a single value is given, then the same percentage is used for all levels.
See also
itk::ImageRegistrationMethodv4::SetMetricSamplingPercentage
References itk::simple::sitkWallClock.
SetMetricSamplingStrategy()
void itk::simple::ImageRegistrationMethod::SetMetricSamplingStrategy (MetricSamplingStrategyType strategy)
Set sampling strategy for sample generation.
See also
itk::ImageRegistrationMethodv4::SetMetricSamplingStrategy
SetMetricUseFixedImageGradientFilter()
void itk::simple::ImageRegistrationMethod::SetMetricUseFixedImageGradientFilter (bool)
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function with be computed as needed.
See also
itk::ImageToImageMetricv4::SetUseFixedImageGradientFilter
Referenced by MetricUseFixedImageGradientFilterOff(), and MetricUseFixedImageGradientFilterOn().
SetMetricUseMovingImageGradientFilter()
void itk::simple::ImageRegistrationMethod::SetMetricUseMovingImageGradientFilter (bool)
Enable image gradient computation by a filter.
By default the image gradient is computed by itk::GradientRecursiveGaussianImageFiter. If disabled then a central difference function will be computed for each sample as needed.
See also
itk::ImageToImageMetricv4::SetUseMovingImageGradientFilter
Referenced by MetricUseMovingImageGradientFilterOff(), and MetricUseMovingImageGradientFilterOn().
SetMovingInitialTransform()
void itk::simple::ImageRegistrationMethod::SetMovingInitialTransform (const Transform & transform) inline
Set a fixed transform component towards moving domain.
The InitialTransform is added to this transform to form the composite transform which maps from the virtual domain to the moving image's domain. The parameters of this transform are not optimized. This is an advanced option used when the output transformed with be composed into a composite transform.
By default this transform is an identity, and not used.
See also
itk::ImageRegistrationMethodv4::SetMovingInitialTransform
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
Definition at line 197 of file sitkImageRegistrationMethod.h.
References m_MovingInitialTransform.
SetOptimizerAsAmoeba()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsAmoeba (double simplexDelta, unsigned int numberOfIterations, double parametersConvergenceTolerance = 1e-8, double functionConvergenceTolerance = 1e-4, bool withRestarts = false)
Set optimizer to Nelder-Mead downhill simplex algorithm.
The simplexDelta is the value that is added and subtracted to the initial parameters to create the initial simplex. The simplexDelta can be indirectly set per parameter by the optimizer parameter scaling either manually or by using an estimator.
See also
ImageRegistrationMethod::SetOptimizerScales
itk::AmoebaOptimizerv4
SetOptimizerAsConjugateGradientLineSearch()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsConjugateGradientLineSearch (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue = 1e-6, unsigned int convergenceWindowSize = 10, double lineSearchLowerLimit = 0, double lineSearchUpperLimit = 5.0, double lineSearchEpsilon = 0.01, unsigned int lineSearchMaximumIterations = 20, EstimateLearningRateType estimateLearningRate = Once, double maximumStepSizeInPhysicalUnits = 0.0)
Conjugate gradient descent optimizer with a golden section line search for nonlinear optimization.
See also
itk::ConjugateGradientLineSearchOptimizerv4Template
References Once.
SetOptimizerAsExhaustive()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsExhaustive (const std::vector< unsigned int > & numberOfSteps, double stepLength = 1.0)
Set the optimizer to sample the metric at regular steps.
At each iteration the GetOptimizerIteration, can be used to index into the sampling grid along with the GetCurrentMetricValue.
The resulting transform and value at the end of execution is the best location.
The OptimizerScales can be used to perform anisotropic sampling.
Note
This optimizer is not suitable for use in conjunction with the multiple scales.
See also
itk::ExhaustiveOptimizerv4
SetOptimizerAsGradientDescent()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsGradientDescent (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue = 1e-6, unsigned int convergenceWindowSize = 10, EstimateLearningRateType estimateLearningRate = Once, double maximumStepSizeInPhysicalUnits = 0.0)
Gradient descent optimizer.
See also
itk::GradientDescentOptimizerv4Template
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
References Once.
SetOptimizerAsGradientDescentLineSearch()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsGradientDescentLineSearch (double learningRate, unsigned int numberOfIterations, double convergenceMinimumValue = 1e-6, unsigned int convergenceWindowSize = 10, double lineSearchLowerLimit = 0, double lineSearchUpperLimit = 5.0, double lineSearchEpsilon = 0.01, unsigned int lineSearchMaximumIterations = 20, EstimateLearningRateType estimateLearningRate = Once, double maximumStepSizeInPhysicalUnits = 0.0)
Gradient descent optimizer with a golden section line search.
See also
itk::GradientDescentLineSearchOptimizerv4Template
Examples
ImageRegistrationMethod2/ImageRegistrationMethod2.cs, ImageRegistrationMethod2/ImageRegistrationMethod2.cxx, and ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx.
References Once.
SetOptimizerAsLBFGS2()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsLBFGS2 (double solutionAccuracy = 1e-5, unsigned int numberOfIterations = 0, unsigned int hessianApproximateAccuracy = 6, unsigned int deltaConvergenceDistance = 0, double deltaConvergenceTolerance = 1e-5, unsigned int lineSearchMaximumEvaluations = 40, double lineSearchMinimumStep = 1e-20, double lineSearchMaximumStep = 1e20, double lineSearchAccuracy = 1e-4)
Limited memory Broyden Fletcher Goldfarb Shannon minimization without bounds.
The default parameters utilize LBFGSB in unbounded mode. This version is from LibLBFGS.
There are upto 3 stopping criteria:
the solution accuracy which is the magnitude of the gradient
the delta convergence which ensures the decrease of the metric
maximum number of iterations
See also
itk::LBFGS2Optimizerv4
SetOptimizerAsLBFGSB()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsLBFGSB (double gradientConvergenceTolerance = 1e-5, unsigned int numberOfIterations = 500, unsigned int maximumNumberOfCorrections = 5, unsigned int maximumNumberOfFunctionEvaluations = 2000, double costFunctionConvergenceFactor = 1e+7, double lowerBound = std::numeric_limits< double >::min(), double upperBound = std::numeric_limits< double >::max(), bool trace = false)
Limited memory Broyden Fletcher Goldfarb Shannon minimization with simple bounds.
The default parameters utilize LBFGSB in unbounded mode.
See also
itk::LBFGSBOptimizerv4
Examples
ImageRegistrationMethodBSpline1/ImageRegistrationMethodBSpline1.cxx.
SetOptimizerAsOnePlusOneEvolutionary()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsOnePlusOneEvolutionary (unsigned int numberOfIterations = 100, double epsilon = 1.5e-4, double initialRadius = 1.01, double growthFactor = -1.0, double shrinkFactor = -1.0, unsigned int seed = sitkWallClock)
1+1 evolutionary optimizer strategy.
The seed parameter is used to seed the pseudo-random number generator. If the seed parameter is 0, then the wall clock is used to seed, otherwise the fixed seed is used for reproducible behavior.
See also
itk::OnePlusOneEvolutionaryOptimizerv4
References itk::simple::sitkWallClock.
SetOptimizerAsPowell()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsPowell (unsigned int numberOfIterations = 100, unsigned int maximumLineIterations = 100, double stepLength = 1, double stepTolerance = 1e-6, double valueTolerance = 1e-6)
Powell optimization using Brent line search.
See also
itk::PowellOptimizerv4
SetOptimizerAsRegularStepGradientDescent()
void itk::simple::ImageRegistrationMethod::SetOptimizerAsRegularStepGradientDescent (double learningRate, double minStep, unsigned int numberOfIterations, double relaxationFactor = 0.5, double gradientMagnitudeTolerance = 1e-4, EstimateLearningRateType estimateLearningRate = Never, double maximumStepSizeInPhysicalUnits = 0.0)
Regular Step Gradient descent optimizer.
See also
itk::RegularStepGradientDescentOptimizerv4
Examples
ImageRegistrationMethod1/ImageRegistrationMethod1.cs, and ImageRegistrationMethod1/ImageRegistrationMethod1.cxx.
References Never.
SetOptimizerScales()
void itk::simple::ImageRegistrationMethod::SetOptimizerScales (const std::vector< double > & scales)
Manually set per parameter weighting for the transform parameters.
SetOptimizerScalesFromIndexShift()
void itk::simple::ImageRegistrationMethod::SetOptimizerScalesFromIndexShift (unsigned int centralRegionRadius = 5, double smallParameterVariation = 0.01)
Estimate scales from maximum voxel shift in index space cause by parameter change.
See also
itk::RegistrationParameterScalesFromIndexShift
SetOptimizerScalesFromJacobian()
void itk::simple::ImageRegistrationMethod::SetOptimizerScalesFromJacobian (unsigned int centralRegionRadius = 5)
Estimate scales from Jacobian norms.
This scales estimator works well with versor based transforms.
See also
itk::RegistrationParameterScalesFromJacobian
SetOptimizerScalesFromPhysicalShift()
void itk::simple::ImageRegistrationMethod::SetOptimizerScalesFromPhysicalShift (unsigned int centralRegionRadius = 5, double smallParameterVariation = 0.01)
Estimating scales of transform parameters a step sizes, from the maximum voxel shift in physical space caused by a parameter change.
See also
itk::RegistrationParameterScalesFromPhysicalShift
Examples
ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetOptimizerWeights()
void itk::simple::ImageRegistrationMethod::SetOptimizerWeights (const std::vector< double > & weights)
A per parameter weighting array for the optimizer.
Allows setting of a per-local-parameter weighting array. If unset, the weights are treated as identity. Weights are multiplied by the gradient at the same time scaling is applied. Weights are similar to the scales but not estimated, and may be used, for example, to easily mask out a particular parameter during optimization to hold it constant. Or they may be used to apply another kind of prior knowledge.
SetShrinkFactorsPerLevel()
void itk::simple::ImageRegistrationMethod::SetShrinkFactorsPerLevel (const std::vector< unsigned int > & shrinkFactors)
Set the isotropic shrink factors for each level.
The virtual domain image is shrunk by this factor relative to the full size of the original virtual domain.
See also
itk::ImageRegistrationMethodv4::SetShrinkFactorsPerLevel
Examples
ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetSmoothingSigmasAreSpecifiedInPhysicalUnits()
void itk::simple::ImageRegistrationMethod::SetSmoothingSigmasAreSpecifiedInPhysicalUnits (bool arg)
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
See also
itk::ImageRegistrationMethodv4::SetSmoothingSigmasAreSpecifiedInPhysicalUnits
Referenced by SmoothingSigmasAreSpecifiedInPhysicalUnitsOff(), and SmoothingSigmasAreSpecifiedInPhysicalUnitsOn().
SetSmoothingSigmasPerLevel()
void itk::simple::ImageRegistrationMethod::SetSmoothingSigmasPerLevel (const std::vector< double > & smoothingSigmas)
Set the sigmas of Gaussian used for smoothing.
The smoothing is applied to both the fixed and the moving images at each level. The number of smoothing sigmas must match the number of shrink factors.
See also
itk::ImageRegistrationMethodv4::SetSmoothingSigmasPerLevel
Examples
ImageRegistrationMethodBSpline3/ImageRegistrationMethodBSpline3.cxx, and ImageRegistrationMethodDisplacement1/ImageRegistrationMethodDisplacement1.cxx.
SetupMetric()
template<class TImageType> void itk::simple::ImageRegistrationMethod::SetupMetric (itk::ImageToImageMetricv4< TImageType, TImageType, TImageType, double, itk::DefaultImageToImageMetricTraitsv4< TImageType, TImageType, TImageType, double > > * , const TImageType * , const TImageType *) protected
SetVirtualDomain()
void itk::simple::ImageRegistrationMethod::SetVirtualDomain (const std::vector< uint32_t > & virtualSize, const std::vector< double > & virtualOrigin, const std::vector< double > & virtualSpacing, const std::vector< double > & virtualDirection)
Set the virtual domain used for sampling.
SetVirtualDomainFromImage()
void itk::simple::ImageRegistrationMethod::SetVirtualDomainFromImage (const Image & virtualImage)
Set the virtual domain used for sampling.
SmoothingSigmasAreSpecifiedInPhysicalUnitsOff()
void itk::simple::ImageRegistrationMethod::SmoothingSigmasAreSpecifiedInPhysicalUnitsOff () inline
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
See also
itk::ImageRegistrationMethodv4::SetSmoothingSigmasAreSpecifiedInPhysicalUnits
Definition at line 666 of file sitkImageRegistrationMethod.h.
References SetSmoothingSigmasAreSpecifiedInPhysicalUnits().
SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()
void itk::simple::ImageRegistrationMethod::SmoothingSigmasAreSpecifiedInPhysicalUnitsOn () inline
Enable the smoothing sigmas for each level in physical units (default) or in terms of voxels.
See also
itk::ImageRegistrationMethodv4::SetSmoothingSigmasAreSpecifiedInPhysicalUnits
Definition at line 661 of file sitkImageRegistrationMethod.h.
References SetSmoothingSigmasAreSpecifiedInPhysicalUnits().
StopRegistration()
bool itk::simple::ImageRegistrationMethod::StopRegistration ()
Stop Registration if actively running.
This is an active method which can be called during a callback. Invoking this method will halt the registration at the current iteration, if supported by the optimizer. The LBFGSB, LBFGS2, and the Amoeba optimizers do not support user stopping.
If user stopping is not supported or the optimizer is available (not executed), then false will be returned.
ToString()
std::string itk::simple::ImageRegistrationMethod::ToString () const override virtual
Print the information about the object to a string.
If called when the process is being executed (during a callback), the ITK Optimizer and Transform objects will be printed.
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 833 of file sitkImageRegistrationMethod.h.
References ImageRegistrationMethod().
Member Data Documentation
m_ActiveOptimizer
itk::ObjectToObjectOptimizerBaseTemplate<double>* itk::simple::ImageRegistrationMethod::m_ActiveOptimizer private
Definition at line 957 of file sitkImageRegistrationMethod.h.
m_FixedInitialTransform
Transform itk::simple::ImageRegistrationMethod::m_FixedInitialTransform private
Definition at line 840 of file sitkImageRegistrationMethod.h.
Referenced by GetFixedInitialTransform(), and SetFixedInitialTransform().
m_InitialTransform
Transform itk::simple::ImageRegistrationMethod::m_InitialTransform private
Definition at line 837 of file sitkImageRegistrationMethod.h.
Referenced by GetInitialTransform().
m_InitialTransformInPlace
bool itk::simple::ImageRegistrationMethod::m_InitialTransformInPlace private
Definition at line 838 of file sitkImageRegistrationMethod.h.
Referenced by GetInitialTransformInPlace().
m_Interpolator
InterpolatorEnum itk::simple::ImageRegistrationMethod::m_Interpolator private
Definition at line 836 of file sitkImageRegistrationMethod.h.
Referenced by GetInterpolator(), and SetInterpolator().
m_Iteration
unsigned int itk::simple::ImageRegistrationMethod::m_Iteration private
Definition at line 954 of file sitkImageRegistrationMethod.h.
m_MetricFixedMaskImage
Image itk::simple::ImageRegistrationMethod::m_MetricFixedMaskImage private
Definition at line 938 of file sitkImageRegistrationMethod.h.
m_MetricIntensityDifferenceThreshold
double itk::simple::ImageRegistrationMethod::m_MetricIntensityDifferenceThreshold private
Definition at line 934 of file sitkImageRegistrationMethod.h.
m_MetricMovingMaskImage
Image itk::simple::ImageRegistrationMethod::m_MetricMovingMaskImage private
Definition at line 939 of file sitkImageRegistrationMethod.h.
m_MetricNumberOfHistogramBins
unsigned int itk::simple::ImageRegistrationMethod::m_MetricNumberOfHistogramBins private
Definition at line 935 of file sitkImageRegistrationMethod.h.
m_MetricRadius
unsigned int itk::simple::ImageRegistrationMethod::m_MetricRadius private
Definition at line 933 of file sitkImageRegistrationMethod.h.
m_MetricSamplingPercentage
std::vector<double> itk::simple::ImageRegistrationMethod::m_MetricSamplingPercentage private
Definition at line 941 of file sitkImageRegistrationMethod.h.
m_MetricSamplingSeed
unsigned int itk::simple::ImageRegistrationMethod::m_MetricSamplingSeed private
Definition at line 943 of file sitkImageRegistrationMethod.h.
m_MetricSamplingStrategy
MetricSamplingStrategyType itk::simple::ImageRegistrationMethod::m_MetricSamplingStrategy private
Definition at line 942 of file sitkImageRegistrationMethod.h.
m_MetricType
MetricType itk::simple::ImageRegistrationMethod::m_MetricType private
Definition at line 932 of file sitkImageRegistrationMethod.h.
m_MetricUseFixedImageGradientFilter
bool itk::simple::ImageRegistrationMethod::m_MetricUseFixedImageGradientFilter private
Definition at line 945 of file sitkImageRegistrationMethod.h.
m_MetricUseMovingImageGradientFilter
bool itk::simple::ImageRegistrationMethod::m_MetricUseMovingImageGradientFilter private
Definition at line 946 of file sitkImageRegistrationMethod.h.
m_MetricValue
double itk::simple::ImageRegistrationMethod::m_MetricValue private
Definition at line 953 of file sitkImageRegistrationMethod.h.
m_MetricVarianceForJointPDFSmoothing
double itk::simple::ImageRegistrationMethod::m_MetricVarianceForJointPDFSmoothing private
Definition at line 936 of file sitkImageRegistrationMethod.h.
m_MovingInitialTransform
Transform itk::simple::ImageRegistrationMethod::m_MovingInitialTransform private
Definition at line 839 of file sitkImageRegistrationMethod.h.
Referenced by GetMovingInitialTransform(), and SetMovingInitialTransform().
m_NumberOfValidPoints
uint64_t itk::simple::ImageRegistrationMethod::m_NumberOfValidPoints private
Definition at line 955 of file sitkImageRegistrationMethod.h.
m_OptimizerConvergenceMinimumValue
double itk::simple::ImageRegistrationMethod::m_OptimizerConvergenceMinimumValue private
Definition at line 873 of file sitkImageRegistrationMethod.h.
m_OptimizerConvergenceWindowSize
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerConvergenceWindowSize private
Definition at line 874 of file sitkImageRegistrationMethod.h.
m_OptimizerCostFunctionConvergenceFactor
double itk::simple::ImageRegistrationMethod::m_OptimizerCostFunctionConvergenceFactor private
Definition at line 878 of file sitkImageRegistrationMethod.h.
m_OptimizerDeltaConvergenceDistance
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerDeltaConvergenceDistance private
Definition at line 898 of file sitkImageRegistrationMethod.h.
m_OptimizerDeltaConvergenceTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerDeltaConvergenceTolerance private
Definition at line 899 of file sitkImageRegistrationMethod.h.
m_OptimizerEpsilon
double itk::simple::ImageRegistrationMethod::m_OptimizerEpsilon private
Definition at line 891 of file sitkImageRegistrationMethod.h.
m_OptimizerEstimateLearningRate
EstimateLearningRateType itk::simple::ImageRegistrationMethod::m_OptimizerEstimateLearningRate private
Definition at line 869 of file sitkImageRegistrationMethod.h.
m_OptimizerFunctionConvergenceTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerFunctionConvergenceTolerance private
Definition at line 886 of file sitkImageRegistrationMethod.h.
m_OptimizerGradientConvergenceTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerGradientConvergenceTolerance private
Definition at line 875 of file sitkImageRegistrationMethod.h.
m_OptimizerGradientMagnitudeTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerGradientMagnitudeTolerance private
Definition at line 872 of file sitkImageRegistrationMethod.h.
m_OptimizerGrowthFactor
double itk::simple::ImageRegistrationMethod::m_OptimizerGrowthFactor private
Definition at line 893 of file sitkImageRegistrationMethod.h.
m_OptimizerHessianApproximationAccuracy
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerHessianApproximationAccuracy private
Definition at line 897 of file sitkImageRegistrationMethod.h.
m_OptimizerInitialRadius
double itk::simple::ImageRegistrationMethod::m_OptimizerInitialRadius private
Definition at line 892 of file sitkImageRegistrationMethod.h.
m_OptimizerLearningRate
double itk::simple::ImageRegistrationMethod::m_OptimizerLearningRate private
Definition at line 862 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchAccuracy
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchAccuracy private
Definition at line 903 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchEpsilon
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchEpsilon private
Definition at line 867 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchLowerLimit
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchLowerLimit private
Definition at line 865 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchMaximumEvaluations
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchMaximumEvaluations private
Definition at line 900 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchMaximumIterations
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchMaximumIterations private
Definition at line 868 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchMaximumStep
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchMaximumStep private
Definition at line 902 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchMinimumStep
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchMinimumStep private
Definition at line 901 of file sitkImageRegistrationMethod.h.
m_OptimizerLineSearchUpperLimit
double itk::simple::ImageRegistrationMethod::m_OptimizerLineSearchUpperLimit private
Definition at line 866 of file sitkImageRegistrationMethod.h.
m_OptimizerLowerBound
double itk::simple::ImageRegistrationMethod::m_OptimizerLowerBound private
Definition at line 879 of file sitkImageRegistrationMethod.h.
m_OptimizerMaximumLineIterations
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerMaximumLineIterations private
Definition at line 888 of file sitkImageRegistrationMethod.h.
m_OptimizerMaximumNumberOfCorrections
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerMaximumNumberOfCorrections private
Definition at line 876 of file sitkImageRegistrationMethod.h.
m_OptimizerMaximumNumberOfFunctionEvaluations
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerMaximumNumberOfFunctionEvaluations private
Definition at line 877 of file sitkImageRegistrationMethod.h.
m_OptimizerMaximumStepSizeInPhysicalUnits
double itk::simple::ImageRegistrationMethod::m_OptimizerMaximumStepSizeInPhysicalUnits private
Definition at line 870 of file sitkImageRegistrationMethod.h.
m_OptimizerMinimumStepLength
double itk::simple::ImageRegistrationMethod::m_OptimizerMinimumStepLength private
Definition at line 863 of file sitkImageRegistrationMethod.h.
m_OptimizerNumberOfIterations
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerNumberOfIterations private
Definition at line 864 of file sitkImageRegistrationMethod.h.
m_OptimizerNumberOfSteps
std::vector<unsigned int> itk::simple::ImageRegistrationMethod::m_OptimizerNumberOfSteps private
Definition at line 882 of file sitkImageRegistrationMethod.h.
m_OptimizerParametersConvergenceTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerParametersConvergenceTolerance private
Definition at line 885 of file sitkImageRegistrationMethod.h.
m_OptimizerRelaxationFactor
double itk::simple::ImageRegistrationMethod::m_OptimizerRelaxationFactor private
Definition at line 871 of file sitkImageRegistrationMethod.h.
m_OptimizerScales
std::vector<double> itk::simple::ImageRegistrationMethod::m_OptimizerScales private
Definition at line 918 of file sitkImageRegistrationMethod.h.
m_OptimizerScalesCentralRegionRadius
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerScalesCentralRegionRadius private
Definition at line 919 of file sitkImageRegistrationMethod.h.
m_OptimizerScalesSmallParameterVariation
double itk::simple::ImageRegistrationMethod::m_OptimizerScalesSmallParameterVariation private
Definition at line 920 of file sitkImageRegistrationMethod.h.
m_OptimizerScalesType
OptimizerScalesType itk::simple::ImageRegistrationMethod::m_OptimizerScalesType private
Definition at line 917 of file sitkImageRegistrationMethod.h.
m_OptimizerSeed
unsigned int itk::simple::ImageRegistrationMethod::m_OptimizerSeed private
Definition at line 895 of file sitkImageRegistrationMethod.h.
m_OptimizerShrinkFactor
double itk::simple::ImageRegistrationMethod::m_OptimizerShrinkFactor private
Definition at line 894 of file sitkImageRegistrationMethod.h.
m_OptimizerSimplexDelta
double itk::simple::ImageRegistrationMethod::m_OptimizerSimplexDelta private
Definition at line 884 of file sitkImageRegistrationMethod.h.
m_OptimizerSolutionAccuracy
double itk::simple::ImageRegistrationMethod::m_OptimizerSolutionAccuracy private
Definition at line 896 of file sitkImageRegistrationMethod.h.
m_OptimizerStepLength
double itk::simple::ImageRegistrationMethod::m_OptimizerStepLength private
Definition at line 883 of file sitkImageRegistrationMethod.h.
m_OptimizerStepTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerStepTolerance private
Definition at line 889 of file sitkImageRegistrationMethod.h.
m_OptimizerTrace
bool itk::simple::ImageRegistrationMethod::m_OptimizerTrace private
Definition at line 881 of file sitkImageRegistrationMethod.h.
m_OptimizerType
OptimizerType itk::simple::ImageRegistrationMethod::m_OptimizerType private
Definition at line 861 of file sitkImageRegistrationMethod.h.
m_OptimizerUpperBound
double itk::simple::ImageRegistrationMethod::m_OptimizerUpperBound private
Definition at line 880 of file sitkImageRegistrationMethod.h.
m_OptimizerValueTolerance
double itk::simple::ImageRegistrationMethod::m_OptimizerValueTolerance private
Definition at line 890 of file sitkImageRegistrationMethod.h.
m_OptimizerWeights
std::vector<double> itk::simple::ImageRegistrationMethod::m_OptimizerWeights private
Definition at line 908 of file sitkImageRegistrationMethod.h.
m_OptimizerWithRestarts
bool itk::simple::ImageRegistrationMethod::m_OptimizerWithRestarts private
Definition at line 887 of file sitkImageRegistrationMethod.h.
m_pfGetCurrentLevel
std::function<unsigned int()> itk::simple::ImageRegistrationMethod::m_pfGetCurrentLevel private
Definition at line 815 of file sitkImageRegistrationMethod.h.
m_pfGetMetricNumberOfValidPoints
std::function<uint64_t()> itk::simple::ImageRegistrationMethod::m_pfGetMetricNumberOfValidPoints private
Definition at line 809 of file sitkImageRegistrationMethod.h.
m_pfGetMetricValue
std::function<double()> itk::simple::ImageRegistrationMethod::m_pfGetMetricValue private
Definition at line 808 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerConvergenceValue
std::function<double()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerConvergenceValue private
Definition at line 807 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerIteration
std::function<unsigned int()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerIteration private
Definition at line 804 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerLearningRate
std::function<double()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerLearningRate private
Definition at line 806 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerPosition
std::function<std::vector<double>()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerPosition private
Definition at line 805 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerScales
std::function<std::vector<double>()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerScales private
Definition at line 810 of file sitkImageRegistrationMethod.h.
m_pfGetOptimizerStopConditionDescription
std::function<std::string()> itk::simple::ImageRegistrationMethod::m_pfGetOptimizerStopConditionDescription private
Definition at line 811 of file sitkImageRegistrationMethod.h.
m_pfOptimizerStopRegistration
std::function<void()> itk::simple::ImageRegistrationMethod::m_pfOptimizerStopRegistration private
Definition at line 812 of file sitkImageRegistrationMethod.h.
m_pfUpdateWithBestValue
std::function<void(itk::TransformBase * outTransform)> itk::simple::ImageRegistrationMethod::m_pfUpdateWithBestValue private
Definition at line 817 of file sitkImageRegistrationMethod.h.
m_ShrinkFactorsPerLevel
std::vector<unsigned int> itk::simple::ImageRegistrationMethod::m_ShrinkFactorsPerLevel private
Definition at line 948 of file sitkImageRegistrationMethod.h.
m_SmoothingSigmasAreSpecifiedInPhysicalUnits
bool itk::simple::ImageRegistrationMethod::m_SmoothingSigmasAreSpecifiedInPhysicalUnits private
Definition at line 950 of file sitkImageRegistrationMethod.h.
m_SmoothingSigmasPerLevel
std::vector<double> itk::simple::ImageRegistrationMethod::m_SmoothingSigmasPerLevel private
Definition at line 949 of file sitkImageRegistrationMethod.h.
m_StopConditionDescription
std::string itk::simple::ImageRegistrationMethod::m_StopConditionDescription private
Definition at line 952 of file sitkImageRegistrationMethod.h.
m_TransformBSplineScaleFactors
std::vector<unsigned int> itk::simple::ImageRegistrationMethod::m_TransformBSplineScaleFactors private
Definition at line 906 of file sitkImageRegistrationMethod.h.
m_VirtualDomainDirection
std::vector<double> itk::simple::ImageRegistrationMethod::m_VirtualDomainDirection private
Definition at line 845 of file sitkImageRegistrationMethod.h.
m_VirtualDomainOrigin
std::vector<double> itk::simple::ImageRegistrationMethod::m_VirtualDomainOrigin private
Definition at line 843 of file sitkImageRegistrationMethod.h.
m_VirtualDomainSize
std::vector<uint32_t> itk::simple::ImageRegistrationMethod::m_VirtualDomainSize private
Definition at line 842 of file sitkImageRegistrationMethod.h.
m_VirtualDomainSpacing
std::vector<double> itk::simple::ImageRegistrationMethod::m_VirtualDomainSpacing private
Definition at line 844 of file sitkImageRegistrationMethod.h.
The documentation for this class was generated from the following file:
sitkImageRegistrationMethod.h