SimpleITK: itk::simple::LabelMapMaskImageFilter Class Reference
itk::simple::LabelMapMaskImageFilter Class Reference
Mask and image with a LabelMap .
#include <sitkLabelMapMaskImageFilter.h>
Detailed Description
Mask and image with a LabelMap .
LabelMapMaskImageFilter mask the content of an input image according to the content of the input LabelMap . The masked pixel of the input image are set to the BackgroundValue. LabelMapMaskImageFilter can keep the input image for one label only, with Negated = false (the default) or it can mask the input image for a single label, when Negated equals true. In Both cases, the label is set with SetLabel() .
Author
Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA de Jouy-en-Josas, France.
This implementation was taken from the Insight Journal paper: https://doi.org/10.54294/q6auw4
See also
LabelMapToBinaryImageFilter , LabelMapToLabelImageFilter
itk::simple::LabelMapMask for the procedural interface
itk::LabelMapMaskImageFilter for the Doxygen on the original ITK class.
Definition at line 55 of file sitkLabelMapMaskImageFilter.h.
Public Types
using PixelIDTypeList = LabelPixelIDTypeList
using Self = LabelMapMaskImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void CropOff ()
void CropOn ()
Image Execute (const Image &labelMapImage, const Image &featureImage)
double GetBackgroundValue () const
bool GetCrop () const
std::vector< unsigned int > GetCropBorder () const
uint64_t GetLabel () const
std::string GetName () const
bool GetNegated () const
LabelMapMaskImageFilter ()
void NegatedOff ()
void NegatedOn ()
void SetBackgroundValue (double BackgroundValue)
void SetCrop (bool Crop)
void SetCropBorder (std::vector< unsigned int > CropBorder)
void SetCropBorder (unsigned int value)
void SetLabel (uint64_t Label)
void SetNegated (bool Negated)
std::string ToString () const
virtual ~LabelMapMaskImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType1, class TImageType2>
Image DualExecuteInternal (const Image *labelMapImage, const Image *featureImage)
Private Attributes
double m_BackgroundValue { 0 }
bool m_Crop { false }
std::vector< unsigned int > m_CropBorder { std::vector<unsigned int>(3, 0) }
std::unique_ptr< detail::DualMemberFunctionFactory< MemberFunctionType > > m_DualMemberFactory
uint64_t m_Label { 1u }
bool m_Negated { false }
Friends
struct detail::DualExecuteInternalAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::LabelMapMaskImageFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    labelMapImage, const Image *
    featureImage)
Setup for member function dispatching
Definition at line 161 of file sitkLabelMapMaskImageFilter.h.
PixelIDTypeList
using itk::simple::LabelMapMaskImageFilter::PixelIDTypeList = LabelPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 67 of file sitkLabelMapMaskImageFilter.h.
Self
using itk::simple::LabelMapMaskImageFilter::Self = LabelMapMaskImageFilter
Definition at line 57 of file sitkLabelMapMaskImageFilter.h.
Constructor & Destructor Documentation
~LabelMapMaskImageFilter()
virtual itk::simple::LabelMapMaskImageFilter::~LabelMapMaskImageFilter () virtual
Destructor
LabelMapMaskImageFilter()
itk::simple::LabelMapMaskImageFilter::LabelMapMaskImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
CropOff()
void itk::simple::LabelMapMaskImageFilter::CropOff () inline
Definition at line 124 of file sitkLabelMapMaskImageFilter.h.
References SetCrop().
CropOn()
void itk::simple::LabelMapMaskImageFilter::CropOn () inline
Set the value of Crop to true or false respectfully.
Definition at line 122 of file sitkLabelMapMaskImageFilter.h.
References SetCrop().
DualExecuteInternal()
template<class TImageType1, class TImageType2> Image itk::simple::LabelMapMaskImageFilter::DualExecuteInternal (const Image * labelMapImage, const Image * featureImage) private
Execute()
Image itk::simple::LabelMapMaskImageFilter::Execute (const Image & labelMapImage, const Image & featureImage)
Execute the filter on the input image
Referenced by detail::DualExecuteInternalAddressor< MemberFunctionType >.
GetBackgroundValue()
double itk::simple::LabelMapMaskImageFilter::GetBackgroundValue () const inline
Set/Get the value used as "background" in the output image. Defaults to NumericTraits<PixelType>::ZeroValue() .
Definition at line 93 of file sitkLabelMapMaskImageFilter.h.
References m_BackgroundValue.
GetCrop()
bool itk::simple::LabelMapMaskImageFilter::GetCrop () const inline
Set/Get whether the image size should be adjusted to the masked image or not.
Definition at line 129 of file sitkLabelMapMaskImageFilter.h.
References m_Crop.
GetCropBorder()
std::vector< unsigned int > itk::simple::LabelMapMaskImageFilter::GetCropBorder () const inline
Set/Get the border added to the mask before the crop. The default is 0 on all the axes.
Definition at line 145 of file sitkLabelMapMaskImageFilter.h.
References m_CropBorder.
GetLabel()
uint64_t itk::simple::LabelMapMaskImageFilter::GetLabel () const inline
The label to mask or to not mask, depending on the value of the Negated ivar.
Definition at line 81 of file sitkLabelMapMaskImageFilter.h.
References m_Label.
GetName()
std::string itk::simple::LabelMapMaskImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 149 of file sitkLabelMapMaskImageFilter.h.
GetNegated()
bool itk::simple::LabelMapMaskImageFilter::GetNegated () const inline
Set/Get whether the Label should be masked or not.
Definition at line 111 of file sitkLabelMapMaskImageFilter.h.
References m_Negated.
NegatedOff()
void itk::simple::LabelMapMaskImageFilter::NegatedOff () inline
Definition at line 106 of file sitkLabelMapMaskImageFilter.h.
References SetNegated().
NegatedOn()
void itk::simple::LabelMapMaskImageFilter::NegatedOn () inline
Set the value of Negated to true or false respectfully.
Definition at line 104 of file sitkLabelMapMaskImageFilter.h.
References SetNegated().
SetBackgroundValue()
void itk::simple::LabelMapMaskImageFilter::SetBackgroundValue (double BackgroundValue) inline
Set/Get the value used as "background" in the output image. Defaults to NumericTraits<PixelType>::ZeroValue() .
Definition at line 87 of file sitkLabelMapMaskImageFilter.h.
References m_BackgroundValue.
SetCrop()
void itk::simple::LabelMapMaskImageFilter::SetCrop (bool Crop) inline
Set/Get whether the image size should be adjusted to the masked image or not.
Definition at line 117 of file sitkLabelMapMaskImageFilter.h.
References itk::simple::Crop(), and m_Crop.
Referenced by CropOff(), and CropOn().
SetCropBorder() [1/2]
void itk::simple::LabelMapMaskImageFilter::SetCropBorder (std::vector< unsigned int > CropBorder) inline
Set/Get the border added to the mask before the crop. The default is 0 on all the axes.
Definition at line 135 of file sitkLabelMapMaskImageFilter.h.
References m_CropBorder.
SetCropBorder() [2/2]
void itk::simple::LabelMapMaskImageFilter::SetCropBorder (unsigned int value) inline
Set the values of the CropBorder vector all to value
Definition at line 140 of file sitkLabelMapMaskImageFilter.h.
References m_CropBorder.
SetLabel()
void itk::simple::LabelMapMaskImageFilter::SetLabel (uint64_t Label) inline
The label to mask or to not mask, depending on the value of the Negated ivar.
Definition at line 75 of file sitkLabelMapMaskImageFilter.h.
References m_Label.
SetNegated()
void itk::simple::LabelMapMaskImageFilter::SetNegated (bool Negated) inline
Set/Get whether the Label should be masked or not.
Definition at line 99 of file sitkLabelMapMaskImageFilter.h.
References m_Negated.
Referenced by NegatedOff(), and NegatedOn().
ToString()
std::string itk::simple::LabelMapMaskImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::DualExecuteInternalAddressor< MemberFunctionType >
friend struct detail::DualExecuteInternalAddressor< MemberFunctionType > friend
Definition at line 156 of file sitkLabelMapMaskImageFilter.h.
References Execute().
Member Data Documentation
m_BackgroundValue
double itk::simple::LabelMapMaskImageFilter::m_BackgroundValue { 0 } private
Definition at line 177 of file sitkLabelMapMaskImageFilter.h.
Referenced by GetBackgroundValue(), and SetBackgroundValue().
m_Crop
bool itk::simple::LabelMapMaskImageFilter::m_Crop { false } private
Definition at line 181 of file sitkLabelMapMaskImageFilter.h.
Referenced by GetCrop(), and SetCrop().
m_CropBorder
std::vector<unsigned int> itk::simple::LabelMapMaskImageFilter::m_CropBorder { std::vector<unsigned int>(3, 0) } private
Definition at line 183 of file sitkLabelMapMaskImageFilter.h.
Referenced by GetCropBorder(), SetCropBorder(), and SetCropBorder().
m_DualMemberFactory
std::unique_ptr<detail::DualMemberFunctionFactory<MemberFunctionType> > itk::simple::LabelMapMaskImageFilter::m_DualMemberFactory private
Definition at line 171 of file sitkLabelMapMaskImageFilter.h.
m_Label
uint64_t itk::simple::LabelMapMaskImageFilter::m_Label { 1u } private
Definition at line 175 of file sitkLabelMapMaskImageFilter.h.
Referenced by GetLabel(), and SetLabel().
m_Negated
bool itk::simple::LabelMapMaskImageFilter::m_Negated { false } private
Definition at line 179 of file sitkLabelMapMaskImageFilter.h.
Referenced by GetNegated(), and SetNegated().
The documentation for this class was generated from the following file:
sitkLabelMapMaskImageFilter.h