SimpleITK: itk::HashImageFilter< TImageType > Class Template Reference
itk::HashImageFilter< TImageType > Class Template Reference
Generates a hash string from an image.
#include <itkHashImageFilter.h>
Detailed Description
template<class TImageType>
class itk::HashImageFilter< TImageType >
Generates a hash string from an image.
Note
This class utilizes low level buffer pointer access, to work with itk::Image and itk::VectorImage. It is modeled after the access an ImageFileWriter provides to an ImageIO.
Todo:
Update in-place on to default after fixing bug in InPlaceImageFilter
Definition at line 41 of file itkHashImageFilter.h.
Public Types
using ConstPointer = SmartPointer< const Self >
using DataObjectPointer = typename DataObject::Pointer
using DataObjectPointerArraySizeType = ProcessObject::DataObjectPointerArraySizeType
enum HashFunction {
SHA1,
MD5
}
using HashObjectType = SimpleDataObjectDecorator< std::string >
using Pointer = SmartPointer< Self >
using RegionType = typename TImageType::RegionType
using Self = HashImageFilter
using Superclass = CastImageFilter< TImageType, TImageType >
Public Types inherited from itk::CastImageFilter< TImageType, TImageType >
typedef SmartPointer< const Self > ConstPointer
typedef typename TInputImage::PixelType InputPixelType
typedef typename OutputImageType::RegionType OutputImageRegionType
typedef typename TOutputImage::PixelType OutputPixelType
typedef SmartPointer< Self > Pointer
typedef CastImageFilter Self
typedef InPlaceImageFilter< TInputImage, TOutputImage > Superclass
Public Types inherited from itk::InPlaceImageFilter< TInputImage, TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef typename InputImageType::ConstPointer InputImageConstPointer
typedef typename InputImageType::PixelType InputImagePixelType
typedef typename InputImageType::Pointer InputImagePointer
typedef typename InputImageType::RegionType InputImageRegionType
typedef TInputImage InputImageType
typedef typename OutputImageType::PixelType OutputImagePixelType
typedef typename OutputImageType::RegionType OutputImageRegionType
typedef SmartPointer< Self > Pointer
typedef InPlaceImageFilter Self
typedef ImageToImageFilter< TInputImage, TOutputImage > Superclass
Public Types inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
typedef SmartPointer< const Self > ConstPointer
typedef typename InputImageType::ConstPointer InputImageConstPointer
typedef typename InputImageType::PixelType InputImagePixelType
typedef typename InputImageType::Pointer InputImagePointer
typedef typename InputImageType::RegionType InputImageRegionType
typedef TInputImage InputImageType
typedef typename OutputImageType::PixelType OutputImagePixelType
typedef typename OutputImageType::RegionType OutputImageRegionType
typedef SmartPointer< Self > Pointer
typedef ImageToImageFilter Self
typedef ImageSource< TOutputImage > Superclass
Public Types inherited from itk::ImageSource< TOutputImage >
typedef SmartPointer< const Self > ConstPointer
typedef Superclass::DataObjectIdentifierType DataObjectIdentifierType
typedef DataObject::Pointer DataObjectPointer
typedef Superclass::DataObjectPointerArraySizeType DataObjectPointerArraySizeType
typedef typename OutputImageType::PixelType OutputImagePixelType
typedef typename OutputImageType::Pointer OutputImagePointer
typedef typename OutputImageType::RegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef SmartPointer< Self > Pointer
typedef ImageSource Self
typedef ProcessObject Superclass
Public Types inherited from itk::ProcessObject
typedef SmartPointer< const Self > ConstPointer
typedef DataObject::DataObjectIdentifierType DataObjectIdentifierType
typedef DataObject::Pointer DataObjectPointer
typedef std::vector< DataObjectPointer > DataObjectPointerArray
typedef DataObjectPointerArray::size_type DataObjectPointerArraySizeType
typedef MultiThreaderBase MultiThreaderType
typedef std::vector< DataObjectIdentifierType > NameArray
typedef SmartPointer< Self > Pointer
typedef ProcessObject Self
typedef Object Superclass
Public Types inherited from itk::Object
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef Object Self
typedef LightObject Superclass
Public Types inherited from itk::LightObject
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
std::string GetHash () const
HashObjectType * GetHashOutput ()
const HashObjectType * GetHashOutput () const
itkGetMacro (HashFunction, HashFunction)
itkNewMacro (Self)
itkSetMacro (HashFunction, HashFunction)
itkTypeMacro (HashImageFilter, CastImageFilter)
DataObjectPointer MakeOutput (DataObjectPointerArraySizeType idx) override
Public Member Functions inherited from itk::CastImageFilter< TImageType, TImageType >
virtual ::itk::LightObject::Pointer CreateAnother () const
const char * GetNameOfClass () const override
Public Member Functions inherited from itk::InPlaceImageFilter< TInputImage, TOutputImage >
virtual bool CanRunInPlace () const
virtual bool GetInPlace () const
virtual bool GetInPlace () const
const char * GetNameOfClass () const override
virtual void InPlaceOff ()
virtual void InPlaceOff ()
virtual void InPlaceOn ()
virtual void InPlaceOn ()
virtual void SetInPlace (bool _arg)
virtual void SetInPlace (bool _arg)
Public Member Functions inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
virtual double GetCoordinateTolerance () const
virtual double GetCoordinateTolerance () const
virtual double GetDirectionTolerance () const
virtual double GetDirectionTolerance () const
const InputImageType * GetInput () const
const InputImageType * GetInput (unsigned int idx) const
const char * GetNameOfClass () const override
void PopBackInput () override
void PopFrontInput () override
virtual void PushBackInput (const InputImageType *input)
virtual void PushFrontInput (const InputImageType *input)
virtual void SetCoordinateTolerance (double _arg)
virtual void SetCoordinateTolerance (double _arg)
virtual void SetDirectionTolerance (double _arg)
virtual void SetDirectionTolerance (double _arg)
virtual void SetInput (const InputImageType *input)
virtual void SetInput (unsigned int, const TInputImage *image)
Public Member Functions inherited from itk::ImageSource< TOutputImage >
const char * GetNameOfClass () const override
OutputImageType * GetOutput ()
OutputImageType * GetOutput ()
const OutputImageType * GetOutput () const
const OutputImageType * GetOutput () const
OutputImageType * GetOutput (unsigned int idx)
virtual void GraftNthOutput (unsigned int idx, DataObject *graft)
virtual void GraftNthOutput (unsigned int idx, DataObject *graft)
virtual void GraftOutput (const DataObjectIdentifierType &key, DataObject *graft)
virtual void GraftOutput (const DataObjectIdentifierType &key, DataObject *graft)
virtual void GraftOutput (DataObject *graft)
virtual void GraftOutput (DataObject *graft)
ProcessObject::DataObjectPointer MakeOutput (const ProcessObject::DataObjectIdentifierType &) override
ProcessObject::DataObjectPointer MakeOutput (const ProcessObject::DataObjectIdentifierType &) override
ProcessObject::DataObjectPointer MakeOutput (ProcessObject::DataObjectPointerArraySizeType idx) override
ProcessObject::DataObjectPointer MakeOutput (ProcessObject::DataObjectPointerArraySizeType idx) override
Public Member Functions inherited from itk::ProcessObject
virtual void AbortGenerateDataOff ()
virtual void AbortGenerateDataOn ()
virtual const bool & GetAbortGenerateData () const
DataObjectPointerArray GetIndexedInputs ()
DataObjectPointerArray GetIndexedOutputs ()
NameArray GetInputNames () const
DataObjectPointerArray GetInputs ()
MultiThreaderType * GetMultiThreader () const
const char * GetNameOfClass () const override
DataObjectPointerArraySizeType GetNumberOfIndexedInputs () const
DataObjectPointerArraySizeType GetNumberOfIndexedOutputs () const
DataObjectPointerArraySizeType GetNumberOfInputs () const
DataObjectPointerArraySizeType GetNumberOfOutputs () const
virtual DataObjectPointerArraySizeType GetNumberOfValidRequiredInputs () const
virtual const ThreadIdType & GetNumberOfWorkUnits () const
virtual const ThreadIdType & GetNumberOfWorkUnits () const
NameArray GetOutputNames () const
DataObjectPointerArray GetOutputs ()
virtual float GetProgress () const
virtual const bool & GetReleaseDataBeforeUpdateFlag () const
virtual const bool & GetReleaseDataBeforeUpdateFlag () const
virtual bool GetReleaseDataFlag () const
virtual bool GetReleaseDataFlag () const
NameArray GetRequiredInputNames () const
bool HasInput (const DataObjectIdentifierType &key) const
bool HasOutput (const DataObjectIdentifierType &key) const
void IncrementProgress (float increment)
virtual void PrepareOutputs ()
virtual void PropagateRequestedRegion (DataObject *output)
virtual void ReleaseDataBeforeUpdateFlagOff ()
virtual void ReleaseDataBeforeUpdateFlagOff ()
virtual void ReleaseDataBeforeUpdateFlagOn ()
virtual void ReleaseDataBeforeUpdateFlagOn ()
void ReleaseDataFlagOff ()
void ReleaseDataFlagOff ()
void ReleaseDataFlagOn ()
void ReleaseDataFlagOn ()
virtual void ResetPipeline ()
virtual void SetAbortGenerateData (bool _arg)
void SetMultiThreader (MultiThreaderType *threader)
virtual void SetNumberOfWorkUnits (ThreadIdType _arg)
virtual void SetNumberOfWorkUnits (ThreadIdType _arg)
virtual void SetReleaseDataBeforeUpdateFlag (bool _arg)
virtual void SetReleaseDataBeforeUpdateFlag (bool _arg)
virtual void SetReleaseDataFlag (bool val)
virtual void SetReleaseDataFlag (bool val)
virtual void Update ()
virtual void UpdateLargestPossibleRegion ()
virtual void UpdateOutputData (DataObject *output)
virtual void UpdateOutputInformation ()
void UpdateProgress (float progress)
Public Member Functions inherited from itk::Object
unsigned long AddObserver (const EventObject &event, Command *cmd) const
unsigned long AddObserver (const EventObject &event, std::function< void(const EventObject &)> function) const
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
Command * GetCommand (unsigned long tag)
bool GetDebug () const
MetaDataDictionary & GetMetaDataDictionary ()
const MetaDataDictionary & GetMetaDataDictionary () const
virtual ModifiedTimeType GetMTime () const
virtual const std::string & GetObjectName () const
virtual const std::string & GetObjectName () const
virtual const TimeStamp & GetTimeStamp () const
bool HasObserver (const EventObject &event) const
void InvokeEvent (const EventObject &)
void InvokeEvent (const EventObject &) const
virtual void Modified () const
void Register () const override
void RemoveAllObservers ()
void RemoveObserver (unsigned long tag) const
void SetDebug (bool debugFlag) const
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (const MetaDataDictionary &rhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
void SetMetaDataDictionary (MetaDataDictionary &&rrhs)
virtual void SetObjectName (std::string _arg)
virtual void SetObjectName (std::string _arg)
void SetReferenceCount (int) override
void UnRegister () const noexcept override
Public Member Functions inherited from itk::LightObject
Pointer Clone () const
virtual void Delete ()
virtual int GetReferenceCount () const
void Print (std::ostream &os, Indent indent=0) const
Protected Member Functions
void AfterThreadedGenerateData () override
void EnlargeOutputRequestedRegion (DataObject *data) override
HashImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const override
Protected Member Functions inherited from itk::CastImageFilter< TImageType, TImageType >
CastImageFilter ()
void DynamicThreadedGenerateData (const OutputImageRegionType &outputRegionForThread) override
void DynamicThreadedGenerateDataDispatched (const OutputImageRegionType &outputRegionForThread)
void DynamicThreadedGenerateDataDispatched (const OutputImageRegionType &outputRegionForThread)
void GenerateData () override
void GenerateOutputInformation () override
~CastImageFilter () override=default
Protected Member Functions inherited from itk::InPlaceImageFilter< TInputImage, TOutputImage >
void AllocateOutputs () override
void AllocateOutputs () override
virtual bool GetRunningInPlace () const
InPlaceImageFilter ()=default
void PrintSelf (std::ostream &os, Indent indent) const override
void ReleaseInputs () override
~InPlaceImageFilter () override=default
Protected Member Functions inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
virtual void CallCopyInputRegionToOutputRegion (OutputImageRegionType &destRegion, const InputImageRegionType &srcRegion)
virtual void CallCopyOutputRegionToInputRegion (InputImageRegionType &destRegion, const OutputImageRegionType &srcRegion)
void GenerateInputRequestedRegion () override
ImageToImageFilter ()
void VerifyInputInformation () const override
~ImageToImageFilter () override=default
Protected Member Functions inherited from itk::ImageSource< TOutputImage >
virtual void BeforeThreadedGenerateData ()
void ClassicMultiThread (ThreadFunctionType callbackFunction)
virtual void DynamicMultiThreadingOff ()
virtual void DynamicMultiThreadingOff ()
virtual void DynamicMultiThreadingOn ()
virtual void DynamicMultiThreadingOn ()
void GenerateData () override
virtual bool GetDynamicMultiThreading () const
virtual bool GetDynamicMultiThreading () const
virtual const ImageRegionSplitterBase * GetImageRegionSplitter () const
ImageSource ()
virtual void SetDynamicMultiThreading (bool _arg)
virtual void SetDynamicMultiThreading (bool _arg)
virtual unsigned int SplitRequestedRegion (unsigned int i, unsigned int pieces, OutputImageRegionType &splitRegion)
virtual void ThreadedGenerateData (const OutputImageRegionType &region, ThreadIdType threadId)
virtual void ThreadedGenerateData (const OutputImageRegionType &region, ThreadIdType threadId)
~ImageSource () override=default
Protected Member Functions inherited from itk::ProcessObject
virtual void AddInput (DataObject *input)
void AddOptionalInputName (const DataObjectIdentifierType &)
void AddOptionalInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void AddOutput (DataObject *output)
bool AddRequiredInputName (const DataObjectIdentifierType &)
bool AddRequiredInputName (const DataObjectIdentifierType &, DataObjectPointerArraySizeType idx)
virtual void CacheInputReleaseDataFlags ()
virtual void GenerateOutputRequestedRegion (DataObject *output)
DataObject * GetInput (const DataObjectIdentifierType &key)
const DataObject * GetInput (const DataObjectIdentifierType &key) const
DataObject * GetInput (DataObjectPointerArraySizeType idx)
DataObject * GetInput (DataObjectPointerArraySizeType idx)
const DataObject * GetInput (DataObjectPointerArraySizeType idx) const
const DataObject * GetInput (DataObjectPointerArraySizeType idx) const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredInputs () const
virtual const DataObjectPointerArraySizeType & GetNumberOfRequiredOutputs () const
DataObject * GetOutput (const DataObjectIdentifierType &key)
DataObject * GetOutput (const DataObjectIdentifierType &key)
const DataObject * GetOutput (const DataObjectIdentifierType &key) const
const DataObject * GetOutput (const DataObjectIdentifierType &key) const
DataObject * GetOutput (DataObjectPointerArraySizeType i)
DataObject * GetOutput (DataObjectPointerArraySizeType i)
const DataObject * GetOutput (DataObjectPointerArraySizeType i) const
const DataObject * GetOutput (DataObjectPointerArraySizeType i) const
DataObject * GetPrimaryInput ()
DataObject * GetPrimaryInput ()
const DataObject * GetPrimaryInput () const
const DataObject * GetPrimaryInput () const
virtual const char * GetPrimaryInputName () const
virtual const char * GetPrimaryInputName () const
DataObject * GetPrimaryOutput ()
DataObject * GetPrimaryOutput ()
const DataObject * GetPrimaryOutput () const
const DataObject * GetPrimaryOutput () const
virtual const char * GetPrimaryOutputName () const
virtual const char * GetPrimaryOutputName () const
virtual bool GetThreaderUpdateProgress () const
virtual bool GetThreaderUpdateProgress () const
bool IsIndexedInputName (const DataObjectIdentifierType &) const
bool IsIndexedOutputName (const DataObjectIdentifierType &) const
bool IsRequiredInputName (const DataObjectIdentifierType &) const
DataObjectPointerArraySizeType MakeIndexFromInputName (const DataObjectIdentifierType &name) const
DataObjectPointerArraySizeType MakeIndexFromOutputName (const DataObjectIdentifierType &name) const
DataObjectIdentifierType MakeNameFromInputIndex (DataObjectPointerArraySizeType idx) const
DataObjectIdentifierType MakeNameFromOutputIndex (DataObjectPointerArraySizeType idx) const
ProcessObject ()
virtual void PropagateResetPipeline ()
virtual void PushBackInput (const DataObject *input)
virtual void PushFrontInput (const DataObject *input)
virtual void RemoveInput (const DataObjectIdentifierType &key)
virtual void RemoveInput (DataObjectPointerArraySizeType)
virtual void RemoveOutput (const DataObjectIdentifierType &key)
virtual void RemoveOutput (DataObjectPointerArraySizeType idx)
bool RemoveRequiredInputName (const DataObjectIdentifierType &)
virtual void RestoreInputReleaseDataFlags ()
virtual void SetInput (const DataObjectIdentifierType &key, DataObject *input)
virtual void SetNthInput (DataObjectPointerArraySizeType idx, DataObject *input)
virtual void SetNthOutput (DataObjectPointerArraySizeType idx, DataObject *output)
void SetNumberOfIndexedInputs (DataObjectPointerArraySizeType num)
void SetNumberOfIndexedOutputs (DataObjectPointerArraySizeType num)
virtual void SetNumberOfRequiredInputs (DataObjectPointerArraySizeType)
virtual void SetNumberOfRequiredOutputs (DataObjectPointerArraySizeType _arg)
virtual void SetOutput (const DataObjectIdentifierType &name, DataObject *output)
virtual void SetPrimaryInput (DataObject *object)
virtual void SetPrimaryInputName (const DataObjectIdentifierType &key)
virtual void SetPrimaryInputName (const DataObjectIdentifierType &key)
virtual void SetPrimaryOutput (DataObject *object)
virtual void SetPrimaryOutputName (const DataObjectIdentifierType &key)
virtual void SetPrimaryOutputName (const DataObjectIdentifierType &key)
void SetRequiredInputNames (const NameArray &)
virtual void SetThreaderUpdateProgress (bool arg)
virtual void SetThreaderUpdateProgress (bool arg)
virtual void ThreaderUpdateProgressOff ()
virtual void ThreaderUpdateProgressOff ()
virtual void ThreaderUpdateProgressOn ()
virtual void ThreaderUpdateProgressOn ()
virtual void VerifyInputInformation () const
virtual void VerifyPreconditions () const
~ProcessObject () override
Protected Member Functions inherited from itk::Object
Object ()
bool PrintObservers (std::ostream &os, Indent indent) const
virtual void SetTimeStamp (const TimeStamp &timeStamp)
~Object () override
Protected Member Functions inherited from itk::LightObject
virtual LightObject::Pointer InternalClone () const
LightObject ()
virtual void PrintHeader (std::ostream &os, Indent indent) const
virtual void PrintTrailer (std::ostream &os, Indent indent) const
virtual ~LightObject ()
Private Member Functions
HashImageFilter (const Self &)
void operator= (const Self &)
Private Attributes
HashFunction m_HashFunction
Additional Inherited Members
Static Public Member Functions inherited from itk::CastImageFilter< TImageType, TImageType >
static Pointer New ()
Static Public Member Functions inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
static double GetGlobalDefaultCoordinateTolerance ()
static double GetGlobalDefaultDirectionTolerance ()
static void SetGlobalDefaultCoordinateTolerance (double)
static void SetGlobalDefaultDirectionTolerance (double)
Static Public Member Functions inherited from itk::Object
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool val)
Static Public Member Functions inherited from itk::LightObject
static void BreakOnError ()
static Pointer New ()
Static Public Attributes inherited from itk::InPlaceImageFilter< TInputImage, TOutputImage >
static constexpr unsigned int InputImageDimension
static constexpr unsigned int OutputImageDimension
Static Public Attributes inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
static constexpr unsigned int InputImageDimension
static constexpr unsigned int OutputImageDimension
Static Public Attributes inherited from itk::ImageSource< TOutputImage >
static constexpr unsigned int OutputImageDimension
Protected Types inherited from itk::ImageToImageFilter< TInputImage, TInputImage >
typedef ImageToImageFilterDetail::ImageRegionCopier< Self::OutputImageDimension, Self::InputImageDimension > InputToOutputRegionCopierType
typedef ImageToImageFilterDetail::ImageRegionCopier< Self::InputImageDimension, Self::OutputImageDimension > OutputToInputRegionCopierType
Static Protected Member Functions inherited from itk::ImageSource< TOutputImage >
static const ImageRegionSplitterBase * GetGlobalDefaultSplitter ()
static ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION ThreaderCallback (void *arg)
Static Protected Member Functions inherited from itk::ProcessObject
static void MakeRequiredOutputs (TSourceObject &sourceObject, const DataObjectPointerArraySizeType numberOfRequiredOutputs)
static constexpr float progressFixedToFloat (uint32_t fixed)
static uint32_t progressFloatToFixed (float f)
static uint32_t progressFloatToFixed (float f)
Protected Attributes inherited from itk::ImageSource< TOutputImage >
bool m_DynamicMultiThreading
Protected Attributes inherited from itk::ProcessObject
TimeStamp m_OutputInformationMTime
bool m_Updating
Protected Attributes inherited from itk::LightObject
std::atomic< int > m_ReferenceCount
Member Typedef Documentation
ConstPointer
template<class TImageType > using itk::HashImageFilter< TImageType >::ConstPointer = SmartPointer<const Self>
Definition at line 48 of file itkHashImageFilter.h.
DataObjectPointer
template<class TImageType > using itk::HashImageFilter< TImageType >::DataObjectPointer = typename DataObject::Pointer
Smart Pointer type to a DataObject.
Definition at line 59 of file itkHashImageFilter.h.
DataObjectPointerArraySizeType
template<class TImageType > using itk::HashImageFilter< TImageType >::DataObjectPointerArraySizeType = ProcessObject::DataObjectPointerArraySizeType
Make a DataObject of the correct type to be used as the specified output.
Definition at line 93 of file itkHashImageFilter.h.
HashObjectType
template<class TImageType > using itk::HashImageFilter< TImageType >::HashObjectType = SimpleDataObjectDecorator<std::string>
Type of DataObjects used for scalar outputs
Definition at line 62 of file itkHashImageFilter.h.
Pointer
template<class TImageType > using itk::HashImageFilter< TImageType >::Pointer = SmartPointer<Self>
Definition at line 47 of file itkHashImageFilter.h.
RegionType
template<class TImageType > using itk::HashImageFilter< TImageType >::RegionType = typename TImageType::RegionType
Definition at line 50 of file itkHashImageFilter.h.
Self
template<class TImageType > using itk::HashImageFilter< TImageType >::Self = HashImageFilter
Standard Self type alias
Definition at line 45 of file itkHashImageFilter.h.
Superclass
template<class TImageType > using itk::HashImageFilter< TImageType >::Superclass = CastImageFilter<TImageType, TImageType>
Definition at line 46 of file itkHashImageFilter.h.
Member Enumeration Documentation
HashFunction
template<class TImageType > enum itk::HashImageFilter::HashFunction
Enumerator
SHA1
MD5
Definition at line 81 of file itkHashImageFilter.h.
Constructor & Destructor Documentation
HashImageFilter() [1/2]
template<class TImageType > itk::HashImageFilter< TImageType >::HashImageFilter () protected
HashImageFilter() [2/2]
template<class TImageType > itk::HashImageFilter< TImageType >::HashImageFilter (const Self &) private
Member Function Documentation
AfterThreadedGenerateData()
template<class TImageType > void itk::HashImageFilter< TImageType >::AfterThreadedGenerateData () override protected virtual
Reimplemented from itk::ImageSource< TOutputImage >.
EnlargeOutputRequestedRegion()
template<class TImageType > void itk::HashImageFilter< TImageType >::EnlargeOutputRequestedRegion (DataObject * data) override protected virtual
Reimplemented from itk::ProcessObject.
GetHash()
template<class TImageType > std::string itk::HashImageFilter< TImageType >::GetHash () const inline
Get the computed Hash values
Definition at line 66 of file itkHashImageFilter.h.
References itk::SimpleDataObjectDecorator< typename T >::Get(), and itk::HashImageFilter< TImageType >::GetHashOutput().
GetHashOutput() [1/2]
template<class TImageType > HashObjectType* itk::HashImageFilter< TImageType >::GetHashOutput () inline
Definition at line 71 of file itkHashImageFilter.h.
References itk::ProcessObject::GetOutput().
Referenced by itk::HashImageFilter< TImageType >::GetHash().
GetHashOutput() [2/2]
template<class TImageType > const HashObjectType* itk::HashImageFilter< TImageType >::GetHashOutput () const inline
Definition at line 76 of file itkHashImageFilter.h.
References itk::ProcessObject::GetOutput().
itkGetMacro()
template<class TImageType > itk::HashImageFilter< TImageType >::itkGetMacro (HashFunction , HashFunction)
itkNewMacro()
template<class TImageType > itk::HashImageFilter< TImageType >::itkNewMacro (Self)
Method for creation through the object factory.
itkSetMacro()
template<class TImageType > itk::HashImageFilter< TImageType >::itkSetMacro (HashFunction , HashFunction)
Set/Get hashing function as enumerated type
itkTypeMacro()
template<class TImageType > itk::HashImageFilter< TImageType >::itkTypeMacro (HashImageFilter< TImageType > , CastImageFilter)
Runtime information support.
MakeOutput()
template<class TImageType > DataObjectPointer itk::HashImageFilter< TImageType >::MakeOutput (DataObjectPointerArraySizeType idx) override virtual
Reimplemented from itk::ProcessObject.
operator=()
template<class TImageType > void itk::HashImageFilter< TImageType >::operator= (const Self &) private
PrintSelf()
template<class TImageType > void itk::HashImageFilter< TImageType >::PrintSelf (std::ostream & os, Indent indent) const override protected virtual
Reimplemented from itk::ProcessObject.
Member Data Documentation
m_HashFunction
template<class TImageType > HashFunction itk::HashImageFilter< TImageType >::m_HashFunction private
Definition at line 125 of file itkHashImageFilter.h.
The documentation for this class was generated from the following file:
itkHashImageFilter.h