SimpleITK: itk::simple::DanielssonDistanceMapImageFilter Class Reference
itk::simple::DanielssonDistanceMapImageFilter Class Reference
This filter computes the distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
#include <sitkDanielssonDistanceMapImageFilter.h>
Detailed Description
This filter computes the distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
TInputImage
Input Image Type
TOutputImage
Output Image Type
TVoronoiImage
Voronoi Image Type. Note the default value is TInputImage.
The input is assumed to contain numeric codes defining objects. The filter will produce as output the following images:
A Voronoi partition using the same numeric codes as the input.
A distance map with the approximation to the euclidean distance. from a particular pixel to the nearest object to this pixel in the input image.
A vector map containing the component of the vector relating the current pixel with the closest point of the closest object to this pixel. Given that the components of the distance are computed in "pixels", the vector is represented by an itk::Offset . That is, physical coordinates are not used.
This filter is N-dimensional and known to be efficient in computational time. The algorithm is the N-dimensional version of the 4SED algorithm given for two dimensions in:
Danielsson, Per-Erik. Euclidean Distance Mapping. Computer Graphics and Image Processing 14, 227-248 (1980).
See also
itk::simple::DanielssonDistanceMap for the procedural interface
itk::DanielssonDistanceMapImageFilter for the Doxygen on the original ITK class.
Definition at line 84 of file sitkDanielssonDistanceMapImageFilter.h.
Public Types
using PixelIDTypeList = IntegerPixelIDTypeList
using Self = DanielssonDistanceMapImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
DanielssonDistanceMapImageFilter ()
Image Execute (const Image &image1)
bool GetInputIsBinary () const
std::string GetName () const
bool GetSquaredDistance () const
bool GetUseImageSpacing () const
Image GetVectorDistanceMap () const
Image GetVoronoiMap () const
void InputIsBinaryOff ()
void InputIsBinaryOn ()
void SetInputIsBinary (bool InputIsBinary)
void SetSquaredDistance (bool SquaredDistance)
void SetUseImageSpacing (bool UseImageSpacing)
void SquaredDistanceOff ()
void SquaredDistanceOn ()
std::string ToString () const
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~DanielssonDistanceMapImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_InputIsBinary { false }
bool m_SquaredDistance { false }
bool m_UseImageSpacing { false }
Image m_VectorDistanceMap { Image() }
Image m_VoronoiMap { Image() }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::DanielssonDistanceMapImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 191 of file sitkDanielssonDistanceMapImageFilter.h.
PixelIDTypeList
using itk::simple::DanielssonDistanceMapImageFilter::PixelIDTypeList = IntegerPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 96 of file sitkDanielssonDistanceMapImageFilter.h.
Self
using itk::simple::DanielssonDistanceMapImageFilter::Self = DanielssonDistanceMapImageFilter
Definition at line 86 of file sitkDanielssonDistanceMapImageFilter.h.
Constructor & Destructor Documentation
~DanielssonDistanceMapImageFilter()
virtual itk::simple::DanielssonDistanceMapImageFilter::~DanielssonDistanceMapImageFilter () virtual
Destructor
DanielssonDistanceMapImageFilter()
itk::simple::DanielssonDistanceMapImageFilter::DanielssonDistanceMapImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::DanielssonDistanceMapImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::DanielssonDistanceMapImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetInputIsBinary()
bool itk::simple::DanielssonDistanceMapImageFilter::GetInputIsBinary () const inline
Set/Get if the input is binary. If this variable is set, each nonzero pixel in the input image will be given a unique numeric code to be used by the Voronoi partition. If the image is binary but you are not interested in the Voronoi regions of the different nonzero pixels, then you need not set this.
Definition at line 121 of file sitkDanielssonDistanceMapImageFilter.h.
References m_InputIsBinary.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::DanielssonDistanceMapImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::DanielssonDistanceMapImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 179 of file sitkDanielssonDistanceMapImageFilter.h.
GetSquaredDistance()
bool itk::simple::DanielssonDistanceMapImageFilter::GetSquaredDistance () const inline
Set/Get if the distance should be squared.
Definition at line 140 of file sitkDanielssonDistanceMapImageFilter.h.
References m_SquaredDistance.
GetUseImageSpacing()
bool itk::simple::DanielssonDistanceMapImageFilter::GetUseImageSpacing () const inline
Set/Get if image spacing should be used in computing distances.
Definition at line 159 of file sitkDanielssonDistanceMapImageFilter.h.
References m_UseImageSpacing.
GetVectorDistanceMap()
Image itk::simple::DanielssonDistanceMapImageFilter::GetVectorDistanceMap () const inline
Get vector field of distances.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 176 of file sitkDanielssonDistanceMapImageFilter.h.
References m_VectorDistanceMap.
GetVoronoiMap()
Image itk::simple::DanielssonDistanceMapImageFilter::GetVoronoiMap () const inline
Get Voronoi Map This map shows for each pixel what object is closest to it. Each object should be labeled by a number (larger than 0), so the map has a value for each pixel corresponding to the label of the closest object.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 168 of file sitkDanielssonDistanceMapImageFilter.h.
References m_VoronoiMap.
InputIsBinaryOff()
void itk::simple::DanielssonDistanceMapImageFilter::InputIsBinaryOff () inline
Definition at line 114 of file sitkDanielssonDistanceMapImageFilter.h.
References SetInputIsBinary().
InputIsBinaryOn()
void itk::simple::DanielssonDistanceMapImageFilter::InputIsBinaryOn () inline
Set the value of InputIsBinary to true or false respectfully.
Definition at line 112 of file sitkDanielssonDistanceMapImageFilter.h.
References SetInputIsBinary().
SetInputIsBinary()
void itk::simple::DanielssonDistanceMapImageFilter::SetInputIsBinary (bool InputIsBinary) inline
Set/Get if the input is binary. If this variable is set, each nonzero pixel in the input image will be given a unique numeric code to be used by the Voronoi partition. If the image is binary but you are not interested in the Voronoi regions of the different nonzero pixels, then you need not set this.
Definition at line 107 of file sitkDanielssonDistanceMapImageFilter.h.
References m_InputIsBinary.
Referenced by InputIsBinaryOff(), and InputIsBinaryOn().
SetSquaredDistance()
void itk::simple::DanielssonDistanceMapImageFilter::SetSquaredDistance (bool SquaredDistance) inline
Set/Get if the distance should be squared.
Definition at line 128 of file sitkDanielssonDistanceMapImageFilter.h.
References m_SquaredDistance.
Referenced by SquaredDistanceOff(), and SquaredDistanceOn().
SetUseImageSpacing()
void itk::simple::DanielssonDistanceMapImageFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Set/Get if image spacing should be used in computing distances.
Definition at line 147 of file sitkDanielssonDistanceMapImageFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
SquaredDistanceOff()
void itk::simple::DanielssonDistanceMapImageFilter::SquaredDistanceOff () inline
Definition at line 135 of file sitkDanielssonDistanceMapImageFilter.h.
References SetSquaredDistance().
SquaredDistanceOn()
void itk::simple::DanielssonDistanceMapImageFilter::SquaredDistanceOn () inline
Set the value of SquaredDistance to true or false respectfully.
Definition at line 133 of file sitkDanielssonDistanceMapImageFilter.h.
References SetSquaredDistance().
ToString()
std::string itk::simple::DanielssonDistanceMapImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseImageSpacingOff()
void itk::simple::DanielssonDistanceMapImageFilter::UseImageSpacingOff () inline
Definition at line 154 of file sitkDanielssonDistanceMapImageFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::DanielssonDistanceMapImageFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 152 of file sitkDanielssonDistanceMapImageFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 192 of file sitkDanielssonDistanceMapImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_InputIsBinary
bool itk::simple::DanielssonDistanceMapImageFilter::m_InputIsBinary { false } private
Definition at line 197 of file sitkDanielssonDistanceMapImageFilter.h.
Referenced by GetInputIsBinary(), and SetInputIsBinary().
m_SquaredDistance
bool itk::simple::DanielssonDistanceMapImageFilter::m_SquaredDistance { false } private
Definition at line 199 of file sitkDanielssonDistanceMapImageFilter.h.
Referenced by GetSquaredDistance(), and SetSquaredDistance().
m_UseImageSpacing
bool itk::simple::DanielssonDistanceMapImageFilter::m_UseImageSpacing { false } private
Definition at line 201 of file sitkDanielssonDistanceMapImageFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
m_VectorDistanceMap
Image itk::simple::DanielssonDistanceMapImageFilter::m_VectorDistanceMap { Image() } private
Definition at line 206 of file sitkDanielssonDistanceMapImageFilter.h.
Referenced by GetVectorDistanceMap().
m_VoronoiMap
Image itk::simple::DanielssonDistanceMapImageFilter::m_VoronoiMap { Image() } private
Definition at line 205 of file sitkDanielssonDistanceMapImageFilter.h.
Referenced by GetVoronoiMap().
The documentation for this class was generated from the following file:
sitkDanielssonDistanceMapImageFilter.h