SimpleITK: itk::simple::FastMarchingBaseImageFilter Class Reference
itk::simple::FastMarchingBaseImageFilter Class Reference
Apply the Fast Marching method to solve an Eikonal equation on an image.
#include <sitkFastMarchingBaseImageFilter.h>
Detailed Description
Apply the Fast Marching method to solve an Eikonal equation on an image.
The speed function can be specified as a speed image or a speed constant. The speed image is set using the method SetInput(). If the speed image is nullptr, a constant speed function is used and is specified using method the SetSpeedConstant() .
If the speed function is constant and of value one, fast marching results is an approximate distance function from the initial alive points.
There are two ways to specify the output image information (LargestPossibleRegion, Spacing, Origin):
it is copied directly from the input speed image
it is specified by the user. Default values are used if the user does not specify all the information.
The output information is computed as follows.
If the speed image is nullptr or if the OverrideOutputInformation is set to true, the output information is set from user specified parameters. These parameters can be specified using methods
FastMarchingImageFilterBase::SetOutputRegion() ,
FastMarchingImageFilterBase::SetOutputSpacing() ,
FastMarchingImageFilterBase::SetOutputDirection() ,
FastMarchingImageFilterBase::SetOutputOrigin() .
Else the output information is copied from the input speed image.
Implementation of this class is based on Chapter 8 of "Level Set Methods and Fast Marching Methods", J.A. Sethian, Cambridge Press, Second edition, 1999.
For an alternative implementation, see itk::FastMarchingImageFilter .
TTraits
traits
See also
FastMarchingImageFilter
ImageFastMarchingTraits
ImageFastMarchingTraits2
itk::simple::FastMarchingBase for the procedural interface
itk::FastMarchingImageFilterBase for the Doxygen on the original ITK class.
Definition at line 98 of file sitkFastMarchingBaseImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = FastMarchingBaseImageFilter
enum TopologyCheckType {
Nothing ,
NoHandles ,
Strict
}
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void AddTrialPoint (std::vector< unsigned int > point)
Add TrialPoints point.
void ClearTrialPoints ()
Remove all TrialPoints points.
Image Execute (const Image &image1)
FastMarchingBaseImageFilter ()
std::vector< double > GetInitialTrialValues () const
std::string GetName () const
double GetNormalizationFactor () const
double GetStoppingValue () const
TopologyCheckType GetTopologyCheck () const
std::vector< std::vector< unsigned int > > GetTrialPoints () const
void SetInitialTrialValues (std::vector< double > InitialTrialValues)
Set the initial seed values for corresponding trial point.
void SetNormalizationFactor (double NormalizationFactor)
void SetStoppingValue (double StoppingValue)
void SetTopologyCheck (TopologyCheckType TopologyCheck)
void SetTrialPoints (std::vector< std::vector< unsigned int > > TrialPoints)
std::string ToString () const
virtual ~FastMarchingBaseImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
std::vector< double > m_InitialTrialValues { std::vector<double>() }
double m_NormalizationFactor { 1.0 }
double m_StoppingValue { std::numeric_limits<float>::max()/2.0 }
TopologyCheckType m_TopologyCheck { itk::simple::FastMarchingBaseImageFilter::Nothing }
std::vector< std::vector< unsigned int > > m_TrialPoints { std::vector< std::vector<unsigned int > >() }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::FastMarchingBaseImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 201 of file sitkFastMarchingBaseImageFilter.h.
PixelIDTypeList
using itk::simple::FastMarchingBaseImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 110 of file sitkFastMarchingBaseImageFilter.h.
Self
using itk::simple::FastMarchingBaseImageFilter::Self = FastMarchingBaseImageFilter
Definition at line 100 of file sitkFastMarchingBaseImageFilter.h.
Member Enumeration Documentation
TopologyCheckType
enum itk::simple::FastMarchingBaseImageFilter::TopologyCheckType
Enumerator
Nothing
NoHandles
Strict
Definition at line 163 of file sitkFastMarchingBaseImageFilter.h.
Constructor & Destructor Documentation
~FastMarchingBaseImageFilter()
virtual itk::simple::FastMarchingBaseImageFilter::~FastMarchingBaseImageFilter () virtual
Destructor
FastMarchingBaseImageFilter()
itk::simple::FastMarchingBaseImageFilter::FastMarchingBaseImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
AddTrialPoint()
void itk::simple::FastMarchingBaseImageFilter::AddTrialPoint (std::vector< unsigned int > point) inline
Add TrialPoints point.
Definition at line 129 of file sitkFastMarchingBaseImageFilter.h.
References m_TrialPoints.
ClearTrialPoints()
void itk::simple::FastMarchingBaseImageFilter::ClearTrialPoints () inline
Remove all TrialPoints points.
Definition at line 132 of file sitkFastMarchingBaseImageFilter.h.
References m_TrialPoints.
Execute()
Image itk::simple::FastMarchingBaseImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::FastMarchingBaseImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetInitialTrialValues()
std::vector< double > itk::simple::FastMarchingBaseImageFilter::GetInitialTrialValues () const inline
Definition at line 185 of file sitkFastMarchingBaseImageFilter.h.
References m_InitialTrialValues.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::FastMarchingBaseImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::FastMarchingBaseImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 189 of file sitkFastMarchingBaseImageFilter.h.
GetNormalizationFactor()
double itk::simple::FastMarchingBaseImageFilter::GetNormalizationFactor () const inline
Set/Get the Normalization Factor for the Speed Image . The values in the Speed Image is divided by this factor. This allows the use of images with integer pixel types to represent the speed.
Definition at line 147 of file sitkFastMarchingBaseImageFilter.h.
References m_NormalizationFactor.
GetStoppingValue()
double itk::simple::FastMarchingBaseImageFilter::GetStoppingValue () const inline
Get the Fast Marching algorithm Stopping Value.
Definition at line 161 of file sitkFastMarchingBaseImageFilter.h.
References m_StoppingValue.
GetTopologyCheck()
TopologyCheckType itk::simple::FastMarchingBaseImageFilter::GetTopologyCheck () const inline
Definition at line 173 of file sitkFastMarchingBaseImageFilter.h.
References m_TopologyCheck.
GetTrialPoints()
std::vector< std::vector< unsigned int > > itk::simple::FastMarchingBaseImageFilter::GetTrialPoints () const inline
Get the container of Trial Points representing the initial front.
Definition at line 126 of file sitkFastMarchingBaseImageFilter.h.
References m_TrialPoints.
SetInitialTrialValues()
void itk::simple::FastMarchingBaseImageFilter::SetInitialTrialValues (std::vector< double > InitialTrialValues) inline
Set the initial seed values for corresponding trial point.
Definition at line 180 of file sitkFastMarchingBaseImageFilter.h.
References m_InitialTrialValues.
SetNormalizationFactor()
void itk::simple::FastMarchingBaseImageFilter::SetNormalizationFactor (double NormalizationFactor) inline
Set/Get the Normalization Factor for the Speed Image . The values in the Speed Image is divided by this factor. This allows the use of images with integer pixel types to represent the speed.
Definition at line 140 of file sitkFastMarchingBaseImageFilter.h.
References m_NormalizationFactor.
SetStoppingValue()
void itk::simple::FastMarchingBaseImageFilter::SetStoppingValue (double StoppingValue) inline
Set the Fast Marching algorithm Stopping Value. The Fast Marching algorithm is terminated when the value of the smallest trial point is greater than the stopping value.
Definition at line 155 of file sitkFastMarchingBaseImageFilter.h.
References m_StoppingValue.
SetTopologyCheck()
void itk::simple::FastMarchingBaseImageFilter::SetTopologyCheck (TopologyCheckType TopologyCheck) inline
Definition at line 168 of file sitkFastMarchingBaseImageFilter.h.
References m_TopologyCheck.
SetTrialPoints()
void itk::simple::FastMarchingBaseImageFilter::SetTrialPoints (std::vector< std::vector< unsigned int > > TrialPoints) inline
Set the container of Trial Points representing the initial front. Trial points are represented as a VectorContainer of LevelSetNodes.
Definition at line 120 of file sitkFastMarchingBaseImageFilter.h.
References m_TrialPoints.
ToString()
std::string itk::simple::FastMarchingBaseImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 202 of file sitkFastMarchingBaseImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_InitialTrialValues
std::vector<double> itk::simple::FastMarchingBaseImageFilter::m_InitialTrialValues { std::vector<double>() } private
Definition at line 215 of file sitkFastMarchingBaseImageFilter.h.
Referenced by GetInitialTrialValues(), and SetInitialTrialValues().
m_NormalizationFactor
double itk::simple::FastMarchingBaseImageFilter::m_NormalizationFactor { 1.0 } private
Definition at line 209 of file sitkFastMarchingBaseImageFilter.h.
Referenced by GetNormalizationFactor(), and SetNormalizationFactor().
m_StoppingValue
double itk::simple::FastMarchingBaseImageFilter::m_StoppingValue { std::numeric_limits<float>::max()/2.0 } private
Definition at line 211 of file sitkFastMarchingBaseImageFilter.h.
Referenced by GetStoppingValue(), and SetStoppingValue().
m_TopologyCheck
TopologyCheckType itk::simple::FastMarchingBaseImageFilter::m_TopologyCheck { itk::simple::FastMarchingBaseImageFilter::Nothing } private
Definition at line 213 of file sitkFastMarchingBaseImageFilter.h.
Referenced by GetTopologyCheck(), and SetTopologyCheck().
m_TrialPoints
std::vector< std::vector<unsigned int> > itk::simple::FastMarchingBaseImageFilter::m_TrialPoints { std::vector< std::vector<unsigned int > >() } private
Definition at line 207 of file sitkFastMarchingBaseImageFilter.h.
Referenced by AddTrialPoint(), ClearTrialPoints(), GetTrialPoints(), and SetTrialPoints().
The documentation for this class was generated from the following file:
sitkFastMarchingBaseImageFilter.h