SimpleITK: itk::simple::SignedDanielssonDistanceMapImageFilter Class Reference
itk::simple::SignedDanielssonDistanceMapImageFilter Class Reference
This filter computes the signed distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
#include <sitkSignedDanielssonDistanceMapImageFilter.h>
Detailed Description
This filter computes the signed distance map of the input image as an approximation with pixel accuracy to the Euclidean distance.
This class is parameterized over the type of the input image and the type of the output image.
For purposes of evaluating the signed distance map, the input is assumed to be binary composed of pixels with value 0 and non-zero.
The inside is considered as having negative distances. Outside is treated as having positive distances. To change the convention, use the InsideIsPositive(bool) function.
As a convention, the distance is evaluated from the boundary of the ON pixels.
The filter returns
A signed distance map with the approximation to the euclidean distance.
A voronoi partition. (See itkDanielssonDistanceMapImageFilter)
A vector map containing the component of the vector relating the current pixel with the closest point of the closest object to this pixel. Given that the components of the distance are computed in "pixels", the vector is represented by an itk::Offset . That is, physical coordinates are not used. (See itkDanielssonDistanceMapImageFilter)
This filter internally uses the DanielssonDistanceMap filter. This filter is N-dimensional.
See also
itkDanielssonDistanceMapImageFilter
itk::simple::SignedDanielssonDistanceMap for the procedural interface
itk::SignedDanielssonDistanceMapImageFilter for the Doxygen on the original ITK class.
Definition at line 68 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Public Types
using PixelIDTypeList = IntegerPixelIDTypeList
using Self = SignedDanielssonDistanceMapImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1)
bool GetInsideIsPositive () const
std::string GetName () const
bool GetSquaredDistance () const
bool GetUseImageSpacing () const
Image GetVectorDistanceMap () const
Image GetVoronoiMap () const
void InsideIsPositiveOff ()
void InsideIsPositiveOn ()
void SetInsideIsPositive (bool InsideIsPositive)
void SetSquaredDistance (bool SquaredDistance)
void SetUseImageSpacing (bool UseImageSpacing)
SignedDanielssonDistanceMapImageFilter ()
void SquaredDistanceOff ()
void SquaredDistanceOn ()
std::string ToString () const
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~SignedDanielssonDistanceMapImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_InsideIsPositive { false }
bool m_SquaredDistance { false }
bool m_UseImageSpacing { false }
Image m_VectorDistanceMap { Image() }
Image m_VoronoiMap { Image() }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::SignedDanielssonDistanceMapImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 172 of file sitkSignedDanielssonDistanceMapImageFilter.h.
PixelIDTypeList
using itk::simple::SignedDanielssonDistanceMapImageFilter::PixelIDTypeList = IntegerPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 80 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Self
using itk::simple::SignedDanielssonDistanceMapImageFilter::Self = SignedDanielssonDistanceMapImageFilter
Definition at line 70 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Constructor & Destructor Documentation
~SignedDanielssonDistanceMapImageFilter()
virtual itk::simple::SignedDanielssonDistanceMapImageFilter::~SignedDanielssonDistanceMapImageFilter () virtual
Destructor
SignedDanielssonDistanceMapImageFilter()
itk::simple::SignedDanielssonDistanceMapImageFilter::SignedDanielssonDistanceMapImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::SignedDanielssonDistanceMapImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::SignedDanielssonDistanceMapImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetInsideIsPositive()
bool itk::simple::SignedDanielssonDistanceMapImageFilter::GetInsideIsPositive () const inline
Get if the inside represents positive values in the signed distance map. See GetInsideIsPositive()
Definition at line 102 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_InsideIsPositive.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::SignedDanielssonDistanceMapImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::SignedDanielssonDistanceMapImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 160 of file sitkSignedDanielssonDistanceMapImageFilter.h.
GetSquaredDistance()
bool itk::simple::SignedDanielssonDistanceMapImageFilter::GetSquaredDistance () const inline
Get the distance squared.
Definition at line 121 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_SquaredDistance.
GetUseImageSpacing()
bool itk::simple::SignedDanielssonDistanceMapImageFilter::GetUseImageSpacing () const inline
Get whether spacing is used.
Definition at line 140 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_UseImageSpacing.
GetVectorDistanceMap()
Image itk::simple::SignedDanielssonDistanceMapImageFilter::GetVectorDistanceMap () const inline
Get vector field of distances.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 157 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_VectorDistanceMap.
GetVoronoiMap()
Image itk::simple::SignedDanielssonDistanceMapImageFilter::GetVoronoiMap () const inline
Get Voronoi Map This map shows for each pixel what object is closest to it. Each object should be labeled by a number (larger than 0), so the map has a value for each pixel corresponding to the label of the closest object.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 149 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_VoronoiMap.
InsideIsPositiveOff()
void itk::simple::SignedDanielssonDistanceMapImageFilter::InsideIsPositiveOff () inline
Definition at line 97 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetInsideIsPositive().
InsideIsPositiveOn()
void itk::simple::SignedDanielssonDistanceMapImageFilter::InsideIsPositiveOn () inline
Set the value of InsideIsPositive to true or false respectfully.
Definition at line 95 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetInsideIsPositive().
SetInsideIsPositive()
void itk::simple::SignedDanielssonDistanceMapImageFilter::SetInsideIsPositive (bool InsideIsPositive) inline
Set if the inside represents positive values in the signed distance map. By convention ON pixels are treated as inside pixels.
Definition at line 90 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_InsideIsPositive.
Referenced by InsideIsPositiveOff(), and InsideIsPositiveOn().
SetSquaredDistance()
void itk::simple::SignedDanielssonDistanceMapImageFilter::SetSquaredDistance (bool SquaredDistance) inline
Set if the distance should be squared.
Definition at line 109 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_SquaredDistance.
Referenced by SquaredDistanceOff(), and SquaredDistanceOn().
SetUseImageSpacing()
void itk::simple::SignedDanielssonDistanceMapImageFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Set if image spacing should be used in computing distances.
Definition at line 128 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
SquaredDistanceOff()
void itk::simple::SignedDanielssonDistanceMapImageFilter::SquaredDistanceOff () inline
Definition at line 116 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetSquaredDistance().
SquaredDistanceOn()
void itk::simple::SignedDanielssonDistanceMapImageFilter::SquaredDistanceOn () inline
Set the value of SquaredDistance to true or false respectfully.
Definition at line 114 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetSquaredDistance().
ToString()
std::string itk::simple::SignedDanielssonDistanceMapImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseImageSpacingOff()
void itk::simple::SignedDanielssonDistanceMapImageFilter::UseImageSpacingOff () inline
Definition at line 135 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::SignedDanielssonDistanceMapImageFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 133 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 173 of file sitkSignedDanielssonDistanceMapImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_InsideIsPositive
bool itk::simple::SignedDanielssonDistanceMapImageFilter::m_InsideIsPositive { false } private
Definition at line 178 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Referenced by GetInsideIsPositive(), and SetInsideIsPositive().
m_SquaredDistance
bool itk::simple::SignedDanielssonDistanceMapImageFilter::m_SquaredDistance { false } private
Definition at line 180 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Referenced by GetSquaredDistance(), and SetSquaredDistance().
m_UseImageSpacing
bool itk::simple::SignedDanielssonDistanceMapImageFilter::m_UseImageSpacing { false } private
Definition at line 182 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
m_VectorDistanceMap
Image itk::simple::SignedDanielssonDistanceMapImageFilter::m_VectorDistanceMap { Image() } private
Definition at line 187 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Referenced by GetVectorDistanceMap().
m_VoronoiMap
Image itk::simple::SignedDanielssonDistanceMapImageFilter::m_VoronoiMap { Image() } private
Definition at line 186 of file sitkSignedDanielssonDistanceMapImageFilter.h.
Referenced by GetVoronoiMap().
The documentation for this class was generated from the following file:
sitkSignedDanielssonDistanceMapImageFilter.h