SimpleITK: itk::simple::VersorRigid3DTransform Class Reference
itk::simple::VersorRigid3DTransform Class Reference
A rotation as a versor around a fixed center with translation of a 3D coordinate space.
#include <sitkVersorRigid3DTransform.h>
Detailed Description
A rotation as a versor around a fixed center with translation of a 3D coordinate space.
See also
itk::VersorRigid3DTransform
Definition at line 34 of file sitkVersorRigid3DTransform.h.
Public Types
using Self = VersorRigid3DTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
std::vector< double > GetCenter () const
std::vector< double > GetMatrix () const
std::string GetName () const override
std::vector< double > GetTranslation () const
std::vector< double > GetVersor () const
VersorRigid3DTransform & operator= (const VersorRigid3DTransform &)
Self & SetCenter (const std::vector< double > &params)
Self & SetMatrix (const std::vector< double > &matrix, double tolerance=1e-10)
Self & SetRotation (const std::vector< double > &axis, double angle)
Self & SetRotation (const std::vector< double > &versor)
Self & SetTranslation (const std::vector< double > &translation)
Self & Translate (const std::vector< double > &offset)
VersorRigid3DTransform ()
VersorRigid3DTransform (const std::vector< double > &axis, double angle, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
VersorRigid3DTransform (const std::vector< double > &versor, const std::vector< double > &translation=std::vector< double >(3, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
VersorRigid3DTransform (const Transform &)
VersorRigid3DTransform (const VersorRigid3DTransform &)
~VersorRigid3DTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< std::vector< double >()> m_pfGetCenter
std::function< std::vector< double >()> m_pfGetMatrix
std::function< std::vector< double >()> m_pfGetTranslation
std::function< std::vector< double >()> m_pfGetVersor
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(const std::vector< double > &, double)> m_pfSetMatrix
std::function< void(const std::vector< double > &)> m_pfSetRotation1
std::function< void(const std::vector< double > &, double)> m_pfSetRotation2
std::function< void(const std::vector< double > &)> m_pfSetTranslation
std::function< void(const std::vector< double > &)> m_pfTranslate
Member Typedef Documentation
Self
using itk::simple::VersorRigid3DTransform::Self = VersorRigid3DTransform
Definition at line 37 of file sitkVersorRigid3DTransform.h.
Superclass
using itk::simple::VersorRigid3DTransform::Superclass = Transform
Definition at line 38 of file sitkVersorRigid3DTransform.h.
Constructor & Destructor Documentation
~VersorRigid3DTransform()
itk::simple::VersorRigid3DTransform::~VersorRigid3DTransform () override
VersorRigid3DTransform() [1/5]
itk::simple::VersorRigid3DTransform::VersorRigid3DTransform ()
Referenced by operator=(), VersorRigid3DTransform(), and VersorRigid3DTransform().
VersorRigid3DTransform() [2/5]
itk::simple::VersorRigid3DTransform::VersorRigid3DTransform (const VersorRigid3DTransform &)
References VersorRigid3DTransform().
VersorRigid3DTransform() [3/5]
itk::simple::VersorRigid3DTransform::VersorRigid3DTransform (const Transform &) explicit
References itk::simple::Transform::Transform().
VersorRigid3DTransform() [4/5]
itk::simple::VersorRigid3DTransform::VersorRigid3DTransform (const std::vector< double > & versor, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0)) explicit
VersorRigid3DTransform() [5/5]
itk::simple::VersorRigid3DTransform::VersorRigid3DTransform (const std::vector< double > & axis, double angle, const std::vector< double > & translation = std::vector< double >(3, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
References VersorRigid3DTransform().
Member Function Documentation
GetCenter()
std::vector< double > itk::simple::VersorRigid3DTransform::GetCenter () const
GetMatrix()
std::vector< double > itk::simple::VersorRigid3DTransform::GetMatrix () const
GetName()
std::string itk::simple::VersorRigid3DTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 63 of file sitkVersorRigid3DTransform.h.
GetTranslation()
std::vector< double > itk::simple::VersorRigid3DTransform::GetTranslation () const
GetVersor()
std::vector< double > itk::simple::VersorRigid3DTransform::GetVersor () const
InternalInitialization() [1/2]
void itk::simple::VersorRigid3DTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::VersorRigid3DTransform::InternalInitialization (TransformType * transform) private
operator=()
VersorRigid3DTransform & itk::simple::VersorRigid3DTransform::operator= (const VersorRigid3DTransform &)
References VersorRigid3DTransform().
SetCenter()
Self & itk::simple::VersorRigid3DTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetMatrix()
Self & itk::simple::VersorRigid3DTransform::SetMatrix (const std::vector< double > & matrix, double tolerance = 1e-10)
SetPimpleTransform()
void itk::simple::VersorRigid3DTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetRotation() [1/2]
Self & itk::simple::VersorRigid3DTransform::SetRotation (const std::vector< double > & axis, double angle)
SetRotation() [2/2]
Self & itk::simple::VersorRigid3DTransform::SetRotation (const std::vector< double > & versor)
parameter
SetTranslation()
Self & itk::simple::VersorRigid3DTransform::SetTranslation (const std::vector< double > & translation)
Translate()
Self & itk::simple::VersorRigid3DTransform::Translate (const std::vector< double > & offset)
additional methods
Member Data Documentation
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::VersorRigid3DTransform::m_pfGetCenter private
Definition at line 110 of file sitkVersorRigid3DTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::VersorRigid3DTransform::m_pfGetMatrix private
Definition at line 117 of file sitkVersorRigid3DTransform.h.
m_pfGetTranslation
std::function<std::vector<double>()> itk::simple::VersorRigid3DTransform::m_pfGetTranslation private
Definition at line 115 of file sitkVersorRigid3DTransform.h.
m_pfGetVersor
std::function<std::vector<double>()> itk::simple::VersorRigid3DTransform::m_pfGetVersor private
Definition at line 113 of file sitkVersorRigid3DTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::VersorRigid3DTransform::m_pfSetCenter private
Definition at line 109 of file sitkVersorRigid3DTransform.h.
m_pfSetMatrix
std::function<void(const std::vector<double> &, double)> itk::simple::VersorRigid3DTransform::m_pfSetMatrix private
Definition at line 118 of file sitkVersorRigid3DTransform.h.
m_pfSetRotation1
std::function<void(const std::vector<double> &)> itk::simple::VersorRigid3DTransform::m_pfSetRotation1 private
Definition at line 111 of file sitkVersorRigid3DTransform.h.
m_pfSetRotation2
std::function<void(const std::vector<double> &, double)> itk::simple::VersorRigid3DTransform::m_pfSetRotation2 private
Definition at line 112 of file sitkVersorRigid3DTransform.h.
m_pfSetTranslation
std::function<void(const std::vector<double> &)> itk::simple::VersorRigid3DTransform::m_pfSetTranslation private
Definition at line 114 of file sitkVersorRigid3DTransform.h.
m_pfTranslate
std::function<void(const std::vector<double> &)> itk::simple::VersorRigid3DTransform::m_pfTranslate private
Definition at line 116 of file sitkVersorRigid3DTransform.h.
The documentation for this class was generated from the following file:
sitkVersorRigid3DTransform.h