SimpleITK: itk::simple::ElastixImageFilter Class Reference
itk::simple::ElastixImageFilter Class Reference
The class that wraps the elastix registration library.
#include <sitkElastixImageFilter.h>
Detailed Description
The class that wraps the elastix registration library.
Examples
Elastix/elx.cxx.
Definition at line 36 of file sitkElastixImageFilter.h.
Classes
class ElastixImageFilterImpl
Public Types
typedef std::string ParameterKeyType
typedef ParameterMapType::const_iterator ParameterMapConstIterator
typedef ParameterMapType::iterator ParameterMapIterator
typedef std::map< ParameterKeyType, ParameterValueVectorType > ParameterMapType
typedef std::vector< ParameterMapType > ParameterMapVectorType
typedef std::string ParameterValueType
typedef ParameterValueVectorType::iterator ParameterValueVectorIterator
typedef std::vector< ParameterValueType > ParameterValueVectorType
typedef ElastixImageFilter Self
typedef std::vector< Image > VectorOfImage
Public Member Functions
Self & AddFixedImage (const Image &fixedImage)
Adds an image to the end of the container of fixed images.
Self & AddFixedMask (const Image &fixedMask)
Adds an image to the end of the container of fixed masks.
Self & AddMovingImage (const Image &movingImage)
Adds an image to the end of the container of moving images.
Self & AddMovingMask (const Image &movingMask)
Adds an image to the end of the container of moving masks.
Self & AddParameter (const std::string key, const std::string value)
Adds a parameter specified by key, with the specified value to all parameter maps.
Self & AddParameter (const std::string key, const std::vector< std::string > value)
Adds a parameter specified by key, with the specified values to all parameter maps.
Self & AddParameter (const unsigned int index, const std::string key, const std::string value)
Adds a parameter specified by key, with the specified value to the parameter map at the specified (zero-based) index.
Self & AddParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
Adds a parameter specified by key, with the specified values to the parameter map at the specified (zero-based) index.
Self & AddParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Adds a parameter map to the container of parameter maps.
ElastixImageFilter ()
Default-constructor.
Image Execute ()
Executes the registration, and returns the result image.
std::map< std::string, std::vector< std::string > > GetDefaultParameterMap (const std::string transformName, const unsigned int numberOfResolutions=4, const double finalGridSpacingInPhysicalUnits=10.0)
Returns the default parameter map for the specified function arguments (transformName may be "translation", "rigid" , "affine", "nonrigid", or "bspline").
VectorOfImage & GetFixedImage ()
Retrieves a reference to the container of fixed images.
Image & GetFixedImage (const unsigned long index)
Retrieves a reference to the fixed image at the specified (zero-based) index.
VectorOfImage & GetFixedMask ()
Retrieves a reference to the container of fixed masks.
Image & GetFixedMask (const unsigned long index)
Retrieves a reference to the fixed mask at the specified (zero-based) index.
std::string GetFixedPointSetFileName ()
Returns the name of the current point set file of points from the fixed image.
std::string GetInitialTransformParameterFileName ()
Returns the initial transform parameter file name.
std::string GetLogFileName ()
Returns the name of the current log file.
bool GetLogToConsole ()
Returns whether logging to console is switched on.
bool GetLogToFile ()
Returns whether logging to file is switched on.
VectorOfImage & GetMovingImage ()
Retrieves a reference to the moving image at the specified (zero-based) index.
Image & GetMovingImage (const unsigned long index)
Retrieves a reference to the moving image at the specified (zero-based) index.
VectorOfImage & GetMovingMask ()
Retrieves a reference to the container of moving masks.
Image & GetMovingMask (const unsigned long index)
Retrieves a reference to the moving mask at the specified (zero-based) index.
std::string GetMovingPointSetFileName ()
Returns the name of the current point set file of points from the moving image.
std::string GetName () const
unsigned int GetNumberOfFixedImages ()
Returns the number of fixed images.
unsigned int GetNumberOfFixedMasks ()
Returns the number of fixed masks.
unsigned int GetNumberOfMovingImages ()
Returns the number of moving images.
unsigned int GetNumberOfMovingMasks ()
Returns the number of moving masks.
unsigned int GetNumberOfParameterMaps ()
Returns the number of parameter maps.
int GetNumberOfThreads ()
Returns the current maximum number of threads.
std::string GetOutputDirectory ()
Returns the current output directory.
std::vector< std::string > GetParameter (const std::string key)
Retrieves the values of the parameter specified by key, when there is only one parameter map.
std::vector< std::string > GetParameter (const unsigned int index, const std::string key)
Retrieves the values of the parameter specified by key, from the parameter map at the specified (zero-based) index.
std::vector< std::map< std::string, std::vector< std::string > > > GetParameterMap ()
Returns a copy of the parameter maps.
std::vector< std::map< std::string, std::vector< std::string > > > GetParameterMaps ()
Image GetResultImage ()
Returns the result image.
std::vector< std::map< std::string, std::vector< std::string > > > GetTransformParameterMap ()
Returns all transform parameter maps.
std::map< std::string, std::vector< std::string > > GetTransformParameterMap (const unsigned int index)
Returns the transform parameter map at the specified (zero-based) index.
Self & LogToConsoleOff ()
Switches logging to console off.
Self & LogToConsoleOn ()
Switches logging to console on.
Self & LogToFileOff ()
Switches logging to file off.
Self & LogToFileOn ()
Switches logging to file on.
Self & PrintParameterMap ()
Prints all parameter maps to standard output.
Self & PrintParameterMap (const ParameterMapType parameterMapVector)
Prints the specified parameter map to standard output.
Self & PrintParameterMap (const ParameterMapVectorType parameterMapVector)
Prints the specified parameter maps to standard output.
std::map< std::string, std::vector< std::string > > ReadParameterFile (const std::string filename)
Reads the parameter file specified by filename, and returns its content as a parameter map.
Self & RemoveFixedImage ()
Removes all fixed images.
Self & RemoveFixedImage (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of fixed images.
Self & RemoveFixedMask ()
Removes all fixed masks.
Self & RemoveFixedMask (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of fixed masks.
Self & RemoveFixedPointSetFileName ()
Clears the current point set file name of points from the fixed image.
Self & RemoveInitialTransformParameterFileName ()
Clears the initial transform parameter file name.
Self & RemoveLogFileName ()
Clears the name of the current log file.
Self & RemoveMovingImage ()
Removes all moving images.
Self & RemoveMovingImage (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of moving images.
Self & RemoveMovingMask ()
Removes all moving masks.
Self & RemoveMovingMask (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of moving masks.
Self & RemoveMovingPointSetFileName ()
Clears the current point set file name of points from the moving image.
Self & RemoveOutputDirectory ()
Clears the name of the current output directory. (Does not remove the actual directory.)
Self & RemoveParameter (const std::string key)
Removes the parameter specified by key from all parameter maps.
Self & RemoveParameter (const unsigned int index, const std::string key)
Removes the parameter specified by key from the parameter map at the specified (zero-based) index.
Self & SetFixedImage (const Image &fixedImage)
Sets a fixed image. Stores the image into the container of fixed images.
Self & SetFixedImage (const VectorOfImage &fixedImages)
Sets multiple fixed images. Stores the images into the container of fixed images.
Self & SetFixedMask (const Image &fixedMask)
Sets a fixed mask. Stores the image into the container of fixed masks.
Self & SetFixedMask (const VectorOfImage &fixedMasks)
Sets multiple fixed masks. Stores the images into the container of fixed masks.
Self & SetFixedPointSetFileName (const std::string fixedPointSetFileName)
Specifies a set of points from the fixed image by a point set file, fixedPointSetFileName.
Self & SetInitialTransformParameterFileName (const std::string initialTransformParmaterFileName)
Specifies the initial transformation by the specified transform parameter file name.
Self & SetLogFileName (const std::string logFileName)
Sets the name of the current log file.
Self & SetLogToConsole (bool)
Switches logging to console on (true) or off (false), as specified by its function argument.
Self & SetLogToFile (const bool logToFile)
Switches logging to file on (true) or off (false), as specified by its function argument.
Self & SetMovingImage (const Image &movingImages)
Sets a moving image. Stores the image into the container of moving images.
Self & SetMovingImage (const VectorOfImage &movingImage)
Sets multiple moving images. Stores the images into the container of moving images.
Self & SetMovingMask (const Image &movingMask)
Sets a moving mask. Stores the image into the container of moving masks.
Self & SetMovingMask (const VectorOfImage &movingMasks)
Sets multiple moving masks. Stores the images into the container of moving masks.
Self & SetMovingPointSetFileName (const std::string movingPointSetFileName)
Specifies a set of points from the moving image by a point set file, movingPointSetFileName.
Self & SetNumberOfThreads (int n)
Sets the maximum number of threads to the specified number n.
Self & SetOutputDirectory (const std::string outputDirectory)
Sets the output directory.
Self & SetParameter (const std::string key, const std::string value)
Sets the value of the parameter specified by key, in all parameter maps.
Self & SetParameter (const std::string key, const std::vector< std::string > value)
Sets the values of the parameter specified by key, in all parameter maps.
Self & SetParameter (const unsigned int index, const std::string key, const std::string value)
Sets the value of the parameter specified by key, in the parameter map at the specified (zero-based) index.
Self & SetParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
Sets the values of the parameter specified by key, in the parameter map at the specified (zero-based) index.
Self & SetParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Specifies a single parameter map.
Self & SetParameterMap (const std::string transformName, const unsigned int numberOfResolutions=4u, const double finalGridSpacingInPhysicalUnits=10.0)
Specifies the parameter map by a transformName ("translation", "rigid" , "affine", "nonrigid", or "bspline"), and optionally numberOfResolutions and finalGridSpacingInPhysicalUnits.
Self & SetParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
Specifies multiple parameter maps.
Self & SetParameterMaps (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
Self & WriteParameterFile (const std::map< std::string, std::vector< std::string > > parameterMap, const std::string filename)
Writes a parameter map to the file, specified by filename.
~ElastixImageFilter ()
Destructor.
Private Attributes
const std::unique_ptr< ElastixImageFilterImpl > m_Pimple
Member Typedef Documentation
ParameterKeyType
typedef std::string itk::simple::ElastixImageFilter::ParameterKeyType
Definition at line 49 of file sitkElastixImageFilter.h.
ParameterMapConstIterator
typedef ParameterMapType::const_iterator itk::simple::ElastixImageFilter::ParameterMapConstIterator
Definition at line 56 of file sitkElastixImageFilter.h.
ParameterMapIterator
typedef ParameterMapType::iterator itk::simple::ElastixImageFilter::ParameterMapIterator
Definition at line 55 of file sitkElastixImageFilter.h.
ParameterMapType
typedef std::map<ParameterKeyType, ParameterValueVectorType> itk::simple::ElastixImageFilter::ParameterMapType
Definition at line 53 of file sitkElastixImageFilter.h.
ParameterMapVectorType
typedef std::vector<ParameterMapType> itk::simple::ElastixImageFilter::ParameterMapVectorType
Definition at line 54 of file sitkElastixImageFilter.h.
ParameterValueType
typedef std::string itk::simple::ElastixImageFilter::ParameterValueType
Definition at line 50 of file sitkElastixImageFilter.h.
ParameterValueVectorIterator
typedef ParameterValueVectorType::iterator itk::simple::ElastixImageFilter::ParameterValueVectorIterator
Definition at line 52 of file sitkElastixImageFilter.h.
ParameterValueVectorType
typedef std::vector<ParameterValueType> itk::simple::ElastixImageFilter::ParameterValueVectorType
Definition at line 51 of file sitkElastixImageFilter.h.
Self
typedef ElastixImageFilter itk::simple::ElastixImageFilter::Self
Definition at line 45 of file sitkElastixImageFilter.h.
VectorOfImage
typedef std::vector<Image> itk::simple::ElastixImageFilter::VectorOfImage
Definition at line 47 of file sitkElastixImageFilter.h.
Constructor & Destructor Documentation
ElastixImageFilter()
itk::simple::ElastixImageFilter::ElastixImageFilter ()
Default-constructor.
~ElastixImageFilter()
itk::simple::ElastixImageFilter::~ElastixImageFilter ()
Destructor.
Member Function Documentation
AddFixedImage()
Self & itk::simple::ElastixImageFilter::AddFixedImage (const Image & fixedImage)
Adds an image to the end of the container of fixed images.
AddFixedMask()
Self & itk::simple::ElastixImageFilter::AddFixedMask (const Image & fixedMask)
Adds an image to the end of the container of fixed masks.
AddMovingImage()
Self & itk::simple::ElastixImageFilter::AddMovingImage (const Image & movingImage)
Adds an image to the end of the container of moving images.
AddMovingMask()
Self & itk::simple::ElastixImageFilter::AddMovingMask (const Image & movingMask)
Adds an image to the end of the container of moving masks.
AddParameter() [1/4]
Self & itk::simple::ElastixImageFilter::AddParameter (const std::string key, const std::string value)
Adds a parameter specified by key, with the specified value to all parameter maps.
AddParameter() [2/4]
Self & itk::simple::ElastixImageFilter::AddParameter (const std::string key, const std::vector< std::string > value)
Adds a parameter specified by key, with the specified values to all parameter maps.
AddParameter() [3/4]
Self & itk::simple::ElastixImageFilter::AddParameter (const unsigned int index, const std::string key, const std::string value)
Adds a parameter specified by key, with the specified value to the parameter map at the specified (zero-based) index.
AddParameter() [4/4]
Self & itk::simple::ElastixImageFilter::AddParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
Adds a parameter specified by key, with the specified values to the parameter map at the specified (zero-based) index.
AddParameterMap()
Self & itk::simple::ElastixImageFilter::AddParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Adds a parameter map to the container of parameter maps.
Execute()
Image itk::simple::ElastixImageFilter::Execute ()
Executes the registration, and returns the result image.
Note
Before executing, the number of moving images must equal the number of fixed images, the number of fixed masks must be either zero, or one, or equal to the number of fixed images, and the number of moving masks must be either zero, or one, or equal to the number of moving images
Examples
Elastix/elx.cxx.
GetDefaultParameterMap()
std::map< std::string, std::vector< std::string > > itk::simple::ElastixImageFilter::GetDefaultParameterMap (const std::string transformName, const unsigned int numberOfResolutions = 4, const double finalGridSpacingInPhysicalUnits = 10.0)
Returns the default parameter map for the specified function arguments (transformName may be "translation", "rigid" , "affine", "nonrigid", or "bspline").
GetFixedImage() [1/2]
VectorOfImage & itk::simple::ElastixImageFilter::GetFixedImage ()
Retrieves a reference to the container of fixed images.
GetFixedImage() [2/2]
Image & itk::simple::ElastixImageFilter::GetFixedImage (const unsigned long index)
Retrieves a reference to the fixed image at the specified (zero-based) index.
GetFixedMask() [1/2]
VectorOfImage & itk::simple::ElastixImageFilter::GetFixedMask ()
Retrieves a reference to the container of fixed masks.
GetFixedMask() [2/2]
Image & itk::simple::ElastixImageFilter::GetFixedMask (const unsigned long index)
Retrieves a reference to the fixed mask at the specified (zero-based) index.
GetFixedPointSetFileName()
std::string itk::simple::ElastixImageFilter::GetFixedPointSetFileName ()
Returns the name of the current point set file of points from the fixed image.
GetInitialTransformParameterFileName()
std::string itk::simple::ElastixImageFilter::GetInitialTransformParameterFileName ()
Returns the initial transform parameter file name.
GetLogFileName()
std::string itk::simple::ElastixImageFilter::GetLogFileName ()
Returns the name of the current log file.
GetLogToConsole()
bool itk::simple::ElastixImageFilter::GetLogToConsole ()
Returns whether logging to console is switched on.
GetLogToFile()
bool itk::simple::ElastixImageFilter::GetLogToFile ()
Returns whether logging to file is switched on.
GetMovingImage() [1/2]
VectorOfImage & itk::simple::ElastixImageFilter::GetMovingImage ()
Retrieves a reference to the moving image at the specified (zero-based) index.
GetMovingImage() [2/2]
Image & itk::simple::ElastixImageFilter::GetMovingImage (const unsigned long index)
Retrieves a reference to the moving image at the specified (zero-based) index.
GetMovingMask() [1/2]
VectorOfImage & itk::simple::ElastixImageFilter::GetMovingMask ()
Retrieves a reference to the container of moving masks.
GetMovingMask() [2/2]
Image & itk::simple::ElastixImageFilter::GetMovingMask (const unsigned long index)
Retrieves a reference to the moving mask at the specified (zero-based) index.
GetMovingPointSetFileName()
std::string itk::simple::ElastixImageFilter::GetMovingPointSetFileName ()
Returns the name of the current point set file of points from the moving image.
GetName()
std::string itk::simple::ElastixImageFilter::GetName () const
GetNumberOfFixedImages()
unsigned int itk::simple::ElastixImageFilter::GetNumberOfFixedImages ()
Returns the number of fixed images.
GetNumberOfFixedMasks()
unsigned int itk::simple::ElastixImageFilter::GetNumberOfFixedMasks ()
Returns the number of fixed masks.
GetNumberOfMovingImages()
unsigned int itk::simple::ElastixImageFilter::GetNumberOfMovingImages ()
Returns the number of moving images.
GetNumberOfMovingMasks()
unsigned int itk::simple::ElastixImageFilter::GetNumberOfMovingMasks ()
Returns the number of moving masks.
GetNumberOfParameterMaps()
unsigned int itk::simple::ElastixImageFilter::GetNumberOfParameterMaps ()
Returns the number of parameter maps.
GetNumberOfThreads()
int itk::simple::ElastixImageFilter::GetNumberOfThreads ()
Returns the current maximum number of threads.
GetOutputDirectory()
std::string itk::simple::ElastixImageFilter::GetOutputDirectory ()
Returns the current output directory.
GetParameter() [1/2]
std::vector< std::string > itk::simple::ElastixImageFilter::GetParameter (const std::string key)
Retrieves the values of the parameter specified by key, when there is only one parameter map.
GetParameter() [2/2]
std::vector< std::string > itk::simple::ElastixImageFilter::GetParameter (const unsigned int index, const std::string key)
Retrieves the values of the parameter specified by key, from the parameter map at the specified (zero-based) index.
GetParameterMap()
std::vector< std::map< std::string, std::vector< std::string > > > itk::simple::ElastixImageFilter::GetParameterMap ()
Returns a copy of the parameter maps.
Referenced by GetParameterMaps().
GetParameterMaps()
std::vector< std::map< std::string, std::vector< std::string > > > itk::simple::ElastixImageFilter::GetParameterMaps () inline
Definition at line 307 of file sitkElastixImageFilter.h.
References GetParameterMap().
GetResultImage()
Image itk::simple::ElastixImageFilter::GetResultImage ()
Returns the result image.
Examples
Elastix/elx.cxx.
GetTransformParameterMap() [1/2]
std::vector< std::map< std::string, std::vector< std::string > > > itk::simple::ElastixImageFilter::GetTransformParameterMap ()
Returns all transform parameter maps.
Examples
Elastix/elx.cxx.
GetTransformParameterMap() [2/2]
std::map< std::string, std::vector< std::string > > itk::simple::ElastixImageFilter::GetTransformParameterMap (const unsigned int index)
Returns the transform parameter map at the specified (zero-based) index.
LogToConsoleOff()
Self & itk::simple::ElastixImageFilter::LogToConsoleOff ()
Switches logging to console off.
LogToConsoleOn()
Self & itk::simple::ElastixImageFilter::LogToConsoleOn ()
Switches logging to console on.
Examples
Elastix/elx.cxx.
LogToFileOff()
Self & itk::simple::ElastixImageFilter::LogToFileOff ()
Switches logging to file off.
LogToFileOn()
Self & itk::simple::ElastixImageFilter::LogToFileOn ()
Switches logging to file on.
PrintParameterMap() [1/3]
Self & itk::simple::ElastixImageFilter::PrintParameterMap ()
Prints all parameter maps to standard output.
PrintParameterMap() [2/3]
Self & itk::simple::ElastixImageFilter::PrintParameterMap (const ParameterMapType parameterMapVector)
Prints the specified parameter map to standard output.
PrintParameterMap() [3/3]
Self & itk::simple::ElastixImageFilter::PrintParameterMap (const ParameterMapVectorType parameterMapVector)
Prints the specified parameter maps to standard output.
ReadParameterFile()
std::map< std::string, std::vector< std::string > > itk::simple::ElastixImageFilter::ReadParameterFile (const std::string filename)
Reads the parameter file specified by filename, and returns its content as a parameter map.
RemoveFixedImage() [1/2]
Self & itk::simple::ElastixImageFilter::RemoveFixedImage ()
Removes all fixed images.
RemoveFixedImage() [2/2]
Self & itk::simple::ElastixImageFilter::RemoveFixedImage (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of fixed images.
RemoveFixedMask() [1/2]
Self & itk::simple::ElastixImageFilter::RemoveFixedMask ()
Removes all fixed masks.
RemoveFixedMask() [2/2]
Self & itk::simple::ElastixImageFilter::RemoveFixedMask (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of fixed masks.
RemoveFixedPointSetFileName()
Self & itk::simple::ElastixImageFilter::RemoveFixedPointSetFileName ()
Clears the current point set file name of points from the fixed image.
RemoveInitialTransformParameterFileName()
Self & itk::simple::ElastixImageFilter::RemoveInitialTransformParameterFileName ()
Clears the initial transform parameter file name.
RemoveLogFileName()
Self & itk::simple::ElastixImageFilter::RemoveLogFileName ()
Clears the name of the current log file.
RemoveMovingImage() [1/2]
Self & itk::simple::ElastixImageFilter::RemoveMovingImage ()
Removes all moving images.
RemoveMovingImage() [2/2]
Self & itk::simple::ElastixImageFilter::RemoveMovingImage (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of moving images.
RemoveMovingMask() [1/2]
Self & itk::simple::ElastixImageFilter::RemoveMovingMask ()
Removes all moving masks.
RemoveMovingMask() [2/2]
Self & itk::simple::ElastixImageFilter::RemoveMovingMask (const unsigned long index)
Removes an image at the specified (zero-based) index from the container of moving masks.
RemoveMovingPointSetFileName()
Self & itk::simple::ElastixImageFilter::RemoveMovingPointSetFileName ()
Clears the current point set file name of points from the moving image.
RemoveOutputDirectory()
Self & itk::simple::ElastixImageFilter::RemoveOutputDirectory ()
Clears the name of the current output directory. (Does not remove the actual directory.)
RemoveParameter() [1/2]
Self & itk::simple::ElastixImageFilter::RemoveParameter (const std::string key)
Removes the parameter specified by key from all parameter maps.
RemoveParameter() [2/2]
Self & itk::simple::ElastixImageFilter::RemoveParameter (const unsigned int index, const std::string key)
Removes the parameter specified by key from the parameter map at the specified (zero-based) index.
SetFixedImage() [1/2]
Self & itk::simple::ElastixImageFilter::SetFixedImage (const Image & fixedImage)
Sets a fixed image. Stores the image into the container of fixed images.
Examples
Elastix/elx.cxx.
SetFixedImage() [2/2]
Self & itk::simple::ElastixImageFilter::SetFixedImage (const VectorOfImage & fixedImages)
Sets multiple fixed images. Stores the images into the container of fixed images.
SetFixedMask() [1/2]
Self & itk::simple::ElastixImageFilter::SetFixedMask (const Image & fixedMask)
Sets a fixed mask. Stores the image into the container of fixed masks.
SetFixedMask() [2/2]
Self & itk::simple::ElastixImageFilter::SetFixedMask (const VectorOfImage & fixedMasks)
Sets multiple fixed masks. Stores the images into the container of fixed masks.
SetFixedPointSetFileName()
Self & itk::simple::ElastixImageFilter::SetFixedPointSetFileName (const std::string fixedPointSetFileName)
Specifies a set of points from the fixed image by a point set file, fixedPointSetFileName.
SetInitialTransformParameterFileName()
Self & itk::simple::ElastixImageFilter::SetInitialTransformParameterFileName (const std::string initialTransformParmaterFileName)
Specifies the initial transformation by the specified transform parameter file name.
SetLogFileName()
Self & itk::simple::ElastixImageFilter::SetLogFileName (const std::string logFileName)
Sets the name of the current log file.
SetLogToConsole()
Self & itk::simple::ElastixImageFilter::SetLogToConsole (bool)
Switches logging to console on (true) or off (false), as specified by its function argument.
SetLogToFile()
Self & itk::simple::ElastixImageFilter::SetLogToFile (const bool logToFile)
Switches logging to file on (true) or off (false), as specified by its function argument.
SetMovingImage() [1/2]
Self & itk::simple::ElastixImageFilter::SetMovingImage (const Image & movingImages)
Sets a moving image. Stores the image into the container of moving images.
Examples
Elastix/elx.cxx.
SetMovingImage() [2/2]
Self & itk::simple::ElastixImageFilter::SetMovingImage (const VectorOfImage & movingImage)
Sets multiple moving images. Stores the images into the container of moving images.
SetMovingMask() [1/2]
Self & itk::simple::ElastixImageFilter::SetMovingMask (const Image & movingMask)
Sets a moving mask. Stores the image into the container of moving masks.
SetMovingMask() [2/2]
Self & itk::simple::ElastixImageFilter::SetMovingMask (const VectorOfImage & movingMasks)
Sets multiple moving masks. Stores the images into the container of moving masks.
SetMovingPointSetFileName()
Self & itk::simple::ElastixImageFilter::SetMovingPointSetFileName (const std::string movingPointSetFileName)
Specifies a set of points from the moving image by a point set file, movingPointSetFileName.
SetNumberOfThreads()
Self & itk::simple::ElastixImageFilter::SetNumberOfThreads (int n)
Sets the maximum number of threads to the specified number n.
Note
As a side effect, it may modify the global maximum number of threads, as it internally calls ITK's MultiThreaderBase.SetGlobalMaximumNumberOfThreads.
SetOutputDirectory()
Self & itk::simple::ElastixImageFilter::SetOutputDirectory (const std::string outputDirectory)
Sets the output directory.
SetParameter() [1/4]
Self & itk::simple::ElastixImageFilter::SetParameter (const std::string key, const std::string value)
Sets the value of the parameter specified by key, in all parameter maps.
SetParameter() [2/4]
Self & itk::simple::ElastixImageFilter::SetParameter (const std::string key, const std::vector< std::string > value)
Sets the values of the parameter specified by key, in all parameter maps.
SetParameter() [3/4]
Self & itk::simple::ElastixImageFilter::SetParameter (const unsigned int index, const std::string key, const std::string value)
Sets the value of the parameter specified by key, in the parameter map at the specified (zero-based) index.
SetParameter() [4/4]
Self & itk::simple::ElastixImageFilter::SetParameter (const unsigned int index, const std::string key, const std::vector< std::string > value)
Sets the values of the parameter specified by key, in the parameter map at the specified (zero-based) index.
SetParameterMap() [1/3]
Self & itk::simple::ElastixImageFilter::SetParameterMap (const std::map< std::string, std::vector< std::string > > parameterMap)
Specifies a single parameter map.
SetParameterMap() [2/3]
Self & itk::simple::ElastixImageFilter::SetParameterMap (const std::string transformName, const unsigned int numberOfResolutions = 4u, const double finalGridSpacingInPhysicalUnits = 10.0)
Specifies the parameter map by a transformName ("translation", "rigid" , "affine", "nonrigid", or "bspline"), and optionally numberOfResolutions and finalGridSpacingInPhysicalUnits.
Examples
Elastix/elx.cxx.
Referenced by SetParameterMaps().
SetParameterMap() [3/3]
Self & itk::simple::ElastixImageFilter::SetParameterMap (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector)
Specifies multiple parameter maps.
SetParameterMaps()
Self & itk::simple::ElastixImageFilter::SetParameterMaps (const std::vector< std::map< std::string, std::vector< std::string > > > parameterMapVector) inline
Definition at line 290 of file sitkElastixImageFilter.h.
References SetParameterMap().
WriteParameterFile()
Self & itk::simple::ElastixImageFilter::WriteParameterFile (const std::map< std::string, std::vector< std::string > > parameterMap, const std::string filename)
Writes a parameter map to the file, specified by filename.
Member Data Documentation
m_Pimple
const std::unique_ptr<ElastixImageFilterImpl> itk::simple::ElastixImageFilter::m_Pimple private
Definition at line 430 of file sitkElastixImageFilter.h.
The documentation for this class was generated from the following file:
sitkElastixImageFilter.h