SimpleITK: itk::simple::ClosingByReconstructionImageFilter Class Reference
itk::simple::ClosingByReconstructionImageFilter Class Reference
Closing by reconstruction of an image.
#include <sitkClosingByReconstructionImageFilter.h>
Detailed Description
Closing by reconstruction of an image.
This filter is similar to the morphological closing, but contrary to the morphological closing, the closing by reconstruction preserves the shape of the components. The closing by reconstruction of an image "f" is defined as:
ClosingByReconstruction(f) = ErosionByReconstruction(f, Dilation(f)).
Closing by reconstruction not only preserves structures preserved by the dilation, but also levels raises the contrast of the darkest regions. If PreserveIntensities is on, a subsequent reconstruction by dilation using a marker image that is the original image for all unaffected pixels.
Closing by reconstruction is described in Chapter 6.3.9 of Pierre Soille's book "Morphological Image Analysis: Principles and Applications", Second Edition, Springer, 2003.
Author
Gaetan Lehmann. Biologie du Developpement et de la Reproduction, INRA de Jouy-en-Josas, France.
See also
GrayscaleMorphologicalClosingImageFilter
itk::simple::ClosingByReconstruction for the procedural interface
itk::ClosingByReconstructionImageFilter for the Doxygen on the original ITK class.
Definition at line 59 of file sitkClosingByReconstructionImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = ClosingByReconstructionImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
ClosingByReconstructionImageFilter ()
Image Execute (const Image &image1)
void FullyConnectedOff ()
void FullyConnectedOn ()
bool GetFullyConnected () const
std::vector< unsigned int > GetKernelRadius () const
KernelEnum GetKernelType () const
std::string GetName () const
bool GetPreserveIntensities () const
void PreserveIntensitiesOff ()
void PreserveIntensitiesOn ()
void SetFullyConnected (bool FullyConnected)
void SetKernelRadius (std::vector< unsigned int > KernelRadius)
void SetKernelRadius (unsigned int value)
void SetKernelType (KernelEnum KernelType)
void SetPreserveIntensities (bool PreserveIntensities)
std::string ToString () const
virtual ~ClosingByReconstructionImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_FullyConnected { false }
std::vector< unsigned int > m_KernelRadius { std::vector<uint32_t>(3, 1) }
KernelEnum m_KernelType { itk::simple::sitkBall }
bool m_PreserveIntensities { false }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::ClosingByReconstructionImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 161 of file sitkClosingByReconstructionImageFilter.h.
PixelIDTypeList
using itk::simple::ClosingByReconstructionImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 71 of file sitkClosingByReconstructionImageFilter.h.
Self
using itk::simple::ClosingByReconstructionImageFilter::Self = ClosingByReconstructionImageFilter
Definition at line 61 of file sitkClosingByReconstructionImageFilter.h.
Constructor & Destructor Documentation
~ClosingByReconstructionImageFilter()
virtual itk::simple::ClosingByReconstructionImageFilter::~ClosingByReconstructionImageFilter () virtual
Destructor
ClosingByReconstructionImageFilter()
itk::simple::ClosingByReconstructionImageFilter::ClosingByReconstructionImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::ClosingByReconstructionImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::ClosingByReconstructionImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::ClosingByReconstructionImageFilter::FullyConnectedOff () inline
Definition at line 118 of file sitkClosingByReconstructionImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::ClosingByReconstructionImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 116 of file sitkClosingByReconstructionImageFilter.h.
References SetFullyConnected().
GetFullyConnected()
bool itk::simple::ClosingByReconstructionImageFilter::GetFullyConnected () const inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 124 of file sitkClosingByReconstructionImageFilter.h.
References m_FullyConnected.
GetKernelRadius()
std::vector< unsigned int > itk::simple::ClosingByReconstructionImageFilter::GetKernelRadius () const inline
Get the radius of the kernel structuring element.
Definition at line 90 of file sitkClosingByReconstructionImageFilter.h.
References m_KernelRadius.
GetKernelType()
KernelEnum itk::simple::ClosingByReconstructionImageFilter::GetKernelType () const inline
Get the kernel or structuring element used for the morphology.
Definition at line 103 of file sitkClosingByReconstructionImageFilter.h.
References m_KernelType.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::ClosingByReconstructionImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::ClosingByReconstructionImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 149 of file sitkClosingByReconstructionImageFilter.h.
GetPreserveIntensities()
bool itk::simple::ClosingByReconstructionImageFilter::GetPreserveIntensities () const inline
Set/Get whether the original intensities of the image retained for those pixels unaffected by the opening by reconstruction. If Off, the output pixel contrast will be reduced.
Definition at line 145 of file sitkClosingByReconstructionImageFilter.h.
References m_PreserveIntensities.
PreserveIntensitiesOff()
void itk::simple::ClosingByReconstructionImageFilter::PreserveIntensitiesOff () inline
Definition at line 139 of file sitkClosingByReconstructionImageFilter.h.
References SetPreserveIntensities().
PreserveIntensitiesOn()
void itk::simple::ClosingByReconstructionImageFilter::PreserveIntensitiesOn () inline
Set the value of PreserveIntensities to true or false respectfully.
Definition at line 137 of file sitkClosingByReconstructionImageFilter.h.
References SetPreserveIntensities().
SetFullyConnected()
void itk::simple::ClosingByReconstructionImageFilter::SetFullyConnected (bool FullyConnected) inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 111 of file sitkClosingByReconstructionImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetKernelRadius() [1/2]
void itk::simple::ClosingByReconstructionImageFilter::SetKernelRadius (std::vector< unsigned int > KernelRadius) inline
Set the radius of the kernel structuring element.
Definition at line 80 of file sitkClosingByReconstructionImageFilter.h.
References m_KernelRadius.
SetKernelRadius() [2/2]
void itk::simple::ClosingByReconstructionImageFilter::SetKernelRadius (unsigned int value) inline
Set the values of the KernelRadius vector all to value
Definition at line 85 of file sitkClosingByReconstructionImageFilter.h.
References m_KernelRadius.
SetKernelType()
void itk::simple::ClosingByReconstructionImageFilter::SetKernelType (KernelEnum KernelType) inline
Set the kernel or structuring element used for the morphology.
Definition at line 97 of file sitkClosingByReconstructionImageFilter.h.
References m_KernelType.
SetPreserveIntensities()
void itk::simple::ClosingByReconstructionImageFilter::SetPreserveIntensities (bool PreserveIntensities) inline
Set/Get whether the original intensities of the image retained for those pixels unaffected by the opening by reconstruction. If Off, the output pixel contrast will be reduced.
Definition at line 132 of file sitkClosingByReconstructionImageFilter.h.
References m_PreserveIntensities.
Referenced by PreserveIntensitiesOff(), and PreserveIntensitiesOn().
ToString()
std::string itk::simple::ClosingByReconstructionImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 162 of file sitkClosingByReconstructionImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FullyConnected
bool itk::simple::ClosingByReconstructionImageFilter::m_FullyConnected { false } private
Definition at line 171 of file sitkClosingByReconstructionImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_KernelRadius
std::vector<unsigned int> itk::simple::ClosingByReconstructionImageFilter::m_KernelRadius { std::vector<uint32_t>(3, 1) } private
Definition at line 167 of file sitkClosingByReconstructionImageFilter.h.
Referenced by GetKernelRadius(), SetKernelRadius(), and SetKernelRadius().
m_KernelType
KernelEnum itk::simple::ClosingByReconstructionImageFilter::m_KernelType { itk::simple::sitkBall } private
Definition at line 169 of file sitkClosingByReconstructionImageFilter.h.
Referenced by GetKernelType(), and SetKernelType().
m_PreserveIntensities
bool itk::simple::ClosingByReconstructionImageFilter::m_PreserveIntensities { false } private
Definition at line 173 of file sitkClosingByReconstructionImageFilter.h.
Referenced by GetPreserveIntensities(), and SetPreserveIntensities().
The documentation for this class was generated from the following file:
sitkClosingByReconstructionImageFilter.h