SimpleITK: itk::simple::IsolatedWatershedImageFilter Class Reference
itk::simple::IsolatedWatershedImageFilter Class Reference
Isolate watershed basins using two seeds.
#include <sitkIsolatedWatershedImageFilter.h>
Detailed Description
Isolate watershed basins using two seeds.
IsolatedWatershedImageFilter labels pixels with ReplaceValue1 that are in the same watershed basin as Seed1 AND NOT the same as Seed2. The filter adjusts the waterlevel until the two seeds are not in different basins. The user supplies a Watershed threshold. The algorithm uses a binary search to adjust the upper waterlevel, starting at UpperValueLimit. UpperValueLimit defaults to the 1.0.
See also
itk::simple::IsolatedWatershed for the procedural interface
itk::IsolatedWatershedImageFilter for the Doxygen on the original ITK class.
Definition at line 46 of file sitkIsolatedWatershedImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = IsolatedWatershedImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1)
double GetIsolatedValueTolerance () const
std::string GetName () const
uint8_t GetReplaceValue1 () const
uint8_t GetReplaceValue2 () const
std::vector< uint32_t > GetSeed1 () const
std::vector< uint32_t > GetSeed2 () const
double GetThreshold () const
double GetUpperValueLimit () const
IsolatedWatershedImageFilter ()
void SetIsolatedValueTolerance (double IsolatedValueTolerance)
void SetReplaceValue1 (uint8_t ReplaceValue1)
void SetReplaceValue2 (uint8_t ReplaceValue2)
void SetSeed1 (std::vector< uint32_t > Seed1)
void SetSeed2 (std::vector< uint32_t > Seed2)
void SetThreshold (double Threshold)
void SetUpperValueLimit (double UpperValueLimit)
std::string ToString () const
virtual ~IsolatedWatershedImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_IsolatedValueTolerance { 0.001 }
uint8_t m_ReplaceValue1 { 1u }
uint8_t m_ReplaceValue2 { 2u }
std::vector< uint32_t > m_Seed1 { std::vector<uint32_t>(3, 0) }
std::vector< uint32_t > m_Seed2 { std::vector<uint32_t>(3, 0) }
double m_Threshold { 0.0 }
double m_UpperValueLimit { 1.0 }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::IsolatedWatershedImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 168 of file sitkIsolatedWatershedImageFilter.h.
PixelIDTypeList
using itk::simple::IsolatedWatershedImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 58 of file sitkIsolatedWatershedImageFilter.h.
Self
using itk::simple::IsolatedWatershedImageFilter::Self = IsolatedWatershedImageFilter
Definition at line 48 of file sitkIsolatedWatershedImageFilter.h.
Constructor & Destructor Documentation
~IsolatedWatershedImageFilter()
virtual itk::simple::IsolatedWatershedImageFilter::~IsolatedWatershedImageFilter () virtual
Destructor
IsolatedWatershedImageFilter()
itk::simple::IsolatedWatershedImageFilter::IsolatedWatershedImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::IsolatedWatershedImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::IsolatedWatershedImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetIsolatedValueTolerance()
double itk::simple::IsolatedWatershedImageFilter::GetIsolatedValueTolerance () const inline
Set/Get the precision required for the intensity threshold value. The default is .001.
Definition at line 124 of file sitkIsolatedWatershedImageFilter.h.
References m_IsolatedValueTolerance.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::IsolatedWatershedImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::IsolatedWatershedImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 156 of file sitkIsolatedWatershedImageFilter.h.
GetReplaceValue1()
uint8_t itk::simple::IsolatedWatershedImageFilter::GetReplaceValue1 () const inline
Set/Get value to replace Seed1(Seed2) pixels, pixels that are within the basin that contains Seed1(Seed2) this value. The default is 1(0).
Definition at line 138 of file sitkIsolatedWatershedImageFilter.h.
References m_ReplaceValue1.
GetReplaceValue2()
uint8_t itk::simple::IsolatedWatershedImageFilter::GetReplaceValue2 () const inline
Set/Get value to replace Seed1(Seed2) pixels, pixels that are within the basin that contains Seed1(Seed2) this value. The default is 1(0).
Definition at line 152 of file sitkIsolatedWatershedImageFilter.h.
References m_ReplaceValue2.
GetSeed1()
std::vector< uint32_t > itk::simple::IsolatedWatershedImageFilter::GetSeed1 () const inline
Set seed point 1. This seed will be isolated from Seed2 (if possible). All pixels connected to this seed will be replaced with ReplaceValue1.
Definition at line 74 of file sitkIsolatedWatershedImageFilter.h.
References m_Seed1.
GetSeed2()
std::vector< uint32_t > itk::simple::IsolatedWatershedImageFilter::GetSeed2 () const inline
Set seed point 2. This seed will be isolated from Seed1 (if possible). All pixels connected to this seed will be replaced with ReplaceValue2.
Definition at line 88 of file sitkIsolatedWatershedImageFilter.h.
References m_Seed2.
GetThreshold()
double itk::simple::IsolatedWatershedImageFilter::GetThreshold () const inline
Set/Get the Watershed threshold. The default is 0.
Definition at line 100 of file sitkIsolatedWatershedImageFilter.h.
References m_Threshold.
GetUpperValueLimit()
double itk::simple::IsolatedWatershedImageFilter::GetUpperValueLimit () const inline
Set/Get the limit on the upper waterlevel value. The default is 1.0.
Definition at line 112 of file sitkIsolatedWatershedImageFilter.h.
References m_UpperValueLimit.
SetIsolatedValueTolerance()
void itk::simple::IsolatedWatershedImageFilter::SetIsolatedValueTolerance (double IsolatedValueTolerance) inline
Set/Get the precision required for the intensity threshold value. The default is .001.
Definition at line 118 of file sitkIsolatedWatershedImageFilter.h.
References m_IsolatedValueTolerance.
SetReplaceValue1()
void itk::simple::IsolatedWatershedImageFilter::SetReplaceValue1 (uint8_t ReplaceValue1) inline
Set/Get value to replace Seed1(Seed2) pixels, pixels that are within the basin that contains Seed1(Seed2) this value. The default is 1(0).
Definition at line 131 of file sitkIsolatedWatershedImageFilter.h.
References m_ReplaceValue1.
SetReplaceValue2()
void itk::simple::IsolatedWatershedImageFilter::SetReplaceValue2 (uint8_t ReplaceValue2) inline
Set/Get value to replace Seed1(Seed2) pixels, pixels that are within the basin that contains Seed1(Seed2) this value. The default is 1(0).
Definition at line 145 of file sitkIsolatedWatershedImageFilter.h.
References m_ReplaceValue2.
SetSeed1()
void itk::simple::IsolatedWatershedImageFilter::SetSeed1 (std::vector< uint32_t > Seed1) inline
Set seed point 1. This seed will be isolated from Seed2 (if possible). All pixels connected to this seed will be replaced with ReplaceValue1.
Definition at line 67 of file sitkIsolatedWatershedImageFilter.h.
References m_Seed1.
SetSeed2()
void itk::simple::IsolatedWatershedImageFilter::SetSeed2 (std::vector< uint32_t > Seed2) inline
Set seed point 2. This seed will be isolated from Seed1 (if possible). All pixels connected to this seed will be replaced with ReplaceValue2.
Definition at line 81 of file sitkIsolatedWatershedImageFilter.h.
References m_Seed2.
SetThreshold()
void itk::simple::IsolatedWatershedImageFilter::SetThreshold (double Threshold) inline
Set/Get the Watershed threshold. The default is 0.
Definition at line 94 of file sitkIsolatedWatershedImageFilter.h.
References m_Threshold, and itk::simple::Threshold().
SetUpperValueLimit()
void itk::simple::IsolatedWatershedImageFilter::SetUpperValueLimit (double UpperValueLimit) inline
Set/Get the limit on the upper waterlevel value. The default is 1.0.
Definition at line 106 of file sitkIsolatedWatershedImageFilter.h.
References m_UpperValueLimit.
ToString()
std::string itk::simple::IsolatedWatershedImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 169 of file sitkIsolatedWatershedImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_IsolatedValueTolerance
double itk::simple::IsolatedWatershedImageFilter::m_IsolatedValueTolerance { 0.001 } private
Definition at line 182 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetIsolatedValueTolerance(), and SetIsolatedValueTolerance().
m_ReplaceValue1
uint8_t itk::simple::IsolatedWatershedImageFilter::m_ReplaceValue1 { 1u } private
Definition at line 184 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetReplaceValue1(), and SetReplaceValue1().
m_ReplaceValue2
uint8_t itk::simple::IsolatedWatershedImageFilter::m_ReplaceValue2 { 2u } private
Definition at line 186 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetReplaceValue2(), and SetReplaceValue2().
m_Seed1
std::vector<uint32_t> itk::simple::IsolatedWatershedImageFilter::m_Seed1 { std::vector<uint32_t>(3, 0) } private
Definition at line 174 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetSeed1(), and SetSeed1().
m_Seed2
std::vector<uint32_t> itk::simple::IsolatedWatershedImageFilter::m_Seed2 { std::vector<uint32_t>(3, 0) } private
Definition at line 176 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetSeed2(), and SetSeed2().
m_Threshold
double itk::simple::IsolatedWatershedImageFilter::m_Threshold { 0.0 } private
Definition at line 178 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetThreshold(), and SetThreshold().
m_UpperValueLimit
double itk::simple::IsolatedWatershedImageFilter::m_UpperValueLimit { 1.0 } private
Definition at line 180 of file sitkIsolatedWatershedImageFilter.h.
Referenced by GetUpperValueLimit(), and SetUpperValueLimit().
The documentation for this class was generated from the following file:
sitkIsolatedWatershedImageFilter.h