SimpleITK: itk::simple::UnsharpMaskImageFilter Class Reference
itk::simple::UnsharpMaskImageFilter Class Reference
Edge enhancement filter.
#include <sitkUnsharpMaskImageFilter.h>
Detailed Description
Edge enhancement filter.
This filter subtracts a smoothed version of the image from the image to achieve the edge enhancing effect. https://en.wikipedia.org/w/index.php?title=Unsharp_masking&oldid=750486803#Photographic_unsharp_masking
It has configurable amount, radius (sigma) and threshold, and whether to clamp the resulting values to the range of output type.
Formula: sharpened=original+[itk::Math::abs (original-blurred)-threshold]*amount
If clamping is turned off (it is on by default), casting to output pixel format is done using C++ defaults, meaning that values are not clamped but rather wrap around e.g. 260 -> 4 (unsigned char).
See also
ImageToImageFilter
SmoothingRecursiveGaussianImageFilter
RescaleIntensityImageFilter
itk::simple::UnsharpMask for the procedural interface
itk::UnsharpMaskImageFilter for the Doxygen on the original ITK class.
Definition at line 60 of file sitkUnsharpMaskImageFilter.h.
Public Types
using PixelIDTypeList = RealPixelIDTypeList
using Self = UnsharpMaskImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void ClampOff ()
void ClampOn ()
Image Execute (const Image &image1)
double GetAmount () const
bool GetClamp () const
std::string GetName () const
std::vector< double > GetSigmas () const
double GetThreshold () const
void SetAmount (double Amount)
void SetClamp (bool Clamp)
void SetSigmas (double s)
void SetSigmas (std::vector< double > Sigmas)
void SetThreshold (double Threshold)
std::string ToString () const
UnsharpMaskImageFilter ()
virtual ~UnsharpMaskImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_Amount { 0.5 }
bool m_Clamp { true }
std::vector< double > m_Sigmas { std::vector<double>(3, 1.0) }
double m_Threshold { 0.0 }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::UnsharpMaskImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 152 of file sitkUnsharpMaskImageFilter.h.
PixelIDTypeList
using itk::simple::UnsharpMaskImageFilter::PixelIDTypeList = RealPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 72 of file sitkUnsharpMaskImageFilter.h.
Self
using itk::simple::UnsharpMaskImageFilter::Self = UnsharpMaskImageFilter
Definition at line 62 of file sitkUnsharpMaskImageFilter.h.
Constructor & Destructor Documentation
~UnsharpMaskImageFilter()
virtual itk::simple::UnsharpMaskImageFilter::~UnsharpMaskImageFilter () virtual
Destructor
UnsharpMaskImageFilter()
itk::simple::UnsharpMaskImageFilter::UnsharpMaskImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
ClampOff()
void itk::simple::UnsharpMaskImageFilter::ClampOff () inline
Definition at line 131 of file sitkUnsharpMaskImageFilter.h.
References SetClamp().
ClampOn()
void itk::simple::UnsharpMaskImageFilter::ClampOn () inline
Set the value of Clamp to true or false respectfully.
Definition at line 129 of file sitkUnsharpMaskImageFilter.h.
References SetClamp().
Execute()
Image itk::simple::UnsharpMaskImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::UnsharpMaskImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetAmount()
double itk::simple::UnsharpMaskImageFilter::GetAmount () const inline
Set/Get amount of enhancement. Usual range: 0.1 to 2.0. Default: 0.5.
Definition at line 104 of file sitkUnsharpMaskImageFilter.h.
References m_Amount.
GetClamp()
bool itk::simple::UnsharpMaskImageFilter::GetClamp () const inline
Set/Get whether to clamp values to supported range of output type. Default: On.
Definition at line 136 of file sitkUnsharpMaskImageFilter.h.
References m_Clamp.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::UnsharpMaskImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::UnsharpMaskImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 140 of file sitkUnsharpMaskImageFilter.h.
GetSigmas()
std::vector< double > itk::simple::UnsharpMaskImageFilter::GetSigmas () const inline
Set/Get Sigma values measured in the units of image spacing. Default: 1.0.
Definition at line 91 of file sitkUnsharpMaskImageFilter.h.
References m_Sigmas.
GetThreshold()
double itk::simple::UnsharpMaskImageFilter::GetThreshold () const inline
Set/Get threshold for enhancement. Default: 0.
Definition at line 117 of file sitkUnsharpMaskImageFilter.h.
References m_Threshold.
SetAmount()
void itk::simple::UnsharpMaskImageFilter::SetAmount (double Amount) inline
Set/Get amount of enhancement. Usual range: 0.1 to 2.0. Default: 0.5.
Definition at line 98 of file sitkUnsharpMaskImageFilter.h.
References m_Amount.
SetClamp()
void itk::simple::UnsharpMaskImageFilter::SetClamp (bool Clamp) inline
Set/Get whether to clamp values to supported range of output type. Default: On.
Definition at line 124 of file sitkUnsharpMaskImageFilter.h.
References itk::simple::Clamp(), and m_Clamp.
Referenced by ClampOff(), and ClampOn().
SetSigmas() [1/2]
void itk::simple::UnsharpMaskImageFilter::SetSigmas (double s) inline
Custom public declarations
Definition at line 76 of file sitkUnsharpMaskImageFilter.h.
References m_Sigmas.
SetSigmas() [2/2]
void itk::simple::UnsharpMaskImageFilter::SetSigmas (std::vector< double > Sigmas) inline
Set/Get Sigma values measured in the units of image spacing. Default: 1.0.
Definition at line 85 of file sitkUnsharpMaskImageFilter.h.
References m_Sigmas.
SetThreshold()
void itk::simple::UnsharpMaskImageFilter::SetThreshold (double Threshold) inline
Set/Get threshold for enhancement. Default: 0.
Definition at line 111 of file sitkUnsharpMaskImageFilter.h.
References m_Threshold, and itk::simple::Threshold().
ToString()
std::string itk::simple::UnsharpMaskImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 153 of file sitkUnsharpMaskImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Amount
double itk::simple::UnsharpMaskImageFilter::m_Amount { 0.5 } private
Definition at line 160 of file sitkUnsharpMaskImageFilter.h.
Referenced by GetAmount(), and SetAmount().
m_Clamp
bool itk::simple::UnsharpMaskImageFilter::m_Clamp { true } private
Definition at line 164 of file sitkUnsharpMaskImageFilter.h.
Referenced by GetClamp(), and SetClamp().
m_Sigmas
std::vector<double> itk::simple::UnsharpMaskImageFilter::m_Sigmas { std::vector<double>(3, 1.0) } private
Definition at line 158 of file sitkUnsharpMaskImageFilter.h.
Referenced by GetSigmas(), SetSigmas(), and SetSigmas().
m_Threshold
double itk::simple::UnsharpMaskImageFilter::m_Threshold { 0.0 } private
Definition at line 162 of file sitkUnsharpMaskImageFilter.h.
Referenced by GetThreshold(), and SetThreshold().
The documentation for this class was generated from the following file:
sitkUnsharpMaskImageFilter.h