SimpleITK: itk::simple::PowImageFilter Class Reference
itk::simple::PowImageFilter Class Reference
Computes the powers of 2 images.
#include <sitkPowImageFilter.h>
Detailed Description
Computes the powers of 2 images.
This class is templated over the types of the two input images and the type of the output image. Numeric conversions (castings) are done by the C++ defaults.
The output of the pow function will be cast to the pixel type of the output image.
The total operation over one pixel will be
output_pixel = static_cast< TOutput >(std::pow(static_cast<RealType>(A),static_cast<RealType>(B)));
The pow function can be applied to two images with the following:
SetInput1(image1);
SetInput2(image2);
Additionally, this filter can be used to raise every pixel of an image to a power of a constant by using
SetInput1(image1);
SetConstant2(constant);
See also
itk::simple::Pow for the procedural interface
itk::PowImageFilter for the Doxygen on the original ITK class.
Definition at line 71 of file sitkPowImageFilter.h.
Public Types
using PixelIDTypeList = typelist2::append<BasicPixelIDTypeList, ComplexPixelIDTypeList>::type
using Self = PowImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1, const Image &image2)
Image Execute (const Image &image1, double constant)
Image Execute (double constant, const Image &image2)
Image Execute (Image &&image1, const Image &image2)
Image Execute (Image &&image1, double constant)
std::string GetName () const
PowImageFilter ()
std::string ToString () const
virtual ~PowImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunction1Type = Image (Self::*)(double constant, const Image& image2)
using MemberFunction2Type = Image (Self::*)(const Image& image1, double constant)
using MemberFunctionType = Image (Self::*)(const Image &image1, const Image &image2)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1, const Image &image2)
template<class TImageType>
Image ExecuteInternal (const Image &image1, double constant)
template<class TImageType>
Image ExecuteInternal (double constant, const Image &image2)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
static const detail::MemberFunctionFactory< MemberFunction1Type > & GetMemberFunctionFactory1 ()
static const detail::MemberFunctionFactory< MemberFunction2Type > & GetMemberFunctionFactory2 ()
Private Attributes
bool m_InPlace {false}
Friends
struct detail::MemberFunctionAddressor< MemberFunction1Type >
struct detail::MemberFunctionAddressor< MemberFunction2Type >
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunction1Type
using itk::simple::PowImageFilter::MemberFunction1Type = Image (Self::*)(double constant, const Image& image2) private
Definition at line 119 of file sitkPowImageFilter.h.
MemberFunction2Type
using itk::simple::PowImageFilter::MemberFunction2Type = Image (Self::*)(const Image& image1, double constant) private
Definition at line 124 of file sitkPowImageFilter.h.
MemberFunctionType
using itk::simple::PowImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1, const Image &image2) private
Setup for member function dispatching
Definition at line 116 of file sitkPowImageFilter.h.
PixelIDTypeList
using itk::simple::PowImageFilter::PixelIDTypeList = typelist2::append<BasicPixelIDTypeList, ComplexPixelIDTypeList>::type
Define the pixels types supported by this filter
Definition at line 83 of file sitkPowImageFilter.h.
Self
using itk::simple::PowImageFilter::Self = PowImageFilter
Definition at line 73 of file sitkPowImageFilter.h.
Constructor & Destructor Documentation
~PowImageFilter()
virtual itk::simple::PowImageFilter::~PowImageFilter () virtual
Destructor
PowImageFilter()
itk::simple::PowImageFilter::PowImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/5]
Image itk::simple::PowImageFilter::Execute (const Image & image1, const Image & image2)
Execute() [2/5]
Image itk::simple::PowImageFilter::Execute (const Image & image1, double constant)
Execute the filter with an image and a constant
Execute() [3/5]
Image itk::simple::PowImageFilter::Execute (double constant, const Image & image2)
Execute() [4/5]
Image itk::simple::PowImageFilter::Execute (Image && image1, const Image & image2)
Execute the filter on the input images
Execute() [5/5]
Image itk::simple::PowImageFilter::Execute (Image && image1, double constant)
ExecuteInternal() [1/3]
template<class TImageType> Image itk::simple::PowImageFilter::ExecuteInternal (const Image & image1, const Image & image2) private
Referenced by detail::MemberFunctionAddressor< MemberFunction1Type >, and detail::MemberFunctionAddressor< MemberFunction2Type >.
ExecuteInternal() [2/3]
template<class TImageType> Image itk::simple::PowImageFilter::ExecuteInternal (const Image & image1, double constant) private
ExecuteInternal() [3/3]
template<class TImageType> Image itk::simple::PowImageFilter::ExecuteInternal (double constant, const Image & image2) private
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::PowImageFilter::GetMemberFunctionFactory () static private
GetMemberFunctionFactory1()
static const detail::MemberFunctionFactory< MemberFunction1Type > & itk::simple::PowImageFilter::GetMemberFunctionFactory1 () static private
GetMemberFunctionFactory2()
static const detail::MemberFunctionFactory< MemberFunction2Type > & itk::simple::PowImageFilter::GetMemberFunctionFactory2 () static private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetName()
std::string itk::simple::PowImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 89 of file sitkPowImageFilter.h.
ToString()
std::string itk::simple::PowImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunction1Type >
friend struct detail::MemberFunctionAddressor< MemberFunction1Type > friend
Definition at line 120 of file sitkPowImageFilter.h.
References ExecuteInternal().
detail::MemberFunctionAddressor< MemberFunction2Type >
friend struct detail::MemberFunctionAddressor< MemberFunction2Type > friend
Definition at line 125 of file sitkPowImageFilter.h.
References ExecuteInternal().
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 127 of file sitkPowImageFilter.h.
References GetMemberFunctionFactory2().
Member Data Documentation
m_InPlace
bool itk::simple::PowImageFilter::m_InPlace {false} private
Definition at line 139 of file sitkPowImageFilter.h.
The documentation for this class was generated from the following file:
sitkPowImageFilter.h