SimpleITK: itk::simple::LevelSetMotionRegistrationFilter Class Reference
itk::simple::LevelSetMotionRegistrationFilter Class Reference
Deformably register two images using level set motion.
#include <sitkLevelSetMotionRegistrationFilter.h>
Detailed Description
Deformably register two images using level set motion.
LevelSetMotionFilter implements a deformable registration algorithm that aligns a fixed and a moving image under level set motion. The equations of motion are similar to those of the DemonsRegistrationFilter . The main differences are: (1) Gradients of the moving image are calculated on a smoothed image while intensity difference are measured on the original images (2) Magnitude of the motion vector is a function of the differences in intensity between the fixed and moving pixel. An adaptive timestep is calculated based on the maximum motion vector over the entire field to ensure stability. The timestep also implicitly converts the motion vector measured in units of intensity to a vector measured in physical units. Demons, on the other hand, defines its motion vectors as function of both the intensity differences and gradient magnitude at each respective pixel. Consider two separate pixels with the same intensity differences between the corresponding fixed and moving pixel pairs. In demons, the motion vector of the pixel over a low gradient region will be larger than the motion vector of the pixel over a large gradient region. This leads to an unstable vector field. In the levelset approach, the motion vectors will be proportional to the gradients, scaled by the maximum gradient over the entire field. The pixel with at the lower gradient position will more less than the pixel at the higher gradient position. (3) Gradients are calculated using minmod finite difference instead of using central differences.
A deformation field is represented as a image whose pixel type is some vector type with at least N elements, where N is the dimension of the fixed image. The vector type must support element access via operator []. It is assumed that the vector elements behave like floating point scalars.
This class is templated over the fixed image type, moving image type and the deformation field type.
The input fixed and moving images are set via methods SetFixedImage and SetMovingImage respectively. An initial deformation field maybe set via SetInitialDisplacementField or SetInput. If no initial field is set, a zero field is used as the initial condition.
The algorithm has one parameters: the number of iteration to be performed.
The output deformation field can be obtained via methods GetOutput or GetDisplacementField.
This class make use of the finite difference solver hierarchy. Update for each iteration is computed in LevelSetMotionFunction.
Warning
This filter assumes that the fixed image type, moving image type and deformation field type all have the same number of dimensions.
Ref: B.C. Vemuri, J. Ye, Y. Chen, C.M. Leonard. "Image registration via level-set motion: applications to atlas-based segmentation". Medical Image Analysis. Vol. 7. pp. 1-20. 2003.
See also
LevelSetMotionRegistrationFunction
DemonsRegistrationFilter
itk::LevelSetMotionRegistrationFilter for the Doxygen on the original ITK class.
Definition at line 85 of file sitkLevelSetMotionRegistrationFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = LevelSetMotionRegistrationFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &fixedImage, const Image &movingImage)
Image Execute (const Image &fixedImage, const Image &movingImage, const Image &initialDisplacementField)
double GetAlpha () const
uint32_t GetElapsedIterations () const
Number of iterations run.
double GetGradientMagnitudeThreshold () const
double GetGradientSmoothingStandardDeviations () const
double GetIntensityDifferenceThreshold () const
double GetMaximumError () const
unsigned int GetMaximumKernelWidth () const
double GetMaximumRMSError () const
double GetMetric () const
std::string GetName () const
uint32_t GetNumberOfIterations () const
double GetRMSChange () const
The Root Mean Square of the levelset upon termination.
bool GetSmoothDisplacementField () const
bool GetSmoothUpdateField () const
std::vector< double > GetStandardDeviations () const
std::vector< double > GetUpdateFieldStandardDeviations () const
bool GetUseImageSpacing () const
LevelSetMotionRegistrationFilter ()
void SetAlpha (double Alpha)
void SetGradientMagnitudeThreshold (double GradientMagnitudeThreshold)
void SetGradientSmoothingStandardDeviations (double GradientSmoothingStandardDeviations)
void SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold)
void SetMaximumError (double MaximumError)
void SetMaximumKernelWidth (unsigned int MaximumKernelWidth)
void SetMaximumRMSError (double MaximumRMSError)
void SetNumberOfIterations (uint32_t NumberOfIterations)
void SetSmoothDisplacementField (bool SmoothDisplacementField)
void SetSmoothUpdateField (bool SmoothUpdateField)
void SetStandardDeviations (double value)
void SetStandardDeviations (std::vector< double > StandardDeviations)
void SetUpdateFieldStandardDeviations (double value)
void SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations)
void SetUseImageSpacing (bool UseImageSpacing)
void SmoothDisplacementFieldOff ()
void SmoothDisplacementFieldOn ()
void SmoothUpdateFieldOff ()
void SmoothUpdateFieldOn ()
std::string ToString () const
void UseImageSpacingOff ()
void UseImageSpacingOn ()
virtual ~LevelSetMotionRegistrationFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *fixedImage, const Image *movingImage, const Image *initialDisplacementField)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_Alpha { 0.1 }
uint32_t m_ElapsedIterations { 0 }
double m_GradientMagnitudeThreshold { 1e-9 }
double m_GradientSmoothingStandardDeviations { 1.0 }
double m_IntensityDifferenceThreshold { 0.001 }
double m_MaximumError { 0.1 }
unsigned int m_MaximumKernelWidth { 30u }
double m_MaximumRMSError { 0.02 }
double m_Metric { 0.0 }
uint32_t m_NumberOfIterations { 10u }
double m_RMSChange { 0.0 }
bool m_SmoothDisplacementField { false }
bool m_SmoothUpdateField { false }
std::vector< double > m_StandardDeviations { std::vector<double>(3, 1.0) }
std::vector< double > m_UpdateFieldStandardDeviations { std::vector<double>(3, 1.0) }
bool m_UseImageSpacing { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::LevelSetMotionRegistrationFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    fixedImage, const Image *
    movingImage, const Image *
    initialDisplacementField)
Setup for member function dispatching
Definition at line 332 of file sitkLevelSetMotionRegistrationFilter.h.
PixelIDTypeList
using itk::simple::LevelSetMotionRegistrationFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 97 of file sitkLevelSetMotionRegistrationFilter.h.
Self
using itk::simple::LevelSetMotionRegistrationFilter::Self = LevelSetMotionRegistrationFilter
Definition at line 87 of file sitkLevelSetMotionRegistrationFilter.h.
Constructor & Destructor Documentation
~LevelSetMotionRegistrationFilter()
virtual itk::simple::LevelSetMotionRegistrationFilter::~LevelSetMotionRegistrationFilter () virtual
Destructor
LevelSetMotionRegistrationFilter()
itk::simple::LevelSetMotionRegistrationFilter::LevelSetMotionRegistrationFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/2]
Image itk::simple::LevelSetMotionRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage)
Execute() [2/2]
Image itk::simple::LevelSetMotionRegistrationFilter::Execute (const Image & fixedImage, const Image & movingImage, const Image & initialDisplacementField)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::LevelSetMotionRegistrationFilter::ExecuteInternal (const Image * fixedImage, const Image * movingImage, const Image * initialDisplacementField) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetAlpha()
double itk::simple::LevelSetMotionRegistrationFilter::GetAlpha () const inline
Definition at line 253 of file sitkLevelSetMotionRegistrationFilter.h.
References m_Alpha.
GetElapsedIterations()
uint32_t itk::simple::LevelSetMotionRegistrationFilter::GetElapsedIterations () const inline
Number of iterations run.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 301 of file sitkLevelSetMotionRegistrationFilter.h.
References m_ElapsedIterations.
GetGradientMagnitudeThreshold()
double itk::simple::LevelSetMotionRegistrationFilter::GetGradientMagnitudeThreshold () const inline
Definition at line 277 of file sitkLevelSetMotionRegistrationFilter.h.
References m_GradientMagnitudeThreshold.
GetGradientSmoothingStandardDeviations()
double itk::simple::LevelSetMotionRegistrationFilter::GetGradientSmoothingStandardDeviations () const inline
Definition at line 116 of file sitkLevelSetMotionRegistrationFilter.h.
References m_GradientSmoothingStandardDeviations.
GetIntensityDifferenceThreshold()
double itk::simple::LevelSetMotionRegistrationFilter::GetIntensityDifferenceThreshold () const inline
Definition at line 266 of file sitkLevelSetMotionRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
GetMaximumError()
double itk::simple::LevelSetMotionRegistrationFilter::GetMaximumError () const inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 240 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumError.
GetMaximumKernelWidth()
unsigned int itk::simple::LevelSetMotionRegistrationFilter::GetMaximumKernelWidth () const inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 228 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumKernelWidth.
GetMaximumRMSError()
double itk::simple::LevelSetMotionRegistrationFilter::GetMaximumRMSError () const inline
Definition at line 136 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumRMSError.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::LevelSetMotionRegistrationFilter::GetMemberFunctionFactory () static private
GetMetric()
double itk::simple::LevelSetMotionRegistrationFilter::GetMetric () const inline
Get the metric value. The metric value is the mean square difference in intensity between the fixed image and transforming moving image computed over the overlapping region between the two images. This is value is only available for the previous iteration and NOT the current iteration.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 316 of file sitkLevelSetMotionRegistrationFilter.h.
References m_Metric.
GetName()
std::string itk::simple::LevelSetMotionRegistrationFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 319 of file sitkLevelSetMotionRegistrationFilter.h.
GetNumberOfIterations()
uint32_t itk::simple::LevelSetMotionRegistrationFilter::GetNumberOfIterations () const inline
Definition at line 126 of file sitkLevelSetMotionRegistrationFilter.h.
References m_NumberOfIterations.
GetRMSChange()
double itk::simple::LevelSetMotionRegistrationFilter::GetRMSChange () const inline
The Root Mean Square of the levelset upon termination.
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 308 of file sitkLevelSetMotionRegistrationFilter.h.
References m_RMSChange.
GetSmoothDisplacementField()
bool itk::simple::LevelSetMotionRegistrationFilter::GetSmoothDisplacementField () const inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 176 of file sitkLevelSetMotionRegistrationFilter.h.
References m_SmoothDisplacementField.
GetSmoothUpdateField()
bool itk::simple::LevelSetMotionRegistrationFilter::GetSmoothUpdateField () const inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 216 of file sitkLevelSetMotionRegistrationFilter.h.
References m_SmoothUpdateField.
GetStandardDeviations()
std::vector< double > itk::simple::LevelSetMotionRegistrationFilter::GetStandardDeviations () const inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 154 of file sitkLevelSetMotionRegistrationFilter.h.
References m_StandardDeviations.
GetUpdateFieldStandardDeviations()
std::vector< double > itk::simple::LevelSetMotionRegistrationFilter::GetUpdateFieldStandardDeviations () const inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 194 of file sitkLevelSetMotionRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
GetUseImageSpacing()
bool itk::simple::LevelSetMotionRegistrationFilter::GetUseImageSpacing () const inline
Definition at line 293 of file sitkLevelSetMotionRegistrationFilter.h.
References m_UseImageSpacing.
SetAlpha()
void itk::simple::LevelSetMotionRegistrationFilter::SetAlpha (double Alpha) inline
Set/Get the parameter alpha. Alpha is added to the calculated gradient magnitude prior to normalizing the gradient to protect against numerical instability as the gradient magnitude approaches zero. This should be set as a small fraction of the intensity dynamic range, for instance 0.04%. Default is the absolute (not percentage) value of 0.1.
Definition at line 248 of file sitkLevelSetMotionRegistrationFilter.h.
References m_Alpha.
SetGradientMagnitudeThreshold()
void itk::simple::LevelSetMotionRegistrationFilter::SetGradientMagnitudeThreshold (double GradientMagnitudeThreshold) inline
Set/Get the threshold below which the gradient magnitude is considered the zero vector. Default is 1e-9.
Definition at line 272 of file sitkLevelSetMotionRegistrationFilter.h.
References m_GradientMagnitudeThreshold.
SetGradientSmoothingStandardDeviations()
void itk::simple::LevelSetMotionRegistrationFilter::SetGradientSmoothingStandardDeviations (double GradientSmoothingStandardDeviations) inline
Set/Get the standard deviation used for smoothing the moving image prior to calculating gradients. The standard deviation is measured in physical units (for instance mm). Note that this smoothing value is not to be confused with the PDEDeformableRegistrationFilter::SetStandardDeviations() method. The method in PDEDeformableRegistrationFilter is for setting the smoothing parameters for regularizing the deformation field between iterations. Those smoothing parameters are set in pixel units not physical units. Deformation field smoothing is not done by default in LevelSetMotionRegistration. This smoothing parameter is to condition the gradient calculation and parameter is specified in physical units.
Definition at line 111 of file sitkLevelSetMotionRegistrationFilter.h.
References m_GradientSmoothingStandardDeviations.
SetIntensityDifferenceThreshold()
void itk::simple::LevelSetMotionRegistrationFilter::SetIntensityDifferenceThreshold (double IntensityDifferenceThreshold) inline
Set/Get the threshold below which the absolute difference of intensity yields a match. When the intensities match between a moving and fixed image pixel, the update vector (for that iteration) will be the zero vector. Default is 0.001.
Definition at line 261 of file sitkLevelSetMotionRegistrationFilter.h.
References m_IntensityDifferenceThreshold.
SetMaximumError()
void itk::simple::LevelSetMotionRegistrationFilter::SetMaximumError (double MaximumError) inline
Set/Get the desired maximum error of the Guassian kernel approximate.
Definition at line 234 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumError.
SetMaximumKernelWidth()
void itk::simple::LevelSetMotionRegistrationFilter::SetMaximumKernelWidth (unsigned int MaximumKernelWidth) inline
Set/Get the desired limits of the Gaussian kernel width.
Definition at line 222 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumKernelWidth.
SetMaximumRMSError()
void itk::simple::LevelSetMotionRegistrationFilter::SetMaximumRMSError (double MaximumRMSError) inline
Definition at line 131 of file sitkLevelSetMotionRegistrationFilter.h.
References m_MaximumRMSError.
SetNumberOfIterations()
void itk::simple::LevelSetMotionRegistrationFilter::SetNumberOfIterations (uint32_t NumberOfIterations) inline
Definition at line 121 of file sitkLevelSetMotionRegistrationFilter.h.
References m_NumberOfIterations.
SetSmoothDisplacementField()
void itk::simple::LevelSetMotionRegistrationFilter::SetSmoothDisplacementField (bool SmoothDisplacementField) inline
Set/Get whether the displacement field is smoothed (regularized). Smoothing the displacement yields a solution elastic in nature. If SmoothDisplacementField is on, then the displacement field is smoothed with a Gaussian whose standard deviations are specified with SetStandardDeviations()
Definition at line 162 of file sitkLevelSetMotionRegistrationFilter.h.
References m_SmoothDisplacementField.
Referenced by SmoothDisplacementFieldOff(), and SmoothDisplacementFieldOn().
SetSmoothUpdateField()
void itk::simple::LevelSetMotionRegistrationFilter::SetSmoothUpdateField (bool SmoothUpdateField) inline
Set/Get whether the update field is smoothed (regularized). Smoothing the update field yields a solution viscous in nature. If SmoothUpdateField is on, then the update field is smoothed with a Gaussian whose standard deviations are specified with SetUpdateFieldStandardDeviations()
Definition at line 202 of file sitkLevelSetMotionRegistrationFilter.h.
References m_SmoothUpdateField.
Referenced by SmoothUpdateFieldOff(), and SmoothUpdateFieldOn().
SetStandardDeviations() [1/2]
void itk::simple::LevelSetMotionRegistrationFilter::SetStandardDeviations (double value) inline
Set the values of the StandardDeviations vector all to value
Definition at line 148 of file sitkLevelSetMotionRegistrationFilter.h.
References m_StandardDeviations.
SetStandardDeviations() [2/2]
void itk::simple::LevelSetMotionRegistrationFilter::SetStandardDeviations (std::vector< double > StandardDeviations) inline
Set/Get the Gaussian smoothing standard deviations for the displacement field. The values are set with respect to pixel coordinates.
Definition at line 143 of file sitkLevelSetMotionRegistrationFilter.h.
References m_StandardDeviations.
SetUpdateFieldStandardDeviations() [1/2]
void itk::simple::LevelSetMotionRegistrationFilter::SetUpdateFieldStandardDeviations (double value) inline
Set the values of the UpdateFieldStandardDeviations vector all to value
Definition at line 188 of file sitkLevelSetMotionRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUpdateFieldStandardDeviations() [2/2]
void itk::simple::LevelSetMotionRegistrationFilter::SetUpdateFieldStandardDeviations (std::vector< double > UpdateFieldStandardDeviations) inline
Set the Gaussian smoothing standard deviations for the update field. The values are set with respect to pixel coordinates.
Definition at line 183 of file sitkLevelSetMotionRegistrationFilter.h.
References m_UpdateFieldStandardDeviations.
SetUseImageSpacing()
void itk::simple::LevelSetMotionRegistrationFilter::SetUseImageSpacing (bool UseImageSpacing) inline
Definition at line 282 of file sitkLevelSetMotionRegistrationFilter.h.
References m_UseImageSpacing.
Referenced by UseImageSpacingOff(), and UseImageSpacingOn().
SmoothDisplacementFieldOff()
void itk::simple::LevelSetMotionRegistrationFilter::SmoothDisplacementFieldOff () inline
Definition at line 169 of file sitkLevelSetMotionRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothDisplacementFieldOn()
void itk::simple::LevelSetMotionRegistrationFilter::SmoothDisplacementFieldOn () inline
Set the value of SmoothDisplacementField to true or false respectfully.
Definition at line 167 of file sitkLevelSetMotionRegistrationFilter.h.
References SetSmoothDisplacementField().
SmoothUpdateFieldOff()
void itk::simple::LevelSetMotionRegistrationFilter::SmoothUpdateFieldOff () inline
Definition at line 209 of file sitkLevelSetMotionRegistrationFilter.h.
References SetSmoothUpdateField().
SmoothUpdateFieldOn()
void itk::simple::LevelSetMotionRegistrationFilter::SmoothUpdateFieldOn () inline
Set the value of SmoothUpdateField to true or false respectfully.
Definition at line 207 of file sitkLevelSetMotionRegistrationFilter.h.
References SetSmoothUpdateField().
ToString()
std::string itk::simple::LevelSetMotionRegistrationFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseImageSpacingOff()
void itk::simple::LevelSetMotionRegistrationFilter::UseImageSpacingOff () inline
Definition at line 289 of file sitkLevelSetMotionRegistrationFilter.h.
References SetUseImageSpacing().
UseImageSpacingOn()
void itk::simple::LevelSetMotionRegistrationFilter::UseImageSpacingOn () inline
Set the value of UseImageSpacing to true or false respectfully.
Definition at line 287 of file sitkLevelSetMotionRegistrationFilter.h.
References SetUseImageSpacing().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 336 of file sitkLevelSetMotionRegistrationFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Alpha
double itk::simple::LevelSetMotionRegistrationFilter::m_Alpha { 0.1 } private
Definition at line 364 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetAlpha(), and SetAlpha().
m_ElapsedIterations
uint32_t itk::simple::LevelSetMotionRegistrationFilter::m_ElapsedIterations { 0 } private
Definition at line 374 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetElapsedIterations().
m_GradientMagnitudeThreshold
double itk::simple::LevelSetMotionRegistrationFilter::m_GradientMagnitudeThreshold { 1e-9 } private
Definition at line 368 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetGradientMagnitudeThreshold(), and SetGradientMagnitudeThreshold().
m_GradientSmoothingStandardDeviations
double itk::simple::LevelSetMotionRegistrationFilter::m_GradientSmoothingStandardDeviations { 1.0 } private
Definition at line 344 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetGradientSmoothingStandardDeviations(), and SetGradientSmoothingStandardDeviations().
m_IntensityDifferenceThreshold
double itk::simple::LevelSetMotionRegistrationFilter::m_IntensityDifferenceThreshold { 0.001 } private
Definition at line 366 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetIntensityDifferenceThreshold(), and SetIntensityDifferenceThreshold().
m_MaximumError
double itk::simple::LevelSetMotionRegistrationFilter::m_MaximumError { 0.1 } private
Definition at line 362 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetMaximumError(), and SetMaximumError().
m_MaximumKernelWidth
unsigned int itk::simple::LevelSetMotionRegistrationFilter::m_MaximumKernelWidth { 30u } private
Definition at line 360 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetMaximumKernelWidth(), and SetMaximumKernelWidth().
m_MaximumRMSError
double itk::simple::LevelSetMotionRegistrationFilter::m_MaximumRMSError { 0.02 } private
Definition at line 350 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetMaximumRMSError(), and SetMaximumRMSError().
m_Metric
double itk::simple::LevelSetMotionRegistrationFilter::m_Metric { 0.0 } private
Definition at line 376 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetMetric().
m_NumberOfIterations
uint32_t itk::simple::LevelSetMotionRegistrationFilter::m_NumberOfIterations { 10u } private
Definition at line 347 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetNumberOfIterations(), and SetNumberOfIterations().
m_RMSChange
double itk::simple::LevelSetMotionRegistrationFilter::m_RMSChange { 0.0 } private
Definition at line 375 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetRMSChange().
m_SmoothDisplacementField
bool itk::simple::LevelSetMotionRegistrationFilter::m_SmoothDisplacementField { false } private
Definition at line 354 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetSmoothDisplacementField(), and SetSmoothDisplacementField().
m_SmoothUpdateField
bool itk::simple::LevelSetMotionRegistrationFilter::m_SmoothUpdateField { false } private
Definition at line 358 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetSmoothUpdateField(), and SetSmoothUpdateField().
m_StandardDeviations
std::vector<double> itk::simple::LevelSetMotionRegistrationFilter::m_StandardDeviations { std::vector<double>(3, 1.0) } private
Definition at line 352 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetStandardDeviations(), SetStandardDeviations(), and SetStandardDeviations().
m_UpdateFieldStandardDeviations
std::vector<double> itk::simple::LevelSetMotionRegistrationFilter::m_UpdateFieldStandardDeviations { std::vector<double>(3, 1.0) } private
Definition at line 356 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetUpdateFieldStandardDeviations(), SetUpdateFieldStandardDeviations(), and SetUpdateFieldStandardDeviations().
m_UseImageSpacing
bool itk::simple::LevelSetMotionRegistrationFilter::m_UseImageSpacing { true } private
Definition at line 370 of file sitkLevelSetMotionRegistrationFilter.h.
Referenced by GetUseImageSpacing(), and SetUseImageSpacing().
The documentation for this class was generated from the following file:
sitkLevelSetMotionRegistrationFilter.h