SimpleITK: itk::simple::GrayscaleGeodesicErodeImageFilter Class Reference
itk::simple::GrayscaleGeodesicErodeImageFilter Class Reference
geodesic gray scale erosion of an image
#include <sitkGrayscaleGeodesicErodeImageFilter.h>
Detailed Description
geodesic gray scale erosion of an image
Geodesic erosion operates on a "marker" image and a "mask" image. The marker image is eroded using an elementary structuring element (neighborhood of radius one using only the face connected neighbors). The resulting image is then compared with the mask image. The output image is the pixelwise maximum of the eroded marker image and the mask image.
Geodesic erosion is run either one iteration or until convergence. In the convergence case, the filter is equivalent to "reconstruction by erosion". This filter is implemented to handle both scenarios. The one iteration case is multi-threaded. The convergence case is delegated to another instance of the same filter (but configured to run a single iteration).
The marker image must be greater than or equal to the mask image (on a pixel by pixel basis).
Geodesic morphology is described in Chapter 6 of Pierre Soille's book "Morphological Image Analysis: Principles and Applications", Second Edition, Springer, 2003.
A noniterative version of this algorithm can be found in the ReconstructionByErosionImageFilter . This noniterative solution is much faster than the implementation provided here. All ITK filters that previously used GrayscaleGeodesicErodeImageFilter as part of their implementation have been converted to use the ReconstructionByErosionImageFilter . The GrayscaleGeodesicErodeImageFilter is maintained for backward compatibility.
See also
MorphologyImageFilter , GrayscaleErodeImageFilter , GrayscaleFunctionErodeImageFilter , BinaryErodeImageFilter , ReconstructionByErosionImageFilter
itk::simple::GrayscaleGeodesicErode for the procedural interface
itk::GrayscaleGeodesicErodeImageFilter for the Doxygen on the original ITK class.
Definition at line 51 of file sitkGrayscaleGeodesicErodeImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = GrayscaleGeodesicErodeImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1, const Image &image2)
void FullyConnectedOff ()
void FullyConnectedOn ()
bool GetFullyConnected () const
std::string GetName () const
bool GetRunOneIteration () const
GrayscaleGeodesicErodeImageFilter ()
void RunOneIterationOff ()
void RunOneIterationOn ()
void SetFullyConnected (bool FullyConnected)
void SetRunOneIteration (bool RunOneIteration)
std::string ToString () const
virtual ~GrayscaleGeodesicErodeImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image& image1, const Image& image2)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1, const Image &image2)
Private Attributes
bool m_FullyConnected {false}
std::unique_ptr< detail::MemberFunctionFactory< MemberFunctionType > > m_MemberFactory
bool m_RunOneIteration {false}
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::GrayscaleGeodesicErodeImageFilter::MemberFunctionType = Image (Self::*)(const Image& image1, const Image& image2) private
Setup for member function dispatching
Definition at line 109 of file sitkGrayscaleGeodesicErodeImageFilter.h.
PixelIDTypeList
using itk::simple::GrayscaleGeodesicErodeImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 63 of file sitkGrayscaleGeodesicErodeImageFilter.h.
Self
using itk::simple::GrayscaleGeodesicErodeImageFilter::Self = GrayscaleGeodesicErodeImageFilter
Definition at line 53 of file sitkGrayscaleGeodesicErodeImageFilter.h.
Constructor & Destructor Documentation
~GrayscaleGeodesicErodeImageFilter()
virtual itk::simple::GrayscaleGeodesicErodeImageFilter::~GrayscaleGeodesicErodeImageFilter () virtual
Destructor
GrayscaleGeodesicErodeImageFilter()
itk::simple::GrayscaleGeodesicErodeImageFilter::GrayscaleGeodesicErodeImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::GrayscaleGeodesicErodeImageFilter::Execute (const Image & image1, const Image & image2)
Execute the filter on the input images
ExecuteInternal()
template<class TImageType> Image itk::simple::GrayscaleGeodesicErodeImageFilter::ExecuteInternal (const Image & image1, const Image & image2) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::GrayscaleGeodesicErodeImageFilter::FullyConnectedOff () inline
Definition at line 87 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::GrayscaleGeodesicErodeImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 86 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References SetFullyConnected().
GetFullyConnected()
bool itk::simple::GrayscaleGeodesicErodeImageFilter::GetFullyConnected () const inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 92 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References m_FullyConnected.
GetName()
std::string itk::simple::GrayscaleGeodesicErodeImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 95 of file sitkGrayscaleGeodesicErodeImageFilter.h.
GetRunOneIteration()
bool itk::simple::GrayscaleGeodesicErodeImageFilter::GetRunOneIteration () const inline
Set/Get whether the filter should run one iteration or until convergence. When run to convergence, this filter is equivalent to "reconstruction by erosion". Default is off.
Definition at line 78 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References m_RunOneIteration.
RunOneIterationOff()
void itk::simple::GrayscaleGeodesicErodeImageFilter::RunOneIterationOff () inline
Definition at line 73 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References SetRunOneIteration().
RunOneIterationOn()
void itk::simple::GrayscaleGeodesicErodeImageFilter::RunOneIterationOn () inline
Set the value of RunOneIteration to true or false respectfully.
Definition at line 72 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References SetRunOneIteration().
SetFullyConnected()
void itk::simple::GrayscaleGeodesicErodeImageFilter::SetFullyConnected (bool FullyConnected) inline
Set/Get whether the connected components are defined strictly by face connectivity or by face+edge+vertex connectivity. Default is FullyConnectedOff. For objects that are 1 pixel wide, use FullyConnectedOn.
Definition at line 83 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetRunOneIteration()
void itk::simple::GrayscaleGeodesicErodeImageFilter::SetRunOneIteration (bool RunOneIteration) inline
Set/Get whether the filter should run one iteration or until convergence. When run to convergence, this filter is equivalent to "reconstruction by erosion". Default is off.
Definition at line 69 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References m_RunOneIteration.
Referenced by RunOneIterationOff(), and RunOneIterationOn().
ToString()
std::string itk::simple::GrayscaleGeodesicErodeImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 110 of file sitkGrayscaleGeodesicErodeImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FullyConnected
bool itk::simple::GrayscaleGeodesicErodeImageFilter::m_FullyConnected {false} private
Definition at line 122 of file sitkGrayscaleGeodesicErodeImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_MemberFactory
std::unique_ptr<detail::MemberFunctionFactory<MemberFunctionType> > itk::simple::GrayscaleGeodesicErodeImageFilter::m_MemberFactory private
Definition at line 115 of file sitkGrayscaleGeodesicErodeImageFilter.h.
m_RunOneIteration
bool itk::simple::GrayscaleGeodesicErodeImageFilter::m_RunOneIteration {false} private
Definition at line 119 of file sitkGrayscaleGeodesicErodeImageFilter.h.
Referenced by GetRunOneIteration(), and SetRunOneIteration().
The documentation for this class was generated from the following file:
sitkGrayscaleGeodesicErodeImageFilter.h