SimpleITK: itk::simple::Similarity2DTransform Class Reference
itk::simple::Similarity2DTransform Class Reference
A similarity 2D transform with rotation in radians and isotropic scaling around a fixed center with translation.
#include <sitkSimilarity2DTransform.h>
Detailed Description
A similarity 2D transform with rotation in radians and isotropic scaling around a fixed center with translation.
See also
itk::Similarity2DTransform
Definition at line 33 of file sitkSimilarity2DTransform.h.
Public Types
using Self = Similarity2DTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
double GetAngle () const
std::vector< double > GetCenter () const
std::vector< double > GetMatrix () const
std::string GetName () const override
double GetScale () const
std::vector< double > GetTranslation () const
Similarity2DTransform & operator= (const Similarity2DTransform &)
Self & SetAngle (double angle)
Self & SetCenter (const std::vector< double > &params)
Self & SetMatrix (const std::vector< double > &matrix, double tolerance=1e-10)
Self & SetScale (double scale)
Self & SetTranslation (const std::vector< double > &translation)
Similarity2DTransform ()
Similarity2DTransform (const Similarity2DTransform &)
Similarity2DTransform (const Transform &)
Similarity2DTransform (double scaleFactor, double angle=0.0, const std::vector< double > &translation=std::vector< double >(2, 0.0), const std::vector< double > &fixedCenter=std::vector< double >(2, 0.0))
~Similarity2DTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< double()> m_pfGetAngle
std::function< std::vector< double >()> m_pfGetCenter
std::function< std::vector< double >()> m_pfGetMatrix
std::function< double()> m_pfGetScale
std::function< std::vector< double >()> m_pfGetTranslation
std::function< void(double)> m_pfSetAngle
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(const std::vector< double > &, double)> m_pfSetMatrix
std::function< void(double)> m_pfSetScale
std::function< void(const std::vector< double > &)> m_pfSetTranslation
Member Typedef Documentation
Self
using itk::simple::Similarity2DTransform::Self = Similarity2DTransform
Definition at line 36 of file sitkSimilarity2DTransform.h.
Superclass
using itk::simple::Similarity2DTransform::Superclass = Transform
Definition at line 37 of file sitkSimilarity2DTransform.h.
Constructor & Destructor Documentation
~Similarity2DTransform()
itk::simple::Similarity2DTransform::~Similarity2DTransform () override
Similarity2DTransform() [1/4]
itk::simple::Similarity2DTransform::Similarity2DTransform ()
Referenced by operator=(), Similarity2DTransform(), and Similarity2DTransform().
Similarity2DTransform() [2/4]
itk::simple::Similarity2DTransform::Similarity2DTransform (double scaleFactor, double angle = 0.0, const std::vector< double > & translation = std::vector< double >(2, 0.0), const std::vector< double > & fixedCenter = std::vector< double >(2, 0.0)) explicit
Similarity2DTransform() [3/4]
itk::simple::Similarity2DTransform::Similarity2DTransform (const Similarity2DTransform &)
References Similarity2DTransform().
Similarity2DTransform() [4/4]
itk::simple::Similarity2DTransform::Similarity2DTransform (const Transform &) explicit
References Similarity2DTransform(), and itk::simple::Transform::Transform().
Member Function Documentation
GetAngle()
double itk::simple::Similarity2DTransform::GetAngle () const
GetCenter()
std::vector< double > itk::simple::Similarity2DTransform::GetCenter () const
GetMatrix()
std::vector< double > itk::simple::Similarity2DTransform::GetMatrix () const
additional methods
GetName()
std::string itk::simple::Similarity2DTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 58 of file sitkSimilarity2DTransform.h.
GetScale()
double itk::simple::Similarity2DTransform::GetScale () const
GetTranslation()
std::vector< double > itk::simple::Similarity2DTransform::GetTranslation () const
InternalInitialization() [1/2]
void itk::simple::Similarity2DTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::Similarity2DTransform::InternalInitialization (TransformType * transform) private
operator=()
Similarity2DTransform & itk::simple::Similarity2DTransform::operator= (const Similarity2DTransform &)
References Similarity2DTransform().
SetAngle()
Self & itk::simple::Similarity2DTransform::SetAngle (double angle)
parameter
SetCenter()
Self & itk::simple::Similarity2DTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetMatrix()
Self & itk::simple::Similarity2DTransform::SetMatrix (const std::vector< double > & matrix, double tolerance = 1e-10)
SetPimpleTransform()
void itk::simple::Similarity2DTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetScale()
Self & itk::simple::Similarity2DTransform::SetScale (double scale)
SetTranslation()
Self & itk::simple::Similarity2DTransform::SetTranslation (const std::vector< double > & translation)
Member Data Documentation
m_pfGetAngle
std::function<double()> itk::simple::Similarity2DTransform::m_pfGetAngle private
Definition at line 106 of file sitkSimilarity2DTransform.h.
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::Similarity2DTransform::m_pfGetCenter private
Definition at line 104 of file sitkSimilarity2DTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::Similarity2DTransform::m_pfGetMatrix private
Definition at line 111 of file sitkSimilarity2DTransform.h.
m_pfGetScale
std::function<double()> itk::simple::Similarity2DTransform::m_pfGetScale private
Definition at line 110 of file sitkSimilarity2DTransform.h.
m_pfGetTranslation
std::function<std::vector<double>()> itk::simple::Similarity2DTransform::m_pfGetTranslation private
Definition at line 108 of file sitkSimilarity2DTransform.h.
m_pfSetAngle
std::function<void(double)> itk::simple::Similarity2DTransform::m_pfSetAngle private
Definition at line 105 of file sitkSimilarity2DTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::Similarity2DTransform::m_pfSetCenter private
Definition at line 103 of file sitkSimilarity2DTransform.h.
m_pfSetMatrix
std::function<void(const std::vector<double> &, double)> itk::simple::Similarity2DTransform::m_pfSetMatrix private
Definition at line 112 of file sitkSimilarity2DTransform.h.
m_pfSetScale
std::function<void(double)> itk::simple::Similarity2DTransform::m_pfSetScale private
Definition at line 109 of file sitkSimilarity2DTransform.h.
m_pfSetTranslation
std::function<void(const std::vector<double> &)> itk::simple::Similarity2DTransform::m_pfSetTranslation private
Definition at line 107 of file sitkSimilarity2DTransform.h.
The documentation for this class was generated from the following file:
sitkSimilarity2DTransform.h