SimpleITK: itk::simple::ObjectnessMeasureImageFilter Class Reference
itk::simple::ObjectnessMeasureImageFilter Class Reference
Enhance M-dimensional objects in N-dimensional images.
#include <sitkObjectnessMeasureImageFilter.h>
Detailed Description
Enhance M-dimensional objects in N-dimensional images.
This filter is a generalization of Frangi's vesselness measurement for detecting M-dimensional object in N-dimensional space. For example a vessel is a 1-D object in 3-D space. The filter can enhance blob-like structures (M=0), vessel-like structures (M=1), 2D plate-like structures (M=2), hyper-plate-like structures (M=3) in N-dimensional images, with M<N.
This filter takes a scalar image as input and produces a real valued image as output which contains the objectness measure at each pixel. Internally, it computes a Hessian via discrete central differences. Before applying this filter it is expected that a Gaussian smoothing filter at an appropriate scale (sigma) was applied to the input image.
The enhancement is based on the eigenvalues of the Hessian matrix. For the Frangi's vesselness case were M=1 and N=3 we have the 3 eigenvalues such that \(| \lambda_1 | < | \lambda_2 | < |\lambda_3 | \) . The formula follows:
\[ R_A = \frac{|\lambda_2|}{|\lambda_3|}, \; R_B = \frac{|\lambda_2|}{|\lambda_2\lambda_3|}, \; S = \sqrt{\lambda_1^2+\lambda_2^2+\lambda_3^2} \]
\[ V_{\sigma}= \begin{cases} (1-e^{-\frac{R_A^2}{2\alpha^2}}) \cdot e^{\frac{R_B^2}{2\beta^2}} \cdot (1-e^{-\frac{S^2}{2\gamma^2}}) & \text{if } \lambda_2<0 \text{ and } \lambda_3<0 \text{,}\\ 0 & \text{otherwise} \end{cases} \]
References
Antiga, L. Generalizing vesselness with respect to dimensionality and shape. https://hdl.handle.net/1926/576
Frangi, AF, Niessen, WJ, Vincken, KL, & Viergever, MA (1998). Multiscale Vessel Enhancement Filtering. In Wells, WM, Colchester, A, & Delp, S, Editors, MICCAI '98 Medical Image Computing and Computer-Assisted Intervention, Lecture Notes in Computer Science, pages 130-137, Springer Verlag, 1998.
See also
itk::HessianToObjectnessMeasureImageFilter
itk::simple::ObjectnessMeasure for the procedural interface
itk::ObjectnessMeasureImageFilter for the Doxygen on the original ITK class.
Definition at line 69 of file sitkObjectnessMeasureImageFilter.h.
Public Types
using PixelIDTypeList = RealPixelIDTypeList
using Self = ObjectnessMeasureImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void BrightObjectOff ()
void BrightObjectOn ()
Image Execute (const Image &image1)
double GetAlpha () const
double GetBeta () const
bool GetBrightObject () const
double GetGamma () const
std::string GetName () const
unsigned int GetObjectDimension () const
bool GetScaleObjectnessMeasure () const
ObjectnessMeasureImageFilter ()
void ScaleObjectnessMeasureOff ()
void ScaleObjectnessMeasureOn ()
void SetAlpha (double Alpha)
void SetBeta (double Beta)
void SetBrightObject (bool BrightObject)
void SetGamma (double Gamma)
void SetObjectDimension (unsigned int ObjectDimension)
void SetScaleObjectnessMeasure (bool ScaleObjectnessMeasure)
std::string ToString () const
virtual ~ObjectnessMeasureImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_Alpha { 0.5 }
double m_Beta { 0.5 }
bool m_BrightObject { true }
double m_Gamma { 5.0 }
unsigned int m_ObjectDimension { 1u }
bool m_ScaleObjectnessMeasure { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::ObjectnessMeasureImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 197 of file sitkObjectnessMeasureImageFilter.h.
PixelIDTypeList
using itk::simple::ObjectnessMeasureImageFilter::PixelIDTypeList = RealPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 81 of file sitkObjectnessMeasureImageFilter.h.
Self
using itk::simple::ObjectnessMeasureImageFilter::Self = ObjectnessMeasureImageFilter
Definition at line 71 of file sitkObjectnessMeasureImageFilter.h.
Constructor & Destructor Documentation
~ObjectnessMeasureImageFilter()
virtual itk::simple::ObjectnessMeasureImageFilter::~ObjectnessMeasureImageFilter () virtual
Destructor
ObjectnessMeasureImageFilter()
itk::simple::ObjectnessMeasureImageFilter::ObjectnessMeasureImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
BrightObjectOff()
void itk::simple::ObjectnessMeasureImageFilter::BrightObjectOff () inline
Definition at line 176 of file sitkObjectnessMeasureImageFilter.h.
References SetBrightObject().
BrightObjectOn()
void itk::simple::ObjectnessMeasureImageFilter::BrightObjectOn () inline
Set the value of BrightObject to true or false respectfully.
Definition at line 174 of file sitkObjectnessMeasureImageFilter.h.
References SetBrightObject().
Execute()
Image itk::simple::ObjectnessMeasureImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::ObjectnessMeasureImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetAlpha()
double itk::simple::ObjectnessMeasureImageFilter::GetAlpha () const inline
Set/Get Alpha, the weight corresponding to R_A (the ratio of the smallest eigenvalue that has to be large to the larger ones). Smaller values lead to increased sensitivity to the object dimensionality.
Definition at line 98 of file sitkObjectnessMeasureImageFilter.h.
References m_Alpha.
GetBeta()
double itk::simple::ObjectnessMeasureImageFilter::GetBeta () const inline
Set/Get Beta, the weight corresponding to R_B (the ratio of the largest eigenvalue that has to be small to the larger ones). Smaller values lead to increased sensitivity to the object dimensionality.
Definition at line 113 of file sitkObjectnessMeasureImageFilter.h.
References m_Beta.
GetBrightObject()
bool itk::simple::ObjectnessMeasureImageFilter::GetBrightObject () const inline
Enhance bright structures on a dark background if true, the opposite if false.
Definition at line 181 of file sitkObjectnessMeasureImageFilter.h.
References m_BrightObject.
GetGamma()
double itk::simple::ObjectnessMeasureImageFilter::GetGamma () const inline
Set/Get Gamma, the weight corresponding to S (the Frobenius norm of the Hessian matrix, or second-order structureness)
Definition at line 128 of file sitkObjectnessMeasureImageFilter.h.
References m_Gamma.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::ObjectnessMeasureImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::ObjectnessMeasureImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 185 of file sitkObjectnessMeasureImageFilter.h.
GetObjectDimension()
unsigned int itk::simple::ObjectnessMeasureImageFilter::GetObjectDimension () const inline
Set/Get the dimensionality of the object (0: points (blobs), 1: lines (vessels), 2: planes (plate-like structures), 3: hyper-planes. ObjectDimension must be smaller than ImageDimension.
Definition at line 162 of file sitkObjectnessMeasureImageFilter.h.
References m_ObjectDimension.
GetScaleObjectnessMeasure()
bool itk::simple::ObjectnessMeasureImageFilter::GetScaleObjectnessMeasure () const inline
Toggle scaling the objectness measure with the magnitude of the largest absolute eigenvalue
Definition at line 147 of file sitkObjectnessMeasureImageFilter.h.
References m_ScaleObjectnessMeasure.
ScaleObjectnessMeasureOff()
void itk::simple::ObjectnessMeasureImageFilter::ScaleObjectnessMeasureOff () inline
Definition at line 142 of file sitkObjectnessMeasureImageFilter.h.
References SetScaleObjectnessMeasure().
ScaleObjectnessMeasureOn()
void itk::simple::ObjectnessMeasureImageFilter::ScaleObjectnessMeasureOn () inline
Set the value of ScaleObjectnessMeasure to true or false respectfully.
Definition at line 140 of file sitkObjectnessMeasureImageFilter.h.
References SetScaleObjectnessMeasure().
SetAlpha()
void itk::simple::ObjectnessMeasureImageFilter::SetAlpha (double Alpha) inline
Set/Get Alpha, the weight corresponding to R_A (the ratio of the smallest eigenvalue that has to be large to the larger ones). Smaller values lead to increased sensitivity to the object dimensionality.
Definition at line 91 of file sitkObjectnessMeasureImageFilter.h.
References m_Alpha.
SetBeta()
void itk::simple::ObjectnessMeasureImageFilter::SetBeta (double Beta) inline
Set/Get Beta, the weight corresponding to R_B (the ratio of the largest eigenvalue that has to be small to the larger ones). Smaller values lead to increased sensitivity to the object dimensionality.
Definition at line 106 of file sitkObjectnessMeasureImageFilter.h.
References m_Beta.
SetBrightObject()
void itk::simple::ObjectnessMeasureImageFilter::SetBrightObject (bool BrightObject) inline
Enhance bright structures on a dark background if true, the opposite if false.
Definition at line 169 of file sitkObjectnessMeasureImageFilter.h.
References m_BrightObject.
Referenced by BrightObjectOff(), and BrightObjectOn().
SetGamma()
void itk::simple::ObjectnessMeasureImageFilter::SetGamma (double Gamma) inline
Set/Get Gamma, the weight corresponding to S (the Frobenius norm of the Hessian matrix, or second-order structureness)
Definition at line 121 of file sitkObjectnessMeasureImageFilter.h.
References m_Gamma.
SetObjectDimension()
void itk::simple::ObjectnessMeasureImageFilter::SetObjectDimension (unsigned int ObjectDimension) inline
Set/Get the dimensionality of the object (0: points (blobs), 1: lines (vessels), 2: planes (plate-like structures), 3: hyper-planes. ObjectDimension must be smaller than ImageDimension.
Definition at line 155 of file sitkObjectnessMeasureImageFilter.h.
References m_ObjectDimension.
SetScaleObjectnessMeasure()
void itk::simple::ObjectnessMeasureImageFilter::SetScaleObjectnessMeasure (bool ScaleObjectnessMeasure) inline
Toggle scaling the objectness measure with the magnitude of the largest absolute eigenvalue
Definition at line 135 of file sitkObjectnessMeasureImageFilter.h.
References m_ScaleObjectnessMeasure.
Referenced by ScaleObjectnessMeasureOff(), and ScaleObjectnessMeasureOn().
ToString()
std::string itk::simple::ObjectnessMeasureImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 198 of file sitkObjectnessMeasureImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Alpha
double itk::simple::ObjectnessMeasureImageFilter::m_Alpha { 0.5 } private
Definition at line 203 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetAlpha(), and SetAlpha().
m_Beta
double itk::simple::ObjectnessMeasureImageFilter::m_Beta { 0.5 } private
Definition at line 206 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetBeta(), and SetBeta().
m_BrightObject
bool itk::simple::ObjectnessMeasureImageFilter::m_BrightObject { true } private
Definition at line 214 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetBrightObject(), and SetBrightObject().
m_Gamma
double itk::simple::ObjectnessMeasureImageFilter::m_Gamma { 5.0 } private
Definition at line 208 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetGamma(), and SetGamma().
m_ObjectDimension
unsigned int itk::simple::ObjectnessMeasureImageFilter::m_ObjectDimension { 1u } private
Definition at line 212 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetObjectDimension(), and SetObjectDimension().
m_ScaleObjectnessMeasure
bool itk::simple::ObjectnessMeasureImageFilter::m_ScaleObjectnessMeasure { true } private
Definition at line 210 of file sitkObjectnessMeasureImageFilter.h.
Referenced by GetScaleObjectnessMeasure(), and SetScaleObjectnessMeasure().
The documentation for this class was generated from the following file:
sitkObjectnessMeasureImageFilter.h