SimpleITK: itk::simple::VersorTransform Class Reference
itk::simple::VersorTransform Class Reference
A 3D rotation transform with rotation as a versor around a fixed center.
#include <sitkVersorTransform.h>
Detailed Description
A 3D rotation transform with rotation as a versor around a fixed center.
See also
itk::VersorTransform
Definition at line 33 of file sitkVersorTransform.h.
Public Types
using Self = VersorTransform
using Superclass = Transform
Public Types inherited from itk::simple::Transform
using Self = Transform
Public Member Functions
std::vector< double > GetCenter () const
std::vector< double > GetMatrix () const
std::string GetName () const override
std::vector< double > GetVersor () const
VersorTransform & operator= (const VersorTransform &)
Self & SetCenter (const std::vector< double > &params)
Self & SetMatrix (const std::vector< double > &matrix, double tolerance=1e-10)
Self & SetRotation (const std::vector< double > &axis, double angle)
Self & SetRotation (const std::vector< double > &versor)
VersorTransform ()
VersorTransform (const std::vector< double > &axis, double angle, const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
VersorTransform (const std::vector< double > &versor, const std::vector< double > &fixedCenter=std::vector< double >(3, 0.0))
VersorTransform (const Transform &)
VersorTransform (const VersorTransform &)
~VersorTransform () override
Public Member Functions inherited from itk::simple::Transform
unsigned int GetDimension () const
Transform GetInverse () const
Return a new inverse transform of the same type as this.
unsigned int GetNumberOfFixedParameters () const
unsigned int GetNumberOfParameters () const
TransformEnum GetTransformEnum () const
Get the TransformEnum of the underlying Transform.
virtual bool IsLinear () const
void MakeUnique ()
Performs actually coping if needed to make object unique.
virtual void SetIdentity ()
virtual bool SetInverse ()
Try to change the current transform to it's inverse.
std::string ToString () const
Transform ()
By default a 3-d identity transform is constructed.
Transform (Image &displacement, TransformEnum type=sitkDisplacementField)
Use an image to construct a transform.
template<unsigned int NDimension>
Transform (itk::CompositeTransform< double, NDimension > *compositeTransform)
Construct a SimpleITK Transform from a pointer to an ITK composite transform.
Transform (itk::TransformBase *transform)
Transform (unsigned int dimensions, TransformEnum type)
Construct a specific transformation.
std::vector< double > TransformPoint (const std::vector< double > &point) const
std::vector< double > TransformVector (const std::vector< double > &vector, const std::vector< double > &point) const
void WriteTransform (const std::string &filename) const
virtual ~Transform ()
Transform & operator= (const Transform &)
Copy constructor and assignment operator.
Transform (const Transform &)
Copy constructor and assignment operator.
itk::TransformBase * GetITKBase ()
const itk::TransformBase * GetITKBase () const
void SetParameters (const std::vector< double > &parameters)
std::vector< double > GetParameters () const
void SetFixedParameters (const std::vector< double > &parameters)
std::vector< double > GetFixedParameters () const
Protected Member Functions
void SetPimpleTransform (std::unique_ptr< PimpleTransformBase > &&pimpleTransform) override
Protected Member Functions inherited from itk::simple::Transform
Transform (PimpleTransformBase *pimpleTransform)
Private Member Functions
void InternalInitialization (itk::TransformBase *transform)
template<typename TransformType>
void InternalInitialization (TransformType *transform)
Private Attributes
std::function< std::vector< double >()> m_pfGetCenter
std::function< std::vector< double >()> m_pfGetMatrix
std::function< std::vector< double >()> m_pfGetVersor
std::function< void(const std::vector< double > &)> m_pfSetCenter
std::function< void(const std::vector< double > &, double)> m_pfSetMatrix
std::function< void(const std::vector< double > &)> m_pfSetRotation1
std::function< void(const std::vector< double > &, double)> m_pfSetRotation2
Member Typedef Documentation
Self
using itk::simple::VersorTransform::Self = VersorTransform
Definition at line 36 of file sitkVersorTransform.h.
Superclass
using itk::simple::VersorTransform::Superclass = Transform
Definition at line 37 of file sitkVersorTransform.h.
Constructor & Destructor Documentation
~VersorTransform()
itk::simple::VersorTransform::~VersorTransform () override
VersorTransform() [1/5]
itk::simple::VersorTransform::VersorTransform ()
Referenced by operator=(), VersorTransform(), and VersorTransform().
VersorTransform() [2/5]
itk::simple::VersorTransform::VersorTransform (const VersorTransform &)
References VersorTransform().
VersorTransform() [3/5]
itk::simple::VersorTransform::VersorTransform (const Transform &) explicit
References itk::simple::Transform::Transform().
VersorTransform() [4/5]
itk::simple::VersorTransform::VersorTransform (const std::vector< double > & versor, const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0)) explicit
VersorTransform() [5/5]
itk::simple::VersorTransform::VersorTransform (const std::vector< double > & axis, double angle, const std::vector< double > & fixedCenter = std::vector< double >(3, 0.0))
References VersorTransform().
Member Function Documentation
GetCenter()
std::vector< double > itk::simple::VersorTransform::GetCenter () const
GetMatrix()
std::vector< double > itk::simple::VersorTransform::GetMatrix () const
additional methods
GetName()
std::string itk::simple::VersorTransform::GetName () const inline override virtual
Name of this class
Reimplemented from itk::simple::Transform.
Definition at line 60 of file sitkVersorTransform.h.
GetVersor()
std::vector< double > itk::simple::VersorTransform::GetVersor () const
InternalInitialization() [1/2]
void itk::simple::VersorTransform::InternalInitialization (itk::TransformBase * transform) private
InternalInitialization() [2/2]
template<typename TransformType> void itk::simple::VersorTransform::InternalInitialization (TransformType * transform) private
operator=()
VersorTransform & itk::simple::VersorTransform::operator= (const VersorTransform &)
References VersorTransform().
SetCenter()
Self & itk::simple::VersorTransform::SetCenter (const std::vector< double > & params)
fixed parameter
SetMatrix()
Self & itk::simple::VersorTransform::SetMatrix (const std::vector< double > & matrix, double tolerance = 1e-10)
SetPimpleTransform()
void itk::simple::VersorTransform::SetPimpleTransform (std::unique_ptr< PimpleTransformBase > && pimpleTransform) override protected virtual
Reimplemented from itk::simple::Transform.
SetRotation() [1/2]
Self & itk::simple::VersorTransform::SetRotation (const std::vector< double > & axis, double angle)
SetRotation() [2/2]
Self & itk::simple::VersorTransform::SetRotation (const std::vector< double > & versor)
parameter
Member Data Documentation
m_pfGetCenter
std::function<std::vector<double>()> itk::simple::VersorTransform::m_pfGetCenter private
Definition at line 100 of file sitkVersorTransform.h.
m_pfGetMatrix
std::function<std::vector<double>()> itk::simple::VersorTransform::m_pfGetMatrix private
Definition at line 104 of file sitkVersorTransform.h.
m_pfGetVersor
std::function<std::vector<double>()> itk::simple::VersorTransform::m_pfGetVersor private
Definition at line 103 of file sitkVersorTransform.h.
m_pfSetCenter
std::function<void(const std::vector<double> &)> itk::simple::VersorTransform::m_pfSetCenter private
Definition at line 99 of file sitkVersorTransform.h.
m_pfSetMatrix
std::function<void(const std::vector<double> &, double)> itk::simple::VersorTransform::m_pfSetMatrix private
Definition at line 105 of file sitkVersorTransform.h.
m_pfSetRotation1
std::function<void(const std::vector<double> &)> itk::simple::VersorTransform::m_pfSetRotation1 private
Definition at line 101 of file sitkVersorTransform.h.
m_pfSetRotation2
std::function<void(const std::vector<double> &, double)> itk::simple::VersorTransform::m_pfSetRotation2 private
Definition at line 102 of file sitkVersorTransform.h.
The documentation for this class was generated from the following file:
sitkVersorTransform.h