SimpleITK: itk::simple::ProjectedLandweberDeconvolutionImageFilter Class Reference
itk::simple::ProjectedLandweberDeconvolutionImageFilter Class Reference
Deconvolve an image using the projected Landweber deconvolution algorithm.
#include <sitkProjectedLandweberDeconvolutionImageFilter.h>
Detailed Description
Deconvolve an image using the projected Landweber deconvolution algorithm.
This filter performs the same calculation per iteration as the LandweberDeconvolutionImageFilter . However, at each iteration, negative pixels in the intermediate result are projected (set) to zero. This is useful if the solution is assumed to always be non-negative, which is the case when dealing with images formed by counting photons, for example.
This code was adapted from the Insight Journal contribution:
"Deconvolution: infrastructure and reference algorithms" by Gaetan Lehmann https://doi.org/10.54294/tvgfv1
Author
Gaetan Lehmann, Biologie du Developpement et de la Reproduction, INRA de Jouy-en-Josas, France
Cory Quammen, The University of North Carolina at Chapel Hill
See also
IterativeDeconvolutionImageFilter
RichardsonLucyDeconvolutionImageFilter
LandweberDeconvolutionImageFilter
itk::simple::ProjectedLandweberDeconvolution for the procedural interface
itk::ProjectedLandweberDeconvolutionImageFilter for the Doxygen on the original ITK class.
Definition at line 66 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Public Types
enum BoundaryConditionType {
ZERO_PAD ,
ZERO_FLUX_NEUMANN_PAD ,
PERIODIC_PAD
}
enum OutputRegionModeType {
SAME ,
VALID
}
using PixelIDTypeList = BasicPixelIDTypeList
using Self = ProjectedLandweberDeconvolutionImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image1, const Image &image2)
double GetAlpha () const
BoundaryConditionType GetBoundaryCondition () const
std::string GetName () const
bool GetNormalize () const
int GetNumberOfIterations () const
OutputRegionModeType GetOutputRegionMode () const
void NormalizeOff ()
void NormalizeOn ()
ProjectedLandweberDeconvolutionImageFilter ()
void SetAlpha (double Alpha)
void SetBoundaryCondition (BoundaryConditionType BoundaryCondition)
void SetNormalize (bool Normalize)
void SetNumberOfIterations (int NumberOfIterations)
void SetOutputRegionMode (OutputRegionModeType OutputRegionMode)
std::string ToString () const
virtual ~ProjectedLandweberDeconvolutionImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1, const Image &image2)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1, const Image &image2)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_Alpha { 0.1 }
BoundaryConditionType m_BoundaryCondition { itk::simple::ProjectedLandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD }
bool m_Normalize { false }
int m_NumberOfIterations { 1 }
OutputRegionModeType m_OutputRegionMode { itk::simple::ProjectedLandweberDeconvolutionImageFilter::SAME }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::ProjectedLandweberDeconvolutionImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1, const Image &image2) private
Setup for member function dispatching
Definition at line 160 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
PixelIDTypeList
using itk::simple::ProjectedLandweberDeconvolutionImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 78 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Self
using itk::simple::ProjectedLandweberDeconvolutionImageFilter::Self = ProjectedLandweberDeconvolutionImageFilter
Definition at line 68 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Member Enumeration Documentation
BoundaryConditionType
enum itk::simple::ProjectedLandweberDeconvolutionImageFilter::BoundaryConditionType
Enumerator
ZERO_PAD
ZERO_FLUX_NEUMANN_PAD
PERIODIC_PAD
Definition at line 124 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
OutputRegionModeType
enum itk::simple::ProjectedLandweberDeconvolutionImageFilter::OutputRegionModeType
Enumerator
SAME
VALID
Definition at line 135 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Constructor & Destructor Documentation
~ProjectedLandweberDeconvolutionImageFilter()
virtual itk::simple::ProjectedLandweberDeconvolutionImageFilter::~ProjectedLandweberDeconvolutionImageFilter () virtual
Destructor
ProjectedLandweberDeconvolutionImageFilter()
itk::simple::ProjectedLandweberDeconvolutionImageFilter::ProjectedLandweberDeconvolutionImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::ProjectedLandweberDeconvolutionImageFilter::Execute (const Image & image1, const Image & image2)
Execute the filter on the input images
ExecuteInternal()
template<class TImageType> Image itk::simple::ProjectedLandweberDeconvolutionImageFilter::ExecuteInternal (const Image & image1, const Image & image2) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetAlpha()
double itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetAlpha () const inline
Get the relaxation factor.
Definition at line 92 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_Alpha.
GetBoundaryCondition()
BoundaryConditionType itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetBoundaryCondition () const inline
Definition at line 133 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_BoundaryCondition.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 148 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
GetNormalize()
bool itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetNormalize () const inline
Definition at line 122 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_Normalize.
GetNumberOfIterations()
int itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetNumberOfIterations () const inline
Get the number of iterations.
Definition at line 104 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_NumberOfIterations.
GetOutputRegionMode()
OutputRegionModeType itk::simple::ProjectedLandweberDeconvolutionImageFilter::GetOutputRegionMode () const inline
Definition at line 144 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_OutputRegionMode.
NormalizeOff()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::NormalizeOff () inline
Definition at line 118 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References SetNormalize().
NormalizeOn()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::NormalizeOn () inline
Set the value of Normalize to true or false respectfully.
Definition at line 116 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References SetNormalize().
SetAlpha()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetAlpha (double Alpha) inline
Set the relaxation factor.
Definition at line 86 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_Alpha.
SetBoundaryCondition()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetBoundaryCondition (BoundaryConditionType BoundaryCondition) inline
Definition at line 128 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_BoundaryCondition.
SetNormalize()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetNormalize (bool Normalize) inline
Normalize the output image by the sum of the kernel components
Definition at line 111 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_Normalize, and itk::simple::Normalize().
Referenced by NormalizeOff(), and NormalizeOn().
SetNumberOfIterations()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetNumberOfIterations (int NumberOfIterations) inline
Set the number of iterations.
Definition at line 98 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_NumberOfIterations.
SetOutputRegionMode()
void itk::simple::ProjectedLandweberDeconvolutionImageFilter::SetOutputRegionMode (OutputRegionModeType OutputRegionMode) inline
Definition at line 139 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References m_OutputRegionMode.
ToString()
std::string itk::simple::ProjectedLandweberDeconvolutionImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 161 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_Alpha
double itk::simple::ProjectedLandweberDeconvolutionImageFilter::m_Alpha { 0.1 } private
Definition at line 166 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Referenced by GetAlpha(), and SetAlpha().
m_BoundaryCondition
BoundaryConditionType itk::simple::ProjectedLandweberDeconvolutionImageFilter::m_BoundaryCondition { itk::simple::ProjectedLandweberDeconvolutionImageFilter::ZERO_FLUX_NEUMANN_PAD } private
Definition at line 172 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Referenced by GetBoundaryCondition(), and SetBoundaryCondition().
m_Normalize
bool itk::simple::ProjectedLandweberDeconvolutionImageFilter::m_Normalize { false } private
Definition at line 170 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Referenced by GetNormalize(), and SetNormalize().
m_NumberOfIterations
int itk::simple::ProjectedLandweberDeconvolutionImageFilter::m_NumberOfIterations { 1 } private
Definition at line 168 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Referenced by GetNumberOfIterations(), and SetNumberOfIterations().
m_OutputRegionMode
OutputRegionModeType itk::simple::ProjectedLandweberDeconvolutionImageFilter::m_OutputRegionMode { itk::simple::ProjectedLandweberDeconvolutionImageFilter::SAME } private
Definition at line 174 of file sitkProjectedLandweberDeconvolutionImageFilter.h.
Referenced by GetOutputRegionMode(), and SetOutputRegionMode().
The documentation for this class was generated from the following file:
sitkProjectedLandweberDeconvolutionImageFilter.h