SimpleITK: itk::simple::InvertDisplacementFieldImageFilter Class Reference
itk::simple::InvertDisplacementFieldImageFilter Class Reference
Iteratively estimate the inverse field of a displacement field.
#include <sitkInvertDisplacementFieldImageFilter.h>
Detailed Description
Iteratively estimate the inverse field of a displacement field.
Author
Nick Tustison
Brian Avants
See also
itk::simple::InvertDisplacementField for the procedural interface
itk::InvertDisplacementFieldImageFilter for the Doxygen on the original ITK class.
Definition at line 50 of file sitkInvertDisplacementFieldImageFilter.h.
Public Types
using PixelIDTypeList = RealVectorPixelIDTypeList
using Self = InvertDisplacementFieldImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
void EnforceBoundaryConditionOff ()
void EnforceBoundaryConditionOn ()
Image Execute (const Image &image1)
bool GetEnforceBoundaryCondition () const
double GetMaxErrorNorm () const
double GetMaxErrorToleranceThreshold () const
uint32_t GetMaximumNumberOfIterations () const
double GetMeanErrorNorm () const
double GetMeanErrorToleranceThreshold () const
std::string GetName () const
InvertDisplacementFieldImageFilter ()
void SetEnforceBoundaryCondition (bool EnforceBoundaryCondition)
void SetMaxErrorToleranceThreshold (double MaxErrorToleranceThreshold)
void SetMaximumNumberOfIterations (uint32_t MaximumNumberOfIterations)
void SetMeanErrorToleranceThreshold (double MeanErrorToleranceThreshold)
std::string ToString () const
virtual ~InvertDisplacementFieldImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType = Image (Self::*)(const Image &image1)
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image &image1)
Private Attributes
bool m_EnforceBoundaryCondition { true }
double m_MaxErrorNorm { 0.0 }
double m_MaxErrorToleranceThreshold { 0.1 }
uint32_t m_MaximumNumberOfIterations { 10u }
double m_MeanErrorNorm { 0.0 }
double m_MeanErrorToleranceThreshold { 0.001 }
std::unique_ptr< detail::MemberFunctionFactory< MemberFunctionType > > m_MemberFactory
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::InvertDisplacementFieldImageFilter::MemberFunctionType = Image (Self::*)(const Image &image1) private
Setup for member function dispatching
Definition at line 140 of file sitkInvertDisplacementFieldImageFilter.h.
PixelIDTypeList
using itk::simple::InvertDisplacementFieldImageFilter::PixelIDTypeList = RealVectorPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 62 of file sitkInvertDisplacementFieldImageFilter.h.
Self
using itk::simple::InvertDisplacementFieldImageFilter::Self = InvertDisplacementFieldImageFilter
Definition at line 52 of file sitkInvertDisplacementFieldImageFilter.h.
Constructor & Destructor Documentation
~InvertDisplacementFieldImageFilter()
virtual itk::simple::InvertDisplacementFieldImageFilter::~InvertDisplacementFieldImageFilter () virtual
Destructor
InvertDisplacementFieldImageFilter()
itk::simple::InvertDisplacementFieldImageFilter::InvertDisplacementFieldImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
EnforceBoundaryConditionOff()
void itk::simple::InvertDisplacementFieldImageFilter::EnforceBoundaryConditionOff () inline
Definition at line 106 of file sitkInvertDisplacementFieldImageFilter.h.
References SetEnforceBoundaryCondition().
EnforceBoundaryConditionOn()
void itk::simple::InvertDisplacementFieldImageFilter::EnforceBoundaryConditionOn () inline
Set the value of EnforceBoundaryCondition to true or false respectfully.
Definition at line 104 of file sitkInvertDisplacementFieldImageFilter.h.
References SetEnforceBoundaryCondition().
Execute()
Image itk::simple::InvertDisplacementFieldImageFilter::Execute (const Image & image1)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::InvertDisplacementFieldImageFilter::ExecuteInternal (const Image & image1) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetEnforceBoundaryCondition()
bool itk::simple::InvertDisplacementFieldImageFilter::GetEnforceBoundaryCondition () const inline
Definition at line 110 of file sitkInvertDisplacementFieldImageFilter.h.
References m_EnforceBoundaryCondition.
GetMaxErrorNorm()
double itk::simple::InvertDisplacementFieldImageFilter::GetMaxErrorNorm () const inline
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 118 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MaxErrorNorm.
GetMaxErrorToleranceThreshold()
double itk::simple::InvertDisplacementFieldImageFilter::GetMaxErrorToleranceThreshold () const inline
Definition at line 84 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MaxErrorToleranceThreshold.
GetMaximumNumberOfIterations()
uint32_t itk::simple::InvertDisplacementFieldImageFilter::GetMaximumNumberOfIterations () const inline
Definition at line 74 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MaximumNumberOfIterations.
GetMeanErrorNorm()
double itk::simple::InvertDisplacementFieldImageFilter::GetMeanErrorNorm () const inline
This is a measurement. Its value is updated in the Execute methods, so the value will only be valid after an execution.
Definition at line 125 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MeanErrorNorm.
GetMeanErrorToleranceThreshold()
double itk::simple::InvertDisplacementFieldImageFilter::GetMeanErrorToleranceThreshold () const inline
Definition at line 94 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MeanErrorToleranceThreshold.
GetName()
std::string itk::simple::InvertDisplacementFieldImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 128 of file sitkInvertDisplacementFieldImageFilter.h.
SetEnforceBoundaryCondition()
void itk::simple::InvertDisplacementFieldImageFilter::SetEnforceBoundaryCondition (bool EnforceBoundaryCondition) inline
Definition at line 99 of file sitkInvertDisplacementFieldImageFilter.h.
References m_EnforceBoundaryCondition.
Referenced by EnforceBoundaryConditionOff(), and EnforceBoundaryConditionOn().
SetMaxErrorToleranceThreshold()
void itk::simple::InvertDisplacementFieldImageFilter::SetMaxErrorToleranceThreshold (double MaxErrorToleranceThreshold) inline
Definition at line 79 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MaxErrorToleranceThreshold.
SetMaximumNumberOfIterations()
void itk::simple::InvertDisplacementFieldImageFilter::SetMaximumNumberOfIterations (uint32_t MaximumNumberOfIterations) inline
Definition at line 69 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MaximumNumberOfIterations.
SetMeanErrorToleranceThreshold()
void itk::simple::InvertDisplacementFieldImageFilter::SetMeanErrorToleranceThreshold (double MeanErrorToleranceThreshold) inline
Definition at line 89 of file sitkInvertDisplacementFieldImageFilter.h.
References m_MeanErrorToleranceThreshold.
ToString()
std::string itk::simple::InvertDisplacementFieldImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 141 of file sitkInvertDisplacementFieldImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_EnforceBoundaryCondition
bool itk::simple::InvertDisplacementFieldImageFilter::m_EnforceBoundaryCondition { true } private
Definition at line 153 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetEnforceBoundaryCondition(), and SetEnforceBoundaryCondition().
m_MaxErrorNorm
double itk::simple::InvertDisplacementFieldImageFilter::m_MaxErrorNorm { 0.0 } private
Definition at line 157 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetMaxErrorNorm().
m_MaxErrorToleranceThreshold
double itk::simple::InvertDisplacementFieldImageFilter::m_MaxErrorToleranceThreshold { 0.1 } private
Definition at line 149 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetMaxErrorToleranceThreshold(), and SetMaxErrorToleranceThreshold().
m_MaximumNumberOfIterations
uint32_t itk::simple::InvertDisplacementFieldImageFilter::m_MaximumNumberOfIterations { 10u } private
Definition at line 147 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetMaximumNumberOfIterations(), and SetMaximumNumberOfIterations().
m_MeanErrorNorm
double itk::simple::InvertDisplacementFieldImageFilter::m_MeanErrorNorm { 0.0 } private
Definition at line 158 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetMeanErrorNorm().
m_MeanErrorToleranceThreshold
double itk::simple::InvertDisplacementFieldImageFilter::m_MeanErrorToleranceThreshold { 0.001 } private
Definition at line 151 of file sitkInvertDisplacementFieldImageFilter.h.
Referenced by GetMeanErrorToleranceThreshold(), and SetMeanErrorToleranceThreshold().
m_MemberFactory
std::unique_ptr<detail::MemberFunctionFactory<MemberFunctionType> > itk::simple::InvertDisplacementFieldImageFilter::m_MemberFactory private
Definition at line 143 of file sitkInvertDisplacementFieldImageFilter.h.
The documentation for this class was generated from the following file:
sitkInvertDisplacementFieldImageFilter.h