SimpleITK: itk::simple::N4BiasFieldCorrectionImageFilter Class Reference
itk::simple::N4BiasFieldCorrectionImageFilter Class Reference
Implementation of the N4 bias field correction algorithm.
#include <sitkN4BiasFieldCorrectionImageFilter.h>
Detailed Description
Implementation of the N4 bias field correction algorithm.
The nonparametric nonuniform intensity normalization (N3) algorithm, as introduced by Sled et al. in 1998 is a method for correcting nonuniformity associated with MR images. The algorithm assumes a simple parametric model (Gaussian) for the bias field and does not require tissue class segmentation. In addition, there are only a couple of parameters to tune with the default values performing quite well. N3 has been publicly available as a set of perl scripts (https://www.bic.mni.mcgill.ca/ServicesSoftwareAdvancedImageProcessingTools/HomePage)
The N4 algorithm, encapsulated with this class, is a variation of the original N3 algorithm with the additional benefits of an improved B-spline fitting routine which allows for multiple resolutions to be used during the correction process. We also modify the iterative update component of algorithm such that the residual bias field is continually updated
Notes for the user:
Since much of the image manipulation is done in the log space of the intensities, input images with negative and small values (< 1) can produce poor results.
The original authors recommend performing the bias field correction on a downsampled version of the original image.
A binary mask or a weighted image can be supplied. If a binary mask is specified, those voxels in the input image which correspond to the voxels in the mask image are used to estimate the bias field. If a UseMaskLabel value is set to false (the default), all non-zero voxels in the MaskImage will be masked; otherwise only voxels in the MaskImage that match the MaskLabel will be used. If a confidence image is specified, the input voxels are weighted in the b-spline fitting routine according to the confidence voxel values.
The filter returns the corrected image. If the bias field is wanted, one can reconstruct it using the class itkBSplineControlPointImageFilter. See the IJ article and the test file for an example.
The 'Z' parameter in Sled's 1998 paper is the square root of the class variable 'm_WienerFilterNoise'.
The basic algorithm iterates between sharpening the intensity histogram of the corrected input image and spatially smoothing those results with a B-spline scalar field estimate of the bias field.
Author
Nicholas J. Tustison
Contributed by Nicholas J. Tustison, James C. Gee in the Insight Journal paper: https://doi.org/10.54294/jculxw
REFERENCE
J.G. Sled, A.P. Zijdenbos and A.C. Evans. "A Nonparametric Method for Automatic Correction of Intensity Nonuniformity in Data" IEEE Transactions on Medical Imaging, Vol 17, No 1. Feb 1998.
N.J. Tustison, B.B. Avants, P.A. Cook, Y. Zheng, A. Egan, P.A. Yushkevich, and J.C. Gee. "N4ITK: Improved N3 Bias Correction" IEEE Transactions on Medical Imaging, 29(6):1310-1320, June 2010.
See also
itk::simple::N4BiasFieldCorrection for the procedural interface
itk::N4BiasFieldCorrectionImageFilter for the Doxygen on the original ITK class.
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cs, and N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Definition at line 92 of file sitkN4BiasFieldCorrectionImageFilter.h.
Public Types
using PixelIDTypeList = RealPixelIDTypeList
using Self = N4BiasFieldCorrectionImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &image)
Image Execute (const Image &image, const Image &maskImage)
double GetBiasFieldFullWidthAtHalfMaximum () const
double GetConvergenceThreshold () const
double GetCurrentConvergenceMeasurement () const
uint32_t GetCurrentLevel () const
uint32_t GetElapsedIterations () const
Image GetLogBiasFieldAsImage (Image referenceImage) const
The computed log bias field correction. Typically, a reduced size image is used as input to the N4 filter using something like itkShrinkImageFilter. Since the output is a corrected version of the input, the user will probably want to apply the bias field correction to the full resolution image. Returns the b-spline log bias field reconstructioned onto the space of the referenceImage parameter. An input image can be corrected by: input/exp(bias_field).
uint8_t GetMaskLabel () const
std::vector< uint32_t > GetMaximumNumberOfIterations () const
std::string GetName () const
std::vector< uint32_t > GetNumberOfControlPoints () const
uint32_t GetNumberOfHistogramBins () const
uint32_t GetSplineOrder () const
bool GetUseMaskLabel () const
double GetWienerFilterNoise () const
N4BiasFieldCorrectionImageFilter ()
void SetBiasFieldFullWidthAtHalfMaximum (double BiasFieldFullWidthAtHalfMaximum)
void SetConvergenceThreshold (double ConvergenceThreshold)
void SetMaskLabel (uint8_t MaskLabel)
void SetMaximumNumberOfIterations (std::vector< uint32_t > MaximumNumberOfIterations)
void SetNumberOfControlPoints (std::vector< uint32_t > NumberOfControlPoints)
void SetNumberOfControlPoints (uint32_t value)
void SetNumberOfHistogramBins (uint32_t NumberOfHistogramBins)
void SetSplineOrder (uint32_t SplineOrder)
void SetUseMaskLabel (bool UseMaskLabel)
void SetWienerFilterNoise (double WienerFilterNoise)
std::string ToString () const
void UseMaskLabelOff ()
void UseMaskLabelOn ()
virtual ~N4BiasFieldCorrectionImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *image, const Image *maskImage)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
double m_BiasFieldFullWidthAtHalfMaximum { 0.15 }
double m_ConvergenceThreshold { 0.001 }
std::unique_ptr< itk::ProcessObject, ProcessObjectDeleter > m_Filter {nullptr}
uint8_t m_MaskLabel { 1 }
std::vector< uint32_t > m_MaximumNumberOfIterations { std::vector<uint32_t>(4,50) }
std::vector< uint32_t > m_NumberOfControlPoints { std::vector<uint32_t>(3, 4) }
uint32_t m_NumberOfHistogramBins { 200u }
std::function< double()> m_pfGetCurrentConvergenceMeasurement
std::function< uint32_t()> m_pfGetCurrentLevel
std::function< uint32_t()> m_pfGetElapsedIterations
std::function< Image(Image)> m_pfGetLogBiasFieldAsImage
uint32_t m_SplineOrder { 3u }
bool m_UseMaskLabel { true }
double m_WienerFilterNoise { 0.01 }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::N4BiasFieldCorrectionImageFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    image, const Image *
    maskImage)
Setup for member function dispatching
Definition at line 301 of file sitkN4BiasFieldCorrectionImageFilter.h.
PixelIDTypeList
using itk::simple::N4BiasFieldCorrectionImageFilter::PixelIDTypeList = RealPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 104 of file sitkN4BiasFieldCorrectionImageFilter.h.
Self
using itk::simple::N4BiasFieldCorrectionImageFilter::Self = N4BiasFieldCorrectionImageFilter
Definition at line 94 of file sitkN4BiasFieldCorrectionImageFilter.h.
Constructor & Destructor Documentation
~N4BiasFieldCorrectionImageFilter()
virtual itk::simple::N4BiasFieldCorrectionImageFilter::~N4BiasFieldCorrectionImageFilter () virtual
Destructor
N4BiasFieldCorrectionImageFilter()
itk::simple::N4BiasFieldCorrectionImageFilter::N4BiasFieldCorrectionImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute() [1/2]
Image itk::simple::N4BiasFieldCorrectionImageFilter::Execute (const Image & image)
Execute() [2/2]
Image itk::simple::N4BiasFieldCorrectionImageFilter::Execute (const Image & image, const Image & maskImage)
Execute the filter on the input image
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cs, and N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
ExecuteInternal()
template<class TImageType> Image itk::simple::N4BiasFieldCorrectionImageFilter::ExecuteInternal (const Image * image, const Image * maskImage) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
GetBiasFieldFullWidthAtHalfMaximum()
double itk::simple::N4BiasFieldCorrectionImageFilter::GetBiasFieldFullWidthAtHalfMaximum () const inline
Get the full width at half maximum parameter characterizing the width of the Gaussian deconvolution. Default = 0.15.
Definition at line 149 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_BiasFieldFullWidthAtHalfMaximum.
GetConvergenceThreshold()
double itk::simple::N4BiasFieldCorrectionImageFilter::GetConvergenceThreshold () const inline
Get the convergence threshold. Convergence is determined by the coefficient of variation of the difference image between the current bias field estimate and the previous estimate. If this value is less than the specified threshold, the algorithm proceeds to the next fitting level or terminates if it is at the last level.
Definition at line 123 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_ConvergenceThreshold.
GetCurrentConvergenceMeasurement()
double itk::simple::N4BiasFieldCorrectionImageFilter::GetCurrentConvergenceMeasurement () const inline
Get the current convergence measurement. This is a helper function for reporting observations.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 275 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_pfGetCurrentConvergenceMeasurement.
GetCurrentLevel()
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::GetCurrentLevel () const inline
Get the current fitting level. This is a helper function for reporting observations.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 257 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_pfGetCurrentLevel.
GetElapsedIterations()
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::GetElapsedIterations () const inline
Get the number of elapsed iterations. This is a helper function for reporting observations.
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Definition at line 266 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_pfGetElapsedIterations.
GetLogBiasFieldAsImage()
Image itk::simple::N4BiasFieldCorrectionImageFilter::GetLogBiasFieldAsImage (Image referenceImage) const inline
The computed log bias field correction. Typically, a reduced size image is used as input to the N4 filter using something like itkShrinkImageFilter. Since the output is a corrected version of the input, the user will probably want to apply the bias field correction to the full resolution image. Returns the b-spline log bias field reconstructioned onto the space of the referenceImage parameter. An input image can be corrected by: input/exp(bias_field).
This is an active measurement. It may be accessed while the filter is being executing in command call-backs and can be accessed after execution.
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cs, and N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Definition at line 285 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_pfGetLogBiasFieldAsImage.
GetMaskLabel()
uint8_t itk::simple::N4BiasFieldCorrectionImageFilter::GetMaskLabel () const inline
Set/Get mask label value. If a binary mask image is specified and if UseMaskValue is true, only those input image voxels corresponding with mask image values equal to MaskLabel are used in estimating the bias field. If a MaskImage is specified and UseMaskLabel is false, all input image voxels corresponding to non-zero voxels in the MaskImage are used in estimating the bias field. Default = 1.
Definition at line 247 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_MaskLabel.
GetMaximumNumberOfIterations()
std::vector< uint32_t > itk::simple::N4BiasFieldCorrectionImageFilter::GetMaximumNumberOfIterations () const inline
Get the maximum number of iterations specified at each fitting level. Default = 50.
Definition at line 136 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_MaximumNumberOfIterations.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::N4BiasFieldCorrectionImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::N4BiasFieldCorrectionImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 288 of file sitkN4BiasFieldCorrectionImageFilter.h.
GetNumberOfControlPoints()
std::vector< uint32_t > itk::simple::N4BiasFieldCorrectionImageFilter::GetNumberOfControlPoints () const inline
Get the control point grid size defining the B-spline estimate of the scalar bias field. In each dimension, the B-spline mesh size is equal to the number of control points in that dimension minus the spline order. Default = 4 control points in each dimension for a mesh size of 1 in each dimension.
Definition at line 196 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_NumberOfControlPoints.
GetNumberOfHistogramBins()
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::GetNumberOfHistogramBins () const inline
Get number of bins defining the log input intensity histogram. Default = 200.
Definition at line 175 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_NumberOfHistogramBins.
GetSplineOrder()
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::GetSplineOrder () const inline
Get the spline order defining the bias field estimate. Default = 3.
Definition at line 209 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_SplineOrder.
GetUseMaskLabel()
bool itk::simple::N4BiasFieldCorrectionImageFilter::GetUseMaskLabel () const inline
Use a mask label for identifying mask functionality. See SetMaskLabel. Defaults to true.
Definition at line 228 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_UseMaskLabel.
GetWienerFilterNoise()
double itk::simple::N4BiasFieldCorrectionImageFilter::GetWienerFilterNoise () const inline
Get the noise estimate defining the Wiener filter. Default = 0.01.
Definition at line 162 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_WienerFilterNoise.
SetBiasFieldFullWidthAtHalfMaximum()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetBiasFieldFullWidthAtHalfMaximum (double BiasFieldFullWidthAtHalfMaximum) inline
Set the full width at half maximum parameter characterizing the width of the Gaussian deconvolution. Default = 0.15.
Definition at line 143 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_BiasFieldFullWidthAtHalfMaximum.
SetConvergenceThreshold()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetConvergenceThreshold (double ConvergenceThreshold) inline
Set the convergence threshold. Convergence is determined by the coefficient of variation of the difference image between the current bias field estimate and the previous estimate. If this value is less than the specified threshold, the algorithm proceeds to the next fitting level or terminates if it is at the last level.
Definition at line 115 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_ConvergenceThreshold.
SetMaskLabel()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetMaskLabel (uint8_t MaskLabel) inline
Set/Get mask label value. If a binary mask image is specified and if UseMaskValue is true, only those input image voxels corresponding with mask image values equal to MaskLabel are used in estimating the bias field. If a MaskImage is specified and UseMaskLabel is false, all input image voxels corresponding to non-zero voxels in the MaskImage are used in estimating the bias field. Default = 1.
Definition at line 238 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_MaskLabel.
SetMaximumNumberOfIterations()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetMaximumNumberOfIterations (std::vector< uint32_t > MaximumNumberOfIterations) inline
Set the maximum number of iterations specified at each fitting level. Default = 50.
Examples
N4BiasFieldCorrection/N4BiasFieldCorrection.cs, and N4BiasFieldCorrection/N4BiasFieldCorrection.cxx.
Definition at line 130 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_MaximumNumberOfIterations.
SetNumberOfControlPoints() [1/2]
void itk::simple::N4BiasFieldCorrectionImageFilter::SetNumberOfControlPoints (std::vector< uint32_t > NumberOfControlPoints) inline
Set the control point grid size defining the B-spline estimate of the scalar bias field. In each dimension, the B-spline mesh size is equal to the number of control points in that dimension minus the spline order. Default = 4 control points in each dimension for a mesh size of 1 in each dimension.
Definition at line 184 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_NumberOfControlPoints.
SetNumberOfControlPoints() [2/2]
void itk::simple::N4BiasFieldCorrectionImageFilter::SetNumberOfControlPoints (uint32_t value) inline
Set the values of the NumberOfControlPoints vector all to value
Definition at line 189 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_NumberOfControlPoints.
SetNumberOfHistogramBins()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetNumberOfHistogramBins (uint32_t NumberOfHistogramBins) inline
Set number of bins defining the log input intensity histogram. Default = 200.
Definition at line 169 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_NumberOfHistogramBins.
SetSplineOrder()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetSplineOrder (uint32_t SplineOrder) inline
Set the spline order defining the bias field estimate. Default = 3.
Definition at line 203 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_SplineOrder.
SetUseMaskLabel()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetUseMaskLabel (bool UseMaskLabel) inline
Use a mask label for identifying mask functionality. See SetMaskLabel. Defaults to true.
Definition at line 216 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_UseMaskLabel.
Referenced by UseMaskLabelOff(), and UseMaskLabelOn().
SetWienerFilterNoise()
void itk::simple::N4BiasFieldCorrectionImageFilter::SetWienerFilterNoise (double WienerFilterNoise) inline
Set the noise estimate defining the Wiener filter. Default = 0.01.
Definition at line 156 of file sitkN4BiasFieldCorrectionImageFilter.h.
References m_WienerFilterNoise.
ToString()
std::string itk::simple::N4BiasFieldCorrectionImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseMaskLabelOff()
void itk::simple::N4BiasFieldCorrectionImageFilter::UseMaskLabelOff () inline
Definition at line 223 of file sitkN4BiasFieldCorrectionImageFilter.h.
References SetUseMaskLabel().
UseMaskLabelOn()
void itk::simple::N4BiasFieldCorrectionImageFilter::UseMaskLabelOn () inline
Set the value of UseMaskLabel to true or false respectfully.
Definition at line 221 of file sitkN4BiasFieldCorrectionImageFilter.h.
References SetUseMaskLabel().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 304 of file sitkN4BiasFieldCorrectionImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_BiasFieldFullWidthAtHalfMaximum
double itk::simple::N4BiasFieldCorrectionImageFilter::m_BiasFieldFullWidthAtHalfMaximum { 0.15 } private
Definition at line 316 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetBiasFieldFullWidthAtHalfMaximum(), and SetBiasFieldFullWidthAtHalfMaximum().
m_ConvergenceThreshold
double itk::simple::N4BiasFieldCorrectionImageFilter::m_ConvergenceThreshold { 0.001 } private
Definition at line 311 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetConvergenceThreshold(), and SetConvergenceThreshold().
m_Filter
std::unique_ptr<itk::ProcessObject, ProcessObjectDeleter> itk::simple::N4BiasFieldCorrectionImageFilter::m_Filter {nullptr} private
Definition at line 339 of file sitkN4BiasFieldCorrectionImageFilter.h.
m_MaskLabel
uint8_t itk::simple::N4BiasFieldCorrectionImageFilter::m_MaskLabel { 1 } private
Definition at line 328 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetMaskLabel(), and SetMaskLabel().
m_MaximumNumberOfIterations
std::vector<uint32_t> itk::simple::N4BiasFieldCorrectionImageFilter::m_MaximumNumberOfIterations { std::vector<uint32_t>(4,50) } private
Definition at line 314 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetMaximumNumberOfIterations(), and SetMaximumNumberOfIterations().
m_NumberOfControlPoints
std::vector<uint32_t> itk::simple::N4BiasFieldCorrectionImageFilter::m_NumberOfControlPoints { std::vector<uint32_t>(3, 4) } private
Definition at line 322 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetNumberOfControlPoints(), SetNumberOfControlPoints(), and SetNumberOfControlPoints().
m_NumberOfHistogramBins
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::m_NumberOfHistogramBins { 200u } private
Definition at line 320 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetNumberOfHistogramBins(), and SetNumberOfHistogramBins().
m_pfGetCurrentConvergenceMeasurement
std::function<double()> itk::simple::N4BiasFieldCorrectionImageFilter::m_pfGetCurrentConvergenceMeasurement private
Definition at line 334 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetCurrentConvergenceMeasurement().
m_pfGetCurrentLevel
std::function<uint32_t()> itk::simple::N4BiasFieldCorrectionImageFilter::m_pfGetCurrentLevel private
Definition at line 332 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetCurrentLevel().
m_pfGetElapsedIterations
std::function<uint32_t()> itk::simple::N4BiasFieldCorrectionImageFilter::m_pfGetElapsedIterations private
Definition at line 333 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetElapsedIterations().
m_pfGetLogBiasFieldAsImage
std::function<Image(Image)> itk::simple::N4BiasFieldCorrectionImageFilter::m_pfGetLogBiasFieldAsImage private
Definition at line 335 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetLogBiasFieldAsImage().
m_SplineOrder
uint32_t itk::simple::N4BiasFieldCorrectionImageFilter::m_SplineOrder { 3u } private
Definition at line 324 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetSplineOrder(), and SetSplineOrder().
m_UseMaskLabel
bool itk::simple::N4BiasFieldCorrectionImageFilter::m_UseMaskLabel { true } private
Definition at line 326 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetUseMaskLabel(), and SetUseMaskLabel().
m_WienerFilterNoise
double itk::simple::N4BiasFieldCorrectionImageFilter::m_WienerFilterNoise { 0.01 } private
Definition at line 318 of file sitkN4BiasFieldCorrectionImageFilter.h.
Referenced by GetWienerFilterNoise(), and SetWienerFilterNoise().
The documentation for this class was generated from the following file:
sitkN4BiasFieldCorrectionImageFilter.h