SimpleITK: itk::simple::ReconstructionByDilationImageFilter Class Reference
itk::simple::ReconstructionByDilationImageFilter Class Reference
grayscale reconstruction by dilation of an image
#include <sitkReconstructionByDilationImageFilter.h>
Detailed Description
grayscale reconstruction by dilation of an image
Reconstruction by dilation operates on a "marker" image and a "mask" image, and is defined as the dilation of the marker image with respect to the mask image iterated until stability.
The marker image must be less than or equal to the mask image (on a pixel by pixel basis).
Geodesic morphology is described in Chapter 6.2 of Pierre Soille's book "Morphological Image Analysis: Principles and Applications", Second Edition, Springer, 2003.
Algorithm implemented in this filter is based on algorithm described by Kevin Robinson and Paul F. Whelan in "Efficient Morphological Reconstruction: A Downhill Filter", Pattern Recognition Letters, Volume 25, Issue 15, November 2004, Pages 1759-1767.
The algorithm, a description of the transform and some applications can be found in "Morphological Grayscale Reconstruction in Image Analysis: Applications and Efficient Algorithms", Luc Vincent, IEEE Transactions on image processing, Vol. 2, April 1993.
Author
Richard Beare. Department of Medicine, Monash University, Melbourne, Australia.
See also
MorphologyImageFilter , GrayscaleDilateImageFilter , GrayscaleFunctionDilateImageFilter , BinaryDilateImageFilter , ReconstructionByErosionImageFilter , OpeningByReconstructionImageFilter , ClosingByReconstructionImageFilter , ReconstructionImageFilter
itk::simple::ReconstructionByDilation for the procedural interface
itk::ReconstructionByDilationImageFilter for the Doxygen on the original ITK class.
Definition at line 65 of file sitkReconstructionByDilationImageFilter.h.
Public Types
using PixelIDTypeList = BasicPixelIDTypeList
using Self = ReconstructionByDilationImageFilter
Public Types inherited from itk::simple::ImageFilter
using Self = ImageFilter
Public Types inherited from itk::simple::ProcessObject
using Self = ProcessObject
Public Member Functions
Image Execute (const Image &markerImage, const Image &maskImage)
void FullyConnectedOff ()
void FullyConnectedOn ()
bool GetFullyConnected () const
std::string GetName () const
bool GetUseInternalCopy () const
ReconstructionByDilationImageFilter ()
void SetFullyConnected (bool FullyConnected)
void SetUseInternalCopy (bool UseInternalCopy)
std::string ToString () const
void UseInternalCopyOff ()
void UseInternalCopyOn ()
virtual ~ReconstructionByDilationImageFilter ()
Public Member Functions inherited from itk::simple::ImageFilter
ImageFilter ()
virtual ~ImageFilter ()=0
Public Member Functions inherited from itk::simple::ProcessObject
virtual void Abort ()
virtual int AddCommand (itk::simple::EventEnum event, const std::function< void()> &func)
Directly add a callback to observe an event.
virtual int AddCommand (itk::simple::EventEnum event, itk::simple::Command &cmd)
Add a Command Object to observer the event.
virtual float GetProgress () const
An Active Measurement of the progress of execution.
virtual bool HasCommand (itk::simple::EventEnum event) const
Query of this object has any registered commands for event.
ProcessObject ()
virtual void RemoveAllCommands ()
Remove all registered commands.
virtual ~ProcessObject ()
virtual void DebugOn ()
virtual void DebugOff ()
virtual bool GetDebug () const
virtual void SetDebug (bool debugFlag)
virtual void SetNumberOfThreads (unsigned int n)
virtual unsigned int GetNumberOfThreads () const
virtual void SetNumberOfWorkUnits (unsigned int n)
virtual unsigned int GetNumberOfWorkUnits () const
Private Types
using MemberFunctionType
Private Member Functions
template<class TImageType>
Image ExecuteInternal (const Image *markerImage, const Image *maskImage)
Static Private Member Functions
static const detail::MemberFunctionFactory< MemberFunctionType > & GetMemberFunctionFactory ()
Private Attributes
bool m_FullyConnected { false }
bool m_UseInternalCopy { true }
Friends
struct detail::MemberFunctionAddressor< MemberFunctionType >
Additional Inherited Members
Static Public Member Functions inherited from itk::simple::ProcessObject
static bool GetGlobalDefaultDebug ()
static void GlobalDefaultDebugOff ()
static void GlobalDefaultDebugOn ()
static void SetGlobalDefaultDebug (bool debugFlag)
static void GlobalWarningDisplayOn ()
static void GlobalWarningDisplayOff ()
static void SetGlobalWarningDisplay (bool flag)
static bool GetGlobalWarningDisplay ()
static double GetGlobalDefaultCoordinateTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultCoordinateTolerance (double)
Access the global tolerance to determine congruent spaces.
static double GetGlobalDefaultDirectionTolerance ()
Access the global tolerance to determine congruent spaces.
static void SetGlobalDefaultDirectionTolerance (double)
Access the global tolerance to determine congruent spaces.
static bool SetGlobalDefaultThreader (const std::string &threader)
Set/Get the default threader used for process objects.
static std::string GetGlobalDefaultThreader ()
Set/Get the default threader used for process objects.
static void SetGlobalDefaultNumberOfThreads (unsigned int n)
static unsigned int GetGlobalDefaultNumberOfThreads ()
Set/Get the default threader used for process objects.
Protected Member Functions inherited from itk::simple::ImageFilter
void CheckImageMatchingDimension (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingPixelType (const Image &image1, const Image &image2, const std::string &image2Name)
void CheckImageMatchingSize (const Image &image1, const Image &image2, const std::string &image2Name)
Protected Member Functions inherited from itk::simple::ProcessObject
virtual unsigned long AddITKObserver (const itk::EventObject &, itk::Command *)
virtual itk::ProcessObject * GetActiveProcess ()
virtual void OnActiveProcessDelete ()
virtual void onCommandDelete (const itk::simple::Command *cmd) noexcept
virtual void PreUpdate (itk::ProcessObject *p)
virtual void RemoveITKObserver (EventCommand &e)
Protected Member Functions inherited from itk::simple::NonCopyable
NonCopyable ()=default
NonCopyable (const NonCopyable &)=delete
NonCopyable & operator= (const NonCopyable &)=delete
Static Protected Member Functions inherited from itk::simple::ImageFilter
template<class TImageType>
static void FixNonZeroIndex (TImageType *img)
Static Protected Member Functions inherited from itk::simple::ProcessObject
template<class TImageType>
static TImageType::ConstPointer CastImageToITK (const Image &img)
template<class TPixelType, unsigned int VImageDimension, unsigned int VLength, template< typename, unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< TPixelType, VLength >, VImageDimension > *img)
template<unsigned int VImageDimension, unsigned int VLength, template< unsigned int > class TVector>
static Image CastITKToImage (itk::Image< TVector< VLength >, VImageDimension > *img)
template<class TImageType>
static Image CastITKToImage (TImageType *img)
static const itk::EventObject & GetITKEventObject (EventEnum e)
template<typename T>
static std::ostream & ToStringHelper (std::ostream &os, const T &v)
static std::ostream & ToStringHelper (std::ostream &os, const char &v)
static std::ostream & ToStringHelper (std::ostream &os, const signed char &v)
static std::ostream & ToStringHelper (std::ostream &os, const unsigned char &v)
Member Typedef Documentation
MemberFunctionType
using itk::simple::ReconstructionByDilationImageFilter::MemberFunctionType private
Initial value:
 Image (Self::*)(const Image *
    markerImage, const Image *
    maskImage)
Setup for member function dispatching
Definition at line 127 of file sitkReconstructionByDilationImageFilter.h.
PixelIDTypeList
using itk::simple::ReconstructionByDilationImageFilter::PixelIDTypeList = BasicPixelIDTypeList
Define the pixels types supported by this filter
Definition at line 77 of file sitkReconstructionByDilationImageFilter.h.
Self
using itk::simple::ReconstructionByDilationImageFilter::Self = ReconstructionByDilationImageFilter
Definition at line 67 of file sitkReconstructionByDilationImageFilter.h.
Constructor & Destructor Documentation
~ReconstructionByDilationImageFilter()
virtual itk::simple::ReconstructionByDilationImageFilter::~ReconstructionByDilationImageFilter () virtual
Destructor
ReconstructionByDilationImageFilter()
itk::simple::ReconstructionByDilationImageFilter::ReconstructionByDilationImageFilter ()
Default Constructor that takes no arguments and initializes default parameters
Member Function Documentation
Execute()
Image itk::simple::ReconstructionByDilationImageFilter::Execute (const Image & markerImage, const Image & maskImage)
Execute the filter on the input image
ExecuteInternal()
template<class TImageType> Image itk::simple::ReconstructionByDilationImageFilter::ExecuteInternal (const Image * markerImage, const Image * maskImage) private
Referenced by detail::MemberFunctionAddressor< MemberFunctionType >.
FullyConnectedOff()
void itk::simple::ReconstructionByDilationImageFilter::FullyConnectedOff () inline
Definition at line 91 of file sitkReconstructionByDilationImageFilter.h.
References SetFullyConnected().
FullyConnectedOn()
void itk::simple::ReconstructionByDilationImageFilter::FullyConnectedOn () inline
Set the value of FullyConnected to true or false respectfully.
Definition at line 89 of file sitkReconstructionByDilationImageFilter.h.
References SetFullyConnected().
GetFullyConnected()
bool itk::simple::ReconstructionByDilationImageFilter::GetFullyConnected () const inline
Definition at line 95 of file sitkReconstructionByDilationImageFilter.h.
References m_FullyConnected.
GetMemberFunctionFactory()
static const detail::MemberFunctionFactory< MemberFunctionType > & itk::simple::ReconstructionByDilationImageFilter::GetMemberFunctionFactory () static private
GetName()
std::string itk::simple::ReconstructionByDilationImageFilter::GetName () const inline virtual
Name of this class
Implements itk::simple::ProcessObject.
Definition at line 115 of file sitkReconstructionByDilationImageFilter.h.
GetUseInternalCopy()
bool itk::simple::ReconstructionByDilationImageFilter::GetUseInternalCopy () const inline
Definition at line 111 of file sitkReconstructionByDilationImageFilter.h.
References m_UseInternalCopy.
SetFullyConnected()
void itk::simple::ReconstructionByDilationImageFilter::SetFullyConnected (bool FullyConnected) inline
Definition at line 84 of file sitkReconstructionByDilationImageFilter.h.
References m_FullyConnected.
Referenced by FullyConnectedOff(), and FullyConnectedOn().
SetUseInternalCopy()
void itk::simple::ReconstructionByDilationImageFilter::SetUseInternalCopy (bool UseInternalCopy) inline
Definition at line 100 of file sitkReconstructionByDilationImageFilter.h.
References m_UseInternalCopy.
Referenced by UseInternalCopyOff(), and UseInternalCopyOn().
ToString()
std::string itk::simple::ReconstructionByDilationImageFilter::ToString () const virtual
Print ourselves out
Reimplemented from itk::simple::ProcessObject.
UseInternalCopyOff()
void itk::simple::ReconstructionByDilationImageFilter::UseInternalCopyOff () inline
Definition at line 107 of file sitkReconstructionByDilationImageFilter.h.
References SetUseInternalCopy().
UseInternalCopyOn()
void itk::simple::ReconstructionByDilationImageFilter::UseInternalCopyOn () inline
Set the value of UseInternalCopy to true or false respectfully.
Definition at line 105 of file sitkReconstructionByDilationImageFilter.h.
References SetUseInternalCopy().
Friends And Related Symbol Documentation
detail::MemberFunctionAddressor< MemberFunctionType >
friend struct detail::MemberFunctionAddressor< MemberFunctionType > friend
Definition at line 130 of file sitkReconstructionByDilationImageFilter.h.
References ExecuteInternal().
Member Data Documentation
m_FullyConnected
bool itk::simple::ReconstructionByDilationImageFilter::m_FullyConnected { false } private
Definition at line 137 of file sitkReconstructionByDilationImageFilter.h.
Referenced by GetFullyConnected(), and SetFullyConnected().
m_UseInternalCopy
bool itk::simple::ReconstructionByDilationImageFilter::m_UseInternalCopy { true } private
Definition at line 139 of file sitkReconstructionByDilationImageFilter.h.
Referenced by GetUseInternalCopy(), and SetUseInternalCopy().
The documentation for this class was generated from the following file:
sitkReconstructionByDilationImageFilter.h