SimpleITK: itk Namespace Reference
itk Namespace Reference
Namespaces
simple
Classes
class CompositeTransform
class CovariantVector
class DefaultImageToImageMetricTraitsv4
class FFTImageFilterFactoryRegisterManager
class HashImageFilter
Generates a hash string from an image.
class HolderCommand
An ITK Command class to hold a object until destruction.
class HolderCommand< T * >
class Image
class ImageBase
class ImageIOFactoryRegisterManager
class ImageRegion
class ImageToImageMetricv4
class LabelMap
class LabelObject
class ObjectToObjectOptimizerBaseTemplate
struct Offset
class RegistrationParameterScalesEstimator
class SmartPointer
class SpatialObject
class Transform
class TransformBaseTemplate
class TransformIOFactoryRegisterManager
class Vector
class VectorImage
class Versor
Typedefs
using TransformBase = TransformBaseTemplate< double >
Functions
void BioRadImageIOFactoryRegister__Private ()
void BMPImageIOFactoryRegister__Private ()
void Bruker2dseqImageIOFactoryRegister__Private ()
void GDCMImageIOFactoryRegister__Private ()
void GE4ImageIOFactoryRegister__Private ()
void GE5ImageIOFactoryRegister__Private ()
void GiplImageIOFactoryRegister__Private ()
void HDF5ImageIOFactoryRegister__Private ()
void HDF5TransformIOFactoryRegister__Private ()
const ImageIOFactoryRegisterManager ImageIOFactoryRegisterManagerInstance (ImageIOFactoryRegisterRegisterList)
void JPEG2000ImageIOFactoryRegister__Private ()
void JPEGImageIOFactoryRegister__Private ()
void LSMImageIOFactoryRegister__Private ()
void MatlabTransformIOFactoryRegister__Private ()
void MetaImageIOFactoryRegister__Private ()
void MINCImageIOFactoryRegister__Private ()
void MINCTransformIOFactoryRegister__Private ()
void MRCImageIOFactoryRegister__Private ()
void NiftiImageIOFactoryRegister__Private ()
void NrrdImageIOFactoryRegister__Private ()
void PNGImageIOFactoryRegister__Private ()
void StimulateImageIOFactoryRegister__Private ()
void TIFFImageIOFactoryRegister__Private ()
const TransformIOFactoryRegisterManager TransformIOFactoryRegisterManagerInstance (TransformIOFactoryRegisterRegisterList)
void TxtTransformIOFactoryRegister__Private ()
void VnlComplexToComplex1DFFTFactoryRegister__Private ()
void VnlComplexToComplexFFTFactoryRegister__Private ()
void VnlForward1DFFTFactoryRegister__Private ()
void VnlForwardFFTFactoryRegister__Private ()
void VnlHalfHermitianToRealInverseFFTFactoryRegister__Private ()
void VnlInverse1DFFTFactoryRegister__Private ()
void VnlInverseFFTFactoryRegister__Private ()
void VnlRealToHalfHermitianForwardFFTFactoryRegister__Private ()
void VTKImageIOFactoryRegister__Private ()
Variables
const FFTImageFilterFactoryRegisterManager FFTImageFilterFactoryRegisterManagerInstance
void(*const ImageIOFactoryRegisterRegisterList [])(void)
void(*const TransformIOFactoryRegisterRegisterList [])(void)
Typedef Documentation
TransformBase
using itk::TransformBase = typedef TransformBaseTemplate<double>
Definition at line 31 of file sitkTransform.h.
Function Documentation
BioRadImageIOFactoryRegister__Private()
void itk::BioRadImageIOFactoryRegister__Private ()
BMPImageIOFactoryRegister__Private()
void itk::BMPImageIOFactoryRegister__Private ()
Bruker2dseqImageIOFactoryRegister__Private()
void itk::Bruker2dseqImageIOFactoryRegister__Private ()
GDCMImageIOFactoryRegister__Private()
void itk::GDCMImageIOFactoryRegister__Private ()
GE4ImageIOFactoryRegister__Private()
void itk::GE4ImageIOFactoryRegister__Private ()
GE5ImageIOFactoryRegister__Private()
void itk::GE5ImageIOFactoryRegister__Private ()
GiplImageIOFactoryRegister__Private()
void itk::GiplImageIOFactoryRegister__Private ()
HDF5ImageIOFactoryRegister__Private()
void itk::HDF5ImageIOFactoryRegister__Private ()
HDF5TransformIOFactoryRegister__Private()
void itk::HDF5TransformIOFactoryRegister__Private ()
ImageIOFactoryRegisterManagerInstance()
const ImageIOFactoryRegisterManager itk::ImageIOFactoryRegisterManagerInstance (ImageIOFactoryRegisterRegisterList)
JPEG2000ImageIOFactoryRegister__Private()
void itk::JPEG2000ImageIOFactoryRegister__Private ()
JPEGImageIOFactoryRegister__Private()
void itk::JPEGImageIOFactoryRegister__Private ()
LSMImageIOFactoryRegister__Private()
void itk::LSMImageIOFactoryRegister__Private ()
MatlabTransformIOFactoryRegister__Private()
void itk::MatlabTransformIOFactoryRegister__Private ()
MetaImageIOFactoryRegister__Private()
void itk::MetaImageIOFactoryRegister__Private ()
MINCImageIOFactoryRegister__Private()
void itk::MINCImageIOFactoryRegister__Private ()
MINCTransformIOFactoryRegister__Private()
void itk::MINCTransformIOFactoryRegister__Private ()
MRCImageIOFactoryRegister__Private()
void itk::MRCImageIOFactoryRegister__Private ()
NiftiImageIOFactoryRegister__Private()
void itk::NiftiImageIOFactoryRegister__Private ()
NrrdImageIOFactoryRegister__Private()
void itk::NrrdImageIOFactoryRegister__Private ()
PNGImageIOFactoryRegister__Private()
void itk::PNGImageIOFactoryRegister__Private ()
StimulateImageIOFactoryRegister__Private()
void itk::StimulateImageIOFactoryRegister__Private ()
TIFFImageIOFactoryRegister__Private()
void itk::TIFFImageIOFactoryRegister__Private ()
TransformIOFactoryRegisterManagerInstance()
const TransformIOFactoryRegisterManager itk::TransformIOFactoryRegisterManagerInstance (TransformIOFactoryRegisterRegisterList)
TxtTransformIOFactoryRegister__Private()
void itk::TxtTransformIOFactoryRegister__Private ()
VnlComplexToComplex1DFFTFactoryRegister__Private()
void itk::VnlComplexToComplex1DFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlComplexToComplexFFTFactoryRegister__Private()
void itk::VnlComplexToComplexFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlForward1DFFTFactoryRegister__Private()
void itk::VnlForward1DFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlForwardFFTFactoryRegister__Private()
void itk::VnlForwardFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlHalfHermitianToRealInverseFFTFactoryRegister__Private()
void itk::VnlHalfHermitianToRealInverseFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlInverse1DFFTFactoryRegister__Private()
void itk::VnlInverse1DFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlInverseFFTFactoryRegister__Private()
void itk::VnlInverseFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VnlRealToHalfHermitianForwardFFTFactoryRegister__Private()
void itk::VnlRealToHalfHermitianForwardFFTFactoryRegister__Private ()
Referenced by itk::FFTImageFilterFactoryRegisterManager::FFTImageFilterFactoryRegisterManager().
VTKImageIOFactoryRegister__Private()
void itk::VTKImageIOFactoryRegister__Private ()
Variable Documentation
FFTImageFilterFactoryRegisterManagerInstance
const FFTImageFilterFactoryRegisterManager itk::FFTImageFilterFactoryRegisterManagerInstance
Definition at line 52 of file itkFFTImageFilterFactoryRegisterManager.h.
ImageIOFactoryRegisterRegisterList
void(* const itk::ImageIOFactoryRegisterRegisterList[])(void)
Initial value:
= {
  BMPImageIOFactoryRegister__Private,BioRadImageIOFactoryRegister__Private,Bruker2dseqImageIOFactoryRegister__Private,GDCMImageIOFactoryRegister__Private,GE4ImageIOFactoryRegister__Private,GE5ImageIOFactoryRegister__Private,GiplImageIOFactoryRegister__Private,HDF5ImageIOFactoryRegister__Private,JPEGImageIOFactoryRegister__Private,JPEG2000ImageIOFactoryRegister__Private,LSMImageIOFactoryRegister__Private,MINCImageIOFactoryRegister__Private,MRCImageIOFactoryRegister__Private,MetaImageIOFactoryRegister__Private,NiftiImageIOFactoryRegister__Private,NrrdImageIOFactoryRegister__Private,PNGImageIOFactoryRegister__Private,StimulateImageIOFactoryRegister__Private,TIFFImageIOFactoryRegister__Private,VTKImageIOFactoryRegister__Private,
  nullptr}
Definition at line 49 of file itkImageIOFactoryRegisterManager.h.
TransformIOFactoryRegisterRegisterList
void(* const itk::TransformIOFactoryRegisterRegisterList[])(void)
Initial value:
= {
  HDF5TransformIOFactoryRegister__Private,MINCTransformIOFactoryRegister__Private,MatlabTransformIOFactoryRegister__Private,TxtTransformIOFactoryRegister__Private,
  nullptr}
Definition at line 49 of file itkTransformIOFactoryRegisterManager.h.